# ArnoldC

In [21]:
! wget http://lhartikk.github.io/ArnoldC.jar

--2024-04-06 17:33:02--  http://lhartikk.github.io/ArnoldC.jar
Resolving lhartikk.github.io (lhartikk.github.io)... 185.199.110.153, 185.199.108.153, 185.199.109.153, ...
Connecting to lhartikk.github.io (lhartikk.github.io)|185.199.110.153|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12958233 (12M) [application/java-archive]
Saving to: ‘ArnoldC.jar’

ArnoldC.jar         100%[===================>]  12.36M  12.4MB/s    in 1.0s

2024-04-06 17:33:03 (12.4 MB/s) - ‘ArnoldC.jar’ saved [12958233/12958233]

In [1]:
import pandas as pd
import subprocess
import time
import copy
from enchant.utils import levenshtein

In [2]:
# programming_languages_list = ['Brainfuck', 'Malbolge', 'Shakespeare', 'Befunge', 'LOLCODE',\
#      'JSFuck', 'ArnoldC', 'Chef', 'Chicken', 'OOK', \
#     'C++', 'Python', 'Mathematica', 'Matlab', 'R', 'JavaScript', \
#    'Whitespace', 'Unlambda', 'Velato','INTERCAL', 'TrollScript']

In [3]:
OIA_ds = pd.read_csv("/Users/beto/Documents/Projects/medLLM/no_small_seqs_clean.csv")
arnold_df = copy.deepcopy(OIA_ds[OIA_ds["language"] == "ArnoldC"])
original_sequences = arnold_df["sequence"].values

arnoldC_code_list = (OIA_ds[OIA_ds["language"] == "ArnoldC"])["GPT4_answer"].values
total_questions = len(arnoldC_code_list)

In [4]:
arnold_df

,sequence,complexity,length_type,language,q_length,GPT4_answer,a_length,temperature,real_code,print_code,no_code,explanation,no_sense,exe_out,correct_execution,Levenshtein
3540,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",1.0,0.0,ArnoldC,169.0,```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE ...,432.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
3541,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",1.0,0.0,ArnoldC,170.0,```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE ...,413.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
3542,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",1.0,0.0,ArnoldC,171.0,```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE ...,315.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
3543,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",1.0,0.0,ArnoldC,172.0,```ArnoldC\nIT'S SHOWTIME\nHEY CHRISTMAS TREE ...,416.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
3544,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",1.0,0.0,ArnoldC,172.0,```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE ...,406.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4125,"187, 218, 260, 295, 301, 314, 379, 410, 452, 469",4.0,0.0,ArnoldC,182.0,```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE ...,921.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN
4126,"29, 63, 95, 140, 150, 190, 221, 437, 482, 491",4.0,0.0,ArnoldC,179.0,```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE ...,428.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN
4127,"3, 11, 84, 144, 156, 177, 188, 199, 229, 284",4.0,0.0,ArnoldC,178.0,```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE ...,687.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN
4128,"26, 94, 98, 137, 176, 301, 323, 330, 372, 444",4.0,0.0,ArnoldC,179.0,```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE ...,733.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN
4129,"39, 81, 88, 210, 215, 378, 416, 430, 439, 490",4.0,0.0,ArnoldC,179.0,```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE ...,699.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN

In [5]:
original_sequences[1:5]

array(['3, 6, 9, 12, 15, 18, 21, 24, 27, 30',
       '4, 8, 12, 16, 20, 24, 28, 32, 36, 40',
       '5, 10, 15, 20, 25, 30, 35, 40, 45, 50',
       '6, 12, 18, 24, 30, 36, 42, 48, 54, 60'], dtype=object)

In [6]:
arnoldC_code_list[1:5]

array(["```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 0\nHEY CHRISTMAS TREE limit\nYOU SET US UP 30\nSTICK AROUND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 3\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nPLUS 3\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE number\nI LIED limit\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
       "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 4\nHEY CHRISTMAS TREE limit\nYOU SET US UP 40\nSTICK AROUND number\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 4\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE number\nI LIED limit\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
       "```ArnoldC\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE step\nYOU SET US UP 5\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP step\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION number\nLET OFF SOME STEAM BENNET 50\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
       "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE result\nYOU SET US UP @NO PROBLEMO\nSTICK AROUND number\nTALK TO THE HAND result\nGET UP result\nYOU'RE FIRED 6\nENOUGH TALK\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nYOU'RE FIRED 1\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE number\nI LET HIM GO 10\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```"],
      dtype=object)

In [7]:
len(arnoldC_code_list)

590

In [8]:
levenshtein("hola", "hola")

0

In [15]:
counter = -1
exe_outputs = []
levenshtein_list = []
correctness_list = []
test_code = []

for code in arnoldC_code_list:#[0:15]:
    code = code.replace("```arnoldc" + "\n","\"")
    code = code.replace("```ArnoldC" + "\n","\"")
    code = code.replace("\n"+ "```","\"")
    
    
    #print(code)
    counter += 1
    name_file = "q_" + str(counter)
    surname_file =  '.arnoldc'
    whole_name = name_file + surname_file
    
    original_seq = original_sequences[counter]
    
    print("######################  INITIALIZE PROCESS ########################## (", str(counter), ")")
    try:
        print("creating file...")
        test_code.append(code)
        ! echo -e {code} > {whole_name}
        #COMPLIE
        print("----------------- compliling")
        rough_jar = subprocess.run(["java", "-jar",  "ArnoldC.jar", whole_name], capture_output=True, text=True)
        print("SUCCESSFUL COMPILATION")
        print(rough_jar.stdout.strip())

        try:
            print("-----------------  executing")
            rough_jar = subprocess.run(["java", name_file], capture_output=True, text=True, timeout=10)
            print("EXECUTION OUT: ")
            print(rough_jar.stdout.strip())
            out = rough_jar.stdout.strip()
            out = out.replace("\n", ", ")
            exe_outputs.append(out)
            correctness_list.append(out==original_seq)
            levenshtein_list.append(levenshtein(out, original_seq))
        except:
            print("**************** execution error ( step 2)")
            print(rough_jar.stderr)
            exe_outputs.append('Execution error')
            correctness_list.append('False')
            levenshtein_list.append(50000)
            pass

    except:       
        print("**************** Execution error (step 1)")
        print(rough_jar.stderr)
        pass

######################  INITIALIZE PROCESS ########################## ( 0 )
creating file...

----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:
0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
######################  INITIALIZE PROCESS ########################## ( 1 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 2 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 3 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:
5
######################  INITIALIZE PROCESS ########################## ( 4 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 5 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 6 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:
8
16
24
32
40
48
56
64
72
80
######################  INITIALIZE PROCESS ########################## ( 7 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 8 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 9 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
######################  INITIALIZE PROCESS ########################## ( 10 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 11 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 12 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 13 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 14 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 15 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 16 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 17 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 18 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 19 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 20 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 21 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 22 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 23 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 24 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 25 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 26 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 27 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 28 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 29 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 30 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:
2
4
6
8
10
12
14
16
18
20
######################  INITIALIZE PROCESS ########################## ( 31 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 32 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 33 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 34 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 35 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 36 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 37 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 38 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 39 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 40 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:
2
4
6
8
10
12
14
16
18
20
######################  INITIALIZE PROCESS ########################## ( 41 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 42 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 43 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
######################  INITIALIZE PROCESS ########################## ( 44 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 45 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 46 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 47 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 48 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 49 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 50 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 51 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
######################  INITIALIZE PROCESS ########################## ( 52 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 53 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 54 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 55 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 56 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 57 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
######################  INITIALIZE PROCESS ########################## ( 58 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 59 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
######################  INITIALIZE PROCESS ########################## ( 60 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 61 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 62 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 63 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 64 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 65 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:
1
7
######################  INITIALIZE PROCESS ########################## ( 66 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:
8
16
24
32
40
48
56
64
72
80
######################  INITIALIZE PROCESS ########################## ( 67 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 68 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 69 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 70 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 71 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 72 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 73 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 74 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 75 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 76 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 77 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 78 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 79 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 80 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 81 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 82 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 83 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 84 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 85 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 86 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 87 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 88 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 89 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 90 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:
2
4
6
8
10
12
14
16
18
20
######################  INITIALIZE PROCESS ########################## ( 91 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:

######################  INITIALIZE PROCESS ########################## ( 92 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION

-----------------  executing
EXECUTION OUT:
4
8
12
16
20
24
28
32
36
40

In [16]:
exe_outputs

['0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38',
 '',
 '',
 '5',
 '',
 '',
 '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
 'Execution error',
 '',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40',
 '',
 '',
 '',
 '',
 '',
 'Execution error',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '',
 '',
 '',
 'Execution error',
 '',
 '',
 '',
 '',
 '',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '',
 '',
 '0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119',
 '',
 '',
 '',
 '',
 '',
 '0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179',
 '',
 '1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200',
 'Execution error',
 '',
 '',
 '',
 '',
 '1, 7',
 '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
 '',
 '',
 'Execution error',
 'Execution error',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '',
 '4, 8, 12, 16, 20, 24, 28, 32, 36, 40',
 '',
 '',
 '',
 '',
 '',
 '',
 'Execution error',
 'Execution error',
 '',
 '',
 '',
 '',
 '1, 2, 3, 4, 5, 6, 7, 8, 9, 10',
 '',
 '',
 '',
 '1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100',
 '',
 '0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119',
 '',
 '',
 '',
 '',
 '',
 '0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179',
 '',
 '',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87',
 '',
 '',
 '',
 '',
 '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
 '',
 '',
 '',
 'Execution error',
 '',
 '',
 '',
 '',
 '',
 '',
 '1, 2, 3, 4, 5, 6, 7, 8, 9, 10',
 '',
 '',
 '',
 '1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120',
 '',
 '',
 '',
 '0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159',
 '',
 '0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179',
 '',
 '',
 '',
 'Execution error',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'Execution error',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'Execution error',
 '',
 '',
 '',
 '',
 '',
 '',
 '0, 0, 0, 0, 0, 0, 0, 0, 0, 0',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '0',
 '',
 '',
 '',
 '',
 '',
 '',
 '0',
 '1, 2, 3, 4, 5, 6, 7, 8, 9, 10',
 '',
 '',
 'Execution error',
 '',
 '',
 '',
 'Execution error',
 '',
 '',
 'Execution error',
 '',
 '',
 '',
 '',
 'Execution error',
 '',
 '1, 2, 3, 5, 8, 13, 21, 34, 55, 89',
 '',
 '',
 '',
 '',
 '1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880',
 '',
 '',
 '',
 '',
 '',
 '',
 'Execution error',
 '1, 2, 3, 4, 5, 6, 7, 8, 9, 10',
 '',
 '',
 '',
 '',
 '1, 3, 7, 15, 31, 63, 127, 255, 511, 1023',
 '-3, 7, 1, -30',
 'Execution error',
 '',
 '',
 'Execution error',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '2, 4, 7, 13, 24, 44, 81, 149, 274, 504',
 '',
 '',
 'Execution error',
 'Execution error',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '1, 1, 2, 2, 3, 3, 4, 4, 5, 5',
 'Execution error',
 '',
 'Execution error',
 '',
 '',
 '',
 '',
 'Execution error',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'Execution error',
 '',
 '1, 1, 2, 4, 7, 13, 24, 44, 81, 149',
 '',
 '',
 'Execution error',
 '',
 '',
 'Execution error',
 '',
 'Execution error',
 'Execution error',
 '',
 '',
 '',
 '',
 'Execution error',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'Execution error',
 '',
 'Execution error',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '0',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '2, 4, 8, 16, 32, 64, 128, 256, 512, 1024',
 '',
 '',
 'Execution error',
 '',
 '',
 '',
 'Execution error',
 '',
 '',
 '',
 '2, 3, 7, 42, 1806, -13358',
 '',
 '',
 '',
 '',
 '',
 '1, 4, 2, 1, 3, 5, 9, 2, 6, 5',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'Execution error',
 '',
 '',
 '',
 '0, 2, 6, 12, 20, 30, 42, 56, 72, 90',
 '',
 '',
 'Execution error',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'Execution error',
 '',
 '',
 '',
 'Execution error',
 '',
 'Execution error',
 '',
 '',
 'Execution error',
 '',
 '',
 '',
 '0, 2, 6, 12, 20, 30, 42, 56, 72, 90',
 '',
 '',
 'Execution error',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'Execution error',
 '',
 '',
 '',
 '',
 '',
 '',
 '18, 39, 71, 194, 197, 219, 263, 270, 416, 473',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '72, 106, 139, 165, 171, 192, 199, 429, 453, 477',
 '187, 218, 260, 295, 301, 314, 379, 410, 452, 469',
 '29, 63, 95, 140, 150, 190, 221, 437, 482, 491',
 '3, 11, 84, 144, 156, 177, 188, 199, 229, 284',
 'Execution error',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '134, 224, 293, 378, 379, 395, 434, 451, 482, 496',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '39, 81, 88, 210, 215, 378, 416, 430, 439, 490',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'Execution error',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '26, 40, 202, 267, 282, 340, 359, 408, 410, 495',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '']

In [17]:
test_code

['"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION @I LIED\nGET UP 20\nENOUGH TALK\n\nSTICK AROUND limit\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 2\nENOUGH TALK\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 0\nHEY CHRISTMAS TREE limit\nYOU SET US UP 30\nSTICK AROUND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 3\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nPLUS 3\nENOUGH TALK\nBECAUSE I\'M GOING TO SAY PLEASE number\nI LIED limit\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 4\nHEY CHRISTMAS TREE limit\nYOU SET US UP 40\nSTICK AROUND number\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 4\nENOUGH TALK\nBECAUSE I\'M GOING TO SAY PLEASE number\nI LIED limit\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE step\nYOU SET US UP 5\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP step\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION number\nLET OFF SOME STEAM BENNET 50\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE result\nYOU SET US UP @NO PROBLEMO\nSTICK AROUND number\nTALK TO THE HAND result\nGET UP result\nYOU\'RE FIRED 6\nENOUGH TALK\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nYOU\'RE FIRED 1\nENOUGH TALK\nBECAUSE I\'M GOING TO SAY PLEASE number\nI LET HIM GO 10\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE sequence\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE num\nYOU SET US UP 0\nHEY CHRISTMAS TREE limit\nYOU SET US UP 70\nSTICK AROUND sequence\nGET TO THE CHOPPER num\nHERE IS MY INVITATION num\nGET UP 7\nENOUGH TALK\nTALK TO THE HAND num\nGET TO THE CHOPPER sequence\nHERE IS MY INVITATION sequence\nHE HAD TO SPLIT 7\nENOUGH TALK\nBECAUSE I\'M GOING TO SAY PLEASE num\nI LET HIM GO limit\nYOU HAVE NO RESPECT FOR LOGIC\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 0\nHEY CHRISTMAS TREE limit\nYOU SET US UP 10\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 8\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 0\nHEY CHRISTMAS TREE i\nYOU SET US UP 1\nSTICK AROUND i\nTALK TO THE HAND i\nGET TO THE CHOPPER number\nHERE IS MY INVITATION i\nGET UP 9\nENOUGH TALK\nGET TO THE CHOPPER i\nHERE IS MY INVITATION i\nGET UP 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 0\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 10\nENOUGH TALK\nBECAUSE I\'M GOING TO SAY PLEASE number\nLESS THAN 100\nBULLSHIT\nCHILL\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE increment\nYOU SET US UP 2\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION 20\nENOUGH TALK\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP increment\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE step\nYOU SET US UP @I LIED\nSTICK AROUND limit\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP step\nENOUGH TALK\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET UP step\nENOUGH TALK\nCHILL\nYOU HAVE NO RESPECT FOR LOGIC"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nSTICK AROUND limit\nTALK TO THE HAND number\nGET TO THE CHOPPA number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nGET TO THE CHOPPA limit\nHERE IS MY INVITATION 20\nLET OFF SOME STEAM BENNET number\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 20\nSTICK AROUND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nBECAUSE I\'M GOING TO SAY PLEASE number\nLESS THAN 31\nBULLSHIT\nCHILL\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 31\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nENOUGH TALK\nYOU HAVE NO RESPECT FOR LOGIC"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 41\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nYOU\'RE FIRED 1\nBECAUSE I\'M GOING TO SAY PLEASE number\nI LIED 50\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nGET TO THE CHOPPER number\nHERE IS MY INVITATION 51\nENOUGH TALK\nSTICK AROUND number\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION @I LIED\nYOU\'RE FIRED @NO PROBLEMO\nENOUGH TALK\n\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP @I LIED\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN @ONE\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE sequence\nYOU SET US UP 71\nSTICK AROUND sequence\nTALK TO THE HAND sequence\nGET UP sequence\nYOU HAVE NO RESPECT FOR LOGIC\nBECAUSE I\'M GOING TO SAY PLEASE sequence < 81\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 81\nSTICK AROUND number\n    TALK TO THE HAND number\n    GET UP number\n    BECAUSE I\'M GOING TO SAY PLEASE number < 91\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nSTICK AROUND limit\nTALK TO THE HAND number\nGET UP number\nYOU\'RE FIRED 1\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION number\nYOU\'RE FIRED 10\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 101\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nYOU\'RE FIRED 1\nBECAUSE I\'M GOING TO SAY PLEASE number\nI LET HIM GO 110\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 111\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nYOU\'RE FIRED 1\nENOUGH TALK\nBECAUSE I\'M GOING TO SAY PLEASE number\nI LET HIM GO 120\nBULLSHIT\nCHILL\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP 130\nSTICK AROUND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nTALK TO THE HAND number\nBECAUSE I\'M GOING TO SAY PLEASE limit\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nYOU\'RE FIRED 1\nENOUGH TALK\nCHILL limit\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 130\nSTICK AROUND number\nI LET HIM GO 140\nGET UP number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nTALK TO THE HAND number\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP 150\nSTICK AROUND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nBECAUSE I\'M GOING TO SAY PLEASE number\nI LIED limit\nYOU HAVE NO RESPECT FOR LOGIC\nBULLSHIT\nYOU HAVE BEEN TERMINATED\nCHILL"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 151\nSTICK AROUND number\nI WANT TO ASK YOU A BUNCH OF THINGS AND I WANT TO HAVE THEM ANSWERED IMMEDIATELY\nTALK TO THE HAND number\nGET UP number\nYOU\'RE FIRED 1\nENOUGH TALK\nBECAUSE I\'M GOING TO SAY PLEASE number\nLESS THAN 161\nBULLSHIT\nCHILL\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 161\n\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\n\nBECAUSE I\'M GOING TO SAY PLEASE number\nLESS THAN 171\nYOU HAVE NO RESPECT FOR LOGIC\n\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 171\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nBECAUSE I\'M GOING TO SAY PLEASE number\nLESS THAN 181\nYOU HAVE NO RESPECT FOR LOGIC\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE condition\nYOU SET US UP 0\nGET TO THE CHOPPER number\nHERE IS MY INVITATION 181\nENOUGH TALK\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION 190\nENOUGH TALK\nSTICK AROUND condition\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nGET TO THE CHOPPER condition\nHERE IS MY INVITATION number\nLET OFF SOME STEAM BENNET limit\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 191\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nENOUGH TALK\nBECAUSE I\'M GOING TO SAY PLEASE number I LIED 200\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 0\nHEY CHRISTMAS TREE limit\nYOU SET US UP 10\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 2\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE step\nYOU SET US UP 3\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP step\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET UP step\nENOUGH TALK\nBECAUSE I\'M GOING TO SAY PLEASE limit\nI\'LL BE BACK 30\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE increment\nYOU SET US UP 4\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP increment\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET UP increment\nENOUGH TALK\nBECAUSE I\'M GOING TO SAY PLEASE limit\nI LIED 40\nYOU HAVE NO RESPECT FOR LOGIC\nCHILL"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 0\nHEY CHRISTMAS TREE limit\nYOU SET US UP 10\nSTICK AROUND limit\nGET UP number\nYOU\'RE FIRED 5\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE step\nYOU SET US UP 6\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP step\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET UP 6\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE counter\nYOU SET US UP 0\nSTICK AROUND counter\nTALK TO THE HAND number\nGET UP number\nYOU\'RE FIRED 7\nGET DOWN counter\nYOU\'RE FIRED 1\nCHILL counter LESS THAN 10\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 8\nHEY CHRISTMAS TREE limit\nYOU SET US UP 80\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nYOU\'RE FIRED 8\nCHILL number\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE multiplier\nYOU SET US UP 1\nSTICK AROUND multiplier\nTALK TO THE HAND number\nGET UP number\nYOU\'RE FIRED 9\nGET TO THE CHOPPER multiplier\nHERE IS MY INVITATION multiplier\nGET UP 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE step\nYOU SET US UP 10\nSTICK AROUND limit\nTALK TO THE HAND number\nGET UP number\nYOU\'RE FIRED step\nBECAUSE I\'M GOING TO SAY PLEASE number\nI LET HIM GO 100\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE step\nYOU SET US UP 2\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION 20\nENOUGH TALK\nSTICK AROUND number\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP step\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE step\nYOU SET US UP 2\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION 20\nENOUGH TALK\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP step\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 2\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 11\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nYOU\'RE FIRED 1\nENOUGH TALK\nBECAUSE I\'M GOING TO SAY PLEASE number\nLESS THAN 21\nBULLSHIT\nCHILL\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nSTICK AROUND limit\nTALK TO THE HAND number\nGET UP number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION 30\nYOU\'RE FIRED number\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION @I LIED\nGET UP 40\nENOUGH TALK\n\nSTICK AROUND limit\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 41\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nYOU\'RE FIRED 1\nHE HAD TO SPLIT 50\nYOU HAVE NO RESPECT FOR LOGIC"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP 60\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nYOU\'RE FIRED 1\nENOUGH TALK\nBECAUSE I\'M GOING TO SAY PLEASE number\nLESS THAN limit\nKNOCK KNOCK\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 61\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nENOUGH TALK\nBECAUSE I\'M GOING TO SAY PLEASE number\nLESS THAN 71\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 71\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nYOU\'RE FIRED 1\nHE HAD TO SPLIT 80\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 81\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nYOU\'RE FIRED 1\nBECAUSE I\'M GOING TO SAY PLEASE number\nLESS THAN 91\nENOUGH TALK\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 91\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nENOUGH TALK\nYOU HAVE NO RESPECT FOR LOGIC"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 100\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nBECAUSE I\'M GOING TO SAY PLEASE number\nLESS THAN 111\nYOU HAVE NO RESPECT FOR LOGIC\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION @I LIED\nGET UP 120\nENOUGH TALK\n\nSTICK AROUND limit\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\n\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 121\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nYOU\'RE FIRED 1\nBECAUSE I\'M GOING TO SAY PLEASE number\nLESS THAN 131\nBULLSHIT\nCHILL\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 130\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nENOUGH TALK\nYOU HAVE NO RESPECT FOR LOGIC"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE sequence\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP 10\nHEY CHRISTMAS TREE i\nYOU SET US UP 0\nSTICK AROUND i\nTALK TO THE HAND sequence\nGET UP sequence\nGET TO THE CHOPPER sequence\nHERE IS MY INVITATION sequence\nYOU\'RE FIRED 1\nENOUGH TALK\nGET TO THE CHOPPER i\nHERE IS MY INVITATION i\nYOU\'RE FIRED 1\nENOUGH TALK\nCHILL i\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE step\nYOU SET US UP 1\n\nSTICK AROUND limit\nTALK TO THE HAND number\nGET UP number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP step\nENOUGH TALK\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION 160\nLET OFF SOME STEAM BENNET number\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 160\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nYOU\'RE FIRED 1\nBECAUSE I\'M GOING TO SAY PLEASE number\nLESS THAN 171\nENOUGH TALK\nYOU HAVE BEEN TERMINATED"',
 '"IT\'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION 180\nENOUGH TALK\n\nSTICK AROUND limit\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED"',

In [18]:
correctness_list

[False,
 False,
 False,
 False,
 False,
 False,
 True,
 'False',
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 'False',
 'False',
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 'False',
 'False',
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 'False',
 False,
 False,
 False,
 'False',
 False,
 False,
 'False',
 False,
 False,
 False,
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 'False',
 False,
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 'False',
 'False',
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 'False',
 False,
 'False',
 False,
 False,
 False,
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 'False',
 False,
 False,
 False,
 False,
 'False',
 False,
 False,
 'False',
 False,
 'False',
 'False',
 False,
 False,
 False,
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 'False',
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 'False',
 False,
 False,
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 'False',
 False,
 False,
 False,
 'False',
 False,
 'False',
 False,
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 'False',
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

In [19]:
levenshtein_list

[39,
 35,
 36,
 36,
 37,
 37,
 0,
 50000,
 39,
 52,
 34,
 38,
 38,
 38,
 38,
 50000,
 38,
 38,
 38,
 39,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 0,
 35,
 36,
 37,
 50000,
 37,
 37,
 37,
 39,
 33,
 0,
 38,
 38,
 118,
 38,
 38,
 38,
 38,
 38,
 39,
 48,
 443,
 48,
 48,
 48,
 48,
 48,
 740,
 48,
 842,
 50000,
 35,
 36,
 37,
 37,
 33,
 0,
 37,
 39,
 50000,
 50000,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 38,
 39,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 48,
 0,
 35,
 0,
 37,
 37,
 37,
 37,
 37,
 39,
 50000,
 50000,
 38,
 38,
 38,
 38,
 10,
 38,
 38,
 38,
 351,
 48,
 443,
 48,
 48,
 48,
 48,
 48,
 740,
 48,
 48,
 0,
 79,
 36,
 37,
 37,
 37,
 0,
 37,
 39,
 33,
 50000,
 38,
 38,
 38,
 38,
 38,
 38,
 10,
 38,
 39,
 48,
 442,
 48,
 48,
 48,
 640,
 48,
 740,
 48,
 48,
 34,
 50000,
 37,
 44,
 36,
 43,
 45,
 35,
 33,
 37,
 50000,
 45,
 34,
 35,
 47,
 53,
 16,
 36,
 41,
 61,
 34,
 50000,
 38,
 28,
 46,
 34,
 23,
 34,
 19,
 40,
 34,
 32,
 37,
 44,
 36,
 43,
 44,
 35,
 33,
 37,
 68,
 45,
 34,
 34,
 26,
 53,
 16,
 50000,
 41,
 61,
 34,
 50000,
 38,
 28,
 50000,
 34,
 23,
 34,
 37,
 50000,
 34,
 7,
 37,
 44,
 36,
 43,
 0,
 35,
 33,
 37,
 68,
 45,
 34,
 50000,
 26,
 53,
 16,
 36,
 41,
 38,
 26,
 50000,
 38,
 28,
 50000,
 34,
 23,
 34,
 37,
 40,
 34,
 32,
 37,
 44,
 36,
 43,
 45,
 35,
 17,
 37,
 68,
 50000,
 50000,
 35,
 47,
 53,
 16,
 36,
 41,
 61,
 34,
 14,
 50000,
 28,
 50000,
 34,
 23,
 34,
 37,
 50000,
 34,
 32,
 37,
 44,
 36,
 43,
 45,
 35,
 33,
 37,
 68,
 45,
 34,
 35,
 47,
 53,
 16,
 36,
 41,
 50000,
 34,
 13,
 38,
 28,
 50000,
 34,
 23,
 50000,
 37,
 50000,
 50000,
 43,
 28,
 28,
 40,
 50000,
 37,
 73,
 58,
 35,
 33,
 32,
 44,
 16,
 46,
 26,
 34,
 41,
 28,
 50000,
 34,
 50000,
 28,
 23,
 25,
 28,
 24,
 23,
 36,
 43,
 28,
 28,
 40,
 36,
 37,
 73,
 58,
 35,
 33,
 32,
 44,
 16,
 46,
 26,
 34,
 41,
 28,
 28,
 34,
 28,
 28,
 23,
 25,
 28,
 24,
 23,
 36,
 43,
 28,
 28,
 0,
 36,
 37,
 50000,
 58,
 35,
 33,
 50000,
 44,
 16,
 46,
 6,
 34,
 41,
 28,
 28,
 34,
 0,
 28,
 23,
 25,
 28,
 24,
 23,
 36,
 43,
 28,
 28,
 40,
 50000,
 37,
 73,
 58,
 10,
 33,
 32,
 50000,
 16,
 46,
 26,
 34,
 41,
 28,
 28,
 34,
 28,
 28,
 23,
 50000,
 28,
 24,
 23,
 50000,
 43,
 50000,
 28,
 40,
 50000,
 37,
 73,
 58,
 10,
 33,
 32,
 50000,
 16,
 46,
 26,
 34,
 41,
 28,
 28,
 34,
 28,
 28,
 23,
 25,
 28,
 24,
 23,
 45,
 44,
 47,
 45,
 46,
 44,
 50000,
 46,
 46,
 48,
 46,
 48,
 46,
 0,
 45,
 46,
 46,
 47,
 44,
 45,
 46,
 45,
 47,
 44,
 0,
 0,
 0,
 0,
 50000,
 45,
 45,
 44,
 47,
 45,
 46,
 44,
 48,
 46,
 46,
 48,
 46,
 0,
 46,
 45,
 45,
 46,
 46,
 47,
 44,
 45,
 46,
 45,
 47,
 44,
 47,
 48,
 48,
 44,
 45,
 0,
 45,
 44,
 47,
 45,
 46,
 44,
 48,
 46,
 46,
 48,
 50000,
 48,
 46,
 45,
 45,
 46,
 46,
 47,
 44,
 45,
 46,
 45,
 47,
 44,
 47,
 48,
 45,
 44,
 45,
 45,
 45,
 44,
 47,
 45,
 46,
 44,
 48,
 46,
 46,
 48,
 46,
 48,
 46,
 45,
 45,
 0,
 46,
 47,
 44,
 45,
 46,
 45,
 47,
 44,
 47,
 48,
 45,
 44,
 45,
 45,
 45,
 44,
 47,
 45,
 46,
 44,
 48,
 46,
 46,
 48,
 46,
 48,
 46,
 45,
 45,
 46,
 46,
 47,
 44,
 45,
 46,
 45,
 47,
 44,
 47,
 48,
 45,
 44,
 45,
 45]

In [20]:
list(arnold_df.columns)

['sequence',
 'complexity',
 'length_type',
 'language',
 'q_length',
 'GPT4_answer',
 'a_length',
 'temperature',
 'real_code',
 'print_code',
 'no_code',
 'explanation',
 'no_sense',
 'exe_out',
 'correct_execution',
 'Levenshtein']

In [21]:
print(len(exe_outputs))
print(len(levenshtein_list))
print(len(correctness_list))

590
590
590

In [22]:
arnold_df["exe_out"] = exe_outputs
arnold_df["correct_execution"] = correctness_list
arnold_df["Levenshtein"] = levenshtein_list
arnold_df

,sequence,complexity,length_type,language,q_length,GPT4_answer,a_length,temperature,real_code,print_code,no_code,explanation,no_sense,exe_out,correct_execution,Levenshtein
3540,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",1.0,0.0,ArnoldC,169.0,```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE ...,432.0,1.000,0.0,0,0.0,0.0,0,"0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24,...",False,39
3541,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",1.0,0.0,ArnoldC,170.0,```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE ...,413.0,1.000,0.0,0,0.0,0.0,0,,False,35
3542,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",1.0,0.0,ArnoldC,171.0,```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE ...,315.0,1.000,0.0,0,0.0,0.0,0,,False,36
3543,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",1.0,0.0,ArnoldC,172.0,```ArnoldC\nIT'S SHOWTIME\nHEY CHRISTMAS TREE ...,416.0,1.000,0.0,0,0.0,0.0,0,5,False,36
3544,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",1.0,0.0,ArnoldC,172.0,```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE ...,406.0,1.000,0.0,0,0.0,0.0,0,,False,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4125,"187, 218, 260, 295, 301, 314, 379, 410, 452, 469",4.0,0.0,ArnoldC,182.0,```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE ...,921.0,0.001,0.0,0,0.0,0.0,0,,False,48
4126,"29, 63, 95, 140, 150, 190, 221, 437, 482, 491",4.0,0.0,ArnoldC,179.0,```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE ...,428.0,0.001,0.0,0,0.0,0.0,0,,False,45
4127,"3, 11, 84, 144, 156, 177, 188, 199, 229, 284",4.0,0.0,ArnoldC,178.0,```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE ...,687.0,0.001,0.0,0,0.0,0.0,0,,False,44
4128,"26, 94, 98, 137, 176, 301, 323, 330, 372, 444",4.0,0.0,ArnoldC,179.0,```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE ...,733.0,0.001,0.0,0,0.0,0.0,0,,False,45
4129,"39, 81, 88, 210, 215, 378, 416, 430, 439, 490",4.0,0.0,ArnoldC,179.0,```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE ...,699.0,0.001,0.0,0,0.0,0.0,0,,False,45

In [23]:
arnold_df.to_csv("arnoldC_evaluation.csv", index=False)

# Python

In [24]:
import pandas as pd
import subprocess
import time
import copy
from enchant.utils import levenshtein

In [47]:
OIA_ds = pd.read_csv("/Users/beto/Documents/Projects/medLLM/no_small_seqs_clean.csv")
python_df = copy.deepcopy(OIA_ds[OIA_ds["language"] == "Python"])
original_sequences = python_df["sequence"].values

python_code_list = (OIA_ds[OIA_ds["language"] == "Python"])["GPT4_answer"].values
total_questions = len(python_code_list)

In [48]:
python_df

,sequence,complexity,length_type,language,q_length,GPT4_answer,a_length,temperature,real_code,print_code,no_code,explanation,no_sense,exe_out,correct_execution,Levenshtein
6490,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",1.0,0.0,Python,168.0,"```python\nfor i in range(2, 21, 2):\n prin...",52.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
6491,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",1.0,0.0,Python,169.0,"```python\nfor i in range(3, 31, 3):\n prin...",52.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
6492,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",1.0,0.0,Python,170.0,"```python\nfor i in range(4, 41, 4):\n prin...",52.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
6493,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",1.0,0.0,Python,171.0,"```python\nfor i in range(5, 55, 5):\n prin...",52.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
6494,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",1.0,0.0,Python,171.0,"```python\nfor i in range(1, 11):\n print(i...",53.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7075,"187, 218, 260, 295, 301, 314, 379, 410, 452, 469",4.0,0.0,Python,181.0,"```python\nsequence = [187, 218, 260, 295, 301...",91.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN
7076,"29, 63, 95, 140, 150, 190, 221, 437, 482, 491",4.0,0.0,Python,178.0,"```python\nsequence = [29, 63, 95, 140, 150, 1...",88.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN
7077,"3, 11, 84, 144, 156, 177, 188, 199, 229, 284",4.0,0.0,Python,177.0,"```python\nsequence = [3, 11, 84, 144, 156, 17...",87.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN
7078,"26, 94, 98, 137, 176, 301, 323, 330, 372, 444",4.0,0.0,Python,178.0,"```python\nprint([26, 94, 98, 137, 176, 301, 3...",68.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN
7079,"39, 81, 88, 210, 215, 378, 416, 430, 439, 490",4.0,0.0,Python,178.0,"```python\nsequence = [39, 81, 88, 210, 215, 3...",88.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN

In [49]:
python_code_list[1:5]

array(['```python\nfor i in range(3, 31, 3):\n    print(i)\n```',
       '```python\nfor i in range(4, 41, 4):\n    print(i)\n```',
       '```python\nfor i in range(5, 55, 5):\n    print(i)\n```',
       '```python\nfor i in range(1, 11):\n    print(i * 6)\n```'],
      dtype=object)

In [50]:
len(python_code_list)

590

In [42]:
counter = -1
exe_outputs = []
levenshtein_list = []
correctness_list = []
test_code = []

for code in python_code_list:#[0:15]:
    code = code.replace("```python" + "\n","\"")
    code = code.replace("```Python" + "\n","\"")
    code = code.replace("\n"+ "```","\"")
    print(code)
    
    
    counter += 1
    name_file = "q_" + str(counter) + ".py"

    original_seq = original_sequences[counter]
    
    print("######################  INITIALIZE PROCESS ########################## (", str(counter), ")")
    try:
        print("creating file...")
        test_code.append(code)
        ! echo -e {code} > {name_file}
        #COMPLIE
        print("----------------- running python script...")
        rough_jar = subprocess.run(["python", name_file], capture_output=True, text=True, timeout=10)
        print("SUCCESSFUL EXECUTION")
        print(rough_jar.stdout.strip())
        out = rough_jar.stdout.strip()
        out = out.replace("\n", ", ")
        print("this is it....")
        print(out)
        exe_outputs.append(out)
        correctness_list.append(out==original_seq)
        levenshtein_list.append(levenshtein(out, original_seq))

        
    except:       
        print("**************** Execution error")
        print(rough_jar.stderr)
        exe_outputs.append('Execution error')
        correctness_list.append('False')
        levenshtein_list.append(50000)
        pass

"for i in range(2, 21, 2):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 0 )
creating file...

----------------- running python script...
SUCCESSFUL EXECUTION
2
4
6
8
10
12
14
16
18
20
this is it....
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
"for i in range(3, 31, 3):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 1 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
3
6
9
12
15
18
21
24
27
30
this is it....
3, 6, 9, 12, 15, 18, 21, 24, 27, 30
"for i in range(4, 41, 4):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 2 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
4
8
12
16
20
24
28
32
36
40
this is it....
4, 8, 12, 16, 20, 24, 28, 32, 36, 40
"for i in range(5, 55, 5):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 3 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
5
10
15
20
25
30
35
40
45
50
this is it....
5, 10, 15, 20, 25, 30, 35, 40, 45, 50
"for i in range(1, 11):
    print(i * 6)"
######################  INITIALIZE PROCESS ########################## ( 4 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
6
12
18
24
30
36
42
48
54
60
this is it....
6, 12, 18, 24, 30, 36, 42, 48, 54, 60
"for i in range(1, 11):
    print(i * 7)"
######################  INITIALIZE PROCESS ########################## ( 5 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
7
14
21
28
35
42
49
56
63
70
this is it....
7, 14, 21, 28, 35, 42, 49, 56, 63, 70
"for i in range(1, 11):
    print(i * 8)"
######################  INITIALIZE PROCESS ########################## ( 6 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
8
16
24
32
40
48
56
64
72
80
this is it....
8, 16, 24, 32, 40, 48, 56, 64, 72, 80
"for i in range(1, 11):
    print(i * 9)"
######################  INITIALIZE PROCESS ########################## ( 7 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
9
18
27
36
45
54
63
72
81
90
this is it....
9, 18, 27, 36, 45, 54, 63, 72, 81, 90
"for i in range(1, 11):
    print(i*10)"
######################  INITIALIZE PROCESS ########################## ( 8 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
10
20
30
40
50
60
70
80
90
100
this is it....
10, 20, 30, 40, 50, 60, 70, 80, 90, 100
"for i in range(1, 20, 2):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 9 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
1
3
5
7
9
11
13
15
17
19
this is it....
1, 3, 5, 7, 9, 11, 13, 15, 17, 19
"for i in range(2, 21, 2):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 10 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
2
4
6
8
10
12
14
16
18
20
this is it....
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
"for i in range(11, 21):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 11 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
11
12
13
14
15
16
17
18
19
20
this is it....
11, 12, 13, 14, 15, 16, 17, 18, 19, 20
"for i in range(21, 31):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 12 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
21
22
23
24
25
26
27
28
29
30
this is it....
21, 22, 23, 24, 25, 26, 27, 28, 29, 30
"for i in range(31, 41):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 13 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
31
32
33
34
35
36
37
38
39
40
this is it....
31, 32, 33, 34, 35, 36, 37, 38, 39, 40
"for i in range(41, 51):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 14 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
41
42
43
44
45
46
47
48
49
50
this is it....
41, 42, 43, 44, 45, 46, 47, 48, 49, 50
"for i in range(51, 61):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 15 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
51
52
53
54
55
56
57
58
59
60
this is it....
51, 52, 53, 54, 55, 56, 57, 58, 59, 60
"for i in range(61, 71):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 16 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
61
62
63
64
65
66
67
68
69
70
this is it....
61, 62, 63, 64, 65, 66, 67, 68, 69, 70
"for i in range(71, 81):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 17 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
71
72
73
74
75
76
77
78
79
80
this is it....
71, 72, 73, 74, 75, 76, 77, 78, 79, 80
"for i in range(81, 91):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 18 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
81
82
83
84
85
86
87
88
89
90
this is it....
81, 82, 83, 84, 85, 86, 87, 88, 89, 90
"for i in range(91, 101):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 19 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
91
92
93
94
95
96
97
98
99
100
this is it....
91, 92, 93, 94, 95, 96, 97, 98, 99, 100
"for i in range(101, 111):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 20 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
101
102
103
104
105
106
107
108
109
110
this is it....
101, 102, 103, 104, 105, 106, 107, 108, 109, 110
"for i in range(111, 121):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 21 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
111
112
113
114
115
116
117
118
119
120
this is it....
111, 112, 113, 114, 115, 116, 117, 118, 119, 120
"for i in range(121, 131):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 22 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
121
122
123
124
125
126
127
128
129
130
this is it....
121, 122, 123, 124, 125, 126, 127, 128, 129, 130
"for i in range(131, 141):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 23 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
131
132
133
134
135
136
137
138
139
140
this is it....
131, 132, 133, 134, 135, 136, 137, 138, 139, 140
"for i in range(141, 151):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 24 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
141
142
143
144
145
146
147
148
149
150
this is it....
141, 142, 143, 144, 145, 146, 147, 148, 149, 150
"for i in range(151, 161):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 25 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
151
152
153
154
155
156
157
158
159
160
this is it....
151, 152, 153, 154, 155, 156, 157, 158, 159, 160
"for i in range(161, 171):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 26 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
161
162
163
164
165
166
167
168
169
170
this is it....
161, 162, 163, 164, 165, 166, 167, 168, 169, 170
"for i in range(171, 181):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 27 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
171
172
173
174
175
176
177
178
179
180
this is it....
171, 172, 173, 174, 175, 176, 177, 178, 179, 180
"for i in range(181, 191):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 28 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
181
182
183
184
185
186
187
188
189
190
this is it....
181, 182, 183, 184, 185, 186, 187, 188, 189, 190
"for i in range(191, 201):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 29 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
191
192
193
194
195
196
197
198
199
200
this is it....
191, 192, 193, 194, 195, 196, 197, 198, 199, 200
"for i in range(2, 21, 2):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 30 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
2
4
6
8
10
12
14
16
18
20
this is it....
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
"for i in range(3, 31, 3):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 31 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
3
6
9
12
15
18
21
24
27
30
this is it....
3, 6, 9, 12, 15, 18, 21, 24, 27, 30
"for i in range(4, 41, 4):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 32 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
4
8
12
16
20
24
28
32
36
40
this is it....
4, 8, 12, 16, 20, 24, 28, 32, 36, 40
"for i in range(5, 55, 5):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 33 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
5
10
15
20
25
30
35
40
45
50
this is it....
5, 10, 15, 20, 25, 30, 35, 40, 45, 50
"for i in range(6, 61, 6):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 34 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
6
12
18
24
30
36
42
48
54
60
this is it....
6, 12, 18, 24, 30, 36, 42, 48, 54, 60
"for i in range(1, 11):
    print(i * 7)"
######################  INITIALIZE PROCESS ########################## ( 35 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
7
14
21
28
35
42
49
56
63
70
this is it....
7, 14, 21, 28, 35, 42, 49, 56, 63, 70
"for i in range(8, 81, 8):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 36 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
8
16
24
32
40
48
56
64
72
80
this is it....
8, 16, 24, 32, 40, 48, 56, 64, 72, 80
"for i in range(1, 11):
    print(i * 9)"
######################  INITIALIZE PROCESS ########################## ( 37 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
9
18
27
36
45
54
63
72
81
90
this is it....
9, 18, 27, 36, 45, 54, 63, 72, 81, 90
"for i in range(10, 101, 10):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 38 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
10
20
30
40
50
60
70
80
90
100
this is it....
10, 20, 30, 40, 50, 60, 70, 80, 90, 100
"for i in range(1, 20, 2):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 39 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
1
3
5
7
9
11
13
15
17
19
this is it....
1, 3, 5, 7, 9, 11, 13, 15, 17, 19
"for i in range(2, 21, 2):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 40 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
2
4
6
8
10
12
14
16
18
20
this is it....
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
"for i in range(11, 21):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 41 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
11
12
13
14
15
16
17
18
19
20
this is it....
11, 12, 13, 14, 15, 16, 17, 18, 19, 20
"for i in range(21, 31):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 42 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
21
22
23
24
25
26
27
28
29
30
this is it....
21, 22, 23, 24, 25, 26, 27, 28, 29, 30
"for i in range(31, 41):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 43 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
31
32
33
34
35
36
37
38
39
40
this is it....
31, 32, 33, 34, 35, 36, 37, 38, 39, 40
"for i in range(41, 51):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 44 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
41
42
43
44
45
46
47
48
49
50
this is it....
41, 42, 43, 44, 45, 46, 47, 48, 49, 50
"for i in range(51, 61):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 45 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
51
52
53
54
55
56
57
58
59
60
this is it....
51, 52, 53, 54, 55, 56, 57, 58, 59, 60
"for i in range(61, 71):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 46 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
61
62
63
64
65
66
67
68
69
70
this is it....
61, 62, 63, 64, 65, 66, 67, 68, 69, 70
"for i in range(71, 81):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 47 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
71
72
73
74
75
76
77
78
79
80
this is it....
71, 72, 73, 74, 75, 76, 77, 78, 79, 80
"for i in range(81, 91):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 48 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
81
82
83
84
85
86
87
88
89
90
this is it....
81, 82, 83, 84, 85, 86, 87, 88, 89, 90
"for i in range(91, 101):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 49 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
91
92
93
94
95
96
97
98
99
100
this is it....
91, 92, 93, 94, 95, 96, 97, 98, 99, 100
"for i in range(101, 111):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 50 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
101
102
103
104
105
106
107
108
109
110
this is it....
101, 102, 103, 104, 105, 106, 107, 108, 109, 110
"for i in range(111, 121):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 51 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
111
112
113
114
115
116
117
118
119
120
this is it....
111, 112, 113, 114, 115, 116, 117, 118, 119, 120
"for i in range(121, 131):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 52 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
121
122
123
124
125
126
127
128
129
130
this is it....
121, 122, 123, 124, 125, 126, 127, 128, 129, 130
"for i in range(131, 141):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 53 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
131
132
133
134
135
136
137
138
139
140
this is it....
131, 132, 133, 134, 135, 136, 137, 138, 139, 140
"for i in range(141, 151):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 54 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
141
142
143
144
145
146
147
148
149
150
this is it....
141, 142, 143, 144, 145, 146, 147, 148, 149, 150
"for i in range(151, 161):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 55 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
151
152
153
154
155
156
157
158
159
160
this is it....
151, 152, 153, 154, 155, 156, 157, 158, 159, 160
"for i in range(161, 171):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 56 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
161
162
163
164
165
166
167
168
169
170
this is it....
161, 162, 163, 164, 165, 166, 167, 168, 169, 170
"for i in range(171, 181):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 57 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
171
172
173
174
175
176
177
178
179
180
this is it....
171, 172, 173, 174, 175, 176, 177, 178, 179, 180
"for i in range(181, 191):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 58 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
181
182
183
184
185
186
187
188
189
190
this is it....
181, 182, 183, 184, 185, 186, 187, 188, 189, 190
"for i in range(191, 201):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 59 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
191
192
193
194
195
196
197
198
199
200
this is it....
191, 192, 193, 194, 195, 196, 197, 198, 199, 200
"for i in range(2, 21, 2):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 60 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
2
4
6
8
10
12
14
16
18
20
this is it....
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
"for i in range(3, 31, 3):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 61 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
3
6
9
12
15
18
21
24
27
30
this is it....
3, 6, 9, 12, 15, 18, 21, 24, 27, 30
"for i in range(4, 41, 4):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 62 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
4
8
12
16
20
24
28
32
36
40
this is it....
4, 8, 12, 16, 20, 24, 28, 32, 36, 40
"for i in range(5, 51, 5):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 63 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
5
10
15
20
25
30
35
40
45
50
this is it....
5, 10, 15, 20, 25, 30, 35, 40, 45, 50
"for i in range(6, 61, 6):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 64 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
6
12
18
24
30
36
42
48
54
60
this is it....
6, 12, 18, 24, 30, 36, 42, 48, 54, 60
"for i in range(1, 11):
    print(i * 7)"
######################  INITIALIZE PROCESS ########################## ( 65 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
7
14
21
28
35
42
49
56
63
70
this is it....
7, 14, 21, 28, 35, 42, 49, 56, 63, 70
"for i in range(1, 11):
    print(i * 8)"
######################  INITIALIZE PROCESS ########################## ( 66 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
8
16
24
32
40
48
56
64
72
80
this is it....
8, 16, 24, 32, 40, 48, 56, 64, 72, 80
"for i in range(1, 11):
    print(9 * i)"
######################  INITIALIZE PROCESS ########################## ( 67 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
9
18
27
36
45
54
63
72
81
90
this is it....
9, 18, 27, 36, 45, 54, 63, 72, 81, 90
"for i in range(10, 101, 10):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 68 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
10
20
30
40
50
60
70
80
90
100
this is it....
10, 20, 30, 40, 50, 60, 70, 80, 90, 100
"for i in range(1, 20, 2):
    print(i)"
######################  INITIALIZE PROCESS ########################## ( 69 )
creating file...
----------------- running python script...
SUCCESSFUL EXECUTION
1
3
5
7
9
11
13
15
17
19
this is it....
1, 3, 5, 7, 9, 11, 13, 15, 17, 19
"for i in range(1, 11):
    print(i*2)"

In [41]:
exe_outputs

['2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '3, 6, 9, 12, 15, 18, 21, 24, 27, 30',
 '4, 8, 12, 16, 20, 24, 28, 32, 36, 40',
 '5, 10, 15, 20, 25, 30, 35, 40, 45, 50',
 '6, 12, 18, 24, 30, 36, 42, 48, 54, 60',
 '7, 14, 21, 28, 35, 42, 49, 56, 63, 70',
 '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
 '9, 18, 27, 36, 45, 54, 63, 72, 81, 90',
 '10, 20, 30, 40, 50, 60, 70, 80, 90, 100',
 '1, 3, 5, 7, 9, 11, 13, 15, 17, 19',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '11, 12, 13, 14, 15, 16, 17, 18, 19, 20',
 '21, 22, 23, 24, 25, 26, 27, 28, 29, 30',
 '31, 32, 33, 34, 35, 36, 37, 38, 39, 40',
 '41, 42, 43, 44, 45, 46, 47, 48, 49, 50']

In [43]:
python_df["exe_out"] = exe_outputs
python_df["correct_execution"] = correctness_list
python_df["Levenshtein"] = levenshtein_list
python_df

,sequence,complexity,length_type,language,q_length,GPT4_answer,a_length,temperature,real_code,print_code,no_code,explanation,no_sense,exe_out,correct_execution,Levenshtein
6490,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",1.0,0.0,Python,168.0,"```python\nfor i in range(2, 21, 2):\n prin...",52.0,1.000,0.0,0,0.0,0.0,0,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",True,0
6491,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",1.0,0.0,Python,169.0,"```python\nfor i in range(3, 31, 3):\n prin...",52.0,1.000,0.0,0,0.0,0.0,0,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",True,0
6492,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",1.0,0.0,Python,170.0,"```python\nfor i in range(4, 41, 4):\n prin...",52.0,1.000,0.0,0,0.0,0.0,0,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",True,0
6493,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",1.0,0.0,Python,171.0,"```python\nfor i in range(5, 55, 5):\n prin...",52.0,1.000,0.0,0,0.0,0.0,0,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",True,0
6494,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",1.0,0.0,Python,171.0,"```python\nfor i in range(1, 11):\n print(i...",53.0,1.000,0.0,0,0.0,0.0,0,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7075,"187, 218, 260, 295, 301, 314, 379, 410, 452, 469",4.0,0.0,Python,181.0,"```python\nsequence = [187, 218, 260, 295, 301...",91.0,0.001,0.0,0,0.0,0.0,0,"[187, 218, 260, 295, 301, 314, 379, 410, 452, ...",False,2
7076,"29, 63, 95, 140, 150, 190, 221, 437, 482, 491",4.0,0.0,Python,178.0,"```python\nsequence = [29, 63, 95, 140, 150, 1...",88.0,0.001,0.0,0,0.0,0.0,0,"[29, 63, 95, 140, 150, 190, 221, 437, 482, 491]",False,2
7077,"3, 11, 84, 144, 156, 177, 188, 199, 229, 284",4.0,0.0,Python,177.0,"```python\nsequence = [3, 11, 84, 144, 156, 17...",87.0,0.001,0.0,0,0.0,0.0,0,"[3, 11, 84, 144, 156, 177, 188, 199, 229, 284]",False,2
7078,"26, 94, 98, 137, 176, 301, 323, 330, 372, 444",4.0,0.0,Python,178.0,"```python\nprint([26, 94, 98, 137, 176, 301, 3...",68.0,0.001,0.0,0,0.0,0.0,0,"[26, 94, 98, 137, 176, 301, 323, 330, 372, 444]",False,2
7079,"39, 81, 88, 210, 215, 378, 416, 430, 439, 490",4.0,0.0,Python,178.0,"```python\nsequence = [39, 81, 88, 210, 215, 3...",88.0,0.001,0.0,0,0.0,0.0,0,"[39, 81, 88, 210, 215, 378, 416, 430, 439, 490]",False,2

In [44]:
python_df.to_csv("python_evaluation.csv", index=False)

# C++

In [46]:
import pandas as pd
import subprocess
import time
import copy
from enchant.utils import levenshtein

In [76]:
OIA_ds = pd.read_csv("/Users/beto/Documents/Projects/medLLM/no_small_seqs_clean.csv")
cpp_df = copy.deepcopy(OIA_ds[OIA_ds["language"] == "C++"])
original_sequences = cpp_df["sequence"].values

cpp_code_list = (OIA_ds[OIA_ds["language"] == "C++"])["GPT4_answer"].values
total_questions = len(cpp_code_list)

In [77]:
cpp_df

,sequence,complexity,length_type,language,q_length,GPT4_answer,a_length,temperature,real_code,print_code,no_code,explanation,no_sense,exe_out,correct_execution,Levenshtein
5900,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",1.0,0.0,C++,165.0,```cpp\n#include <iostream>\n\nint main() {\n ...,135.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
5901,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",1.0,0.0,C++,166.0,```cpp\n#include <iostream>\n\nint main() {\n ...,135.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
5902,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",1.0,0.0,C++,167.0,```cpp\n#include <iostream>\nusing namespace s...,151.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
5903,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",1.0,0.0,C++,168.0,```cpp\n#include <iostream>\n\nint main() {\n ...,166.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
5904,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",1.0,0.0,C++,168.0,```cpp\n#include <iostream>\n\nint main() {\n ...,135.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6485,"187, 218, 260, 295, 301, 314, 379, 410, 452, 469",4.0,0.0,C++,178.0,```cpp\n#include <iostream>\n\nint main() {\n ...,220.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN
6486,"29, 63, 95, 140, 150, 190, 221, 437, 482, 491",4.0,0.0,C++,175.0,```cpp\n#include <iostream>\n\nint main() {\n ...,212.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN
6487,"3, 11, 84, 144, 156, 177, 188, 199, 229, 284",4.0,0.0,C++,174.0,```cpp\n#include <iostream>\n\nint main() {\n ...,211.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN
6488,"26, 94, 98, 137, 176, 301, 323, 330, 372, 444",4.0,0.0,C++,175.0,```cpp\n#include <iostream>\n\nint main() {\n ...,212.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN
6489,"39, 81, 88, 210, 215, 378, 416, 430, 439, 490",4.0,0.0,C++,175.0,```cpp\n#include <iostream>\n\nint main() {\n ...,241.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN

In [78]:
cpp_code_list[1:5]

array(['```cpp\n#include <iostream>\n\nint main() {\n    for(int i = 3; i <= 30; i += 3) {\n        std::cout << i << " ";\n    }\n    return 0;\n}\n```',
       '```cpp\n#include <iostream>\nusing namespace std;\n\nint main() {\n    for (int i = 1; i <= 10; ++i) {\n        cout << i*4 << " ";\n    }\n    return 0;\n}\n```',
       '```cpp\n#include <iostream>\n\nint main() {\n    for(int i = 5; i <= 50; i += 5) {\n        std::cout << i;\n        if(i < 50) std::cout << ", ";\n    }\n    return 0;\n}\n```',
       '```cpp\n#include <iostream>\n\nint main() {\n    for(int i = 6; i <= 60; i += 6) {\n        std::cout << i << " ";\n    }\n    return 0;\n}\n```'],
      dtype=object)

In [79]:
len(cpp_code_list)

590

In [90]:
counter = -1
exe_outputs = []
levenshtein_list = []
correctness_list = []
test_code = []

for code in cpp_code_list:
    code = code.replace("```cpp" + "\n","\"")
    code = code.replace("```Cpp" + "\n","\"")
    code = code.replace("\n"+ "```","\"")
    
    
    #print(code)
    counter += 1
    name_file = "cpp_" + str(counter)
    surname_file =  '.cpp'
    whole_name = name_file + surname_file
    
    original_seq = original_sequences[counter]
    
    print("######################  INITIALIZE PROCESS ########################## (", str(counter), ")")
    try:
        print("creating file...")
        test_code.append(code)
        ! echo -e {code} > {whole_name}
        #COMPLIE
        print("----------------- compliling")
        rough_jar = subprocess.run(["make",  name_file], capture_output=True, text=True)
        print("SUCCESSFUL COMPILATION")
        print(rough_jar.stdout.strip())

        try:
            print("-----------------  executing")
            rough_jar = subprocess.run(["./{}".format(name_file)], capture_output=True, text=True, timeout=10)
            print("EXECUTION OUT: ")
            print(rough_jar.stdout.strip())
            out = rough_jar.stdout.strip()
            out = out.replace("\n", ", ")
            exe_outputs.append(out)
            correctness_list.append(out==original_seq)
            levenshtein_list.append(levenshtein(out, original_seq))
        except:
            print("**************** execution error ( step 2)")
            print(rough_jar.stderr)
            exe_outputs.append('Execution error')
            correctness_list.append('False')
            levenshtein_list.append(50000)
            pass

    except:       
        print("**************** Execution error (step 1)")
        print(rough_jar.stderr)
        pass

######################  INITIALIZE PROCESS ########################## ( 0 )
creating file...

----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_0.cpp   -o cpp_0
-----------------  executing
**************** execution error ( step 2)
cpp_0.cpp:5:28: error: expected expression
        std::cout << i <<  ;
                           ^
1 error generated.
make: *** [cpp_0] Error 1

######################  INITIALIZE PROCESS ########################## ( 1 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_1.cpp   -o cpp_1
-----------------  executing
**************** execution error ( step 2)
cpp_1.cpp:5:28: error: expected expression
        std::cout << i <<  ;
                           ^
1 error generated.
make: *** [cpp_1] Error 1

######################  INITIALIZE PROCESS ########################## ( 2 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_2.cpp   -o cpp_2
-----------------  executing
**************** execution error ( step 2)
cpp_2.cpp:6:25: error: expected expression
        cout << i*4 <<  ;
                        ^
1 error generated.
make: *** [cpp_2] Error 1

######################  INITIALIZE PROCESS ########################## ( 3 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_3.cpp   -o cpp_3
-----------------  executing
**************** execution error ( step 2)
cpp_3.cpp:6:33: error: expected expression
        if(i < 50) std::cout << , ;
                                ^
cpp_3.cpp:6:35: error: expected expression
        if(i < 50) std::cout << , ;
                                  ^
2 errors generated.
make: *** [cpp_3] Error 1

######################  INITIALIZE PROCESS ########################## ( 4 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_4.cpp   -o cpp_4
-----------------  executing
**************** execution error ( step 2)
cpp_4.cpp:5:28: error: expected expression
        std::cout << i <<  ;
                           ^
1 error generated.
make: *** [cpp_4] Error 1

######################  INITIALIZE PROCESS ########################## ( 5 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_5.cpp   -o cpp_5
-----------------  executing
**************** execution error ( step 2)
cpp_5.cpp:4:29: error: expected expression
       std::cout << 7*i <<  ;
                            ^
1 error generated.
make: *** [cpp_5] Error 1

######################  INITIALIZE PROCESS ########################## ( 6 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_6.cpp   -o cpp_6
-----------------  executing
**************** execution error ( step 2)
cpp_6.cpp:6:27: error: expected expression
        cout << 8 * i <<  ;
                          ^
1 error generated.
make: *** [cpp_6] Error 1

######################  INITIALIZE PROCESS ########################## ( 7 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_7.cpp   -o cpp_7
-----------------  executing
EXECUTION OUT:
9
18
27
36
45
54
63
72
81
90
######################  INITIALIZE PROCESS ########################## ( 8 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_8.cpp   -o cpp_8
-----------------  executing
**************** execution error ( step 2)
cpp_8.cpp:5:28: error: expected expression
        std::cout << i <<  ;
                           ^
1 error generated.
make: *** [cpp_8] Error 1

######################  INITIALIZE PROCESS ########################## ( 9 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_9.cpp   -o cpp_9
-----------------  executing
**************** execution error ( step 2)
cpp_9.cpp:5:28: error: expected expression
        std::cout << i <<  ;
                           ^
1 error generated.
make: *** [cpp_9] Error 1

######################  INITIALIZE PROCESS ########################## ( 10 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_10.cpp   -o cpp_10
-----------------  executing
**************** execution error ( step 2)
cpp_10.cpp:6:23: error: expected expression
        cout << i <<  ;
                      ^
1 error generated.
make: *** [cpp_10] Error 1

######################  INITIALIZE PROCESS ########################## ( 11 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_11.cpp   -o cpp_11
-----------------  executing
EXECUTION OUT:
11
12
13
14
15
16
17
18
19
20
######################  INITIALIZE PROCESS ########################## ( 12 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_12.cpp   -o cpp_12
-----------------  executing
**************** execution error ( step 2)
cpp_12.cpp:5:28: error: expected expression
        std::cout << i <<  ;
                           ^
1 error generated.
make: *** [cpp_12] Error 1

######################  INITIALIZE PROCESS ########################## ( 13 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_13.cpp   -o cpp_13
-----------------  executing
EXECUTION OUT:
31
32
33
34
35
36
37
38
39
40
######################  INITIALIZE PROCESS ########################## ( 14 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_14.cpp   -o cpp_14
-----------------  executing
**************** execution error ( step 2)
cpp_14.cpp:5:28: error: expected expression
        std::cout << i <<  ;
                           ^
1 error generated.
make: *** [cpp_14] Error 1

######################  INITIALIZE PROCESS ########################## ( 15 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_15.cpp   -o cpp_15
-----------------  executing
**************** execution error ( step 2)
cpp_15.cpp:6:23: error: expected expression
        cout << i <<  ;
                      ^
1 error generated.
make: *** [cpp_15] Error 1

######################  INITIALIZE PROCESS ########################## ( 16 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_16.cpp   -o cpp_16
-----------------  executing
**************** execution error ( step 2)
cpp_16.cpp:5:28: error: expected expression
        std::cout << i <<  ;
                           ^
1 error generated.
make: *** [cpp_16] Error 1

######################  INITIALIZE PROCESS ########################## ( 17 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_17.cpp   -o cpp_17
-----------------  executing
**************** execution error ( step 2)
cpp_17.cpp:5:19: error: expected expression
        cout<<i<< ;
                  ^
1 error generated.
make: *** [cpp_17] Error 1

######################  INITIALIZE PROCESS ########################## ( 18 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_18.cpp   -o cpp_18
-----------------  executing
**************** execution error ( step 2)
cpp_18.cpp:4:28: error: expected expression
        std::cout << i <<  ;
                           ^
1 error generated.
make: *** [cpp_18] Error 1

######################  INITIALIZE PROCESS ########################## ( 19 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_19.cpp   -o cpp_19
-----------------  executing
**************** execution error ( step 2)
cpp_19.cpp:5:28: error: expected expression
        std::cout << i <<  ;
                           ^
1 error generated.
make: *** [cpp_19] Error 1

######################  INITIALIZE PROCESS ########################## ( 20 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_20.cpp   -o cpp_20
-----------------  executing
**************** execution error ( step 2)
cpp_20.cpp:5:27: error: expected expression
        std::cout << i << , ;
                          ^
cpp_20.cpp:5:29: error: expected expression
        std::cout << i << , ;
                            ^
2 errors generated.
make: *** [cpp_20] Error 1

######################  INITIALIZE PROCESS ########################## ( 21 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_21.cpp   -o cpp_21
-----------------  executing
**************** execution error ( step 2)
cpp_21.cpp:5:27: error: expected expression
        std::cout << i << , ;
                          ^
cpp_21.cpp:5:29: error: expected expression
        std::cout << i << , ;
                            ^
2 errors generated.
make: *** [cpp_21] Error 1

######################  INITIALIZE PROCESS ########################## ( 22 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_22.cpp   -o cpp_22
-----------------  executing
**************** execution error ( step 2)
cpp_22.cpp:6:23: error: expected expression
        cout << i <<  ;
                      ^
1 error generated.
make: *** [cpp_22] Error 1

######################  INITIALIZE PROCESS ########################## ( 23 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_23.cpp   -o cpp_23
-----------------  executing
**************** execution error ( step 2)
cpp_23.cpp:5:28: error: expected expression
        std::cout << i <<  ;
                           ^
1 error generated.
make: *** [cpp_23] Error 1

######################  INITIALIZE PROCESS ########################## ( 24 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_24.cpp   -o cpp_24
-----------------  executing
**************** execution error ( step 2)
cpp_24.cpp:6:34: error: expected expression
        if(i < 150) std::cout << , ;
                                 ^
cpp_24.cpp:6:36: error: expected expression
        if(i < 150) std::cout << , ;
                                   ^
2 errors generated.
make: *** [cpp_24] Error 1

######################  INITIALIZE PROCESS ########################## ( 25 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_25.cpp   -o cpp_25
-----------------  executing
**************** execution error ( step 2)
cpp_25.cpp:6:23: error: expected expression
        cout << i <<  ;
                      ^
1 error generated.
make: *** [cpp_25] Error 1

######################  INITIALIZE PROCESS ########################## ( 26 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_26.cpp   -o cpp_26
-----------------  executing
**************** execution error ( step 2)
cpp_26.cpp:4:28: error: expected expression
        std::cout << i <<  ;
                           ^
1 error generated.
make: *** [cpp_26] Error 1

######################  INITIALIZE PROCESS ########################## ( 27 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_27.cpp   -o cpp_27
-----------------  executing
**************** execution error ( step 2)
cpp_27.cpp:5:28: error: expected expression
        std::cout << i <<  ;
                           ^
1 error generated.
make: *** [cpp_27] Error 1

######################  INITIALIZE PROCESS ########################## ( 28 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_28.cpp   -o cpp_28
-----------------  executing
**************** execution error ( step 2)
cpp_28.cpp:5:28: error: expected expression
        std::cout << i <<  ;
                           ^
1 error generated.
make: *** [cpp_28] Error 1

######################  INITIALIZE PROCESS ########################## ( 29 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_29.cpp   -o cpp_29
-----------------  executing
EXECUTION OUT:
191
192
193
194
195
196
197
198
199
200
######################  INITIALIZE PROCESS ########################## ( 30 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_30.cpp   -o cpp_30
-----------------  executing
**************** execution error ( step 2)
cpp_30.cpp:6:23: error: expected expression
        cout << i <<  ;
                      ^
1 error generated.
make: *** [cpp_30] Error 1

######################  INITIALIZE PROCESS ########################## ( 31 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_31.cpp   -o cpp_31
-----------------  executing
**************** execution error ( step 2)
cpp_31.cpp:6:23: error: expected expression
        cout << i <<  ;
                      ^
1 error generated.
make: *** [cpp_31] Error 1

######################  INITIALIZE PROCESS ########################## ( 32 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_32.cpp   -o cpp_32
-----------------  executing
**************** execution error ( step 2)
cpp_32.cpp:5:28: error: expected expression
        std::cout << i <<  ;
                           ^
1 error generated.
make: *** [cpp_32] Error 1

######################  INITIALIZE PROCESS ########################## ( 33 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_33.cpp   -o cpp_33
-----------------  executing
**************** execution error ( step 2)
cpp_33.cpp:5:37: error: expected expression
        std::cout << i << (i < 50 ? ,  : );
                                    ^
cpp_33.cpp:5:40: error: expected expression
        std::cout << i << (i < 50 ? ,  : );
                                       ^
cpp_33.cpp:5:42: error: expected expression
        std::cout << i << (i < 50 ? ,  : );
                                         ^
3 errors generated.
make: *** [cpp_33] Error 1

######################  INITIALIZE PROCESS ########################## ( 34 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_34.cpp   -o cpp_34
-----------------  executing
**************** execution error ( step 2)
cpp_34.cpp:5:32: error: expected expression
        std::cout << 6 * i <<  ;
                               ^
1 error generated.
make: *** [cpp_34] Error 1

######################  INITIALIZE PROCESS ########################## ( 35 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_35.cpp   -o cpp_35
-----------------  executing
EXECUTION OUT:
7
14
21
28
35
42
49
56
63
70
######################  INITIALIZE PROCESS ########################## ( 36 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_36.cpp   -o cpp_36
-----------------  executing
EXECUTION OUT:
8
16
24
32
40
48
56
64
72
80
######################  INITIALIZE PROCESS ########################## ( 37 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_37.cpp   -o cpp_37
-----------------  executing
**************** execution error ( step 2)
cpp_37.cpp:5:41: error: expected expression
        std::cout << 9 * i << (i < 10 ? ,  : );
                                        ^
cpp_37.cpp:5:44: error: expected expression
        std::cout << 9 * i << (i < 10 ? ,  : );
                                           ^
cpp_37.cpp:5:46: error: expected expression
        std::cout << 9 * i << (i < 10 ? ,  : );
                                             ^
3 errors generated.
make: *** [cpp_37] Error 1

######################  INITIALIZE PROCESS ########################## ( 38 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_38.cpp   -o cpp_38
-----------------  executing
**************** execution error ( step 2)
cpp_38.cpp:6:23: error: expected expression
        cout << i <<  ;
                      ^
1 error generated.
make: *** [cpp_38] Error 1

######################  INITIALIZE PROCESS ########################## ( 39 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_39.cpp   -o cpp_39
-----------------  executing
**************** execution error ( step 2)
cpp_39.cpp:6:23: error: expected expression
        cout << i <<  ;
                      ^
1 error generated.
make: *** [cpp_39] Error 1

######################  INITIALIZE PROCESS ########################## ( 40 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_40.cpp   -o cpp_40
-----------------  executing
**************** execution error ( step 2)
cpp_40.cpp:5:28: error: expected expression
        std::cout << i <<  ;
                           ^
1 error generated.
make: *** [cpp_40] Error 1

######################  INITIALIZE PROCESS ########################## ( 41 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_41.cpp   -o cpp_41
-----------------  executing
**************** execution error ( step 2)
cpp_41.cpp:6:23: error: expected expression
        cout << i <<  ;
                      ^
1 error generated.
make: *** [cpp_41] Error 1

######################  INITIALIZE PROCESS ########################## ( 42 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_42.cpp   -o cpp_42
-----------------  executing
**************** execution error ( step 2)
cpp_42.cpp:6:23: error: expected expression
        cout << i <<  ;
                      ^
1 error generated.
make: *** [cpp_42] Error 1

######################  INITIALIZE PROCESS ########################## ( 43 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_43.cpp   -o cpp_43
-----------------  executing
**************** execution error ( step 2)
cpp_43.cpp:5:28: error: expected expression
        std::cout << i <<  ;
                           ^
1 error generated.
make: *** [cpp_43] Error 1

######################  INITIALIZE PROCESS ########################## ( 44 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_44.cpp   -o cpp_44
-----------------  executing
**************** execution error ( step 2)
cpp_44.cpp:5:28: error: expected expression
        std::cout << i <<  ;
                           ^
1 error generated.
make: *** [cpp_44] Error 1

######################  INITIALIZE PROCESS ########################## ( 45 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_45.cpp   -o cpp_45
-----------------  executing
EXECUTION OUT:
51
52
53
54
55
56
57
58
59
60
######################  INITIALIZE PROCESS ########################## ( 46 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_46.cpp   -o cpp_46
-----------------  executing
**************** execution error ( step 2)
cpp_46.cpp:5:28: error: expected expression
        std::cout << i <<  ;
                           ^
1 error generated.
make: *** [cpp_46] Error 1

######################  INITIALIZE PROCESS ########################## ( 47 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_47.cpp   -o cpp_47
-----------------  executing
**************** execution error ( step 2)
cpp_47.cpp:5:28: error: expected expression
        std::cout << i <<  ;
                           ^
1 error generated.
make: *** [cpp_47] Error 1

######################  INITIALIZE PROCESS ########################## ( 48 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_48.cpp   -o cpp_48
-----------------  executing
**************** execution error ( step 2)
cpp_48.cpp:6:22: error: expected expression
        cout << i << , ;
                     ^
cpp_48.cpp:6:24: error: expected expression
        cout << i << , ;
                       ^
2 errors generated.
make: *** [cpp_48] Error 1

######################  INITIALIZE PROCESS ########################## ( 49 )
creating file...
----------------- compliling
SUCCESSFUL COMPILATION
c++     cpp_49.cpp   -o cpp_49
-----------------  executing
**************** execution error ( step 2)
cpp_49.cpp:5:27: error: expected expression
        std::cout << i << , ;
                          ^
cpp_49.cpp:5:29: error: expected expression
        std::cout << i << , ;
                            ^
2 errors generated.
make: *** [cpp_49] Error 1

######################  INITIALIZE PROCESS ########################## ( 50 )
creating file...
----------------- compliling

In [91]:
exe_outputs

['Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '9, 18, 27, 36, 45, 54, 63, 72, 81, 90',
 'Execution error',
 'Execution error',
 'Execution error',
 '11, 12, 13, 14, 15, 16, 17, 18, 19, 20',
 'Execution error',
 '31, 32, 33, 34, 35, 36, 37, 38, 39, 40',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '191, 192, 193, 194, 195, 196, 197, 198, 199, 200',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '7, 14, 21, 28, 35, 42, 49, 56, 63, 70',
 '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '51, 52, 53, 54, 55, 56, 57, 58, 59, 60',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '171, 172, 173, 174, 175, 176, 177, 178, 179, 180',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '6, 12, 18, 24, 30, 36, 42, 48, 54, 60',
 '7, 14, 21, 28, 35, 42, 49, 56, 63, 70',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '111, 112, 113, 114, 115, 116, 117, 118, 119, 120',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '7, 14, 21, 28, 35, 42, 49, 56, 63, 70',
 '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
 '9, 18, 27, 36, 45, 54, 63, 72, 81, 90',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '0, 1, 2, 5, 12, 29, 70, 169, 408, 985',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000',
 'Execution error',
 'Execution error',
 'Execution error',
 '1, 10, 11, 100, 101, 110, 111, 1000, 1001, 1010',
 'Execution error',
 '1, 2, 145, 40585',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '1, 0, 11, 0, 01, 10, 111, 0, 01, 10',
 '0, 1, 81, 512, 2401, 4913, 5832, 17576, 19683, 234256',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '4, 6, 9, 10, 14, 15, 21, 22, 25, 26',
 '0000000001, 0000000010, 0000000100, 0000001000, 0000010000, 0000100000, 0001000000, 0010000000, 0100000000, 1000000000',
 '0, 1, 81, 512, 2401, 4913, 5832, 17576, 19683, 234256',
 '1, 2, 145, 40585',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000',
 'Execution error',
 'Execution error',
 'Execution error',
 '0000000001, 0000000010, 0000000100, 0000001000, 0000010000, 0000100000, 0001000000, 0010000000, 0100000000, 1000000000',
 '0, 1, 81, 512, 2401, 4913, 5832, 17576, 19683, 234256',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '1, 11, 111, 1111, 11111, 111111, 1111111, 11111111, 111111111, 1111111111',
 '31, 311, 3111, 31111, 311111, 3111111, 31111111, 311111111',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '2, 4, 8, 16, 32, 64, 128, 256, 512, 1024',
 'Execution error',
 'Execution error',
 '1, 11, 111, 1111, 11111, 111111, 1111111, 11111111, 111111111, 1111111111',
 '31, 311, 3111, 31111, 311111, 3111111, 31111111, 311111111',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '19, 31, 61, 89, 107, 127, 521, 607, 1279, 2203',
 'Execution error',
 'Execution error',
 '1, 8, 10, 18, 19, 100, 101, 108, 109, 110',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '1, 11, 111, 1111, 11111, 111111, 1111111, 11111111, 111111111, 1111111111',
 '31, 311, 3111, 31111, 311111, 3111111, 31111111, 311111111',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '19, 31, 61, 89, 107, 127, 521, 607, 1279, 2203',
 'Execution error',
 'Execution error',
 '1, 8, 10, 18, 19, 100, 101, 108, 109, 110',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '1, 11, 111, 1111, 11111, 111111, 1111111, 11111111, 111111111, 1111111111',
 '31, 311, 3111, 31111, 311111, 3111111, 31111111, 311111111',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '1, 2, 145, 40585',
 '19, 31, 61, 89, 107, 127, 521, 607, 1279, 2203',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '2, 4, 8, 16, 32, 64, 128, 256, 512, 1024',
 'Execution error',
 'Execution error',
 '1, 11, 111, 1111, 11111, 111111, 1111111, 11111111, 111111111, 1111111111',
 '31, 311, 3111, 31111, 311111, 3111111, 31111111, 311111111',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '19, 31, 61, 89, 107, 127, 521, 607, 1279, 2203',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '20, 48, 95, 234, 282, 296, 352, 402, 428, 481',
 'Execution error',
 'Execution error',
 'Execution error',
 '26, 50, 114, 148, 160, 170, 274, 347, 432, 497',
 '48, 94, 176, 177, 219, 276, 282, 283, 459, 488',
 'Execution error',
 '15, 95, 115, 195, 240, 318, 326, 350, 432, 450',
 '134, 224, 293, 378, 379, 395, 434, 451, 482, 496',
 '23, 93, 142, 145, 245, 266, 296, 317, 428, 495',
 '18, 39, 71, 194, 197, 219, 263, 270, 416, 473',
 'Execution error',
 'Execution error',
 '34, 92, 164, 165, 209, 296, 414, 456, 467, 494',
 'Execution error',
 'Execution error',
 '12, 36, 96, 119, 171, 213, 221, 232, 363, 451',
 '38, 91, 142, 197, 215, 313, 316, 319, 423, 466',
 'Execution error',
 '27, 101, 105, 164, 245, 290, 304, 441, 449, 490',
 'Execution error',
 'Execution error',
 '187, 218, 260, 295, 301, 314, 379, 410, 452, 469',
 'Execution error',
 'Execution error',
 '26, 94, 98, 137, 176, 301, 323, 330, 372, 444',
 '39, 81, 88, 210, 215, 378, 416, 430, 439, 490',
 'Execution error',
 'Execution error',
 '90, 203, 212, 235, 270, 324, 342, 352, 371, 417',
 '20, 48, 95, 234, 282, 296, 352, 402, 428, 481',
 '62, 98, 130, 154, 290, 315, 324, 385, 408, 447',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '139, 252, 272, 281, 304, 361, 370, 415, 438, 500',
 '15, 95, 115, 195, 240, 318, 326, 350, 432, 450',
 '134, 224, 293, 378, 379, 395, 434, 451, 482, 496',
 '23, 93, 142, 145, 245, 266, 296, 317, 428, 495',
 '18, 39, 71, 194, 197, 219, 263, 270, 416, 473',
 'Execution error',
 '26, 40, 202, 267, 282, 340, 359, 408, 410, 495',
 'Execution error',
 '16, 119, 121, 123, 135, 139, 285, 311, 409, 412',
 '8, 11, 12, 103, 116, 196, 247, 254, 389, 427',
 'Execution error',
 '38, 91, 142, 197, 215, 313, 316, 319, 423, 466',
 '7, 42, 147, 201, 213, 248, 310, 332, 436, 479',
 '27, 101, 105, 164, 245, 290, 304, 441, 449, 490',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '26, 94, 98, 137, 176, 301, 323, 330, 372, 444',
 '39, 81, 88, 210, 215, 378, 416, 430, 439, 490',
 '29, 57, 68, 120, 134, 140, 173, 197, 283, 313',
 '24, 26, 36, 40, 184, 226, 244, 384, 391, 423',
 '90, 203, 212, 235, 270, 324, 342, 352, 371, 417',
 'Execution error',
 '62, 98, 130, 154, 290, 315, 324, 385, 408, 447',
 'Execution error',
 '128, 151, 153, 217, 224, 332, 382, 400, 450, 478',
 'Execution error',
 'Execution error',
 '139, 252, 272, 281, 304, 361, 370, 415, 438, 500',
 '15, 95, 115, 195, 240, 318, 326, 350, 432, 450',
 'Execution error',
 '23, 93, 142, 145, 245, 266, 296, 317, 428, 495',
 'Execution error',
 '9, 84, 144, 170, 325, 393, 401, 405, 435, 497',
 '26, 40, 202, 267, 282, 340, 359, 408, 410, 495',
 '34, 92, 164, 165, 209, 296, 414, 456, 467, 494',
 '16, 119, 121, 123, 135, 139, 285, 311, 409, 412',
 'Execution error',
 'Execution error',
 '38, 91, 142, 197, 215, 313, 316, 319, 423, 466',
 'Execution error',
 '27, 101, 105, 164, 245, 290, 304, 441, 449, 490',
 'Execution error',
 '72, 106, 139, 165, 171, 192, 199, 429, 453, 477',
 '187, 218, 260, 295, 301, 314, 379, 410, 452, 469',
 'Execution error',
 '3, 11, 84, 144, 156, 177, 188, 199, 229, 284',
 'Execution error',
 '39, 81, 88, 210, 215, 378, 416, 430, 439, 490',
 '29, 57, 68, 120, 134, 140, 173, 197, 283, 313',
 '24, 26, 36, 40, 184, 226, 244, 384, 391, 423',
 '90, 203, 212, 235, 270, 324, 342, 352, 371, 417',
 'Execution error',
 '62, 98, 130, 154, 290, 315, 324, 385, 408, 447',
 'Execution error',
 '128, 151, 153, 217, 224, 332, 382, 400, 450, 478',
 '26, 50, 114, 148, 160, 170, 274, 347, 432, 497',
 '48, 94, 176, 177, 219, 276, 282, 283, 459, 488',
 '139, 252, 272, 281, 304, 361, 370, 415, 438, 500',
 'Execution error',
 '134, 224, 293, 378, 379, 395, 434, 451, 482, 496',
 'Execution error',
 '18, 39, 71, 194, 197, 219, 263, 270, 416, 473',
 '9, 84, 144, 170, 325, 393, 401, 405, 435, 497',
 'Execution error',
 '34, 92, 164, 165, 209, 296, 414, 456, 467, 494',
 '16, 119, 121, 123, 135, 139, 285, 311, 409, 412',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '27, 101, 105, 164, 245, 290, 304, 441, 449, 490',
 'Execution error',
 '72, 106, 139, 165, 171, 192, 199, 429, 453, 477',
 'Execution error',
 '29, 63, 95, 140, 150, 190, 221, 437, 482, 491',
 'Execution error',
 '26, 94, 98, 137, 176, 301, 323, 330, 372, 444',
 '39, 81, 88, 210, 215, 378, 416, 430, 439, 490',
 '29, 57, 68, 120, 134, 140, 173, 197, 283, 313',
 '24, 26, 36, 40, 184, 226, 244, 384, 391, 423',
 'Execution error',
 'Execution error',
 'Execution error',
 'Execution error',
 '128, 151, 153, 217, 224, 332, 382, 400, 450, 478',
 '26, 50, 114, 148, 160, 170, 274, 347, 432, 497',
 '48, 94, 176, 177, 219, 276, 282, 283, 459, 488',
 '139, 252, 272, 281, 304, 361, 370, 415, 438, 500',
 '15, 95, 115, 195, 240, 318, 326, 350, 432, 450',
 'Execution error',
 '23, 93, 142, 145, 245, 266, 296, 317, 428, 495',
 'Execution error',
 '9, 84, 144, 170, 325, 393, 401, 405, 435, 497',
 '26, 40, 202, 267, 282, 340, 359, 408, 410, 495',
 '34, 92, 164, 165, 209, 296, 414, 456, 467, 494',
 '16, 119, 121, 123, 135, 139, 285, 311, 409, 412',
 'Execution error',
 '12, 36, 96, 119, 171, 213, 221, 232, 363, 451',
 '38, 91, 142, 197, 215, 313, 316, 319, 423, 466',
 'Execution error',
 '27, 101, 105, 164, 245, 290, 304, 441, 449, 490',
 'Execution error',
 '72, 106, 139, 165, 171, 192, 199, 429, 453, 477',
 '187, 218, 260, 295, 301, 314, 379, 410, 452, 469',
 '29, 63, 95, 140, 150, 190, 221, 437, 482, 491',
 '3, 11, 84, 144, 156, 177, 188, 199, 229, 284',
 '26, 94, 98, 137, 176, 301, 323, 330, 372, 444',
 'Execution error']

In [88]:
correctness_list

['False',
 'False',
 'False',
 'False',
 'False',
 'False',
 'False',
 True,
 'False',
 'False',
 'False',
 True,
 'False',
 True,
 'False']

In [89]:
levenshtein_list

[50000,
 50000,
 50000,
 50000,
 50000,
 50000,
 50000,
 0,
 50000,
 50000,
 50000,
 0,
 50000,
 0,
 50000]

In [92]:
cpp_df["exe_out"] = exe_outputs
cpp_df["correct_execution"] = correctness_list
cpp_df["Levenshtein"] = levenshtein_list
cpp_df

,sequence,complexity,length_type,language,q_length,GPT4_answer,a_length,temperature,real_code,print_code,no_code,explanation,no_sense,exe_out,correct_execution,Levenshtein
5900,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",1.0,0.0,C++,165.0,```cpp\n#include <iostream>\n\nint main() {\n ...,135.0,1.000,0.0,0,0.0,0.0,0,Execution error,False,50000
5901,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",1.0,0.0,C++,166.0,```cpp\n#include <iostream>\n\nint main() {\n ...,135.0,1.000,0.0,0,0.0,0.0,0,Execution error,False,50000
5902,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",1.0,0.0,C++,167.0,```cpp\n#include <iostream>\nusing namespace s...,151.0,1.000,0.0,0,0.0,0.0,0,Execution error,False,50000
5903,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",1.0,0.0,C++,168.0,```cpp\n#include <iostream>\n\nint main() {\n ...,166.0,1.000,0.0,0,0.0,0.0,0,Execution error,False,50000
5904,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",1.0,0.0,C++,168.0,```cpp\n#include <iostream>\n\nint main() {\n ...,135.0,1.000,0.0,0,0.0,0.0,0,Execution error,False,50000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6485,"187, 218, 260, 295, 301, 314, 379, 410, 452, 469",4.0,0.0,C++,178.0,```cpp\n#include <iostream>\n\nint main() {\n ...,220.0,0.001,0.0,0,0.0,0.0,0,"187, 218, 260, 295, 301, 314, 379, 410, 452, 469",True,0
6486,"29, 63, 95, 140, 150, 190, 221, 437, 482, 491",4.0,0.0,C++,175.0,```cpp\n#include <iostream>\n\nint main() {\n ...,212.0,0.001,0.0,0,0.0,0.0,0,"29, 63, 95, 140, 150, 190, 221, 437, 482, 491",True,0
6487,"3, 11, 84, 144, 156, 177, 188, 199, 229, 284",4.0,0.0,C++,174.0,```cpp\n#include <iostream>\n\nint main() {\n ...,211.0,0.001,0.0,0,0.0,0.0,0,"3, 11, 84, 144, 156, 177, 188, 199, 229, 284",True,0
6488,"26, 94, 98, 137, 176, 301, 323, 330, 372, 444",4.0,0.0,C++,175.0,```cpp\n#include <iostream>\n\nint main() {\n ...,212.0,0.001,0.0,0,0.0,0.0,0,"26, 94, 98, 137, 176, 301, 323, 330, 372, 444",True,0
6489,"39, 81, 88, 210, 215, 378, 416, 430, 439, 490",4.0,0.0,C++,175.0,```cpp\n#include <iostream>\n\nint main() {\n ...,241.0,0.001,0.0,0,0.0,0.0,0,Execution error,False,50000

In [93]:
cpp_df.to_csv("Cpp_evaluation.csv", index=False)

# R

In [94]:
import pandas as pd
import subprocess
import time
import copy
from enchant.utils import levenshtein

In [95]:
OIA_ds = pd.read_csv("/Users/beto/Documents/Projects/medLLM/no_small_seqs_clean.csv")
r_df = copy.deepcopy(OIA_ds[OIA_ds["language"] == "R"])
original_sequences = r_df["sequence"].values

r_code_list = (OIA_ds[OIA_ds["language"] == "R"])["GPT4_answer"].values
total_questions = len(r_code_list)

In [96]:
r_df

,sequence,complexity,length_type,language,q_length,GPT4_answer,a_length,temperature,real_code,print_code,no_code,explanation,no_sense,exe_out,correct_execution,Levenshtein
8260,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",1.0,0.0,R,163.0,"```r\nseq(2, 20, by = 2)\n```",27.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
8261,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",1.0,0.0,R,164.0,"```r\nseq(3, 30, by=3)\n```",25.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
8262,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",1.0,0.0,R,165.0,"```r\nseq(4, 40, by=4)\n```",25.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
8263,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",1.0,0.0,R,166.0,"```r\nseq(5, 50, by=5)\n```",25.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
8264,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",1.0,0.0,R,166.0,"```r\nseq(6, 60, by = 6)\n```",27.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8845,"187, 218, 260, 295, 301, 314, 379, 410, 452, 469",4.0,0.0,R,176.0,"```r\nseq <- c(187, 218, 260, 295, 301, 314, 3...",78.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN
8846,"29, 63, 95, 140, 150, 190, 221, 437, 482, 491",4.0,0.0,R,173.0,"```r\nsequence <- c(29, 63, 95, 140, 150, 190,...",85.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN
8847,"3, 11, 84, 144, 156, 177, 188, 199, 229, 284",4.0,0.0,R,172.0,"```r\nsequence <- c(3, 11, 84, 144, 156, 177, ...",84.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN
8848,"26, 94, 98, 137, 176, 301, 323, 330, 372, 444",4.0,0.0,R,173.0,"```r\nsequence <- c(26, 94, 98, 137, 176, 301,...",85.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN
8849,"39, 81, 88, 210, 215, 378, 416, 430, 439, 490",4.0,0.0,R,173.0,"```r\nseq <- c(39, 81, 88, 210, 215, 378, 416,...",75.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN

In [97]:
r_code_list[1:5]

array(['```r\nseq(3, 30, by=3)\n```', '```r\nseq(4, 40, by=4)\n```',
       '```r\nseq(5, 50, by=5)\n```', '```r\nseq(6, 60, by = 6)\n```'],
      dtype=object)

In [98]:
len(r_code_list)

590

In [134]:

counter = -1
exe_outputs = []
levenshtein_list = []
correctness_list = []
test_code = []

for code in r_code_list:#[0:15]:
    code = code.replace("```r" + "\n","\"")
    code = code.replace("```R" + "\n","\"")
    code = code.replace("\n"+ "```","\"")
    
    
    #print(code)
    counter += 1
    name_file = "r_" + str(counter)
    surname_file =  '.R'
    whole_name = name_file + surname_file
    
    original_seq = original_sequences[counter]
    
    print("######################  INITIALIZE PROCESS ########################## (", str(counter), ")")
    try:
        print("creating file...")
        test_code.append(code)
        ! echo -e {code} > {whole_name}
        
        rough_jar = subprocess.run(["Rscript", whole_name], capture_output=True, text=True, timeout=10)
        print("EXECUTION OUT: ")
        # print(rough_jar.stdout.strip())
        out = rough_jar.stdout.strip()
        #out = out.replace("\n", ", ")
        out = out.replace("[1]  ","")
        out = out.replace("[1] ","")
        out = out.replace("  ",", ")
        out = out.replace(" ",", ")
        out = out.replace(",, ", ", ")
        exe_outputs.append(out)
        correctness_list.append(out==original_seq)
        levenshtein_list.append(levenshtein(out, original_seq))
        print("out", out)
        print("original", original_seq)
    except:
        print("**************** execution error ( step 2)")
        print(rough_jar.stderr)
        exe_outputs.append('Execution error')
        correctness_list.append('False')
        levenshtein_list.append(50000)
        pass

######################  INITIALIZE PROCESS ########################## ( 0 )
creating file...

EXECUTION OUT:
out 2, 4, 6, 8, 10, 12, 14, 16, 18, 20
original 2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 1 )
creating file...
EXECUTION OUT:
out 3, 6, 9, 12, 15, 18, 21, 24, 27, 30
original 3, 6, 9, 12, 15, 18, 21, 24, 27, 30
######################  INITIALIZE PROCESS ########################## ( 2 )
creating file...
EXECUTION OUT:
out 4, 8, 12, 16, 20, 24, 28, 32, 36, 40
original 4, 8, 12, 16, 20, 24, 28, 32, 36, 40
######################  INITIALIZE PROCESS ########################## ( 3 )
creating file...
EXECUTION OUT:
out 5, 10, 15, 20, 25, 30, 35, 40, 45, 50
original 5, 10, 15, 20, 25, 30, 35, 40, 45, 50
######################  INITIALIZE PROCESS ########################## ( 4 )
creating file...
EXECUTION OUT:
out 6, 12, 18, 24, 30, 36, 42, 48, 54, 60
original 6, 12, 18, 24, 30, 36, 42, 48, 54, 60
######################  INITIALIZE PROCESS ########################## ( 5 )
creating file...
EXECUTION OUT:
out 7, 14, 21, 28, 35, 42, 49, 56, 63, 70
original 7, 14, 21, 28, 35, 42, 49, 56, 63, 70
######################  INITIALIZE PROCESS ########################## ( 6 )
creating file...
EXECUTION OUT:
out 8, 16, 24, 32, 40, 48, 56, 64, 72, 80
original 8, 16, 24, 32, 40, 48, 56, 64, 72, 80
######################  INITIALIZE PROCESS ########################## ( 7 )
creating file...
EXECUTION OUT:
out 9, 18, 27, 36, 45, 54, 63, 72, 81, 90
original 9, 18, 27, 36, 45, 54, 63, 72, 81, 90
######################  INITIALIZE PROCESS ########################## ( 8 )
creating file...
EXECUTION OUT:
out 10, 20, 30, 40, 50, 60, 70, 80, 90, 100
original 10, 20, 30, 40, 50, 60, 70, 80, 90, 100
######################  INITIALIZE PROCESS ########################## ( 9 )
creating file...
EXECUTION OUT:
out 1, 3, 5, 7, 9, 11, 13, 15, 17, 19
original 1, 3, 5, 7, 9, 11, 13, 15, 17, 19
######################  INITIALIZE PROCESS ########################## ( 10 )
creating file...
EXECUTION OUT:
out 2, 4, 6, 8, 10, 12, 14, 16, 18, 20
original 2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 11 )
creating file...
EXECUTION OUT:
out 11, 12, 13, 14, 15, 16, 17, 18, 19, 20
original 11, 12, 13, 14, 15, 16, 17, 18, 19, 20
######################  INITIALIZE PROCESS ########################## ( 12 )
creating file...
EXECUTION OUT:
out 21, 22, 23, 24, 25, 26, 27, 28, 29, 30
original 21, 22, 23, 24, 25, 26, 27, 28, 29, 30
######################  INITIALIZE PROCESS ########################## ( 13 )
creating file...
EXECUTION OUT:
out 31, 32, 33, 34, 35, 36, 37, 38, 39, 40
original 31, 32, 33, 34, 35, 36, 37, 38, 39, 40
######################  INITIALIZE PROCESS ########################## ( 14 )
creating file...
EXECUTION OUT:
out 41, 42, 43, 44, 45, 46, 47, 48, 49, 50
original 41, 42, 43, 44, 45, 46, 47, 48, 49, 50
######################  INITIALIZE PROCESS ########################## ( 15 )
creating file...
EXECUTION OUT:
out 51, 52, 53, 54, 55, 56, 57, 58, 59, 60
original 51, 52, 53, 54, 55, 56, 57, 58, 59, 60
######################  INITIALIZE PROCESS ########################## ( 16 )
creating file...
EXECUTION OUT:
out 61, 62, 63, 64, 65, 66, 67, 68, 69, 70
original 61, 62, 63, 64, 65, 66, 67, 68, 69, 70
######################  INITIALIZE PROCESS ########################## ( 17 )
creating file...
EXECUTION OUT:
out 71, 72, 73, 74, 75, 76, 77, 78, 79, 80
original 71, 72, 73, 74, 75, 76, 77, 78, 79, 80
######################  INITIALIZE PROCESS ########################## ( 18 )
creating file...
EXECUTION OUT:
out 81, 82, 83, 84, 85, 86, 87, 88, 89, 90
original 81, 82, 83, 84, 85, 86, 87, 88, 89, 90
######################  INITIALIZE PROCESS ########################## ( 19 )
creating file...
EXECUTION OUT:
out 91, 92, 93, 94, 95, 96, 97, 98, 99, 100
original 91, 92, 93, 94, 95, 96, 97, 98, 99, 100
######################  INITIALIZE PROCESS ########################## ( 20 )
creating file...
EXECUTION OUT:
out 101, 102, 103, 104, 105, 106, 107, 108, 109, 110
original 101, 102, 103, 104, 105, 106, 107, 108, 109, 110
######################  INITIALIZE PROCESS ########################## ( 21 )
creating file...
EXECUTION OUT:
out 111, 112, 113, 114, 115, 116, 117, 118, 119, 120
original 111, 112, 113, 114, 115, 116, 117, 118, 119, 120
######################  INITIALIZE PROCESS ########################## ( 22 )
creating file...
EXECUTION OUT:
out 121, 122, 123, 124, 125, 126, 127, 128, 129, 130
original 121, 122, 123, 124, 125, 126, 127, 128, 129, 130
######################  INITIALIZE PROCESS ########################## ( 23 )
creating file...
EXECUTION OUT:
out 131, 132, 133, 134, 135, 136, 137, 138, 139, 140
original 131, 132, 133, 134, 135, 136, 137, 138, 139, 140
######################  INITIALIZE PROCESS ########################## ( 24 )
creating file...
EXECUTION OUT:
out 141, 142, 143, 144, 145, 146, 147, 148, 149, 150
original 141, 142, 143, 144, 145, 146, 147, 148, 149, 150
######################  INITIALIZE PROCESS ########################## ( 25 )
creating file...
EXECUTION OUT:
out 151, 152, 153, 154, 155, 156, 157, 158, 159, 160
original 151, 152, 153, 154, 155, 156, 157, 158, 159, 160
######################  INITIALIZE PROCESS ########################## ( 26 )
creating file...
EXECUTION OUT:
out 161, 162, 163, 164, 165, 166, 167, 168, 169, 170
original 161, 162, 163, 164, 165, 166, 167, 168, 169, 170
######################  INITIALIZE PROCESS ########################## ( 27 )
creating file...
EXECUTION OUT:
out 171, 172, 173, 174, 175, 176, 177, 178, 179, 180
original 171, 172, 173, 174, 175, 176, 177, 178, 179, 180
######################  INITIALIZE PROCESS ########################## ( 28 )
creating file...
EXECUTION OUT:
out 181, 182, 183, 184, 185, 186, 187, 188, 189, 190
original 181, 182, 183, 184, 185, 186, 187, 188, 189, 190
######################  INITIALIZE PROCESS ########################## ( 29 )
creating file...
EXECUTION OUT:
out 191, 192, 193, 194, 195, 196, 197, 198, 199, 200
original 191, 192, 193, 194, 195, 196, 197, 198, 199, 200
######################  INITIALIZE PROCESS ########################## ( 30 )
creating file...
EXECUTION OUT:
out 2, 4, 6, 8, 10, 12, 14, 16, 18, 20
original 2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 31 )
creating file...
EXECUTION OUT:
out 3, 6, 9, 12, 15, 18, 21, 24, 27, 30
original 3, 6, 9, 12, 15, 18, 21, 24, 27, 30
######################  INITIALIZE PROCESS ########################## ( 32 )
creating file...
EXECUTION OUT:
out 4, 8, 12, 16, 20, 24, 28, 32, 36, 40
original 4, 8, 12, 16, 20, 24, 28, 32, 36, 40
######################  INITIALIZE PROCESS ########################## ( 33 )
creating file...
EXECUTION OUT:
out 5, 10, 15, 20, 25, 30, 35, 40, 45, 50
original 5, 10, 15, 20, 25, 30, 35, 40, 45, 50
######################  INITIALIZE PROCESS ########################## ( 34 )
creating file...
EXECUTION OUT:
out 6, 12, 18, 24, 30, 36, 42, 48, 54, 60
original 6, 12, 18, 24, 30, 36, 42, 48, 54, 60
######################  INITIALIZE PROCESS ########################## ( 35 )
creating file...
EXECUTION OUT:
out 7, 14, 21, 28, 35, 42, 49, 56, 63, 70
original 7, 14, 21, 28, 35, 42, 49, 56, 63, 70
######################  INITIALIZE PROCESS ########################## ( 36 )
creating file...
EXECUTION OUT:
out 8, 16, 24, 32, 40, 48, 56, 64, 72, 80
original 8, 16, 24, 32, 40, 48, 56, 64, 72, 80
######################  INITIALIZE PROCESS ########################## ( 37 )
creating file...
EXECUTION OUT:
out 9, 18, 27, 36, 45, 54, 63, 72, 81, 90
original 9, 18, 27, 36, 45, 54, 63, 72, 81, 90
######################  INITIALIZE PROCESS ########################## ( 38 )
creating file...
EXECUTION OUT:
out 10, 20, 30, 40, 50, 60, 70, 80, 90, 100
original 10, 20, 30, 40, 50, 60, 70, 80, 90, 100
######################  INITIALIZE PROCESS ########################## ( 39 )
creating file...
EXECUTION OUT:
out 1, 3, 5, 7, 9, 11, 13, 15, 17, 19
original 1, 3, 5, 7, 9, 11, 13, 15, 17, 19
######################  INITIALIZE PROCESS ########################## ( 40 )
creating file...
EXECUTION OUT:
out 2, 4, 6, 8, 10, 12, 14, 16, 18, 20
original 2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 41 )
creating file...
EXECUTION OUT:
out 11, 12, 13, 14, 15, 16, 17, 18, 19, 20
original 11, 12, 13, 14, 15, 16, 17, 18, 19, 20
######################  INITIALIZE PROCESS ########################## ( 42 )
creating file...
EXECUTION OUT:
out 21, 22, 23, 24, 25, 26, 27, 28, 29, 30
original 21, 22, 23, 24, 25, 26, 27, 28, 29, 30
######################  INITIALIZE PROCESS ########################## ( 43 )
creating file...
EXECUTION OUT:
out 31, 32, 33, 34, 35, 36, 37, 38, 39, 40
original 31, 32, 33, 34, 35, 36, 37, 38, 39, 40
######################  INITIALIZE PROCESS ########################## ( 44 )
creating file...
EXECUTION OUT:
out 41, 42, 43, 44, 45, 46, 47, 48, 49, 50
original 41, 42, 43, 44, 45, 46, 47, 48, 49, 50
######################  INITIALIZE PROCESS ########################## ( 45 )
creating file...
EXECUTION OUT:
out 51, 52, 53, 54, 55, 56, 57, 58, 59, 60
original 51, 52, 53, 54, 55, 56, 57, 58, 59, 60
######################  INITIALIZE PROCESS ########################## ( 46 )
creating file...
EXECUTION OUT:
out 61, 62, 63, 64, 65, 66, 67, 68, 69, 70
original 61, 62, 63, 64, 65, 66, 67, 68, 69, 70
######################  INITIALIZE PROCESS ########################## ( 47 )
creating file...
EXECUTION OUT:
out 71, 72, 73, 74, 75, 76, 77, 78, 79, 80
original 71, 72, 73, 74, 75, 76, 77, 78, 79, 80
######################  INITIALIZE PROCESS ########################## ( 48 )
creating file...
EXECUTION OUT:
out 81, 82, 83, 84, 85, 86, 87, 88, 89, 90
original 81, 82, 83, 84, 85, 86, 87, 88, 89, 90
######################  INITIALIZE PROCESS ########################## ( 49 )
creating file...
EXECUTION OUT:
out 91, 92, 93, 94, 95, 96, 97, 98, 99, 100
original 91, 92, 93, 94, 95, 96, 97, 98, 99, 100
######################  INITIALIZE PROCESS ########################## ( 50 )
creating file...
EXECUTION OUT:
out 101, 102, 103, 104, 105, 106, 107, 108, 109, 110
original 101, 102, 103, 104, 105, 106, 107, 108, 109, 110
######################  INITIALIZE PROCESS ########################## ( 51 )
creating file...
EXECUTION OUT:
out 111, 112, 113, 114, 115, 116, 117, 118, 119, 120
original 111, 112, 113, 114, 115, 116, 117, 118, 119, 120
######################  INITIALIZE PROCESS ########################## ( 52 )
creating file...
EXECUTION OUT:
out 121, 122, 123, 124, 125, 126, 127, 128, 129, 130
original 121, 122, 123, 124, 125, 126, 127, 128, 129, 130
######################  INITIALIZE PROCESS ########################## ( 53 )
creating file...
EXECUTION OUT:
out 131, 132, 133, 134, 135, 136, 137, 138, 139, 140
original 131, 132, 133, 134, 135, 136, 137, 138, 139, 140
######################  INITIALIZE PROCESS ########################## ( 54 )
creating file...
EXECUTION OUT:
out 141, 142, 143, 144, 145, 146, 147, 148, 149, 150
original 141, 142, 143, 144, 145, 146, 147, 148, 149, 150
######################  INITIALIZE PROCESS ########################## ( 55 )
creating file...
EXECUTION OUT:
out 151, 152, 153, 154, 155, 156, 157, 158, 159, 160
original 151, 152, 153, 154, 155, 156, 157, 158, 159, 160
######################  INITIALIZE PROCESS ########################## ( 56 )
creating file...
EXECUTION OUT:
out 161, 162, 163, 164, 165, 166, 167, 168, 169, 170
original 161, 162, 163, 164, 165, 166, 167, 168, 169, 170
######################  INITIALIZE PROCESS ########################## ( 57 )
creating file...
EXECUTION OUT:
out 171, 172, 173, 174, 175, 176, 177, 178, 179, 180
original 171, 172, 173, 174, 175, 176, 177, 178, 179, 180
######################  INITIALIZE PROCESS ########################## ( 58 )
creating file...
EXECUTION OUT:
out 181, 182, 183, 184, 185, 186, 187, 188, 189, 190
original 181, 182, 183, 184, 185, 186, 187, 188, 189, 190
######################  INITIALIZE PROCESS ########################## ( 59 )
creating file...
EXECUTION OUT:
out 191, 192, 193, 194, 195, 196, 197, 198, 199, 200
original 191, 192, 193, 194, 195, 196, 197, 198, 199, 200
######################  INITIALIZE PROCESS ########################## ( 60 )
creating file...
EXECUTION OUT:
out 2, 4, 6, 8, 10, 12, 14, 16, 18, 20
original 2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 61 )
creating file...
EXECUTION OUT:
out 3, 6, 9, 12, 15, 18, 21, 24, 27, 30
original 3, 6, 9, 12, 15, 18, 21, 24, 27, 30
######################  INITIALIZE PROCESS ########################## ( 62 )
creating file...
EXECUTION OUT:
out 4, 8, 12, 16, 20, 24, 28, 32, 36, 40
original 4, 8, 12, 16, 20, 24, 28, 32, 36, 40
######################  INITIALIZE PROCESS ########################## ( 63 )
creating file...
EXECUTION OUT:
out 5, 10, 15, 20, 25, 30, 35, 40, 45, 50
original 5, 10, 15, 20, 25, 30, 35, 40, 45, 50
######################  INITIALIZE PROCESS ########################## ( 64 )
creating file...
EXECUTION OUT:
out 6, 12, 18, 24, 30, 36, 42, 48, 54, 60
original 6, 12, 18, 24, 30, 36, 42, 48, 54, 60
######################  INITIALIZE PROCESS ########################## ( 65 )
creating file...
EXECUTION OUT:
out 7, 14, 21, 28, 35, 42, 49, 56, 63, 70
original 7, 14, 21, 28, 35, 42, 49, 56, 63, 70
######################  INITIALIZE PROCESS ########################## ( 66 )
creating file...
EXECUTION OUT:
out 8, 16, 24, 32, 40, 48, 56, 64, 72, 80
original 8, 16, 24, 32, 40, 48, 56, 64, 72, 80
######################  INITIALIZE PROCESS ########################## ( 67 )
creating file...
EXECUTION OUT:
out 9, 18, 27, 36, 45, 54, 63, 72, 81, 90
original 9, 18, 27, 36, 45, 54, 63, 72, 81, 90
######################  INITIALIZE PROCESS ########################## ( 68 )
creating file...
EXECUTION OUT:
out 10, 20, 30, 40, 50, 60, 70, 80, 90, 100
original 10, 20, 30, 40, 50, 60, 70, 80, 90, 100
######################  INITIALIZE PROCESS ########################## ( 69 )
creating file...
EXECUTION OUT:
out 1, 3, 5, 7, 9, 11, 13, 15, 17, 19
original 1, 3, 5, 7, 9, 11, 13, 15, 17, 19
######################  INITIALIZE PROCESS ########################## ( 70 )
creating file...
EXECUTION OUT:
out 2, 4, 6, 8, 10, 12, 14, 16, 18, 20
original 2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 71 )
creating file...
EXECUTION OUT:
out 11, 12, 13, 14, 15, 16, 17, 18, 19, 20
original 11, 12, 13, 14, 15, 16, 17, 18, 19, 20
######################  INITIALIZE PROCESS ########################## ( 72 )
creating file...
EXECUTION OUT:
out 21, 22, 23, 24, 25, 26, 27, 28, 29, 30
original 21, 22, 23, 24, 25, 26, 27, 28, 29, 30
######################  INITIALIZE PROCESS ########################## ( 73 )
creating file...
EXECUTION OUT:
out 31, 32, 33, 34, 35, 36, 37, 38, 39, 40
original 31, 32, 33, 34, 35, 36, 37, 38, 39, 40
######################  INITIALIZE PROCESS ########################## ( 74 )
creating file...
EXECUTION OUT:
out 41, 42, 43, 44, 45, 46, 47, 48, 49, 50
original 41, 42, 43, 44, 45, 46, 47, 48, 49, 50
######################  INITIALIZE PROCESS ########################## ( 75 )
creating file...
EXECUTION OUT:
out 51, 52, 53, 54, 55, 56, 57, 58, 59, 60
original 51, 52, 53, 54, 55, 56, 57, 58, 59, 60
######################  INITIALIZE PROCESS ########################## ( 76 )
creating file...
EXECUTION OUT:
out 61, 62, 63, 64, 65, 66, 67, 68, 69, 70
original 61, 62, 63, 64, 65, 66, 67, 68, 69, 70
######################  INITIALIZE PROCESS ########################## ( 77 )
creating file...
EXECUTION OUT:
out 71, 72, 73, 74, 75, 76, 77, 78, 79, 80
original 71, 72, 73, 74, 75, 76, 77, 78, 79, 80
######################  INITIALIZE PROCESS ########################## ( 78 )
creating file...
EXECUTION OUT:
out 81, 82, 83, 84, 85, 86, 87, 88, 89, 90
original 81, 82, 83, 84, 85, 86, 87, 88, 89, 90
######################  INITIALIZE PROCESS ########################## ( 79 )
creating file...
EXECUTION OUT:
out 91, 92, 93, 94, 95, 96, 97, 98, 99, 100
original 91, 92, 93, 94, 95, 96, 97, 98, 99, 100
######################  INITIALIZE PROCESS ########################## ( 80 )
creating file...
EXECUTION OUT:
out 101, 102, 103, 104, 105, 106, 107, 108, 109, 110
original 101, 102, 103, 104, 105, 106, 107, 108, 109, 110
######################  INITIALIZE PROCESS ########################## ( 81 )
creating file...
EXECUTION OUT:
out 111, 112, 113, 114, 115, 116, 117, 118, 119, 120
original 111, 112, 113, 114, 115, 116, 117, 118, 119, 120
######################  INITIALIZE PROCESS ########################## ( 82 )
creating file...
EXECUTION OUT:
out 121, 122, 123, 124, 125, 126, 127, 128, 129, 130
original 121, 122, 123, 124, 125, 126, 127, 128, 129, 130
######################  INITIALIZE PROCESS ########################## ( 83 )
creating file...
EXECUTION OUT:
out 131, 132, 133, 134, 135, 136, 137, 138, 139, 140
original 131, 132, 133, 134, 135, 136, 137, 138, 139, 140
######################  INITIALIZE PROCESS ########################## ( 84 )
creating file...
EXECUTION OUT:
out 141, 142, 143, 144, 145, 146, 147, 148, 149, 150
original 141, 142, 143, 144, 145, 146, 147, 148, 149, 150
######################  INITIALIZE PROCESS ########################## ( 85 )
creating file...
EXECUTION OUT:
out 151, 152, 153, 154, 155, 156, 157, 158, 159, 160
original 151, 152, 153, 154, 155, 156, 157, 158, 159, 160
######################  INITIALIZE PROCESS ########################## ( 86 )
creating file...
EXECUTION OUT:
out 161, 162, 163, 164, 165, 166, 167, 168, 169, 170
original 161, 162, 163, 164, 165, 166, 167, 168, 169, 170
######################  INITIALIZE PROCESS ########################## ( 87 )
creating file...
EXECUTION OUT:
out 171, 172, 173, 174, 175, 176, 177, 178, 179, 180
original 171, 172, 173, 174, 175, 176, 177, 178, 179, 180
######################  INITIALIZE PROCESS ########################## ( 88 )
creating file...
EXECUTION OUT:
out 181, 182, 183, 184, 185, 186, 187, 188, 189, 190
original 181, 182, 183, 184, 185, 186, 187, 188, 189, 190
######################  INITIALIZE PROCESS ########################## ( 89 )
creating file...
EXECUTION OUT:
out 191, 192, 193, 194, 195, 196, 197, 198, 199, 200
original 191, 192, 193, 194, 195, 196, 197, 198, 199, 200
######################  INITIALIZE PROCESS ########################## ( 90 )
creating file...
EXECUTION OUT:
out 2, 4, 6, 8, 10, 12, 14, 16, 18, 20
original 2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 91 )
creating file...
EXECUTION OUT:
out 3, 6, 9, 12, 15, 18, 21, 24, 27, 30
original 3, 6, 9, 12, 15, 18, 21, 24, 27, 30
######################  INITIALIZE PROCESS ########################## ( 92 )
creating file...
EXECUTION OUT:
out 4, 8, 12, 16, 20, 24, 28, 32, 36, 40
original 4, 8, 12, 16, 20, 24, 28, 32, 36, 40
######################  INITIALIZE PROCESS ########################## ( 93 )
creating file...
EXECUTION OUT:
out 5, 10, 15, 20, 25, 30, 35, 40, 45, 50
original 5, 10, 15, 20, 25, 30, 35, 40, 45, 50
######################  INITIALIZE PROCESS ########################## ( 94 )
creating file...
EXECUTION OUT:
out 6, 12, 18, 24, 30, 36, 42, 48, 54, 60
original 6, 12, 18, 24, 30, 36, 42, 48, 54, 60
######################  INITIALIZE PROCESS ########################## ( 95 )
creating file...
EXECUTION OUT:
out 7, 14, 21, 28, 35, 42, 49, 56, 63, 70
original 7, 14, 21, 28, 35, 42, 49, 56, 63, 70
######################  INITIALIZE PROCESS ########################## ( 96 )
creating file...
EXECUTION OUT:
out 8, 16, 24, 32, 40, 48, 56, 64, 72, 80
original 8, 16, 24, 32, 40, 48, 56, 64, 72, 80
######################  INITIALIZE PROCESS ########################## ( 97 )
creating file...
EXECUTION OUT:
out 9, 18, 27, 36, 45, 54, 63, 72, 81, 90
original 9, 18, 27, 36, 45, 54, 63, 72, 81, 90

In [135]:
exe_outputs

['2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '3, 6, 9, 12, 15, 18, 21, 24, 27, 30',
 '4, 8, 12, 16, 20, 24, 28, 32, 36, 40',
 '5, 10, 15, 20, 25, 30, 35, 40, 45, 50',
 '6, 12, 18, 24, 30, 36, 42, 48, 54, 60',
 '7, 14, 21, 28, 35, 42, 49, 56, 63, 70',
 '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
 '9, 18, 27, 36, 45, 54, 63, 72, 81, 90',
 '10, 20, 30, 40, 50, 60, 70, 80, 90, 100',
 '1, 3, 5, 7, 9, 11, 13, 15, 17, 19',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '11, 12, 13, 14, 15, 16, 17, 18, 19, 20',
 '21, 22, 23, 24, 25, 26, 27, 28, 29, 30',
 '31, 32, 33, 34, 35, 36, 37, 38, 39, 40',
 '41, 42, 43, 44, 45, 46, 47, 48, 49, 50',
 '51, 52, 53, 54, 55, 56, 57, 58, 59, 60',
 '61, 62, 63, 64, 65, 66, 67, 68, 69, 70',
 '71, 72, 73, 74, 75, 76, 77, 78, 79, 80',
 '81, 82, 83, 84, 85, 86, 87, 88, 89, 90',
 '91, 92, 93, 94, 95, 96, 97, 98, 99, 100',
 '101, 102, 103, 104, 105, 106, 107, 108, 109, 110',
 '111, 112, 113, 114, 115, 116, 117, 118, 119, 120',
 '121, 122, 123, 124, 125, 126, 127, 128, 129, 130',
 '131, 132, 133, 134, 135, 136, 137, 138, 139, 140',
 '141, 142, 143, 144, 145, 146, 147, 148, 149, 150',
 '151, 152, 153, 154, 155, 156, 157, 158, 159, 160',
 '161, 162, 163, 164, 165, 166, 167, 168, 169, 170',
 '171, 172, 173, 174, 175, 176, 177, 178, 179, 180',
 '181, 182, 183, 184, 185, 186, 187, 188, 189, 190',
 '191, 192, 193, 194, 195, 196, 197, 198, 199, 200',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '3, 6, 9, 12, 15, 18, 21, 24, 27, 30',
 '4, 8, 12, 16, 20, 24, 28, 32, 36, 40',
 '5, 10, 15, 20, 25, 30, 35, 40, 45, 50',
 '6, 12, 18, 24, 30, 36, 42, 48, 54, 60',
 '7, 14, 21, 28, 35, 42, 49, 56, 63, 70',
 '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
 '9, 18, 27, 36, 45, 54, 63, 72, 81, 90',
 '10, 20, 30, 40, 50, 60, 70, 80, 90, 100',
 '1, 3, 5, 7, 9, 11, 13, 15, 17, 19',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '11, 12, 13, 14, 15, 16, 17, 18, 19, 20',
 '21, 22, 23, 24, 25, 26, 27, 28, 29, 30',
 '31, 32, 33, 34, 35, 36, 37, 38, 39, 40',
 '41, 42, 43, 44, 45, 46, 47, 48, 49, 50',
 '51, 52, 53, 54, 55, 56, 57, 58, 59, 60',
 '61, 62, 63, 64, 65, 66, 67, 68, 69, 70',
 '71, 72, 73, 74, 75, 76, 77, 78, 79, 80',
 '81, 82, 83, 84, 85, 86, 87, 88, 89, 90',
 '91, 92, 93, 94, 95, 96, 97, 98, 99, 100',
 '101, 102, 103, 104, 105, 106, 107, 108, 109, 110',
 '111, 112, 113, 114, 115, 116, 117, 118, 119, 120',
 '121, 122, 123, 124, 125, 126, 127, 128, 129, 130',
 '131, 132, 133, 134, 135, 136, 137, 138, 139, 140',
 '141, 142, 143, 144, 145, 146, 147, 148, 149, 150',
 '151, 152, 153, 154, 155, 156, 157, 158, 159, 160',
 '161, 162, 163, 164, 165, 166, 167, 168, 169, 170',
 '171, 172, 173, 174, 175, 176, 177, 178, 179, 180',
 '181, 182, 183, 184, 185, 186, 187, 188, 189, 190',
 '191, 192, 193, 194, 195, 196, 197, 198, 199, 200',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '3, 6, 9, 12, 15, 18, 21, 24, 27, 30',
 '4, 8, 12, 16, 20, 24, 28, 32, 36, 40',
 '5, 10, 15, 20, 25, 30, 35, 40, 45, 50',
 '6, 12, 18, 24, 30, 36, 42, 48, 54, 60',
 '7, 14, 21, 28, 35, 42, 49, 56, 63, 70',
 '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
 '9, 18, 27, 36, 45, 54, 63, 72, 81, 90',
 '10, 20, 30, 40, 50, 60, 70, 80, 90, 100',
 '1, 3, 5, 7, 9, 11, 13, 15, 17, 19',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '11, 12, 13, 14, 15, 16, 17, 18, 19, 20',
 '21, 22, 23, 24, 25, 26, 27, 28, 29, 30',
 '31, 32, 33, 34, 35, 36, 37, 38, 39, 40',
 '41, 42, 43, 44, 45, 46, 47, 48, 49, 50',
 '51, 52, 53, 54, 55, 56, 57, 58, 59, 60',
 '61, 62, 63, 64, 65, 66, 67, 68, 69, 70',
 '71, 72, 73, 74, 75, 76, 77, 78, 79, 80',
 '81, 82, 83, 84, 85, 86, 87, 88, 89, 90',
 '91, 92, 93, 94, 95, 96, 97, 98, 99, 100',
 '101, 102, 103, 104, 105, 106, 107, 108, 109, 110',
 '111, 112, 113, 114, 115, 116, 117, 118, 119, 120',
 '121, 122, 123, 124, 125, 126, 127, 128, 129, 130',
 '131, 132, 133, 134, 135, 136, 137, 138, 139, 140',
 '141, 142, 143, 144, 145, 146, 147, 148, 149, 150',
 '151, 152, 153, 154, 155, 156, 157, 158, 159, 160',
 '161, 162, 163, 164, 165, 166, 167, 168, 169, 170',
 '171, 172, 173, 174, 175, 176, 177, 178, 179, 180',
 '181, 182, 183, 184, 185, 186, 187, 188, 189, 190',
 '191, 192, 193, 194, 195, 196, 197, 198, 199, 200',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '3, 6, 9, 12, 15, 18, 21, 24, 27, 30',
 '4, 8, 12, 16, 20, 24, 28, 32, 36, 40',
 '5, 10, 15, 20, 25, 30, 35, 40, 45, 50',
 '6, 12, 18, 24, 30, 36, 42, 48, 54, 60',
 '7, 14, 21, 28, 35, 42, 49, 56, 63, 70',
 '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
 '9, 18, 27, 36, 45, 54, 63, 72, 81, 90',
 '10, 20, 30, 40, 50, 60, 70, 80, 90, 100',
 '1, 3, 5, 7, 9, 11, 13, 15, 17, 19',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '11, 12, 13, 14, 15, 16, 17, 18, 19, 20',
 '21, 22, 23, 24, 25, 26, 27, 28, 29, 30',
 '31, 32, 33, 34, 35, 36, 37, 38, 39, 40',
 '41, 42, 43, 44, 45, 46, 47, 48, 49, 50',
 '51, 52, 53, 54, 55, 56, 57, 58, 59, 60',
 '61, 62, 63, 64, 65, 66, 67, 68, 69, 70',
 '71, 72, 73, 74, 75, 76, 77, 78, 79, 80',
 '81, 82, 83, 84, 85, 86, 87, 88, 89, 90',
 '91, 92, 93, 94, 95, 96, 97, 98, 99, 100',
 '101, 102, 103, 104, 105, 106, 107, 108, 109, 110',
 '111, 112, 113, 114, 115, 116, 117, 118, 119, 120',
 '121, 122, 123, 124, 125, 126, 127, 128, 129, 130',
 '131, 132, 133, 134, 135, 136, 137, 138, 139, 140',
 '141, 142, 143, 144, 145, 146, 147, 148, 149, 150',
 '151, 152, 153, 154, 155, 156, 157, 158, 159, 160',
 '161, 162, 163, 164, 165, 166, 167, 168, 169, 170',
 '171, 172, 173, 174, 175, 176, 177, 178, 179, 180',
 '181, 182, 183, 184, 185, 186, 187, 188, 189, 190',
 '191, 192, 193, 194, 195, 196, 197, 198, 199, 200',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '3, 6, 9, 12, 15, 18, 21, 24, 27, 30',
 '4, 8, 12, 16, 20, 24, 28, 32, 36, 40',
 '5, 10, 15, 20, 25, 30, 35, 40, 45, 50',
 '6, 12, 18, 24, 30, 36, 42, 48, 54, 60',
 '7, 14, 21, 28, 35, 42, 49, 56, 63, 70',
 '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
 '9, 18, 27, 36, 45, 54, 63, 72, 81, 90',
 '10, 20, 30, 40, 50, 60, 70, 80, 90, 100',
 '1, 3, 5, 7, 9, 11, 13, 15, 17, 19',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '11, 12, 13, 14, 15, 16, 17, 18, 19, 20',
 '21, 22, 23, 24, 25, 26, 27, 28, 29, 30',
 '31, 32, 33, 34, 35, 36, 37, 38, 39, 40',
 '41, 42, 43, 44, 45, 46, 47, 48, 49, 50',
 '51, 52, 53, 54, 55, 56, 57, 58, 59, 60',
 '61, 62, 63, 64, 65, 66, 67, 68, 69, 70',
 '71, 72, 73, 74, 75, 76, 77, 78, 79, 80',
 '81, 82, 83, 84, 85, 86, 87, 88, 89, 90',
 '91, 92, 93, 94, 95, 96, 97, 98, 99, 100',
 '101, 102, 103, 104, 105, 106, 107, 108, 109, 110',
 '111, 112, 113, 114, 115, 116, 117, 118, 119, 120',
 '121, 122, 123, 124, 125, 126, 127, 128, 129, 130',
 '131, 132, 133, 134, 135, 136, 137, 138, 139, 140',
 '141, 142, 143, 144, 145, 146, 147, 148, 149, 150',
 '151, 152, 153, 154, 155, 156, 157, 158, 159, 160',
 '161, 162, 163, 164, 165, 166, 167, 168, 169, 170',
 '171, 172, 173, 174, 175, 176, 177, 178, 179, 180',
 '181, 182, 183, 184, 185, 186, 187, 188, 189, 190',
 '191, 192, 193, 194, 195, 196, 197, 198, 199, 200',
 '2\n5\n7\n11\n13\n17\n19\n23\n29\n31',
 '1, 1, 2, 3, 5, 8, 13, 21, 34, 55',
 ', 1, , 2, , 4, , 8, 16, 32, 64, 128, 256, 512',
 ', , 1, , , 3, , , 9, , 27, , 81, , 243, , 729, 2187, 6561, 19683',
 ', 1, , 4, , 9, 16, 25, 36, 49, 64, 81, 100',
 ', 1, , 8, , 27, , 64, 125, 216, 343, 512, 729, 1000',
 ', , 1, , , 1, , , 2, , , 6, , , 24, , 120, , 720, , 5040, 40320, 362880',
 '1, 3, 6, 10, 15, 21, 28, 36, 45, 55',
 ', 2, , 1, , 3, , 6, 10, 19, 35, 64, 118, 217',
 ', 0, , 1, , 5, , 16, , 42, , 99, 219, 466, 968, 1981',
 '1.000000e+00, 1.600000e+01, 1.968300e+04, 4.294967e+09, 2.980232e+17\n, [6], 1.031442e+28, 2.569236e+41, 6.277102e+57, 1.966271e+77, 1.000000e+100',
 ', , 1, , , 2, , , 5, , 14, , 42, , 132, , 429, 1430, 4862, 16796',
 '3, 5, 7, 11, 13, 17, 19, 23, 29, 31',
 '4, 6, 9, 10, 14, 15, 21, 22, 25, 26',
 '',
 ', , 0, , , 1, , , 81, , 512, , 2401, , 4913, , 5832, 17576, 19683, 234256',
 '',
 ', 1, , 7, 19, 37, 61, 91, 127, 169, 217, 271',
 ', 1, , 8, 10, 18, 19, 100, 101, 108, 109, 110',
 ', 3, , 7, , 15, , 31, , 63, 127, 255, 511, 1023, 2047',
 ', 1, , 2, , 7, 14, 34, 68, 78, 156, 161, 322',
 ', 1, , 1, , 2, , 4, , 8, 16, 31, 61, 120, 236',
 ', 1, , 6, 21, 52, 105, 186, 301, 456, 657, 910',
 '0, 1, 1, 2, 1, 2, 2, 3, 1, 2',
 '0\n1\n1\n4\n21\n118\n680\n3970\n23358\n138099',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 "Fatal, error:, no, fue, posible, abrir, el, archivo, 'r_176.R':, No, such, file, or, directory",
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 ', 1, , 2, , 4, , 8, 16, 32, 64, 128, 256, 512',
 ', 0, , 1, , 3, , 7, 15, 31, 63, 127, 255, 511',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 1, 2, 3, 5, 8, 13, 21, 34, 55',
 ', 1, , 2, , 4, , 8, 16, 32, 64, 128, 256, 512',
 ', , 1, , , 3, , , 9, , 27, , 81, , 243, , 729, 2187, 6561, 19683',
 ', 1, , 4, , 9, 16, 25, 36, 49, 64, 81, 100',
 ', 1, , 8, , 27, , 64, 125, 216, 343, 512, 729, 1000',
 ', , 1, , , 1, , , 2, , , 6, , , 24, , 120, , 720, , 5040, 40320, 362880',
 '1, 3, 6, 10, 15, 21, 28, 36, 45, 55',
 '2, 1, 3, 5, 6, 9, 14, 20, 29, 43',
 ', 0, , 1, , 3, , 8, , 20, , 49, 119, 288, 696, 1681',
 ', , , , , 1, , , , , , 4, , , , , 27, , , , , 256, , , , 3125, , , , 46656\n, [7], , , 823543, , 16777216, , 387420489, 10000000000',
 ', 1, , 1, , 2, , 5, , 14, , 42, 132, 429, 1430, 4862',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '4, 6, 9, 10, 14, 15, 21, 22, 25, 26',
 '1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0\n, [38], 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0\n, [75], 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0\n[112], 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0\n[149], 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0\n[186], 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0\n[223], 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0\n[260], 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0\n[297], 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0',
 ', , 0, , , 1, , , 81, , 512, , 2401, , 4913, , 5832, 17576, 19683, 234256',
 ', , 1, , , 2, , 145, 40585',
 ', 2, , 5, 10, 17, 26, 37, 50, 65, 82, 101',
 ', 1, , 8, 10, 18, 19, 100, 101, 108, 109, 110',
 '1.000000e+00, 3.000000e+00, 1.500000e+01, 2.550000e+02, 6.553500e+04\n, [6], 4.294967e+09, 1.844674e+19, 3.402824e+38, 1.157921e+77, 1.340781e+154',
 ', 1, , 2, , 4, , 8, 16, 27, 51, 64, 125, 140',
 ', 1, , 2, , 3, , 6, 11, 20, 37, 68, 125, 230',
 ', 1, , 8, , 27, , 64, 125, 216, 343, 512, 729, 1000',
 '0, 1, 1, 2, 1, 2, 2, 3, 1, 2',
 '',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 "Fatal, error:, no, fue, posible, abrir, el, archivo, 'r_206.R':, No, such, file, or, directory",
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 ', 1, , 2, , 4, , 8, 16, 32, 64, 128, 256, 512',
 ', 0, , 1, , 3, , 7, 15, 31, 63, 127, 255, 511',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 1, 2, 3, 5, 8, 13, 21, 34, 55',
 ', 1, , 2, , 4, , 8, 16, 32, 64, 128, 256, 512',
 ', , 1, , , 3, , , 9, , 27, , 81, , 243, , 729, 2187, 6561, 19683',
 ', 1, , 2, , 3, , 4, , 5, , 6, , 7, , 8, , 9, 10, 11, 12, 13, 14, 15, 16, 17, 18\n, [19], 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36\n, [37], 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54\n, [55], 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72\n, [73], 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90\n, [91], 91, 92, 93, 94, 95, 96, 97, 98, 99, 100',
 ', 1, , 8, , 27, , 64, 125, 216, 343, 512, 729, 1000',
 ', , 1, , , 1, , , 2, , , 6, , , 24, , 120, , 720, , 5040, 40320, 362880',
 '1, 3, 6, 10, 15, 21, 28, 36, 45, 55',
 '2, 1, 3, 4, 7, 11, 18, 29, 47, 76',
 '',
 ', , , , , 1, , , , , , 4, , , , , 27, , , , , 256, , , , 3125, , , , 46656\n, [7], , , 823543, , 16777216, , 387420489, 10000000000',
 ', , 1, , , 2, , , 6, , 20, , 70, , 252, , 924, 3432, 12870, 48620',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '4, 6, 9, 10, 14, 15, 21, 22, 25, 26',
 '',
 ', , 0, , , 1, , , 81, , 512, , 2401, , 4913, , 5832, 17576, 19683, 234256',
 ', , 1, , , 2, , 145, 40585',
 ', 2, , 5, 10, 17, 26, 37, 50, 65, 82, 101',
 ', 1, , 8, 10, 18, 19, 100, 101, 108, 109, 110',
 ', 3, , 7, , 15, , 31, , 63, 127, 255, 511, 1023, 2047',
 '1, 2, 3, 6, 9, 23, 28, 38, 58, 89',
 ', 1, , 2, , 4, , 8, 13, 23, 40, 68, 118, 203',
 ', 1, , 6, 21, 52, 105, 186, 301, 456, 657, 910',
 '0, 1, 1, 2, 1, 2, 2, 3, 1, 2',
 ', 1, , 2, , 4, , 8, 16, 32, 64, 128, 256, 512',
 '2, 5, 7, 11, 13, 17, 19, 23, 29, 31',
 ', , , 1, 111111, , , 161, 1111611, 1411621',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 ', 1, , 2, , 4, , 8, 16, 32, 64, 128, 256, 512',
 ', 0, , 1, , 3, , 7, 15, 31, 63, 127, 255, 511',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 1, 2, 3, 5, 8, 13, 21, 34, 55',
 ', 1, , 2, , 4, , 8, 16, 32, 64, 128, 256, 512',
 ', , 1, , , 3, , , 9, , 27, , 81, , 243, , 729, 2187, 6561, 19683',
 ', 1, , 4, , 9, 16, 25, 36, 49, 64, 81, 100',
 ', 1, , 8, , 27, , 64, 125, 216, 343, 512, 729, 1000',
 ', , 1, , , 1, , , 2, , , 6, , , 24, , 120, , 720, , 5040, 40320, 362880',
 '1, 3, 6, 10, 15, 21, 28, 36, 45, 55',
 '2, 1, 3, 4, 7, 11, 18, 29, 47, 76',
 '',
 ', , , , , 1, , , , , , 4, , , , , 27, , , , , 256, , , , 3125, , , , 46656\n, [7], , , 823543, , 16777216, , 387420489, 10000000000',
 ', , 1, , , 2, , , 5, , 14, , 42, , 132, , 429, 1430, 4862, 16796',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '4, 6, 9, 10, 14, 15, 21, 22, 25, 26',
 '01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00\n[26], 00, 00, 00, 00, 00, 00, 00\n, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00\n[26], 00, 00, 00, 00, 00, 00, 00\n, 01, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00\n[26], 00, 00, 00, 00, 00, 00, 00\n, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00\n[26], 00, 00, 00, 00, 00, 00, 00\n, 01, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00\n[26], 00, 00, 00, 00, 00, 00, 00\n, 00, 01, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00\n[26], 00, 00, 00, 00, 00, 00, 00\n, 01, 01, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00\n[26], 00, 00, 00, 00, 00, 00, 00\n, 00, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00\n[26], 00, 00, 00, 00, 00, 00, 00\n, 01, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00\n[26], 00, 00, 00, 00, 00, 00, 00\n, 00, 01, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00\n[26], 00, 00, 00, 00, 00, 00, 00',
 ', , 0, , , 1, , , 81, , 512, , 2401, , 4913, , 5832, 17576, 19683, 234256',
 '',
 ', 2, , 5, 10, 17, 26, 37, 50, 65, 82, 101',
 ', 1, , 8, 10, 18, 19, 100, 101, 108, 109, 110',
 '1.000000e+00, 3.000000e+00, 1.500000e+01, 2.550000e+02, 6.553500e+04\n, [6], 4.294967e+09, 1.844674e+19, 3.402824e+38, 1.157921e+77, 1.340781e+154',
 '1, 2, 4, 8, 16, 23, 28, 38, 58, 89',
 ', 1, , 2, , 4, , 8, 13, 23, 40, 68, 118, 203',
 ', 1, , 8, , 27, , 64, 125, 216, 343, 512, 729, 1000',
 '0, 1, 1, 2, 1, 2, 2, 3, 1, 2',
 ', 1, , 2, , 4, , 8, 16, 32, 64, 128, 256, 512',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '"1", , , , "111111", "161", , , "1111611", "1411621"',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 ', 1, , 2, , 4, , 8, 16, 32, 64, 128, 256, 512',
 ', 0, , 1, , 3, , 7, 15, 31, 63, 127, 255, 511',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 1, 2, 3, 5, 8, 13, 21, 34, 55',
 ', 1, , 2, , 4, , 8, 16, 32, 64, 128, 256, 512',
 ', , 1, , , 3, , , 9, , 27, , 81, , 243, , 729, 2187, 6561, 19683',
 ', 1, , 4, , 9, 16, 25, 36, 49, 64, 81, 100',
 ', 1, , 8, , 27, , 64, 125, 216, 343, 512, 729, 1000',
 ', , 1, , , 1, , , 2, , , 6, , , 24, , 120, , 720, , 5040, 40320, 362880',
 '1, 3, 6, 10, 15, 21, 28, 36, 45, 55',
 '2, 1, 3, 5, 6, 9, 14, 20, 29, 43',
 '',
 ', , , , , 1, , , , , , 4, , , , , 27, , , , , 256, , , , 3125, , , , 46656\n, [7], , , 823543, , 16777216, , 387420489, 10000000000',
 ', , 1, , , 2, , , 6, , 20, , 70, , 252, , 924, 3432, 12870, 48620',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '4, 6, 9, 10, 14, 15, 21, 22, 25, 26',
 '01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00\n[26], 00, 00, 00, 00, 00, 00, 00\n, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00\n[26], 00, 00, 00, 00, 00, 00, 00\n, 01, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00\n[26], 00, 00, 00, 00, 00, 00, 00\n, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00\n[26], 00, 00, 00, 00, 00, 00, 00\n, 01, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00\n[26], 00, 00, 00, 00, 00, 00, 00\n, 00, 01, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00\n[26], 00, 00, 00, 00, 00, 00, 00\n, 01, 01, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00\n[26], 00, 00, 00, 00, 00, 00, 00\n, 00, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00\n[26], 00, 00, 00, 00, 00, 00, 00\n, 01, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00\n[26], 00, 00, 00, 00, 00, 00, 00\n, 00, 01, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00\n[26], 00, 00, 00, 00, 00, 00, 00',
 ', , 0, , , 1, , , 81, , 512, , 2401, , 4913, , 5832, 17576, 19683, 234256',
 '',
 ', 1, , 6, 21, 52, 105, 186, 301, 456, 657, 910',
 ', 1, , 8, 10, 18, 19, 100, 101, 108, 109, 110',
 ', 3, , 7, , 15, , 31, , 63, 127, 255, 511, 1023, 2047',
 ', 1, , 2, , 3, , 6, , 9, 18, 27, 54, 81, 162',
 ', 1, , 2, , 4, , 8, 13, 23, 40, 68, 118, 203',
 ', 1, , 6, 21, 52, 105, 186, 301, 456, 657, 910',
 '0, 1, 1, 2, 1, 2, 2, 3, 1, 2',
 ', 1, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '"1", , , , "111111", "161", , , "1111611", "1411621"',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 ', 1, , 2, , 4, , 8, 16, 32, 64, 128, 256, 512',
 ', 0, , 1, , 3, , 7, 15, 31, 63, 127, 255, 511',
 ', 1, , 2, , 3, , 4, , 5, , 6, , 7, , 8, , 9, 10, 11, 12, 13, 14, 15, 16, 17, 18\n, [19], 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36\n, [37], 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54\n, [55], 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72\n, [73], 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90\n, [91], 91, 92, 93, 94, 95, 96, 97, 98, 99, 100',
 ', 1, , 8, , 27, , 64, 125, 216, 343, 512, 729, 1000',
 '',
 '1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5',
 ', 2, , 4, , 8, , 16, , 32, , 64, 128, 256, 512, 1024',
 '2, 6, 11, 17, 24, 32, 41, 51, 62, 74',
 '7, 11, 13, 17, 19, 23, 29, 31, 37, 41',
 '',
 '0\n9\n99\n999\n9999\n99999\n999999\n9999999',
 ', 1, , 5, 11, 19, 29, 41, 55, 71, 89, 109',
 ', , 6, , 36, , 168, , 720, 2976, 12096',
 ', 0, , 0, , 2, , 4, , 9, 17, 31, 54, 92, 154',
 ', 3, 37, 67, 101, 137, 199, 269, 307, 353, 389',
 ', , 1, , , 2, , 145, 40585',
 '',
 ', , , 2, , , , 3, , , , 7, , , 43, , 1807, 3263443',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 ', 1, , 8, 10, 18, 19, 100, 101, 108, 109, 110',
 '0, 1, 1, 2, 2, 3, 3, 3',
 '0, 1, 0, NA, 0, NA, 0, NA, 0, NA',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 4, 2, 1, 3, 5, 9, 2, 6, 5',
 '1, 7, 3, 2, 0, 5, 0, 7, 9, 8',
 '1, 0, 1, 2, 3, 1, 6, 11',
 '0, 1, 3, 7, 15, 31, 63',
 '3, 5, 11, 17, 31, 41, 59, 67',

In [136]:
correctness_list

[True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 True]

In [133]:
levenshtein_list

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [137]:
r_df["exe_out"] = exe_outputs
r_df["correct_execution"] = correctness_list
r_df["Levenshtein"] = levenshtein_list
r_df

,sequence,complexity,length_type,language,q_length,GPT4_answer,a_length,temperature,real_code,print_code,no_code,explanation,no_sense,exe_out,correct_execution,Levenshtein
8260,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",1.0,0.0,R,163.0,"```r\nseq(2, 20, by = 2)\n```",27.0,1.000,0.0,0,0.0,0.0,0,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",True,0
8261,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",1.0,0.0,R,164.0,"```r\nseq(3, 30, by=3)\n```",25.0,1.000,0.0,0,0.0,0.0,0,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",True,0
8262,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",1.0,0.0,R,165.0,"```r\nseq(4, 40, by=4)\n```",25.0,1.000,0.0,0,0.0,0.0,0,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",True,0
8263,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",1.0,0.0,R,166.0,"```r\nseq(5, 50, by=5)\n```",25.0,1.000,0.0,0,0.0,0.0,0,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",True,0
8264,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",1.0,0.0,R,166.0,"```r\nseq(6, 60, by = 6)\n```",27.0,1.000,0.0,0,0.0,0.0,0,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8845,"187, 218, 260, 295, 301, 314, 379, 410, 452, 469",4.0,0.0,R,176.0,"```r\nseq <- c(187, 218, 260, 295, 301, 314, 3...",78.0,0.001,0.0,0,0.0,0.0,0,"187, 218, 260, 295, 301, 314, 379, 410, 452, 469",True,0
8846,"29, 63, 95, 140, 150, 190, 221, 437, 482, 491",4.0,0.0,R,173.0,"```r\nsequence <- c(29, 63, 95, 140, 150, 190,...",85.0,0.001,0.0,0,0.0,0.0,0,"29, 63, 95, 140, 150, 190, 221, 437, 482, 491",True,0
8847,"3, 11, 84, 144, 156, 177, 188, 199, 229, 284",4.0,0.0,R,172.0,"```r\nsequence <- c(3, 11, 84, 144, 156, 177, ...",84.0,0.001,0.0,0,0.0,0.0,0,", 3, 11, 84, 144, 156, 177, 188, 199, 229, 284",False,2
8848,"26, 94, 98, 137, 176, 301, 323, 330, 372, 444",4.0,0.0,R,173.0,"```r\nsequence <- c(26, 94, 98, 137, 176, 301,...",85.0,0.001,0.0,0,0.0,0.0,0,"26, 94, 98, 137, 176, 301, 323, 330, 372, 444",True,0
8849,"39, 81, 88, 210, 215, 378, 416, 430, 439, 490",4.0,0.0,R,173.0,"```r\nseq <- c(39, 81, 88, 210, 215, 378, 416,...",75.0,0.001,0.0,0,0.0,0.0,0,"39, 81, 88, 210, 215, 378, 416, 430, 439, 490",True,0

In [138]:
r_df.to_csv("R_evaluation.csv", index=False)

# Octave/MATLAB

In [139]:
import pandas as pd
import subprocess
import time
import copy
from enchant.utils import levenshtein

In [142]:
OIA_ds = pd.read_csv("/Users/beto/Documents/Projects/medLLM/no_small_seqs_clean.csv")
oct_df = copy.deepcopy(OIA_ds[OIA_ds["language"] == "Matlab"])
original_sequences = oct_df["sequence"].values

oct_code_list = (OIA_ds[OIA_ds["language"] == "Matlab"])["GPT4_answer"].values
total_questions = len(oct_code_list)

In [143]:
oct_df

,sequence,complexity,length_type,language,q_length,GPT4_answer,a_length,temperature,real_code,print_code,no_code,explanation,no_sense,exe_out,correct_execution,Levenshtein
7670,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",1.0,0.0,Matlab,168.0,```matlab\ndisp(2:2:20)\n```,26.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
7671,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",1.0,0.0,Matlab,169.0,```matlab\nfor i = 3:3:30\n disp(i)\nend\n```,44.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
7672,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",1.0,0.0,Matlab,170.0,```matlab\ndisp(4:4:40)\n```,26.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
7673,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",1.0,0.0,Matlab,171.0,```matlab\ndisp(5:5:50);\n```,27.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
7674,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",1.0,0.0,Matlab,171.0,```matlab\nfor i = 1:10\n disp(6*i);\nend\n```,45.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8255,"187, 218, 260, 295, 301, 314, 379, 410, 452, 469",4.0,0.0,Matlab,181.0,"```matlab\nsequence = [187, 218, 260, 295, 301...",91.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN
8256,"29, 63, 95, 140, 150, 190, 221, 437, 482, 491",4.0,0.0,Matlab,178.0,"```matlab\nsequence = [29, 63, 95, 140, 150, 1...",88.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN
8257,"3, 11, 84, 144, 156, 177, 188, 199, 229, 284",4.0,0.0,Matlab,177.0,"```matlab\nsequence = [3, 11, 84, 144, 156, 17...",87.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN
8258,"26, 94, 98, 137, 176, 301, 323, 330, 372, 444",4.0,0.0,Matlab,178.0,"```matlab\nsequence = [26, 94, 98, 137, 176, 3...",88.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN
8259,"39, 81, 88, 210, 215, 378, 416, 430, 439, 490",4.0,0.0,Matlab,178.0,"```matlab\nsequence = [39, 81, 88, 210, 215, 3...",88.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN

In [144]:
oct_code_list[1:5]

array(['```matlab\nfor i = 3:3:30\n    disp(i)\nend\n```',
       '```matlab\ndisp(4:4:40)\n```', '```matlab\ndisp(5:5:50);\n```',
       '```matlab\nfor i = 1:10\n    disp(6*i);\nend\n```'], dtype=object)

In [145]:
len(oct_code_list)

590

In [171]:

counter = -1
exe_outputs = []
levenshtein_list = []
correctness_list = []
test_code = []

for code in oct_code_list:#[0:15]:
    code = code.replace("```matlab" + "\n","\"")
    code = code.replace("```Matlab" + "\n","\"")
    code = code.replace("\n"+ "```","\"")
    
    
    #print(code)
    counter += 1
    name_file = "oct_" + str(counter)
    surname_file =  '.m'
    whole_name = name_file + surname_file
    
    original_seq = original_sequences[counter]
    
    print("######################  INITIALIZE PROCESS ########################## (", str(counter), ")")
    try:
        print("creating file...")
        test_code.append(code)
        ! echo -e {code} > {whole_name}
        
        rough_jar = subprocess.run(["octave", whole_name], capture_output=True, text=True, timeout=10)
        print("EXECUTION OUT: ")
        # print(rough_jar.stdout.strip())
        out = rough_jar.stdout.strip()
        out = out.replace("\n", ", ")
        out = out.replace("   ",", ")
        out = out.replace(",  ",", ")
        #out = out.replace(" ",", ")
        # out = out.replace(",, ", ", ")
        print(out)
        exe_outputs.append(out)
        correctness_list.append(out==original_seq)
        levenshtein_list.append(levenshtein(out, original_seq))

    except:
        print("**************** execution error ( step 2)")
        print(rough_jar.stderr)
        exe_outputs.append('Execution error')
        correctness_list.append('False')
        levenshtein_list.append(50000)
        pass

######################  INITIALIZE PROCESS ########################## ( 0 )
creating file...

EXECUTION OUT:
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 1 )
creating file...
EXECUTION OUT:
3, 6, 9, 12, 15, 18, 21, 24, 27, 30
######################  INITIALIZE PROCESS ########################## ( 2 )
creating file...
EXECUTION OUT:
4, 8, 12, 16, 20, 24, 28, 32, 36, 40
######################  INITIALIZE PROCESS ########################## ( 3 )
creating file...
EXECUTION OUT:
5, 10, 15, 20, 25, 30, 35, 40, 45, 50
######################  INITIALIZE PROCESS ########################## ( 4 )
creating file...
EXECUTION OUT:
6, 12, 18, 24, 30, 36, 42, 48, 54, 60
######################  INITIALIZE PROCESS ########################## ( 5 )
creating file...
EXECUTION OUT:
7, 14, 21, 28, 35, 42, 49, 56, 63, 70
######################  INITIALIZE PROCESS ########################## ( 6 )
creating file...
EXECUTION OUT:
8, 16, 24, 32, 40, 48, 56, 64, 72, 80
######################  INITIALIZE PROCESS ########################## ( 7 )
creating file...
EXECUTION OUT:
9, 18, 27, 36, 45, 54, 63, 72, 81, 90
######################  INITIALIZE PROCESS ########################## ( 8 )
creating file...
EXECUTION OUT:
10, 20, 30, 40, 50, 60, 70, 80, 90, 100
######################  INITIALIZE PROCESS ########################## ( 9 )
creating file...
EXECUTION OUT:
1, 3, 5, 7, 9, 11, 13, 15, 17, 19
######################  INITIALIZE PROCESS ########################## ( 10 )
creating file...
EXECUTION OUT:
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 11 )
creating file...
EXECUTION OUT:
11, 12, 13, 14, 15, 16, 17, 18, 19, 20
######################  INITIALIZE PROCESS ########################## ( 12 )
creating file...
EXECUTION OUT:
21, 22, 23, 24, 25, 26, 27, 28, 29, 30
######################  INITIALIZE PROCESS ########################## ( 13 )
creating file...
EXECUTION OUT:
31, 32, 33, 34, 35, 36, 37, 38, 39, 40
######################  INITIALIZE PROCESS ########################## ( 14 )
creating file...
EXECUTION OUT:
41, 42, 43, 44, 45, 46, 47, 48, 49, 50
######################  INITIALIZE PROCESS ########################## ( 15 )
creating file...
EXECUTION OUT:
51, 52, 53, 54, 55, 56, 57, 58, 59, 60
######################  INITIALIZE PROCESS ########################## ( 16 )
creating file...
EXECUTION OUT:
61, 62, 63, 64, 65, 66, 67, 68, 69, 70
######################  INITIALIZE PROCESS ########################## ( 17 )
creating file...
EXECUTION OUT:
71, 72, 73, 74, 75, 76, 77, 78, 79, 80
######################  INITIALIZE PROCESS ########################## ( 18 )
creating file...
EXECUTION OUT:
81, 82, 83, 84, 85, 86, 87, 88, 89, 90
######################  INITIALIZE PROCESS ########################## ( 19 )
creating file...
EXECUTION OUT:
91, 92, 93, 94, 95, 96, 97, 98, 99, 100
######################  INITIALIZE PROCESS ########################## ( 20 )
creating file...
EXECUTION OUT:
101, 102, 103, 104, 105, 106, 107, 108, 109, 110
######################  INITIALIZE PROCESS ########################## ( 21 )
creating file...
EXECUTION OUT:
111, 112, 113, 114, 115, 116, 117, 118, 119, 120
######################  INITIALIZE PROCESS ########################## ( 22 )
creating file...
EXECUTION OUT:
121, 122, 123, 124, 125, 126, 127, 128, 129, 130
######################  INITIALIZE PROCESS ########################## ( 23 )
creating file...
EXECUTION OUT:
131, 132, 133, 134, 135, 136, 137, 138, 139, 140
######################  INITIALIZE PROCESS ########################## ( 24 )
creating file...
EXECUTION OUT:
141, 142, 143, 144, 145, 146, 147, 148, 149, 150
######################  INITIALIZE PROCESS ########################## ( 25 )
creating file...
EXECUTION OUT:
151, 152, 153, 154, 155, 156, 157, 158, 159, 160
######################  INITIALIZE PROCESS ########################## ( 26 )
creating file...
EXECUTION OUT:
161, 162, 163, 164, 165, 166, 167, 168, 169, 170
######################  INITIALIZE PROCESS ########################## ( 27 )
creating file...
EXECUTION OUT:
171, 172, 173, 174, 175, 176, 177, 178, 179, 180
######################  INITIALIZE PROCESS ########################## ( 28 )
creating file...
EXECUTION OUT:
181, 182, 183, 184, 185, 186, 187, 188, 189, 190
######################  INITIALIZE PROCESS ########################## ( 29 )
creating file...
EXECUTION OUT:
191, 192, 193, 194, 195, 196, 197, 198, 199, 200
######################  INITIALIZE PROCESS ########################## ( 30 )
creating file...
EXECUTION OUT:
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 31 )
creating file...
EXECUTION OUT:
3, 6, 9, 12, 15, 18, 21, 24, 27, 30
######################  INITIALIZE PROCESS ########################## ( 32 )
creating file...
EXECUTION OUT:
4, 8, 12, 16, 20, 24, 28, 32, 36, 40
######################  INITIALIZE PROCESS ########################## ( 33 )
creating file...
EXECUTION OUT:
5, 10, 15, 20, 25, 30, 35, 40, 45, 50
######################  INITIALIZE PROCESS ########################## ( 34 )
creating file...
EXECUTION OUT:
6, 12, 18, 24, 30, 36, 42, 48, 54, 60
######################  INITIALIZE PROCESS ########################## ( 35 )
creating file...
EXECUTION OUT:
7, 14, 21, 28, 35, 42, 49, 56, 63, 70
######################  INITIALIZE PROCESS ########################## ( 36 )
creating file...
EXECUTION OUT:
8, 16, 24, 32, 40, 48, 56, 64, 72, 80
######################  INITIALIZE PROCESS ########################## ( 37 )
creating file...
EXECUTION OUT:
9, 18, 27, 36, 45, 54, 63, 72, 81, 90
######################  INITIALIZE PROCESS ########################## ( 38 )
creating file...
EXECUTION OUT:
10, 20, 30, 40, 50, 60, 70, 80, 90, 100
######################  INITIALIZE PROCESS ########################## ( 39 )
creating file...
EXECUTION OUT:
ans =, ,,  1, 3, 5, 7, 9, 11, 13, 15, 17, 19
######################  INITIALIZE PROCESS ########################## ( 40 )
creating file...
EXECUTION OUT:
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 41 )
creating file...
EXECUTION OUT:
11, 12, 13, 14, 15, 16, 17, 18, 19, 20
######################  INITIALIZE PROCESS ########################## ( 42 )
creating file...
EXECUTION OUT:
21, 22, 23, 24, 25, 26, 27, 28, 29, 30
######################  INITIALIZE PROCESS ########################## ( 43 )
creating file...
EXECUTION OUT:
31, 32, 33, 34, 35, 36, 37, 38, 39, 40
######################  INITIALIZE PROCESS ########################## ( 44 )
creating file...
EXECUTION OUT:
41, 42, 43, 44, 45, 46, 47, 48, 49, 50
######################  INITIALIZE PROCESS ########################## ( 45 )
creating file...
EXECUTION OUT:
51, 52, 53, 54, 55, 56, 57, 58, 59, 60
######################  INITIALIZE PROCESS ########################## ( 46 )
creating file...
EXECUTION OUT:
61, 62, 63, 64, 65, 66, 67, 68, 69, 70
######################  INITIALIZE PROCESS ########################## ( 47 )
creating file...
EXECUTION OUT:
71, 72, 73, 74, 75, 76, 77, 78, 79, 80
######################  INITIALIZE PROCESS ########################## ( 48 )
creating file...
EXECUTION OUT:
81, 82, 83, 84, 85, 86, 87, 88, 89, 90
######################  INITIALIZE PROCESS ########################## ( 49 )
creating file...
EXECUTION OUT:
91, 92, 93, 94, 95, 96, 97, 98, 99, 100
######################  INITIALIZE PROCESS ########################## ( 50 )
creating file...
EXECUTION OUT:
101, 102, 103, 104, 105, 106, 107, 108, 109, 110
######################  INITIALIZE PROCESS ########################## ( 51 )
creating file...
EXECUTION OUT:
111, 112, 113, 114, 115, 116, 117, 118, 119, 120
######################  INITIALIZE PROCESS ########################## ( 52 )
creating file...
EXECUTION OUT:
121, 122, 123, 124, 125, 126, 127, 128, 129, 130
######################  INITIALIZE PROCESS ########################## ( 53 )
creating file...
EXECUTION OUT:
131, 132, 133, 134, 135, 136, 137, 138, 139, 140
######################  INITIALIZE PROCESS ########################## ( 54 )
creating file...
EXECUTION OUT:
141, 142, 143, 144, 145, 146, 147, 148, 149, 150
######################  INITIALIZE PROCESS ########################## ( 55 )
creating file...
EXECUTION OUT:
151, 152, 153, 154, 155, 156, 157, 158, 159, 160
######################  INITIALIZE PROCESS ########################## ( 56 )
creating file...
EXECUTION OUT:
161, 162, 163, 164, 165, 166, 167, 168, 169, 170
######################  INITIALIZE PROCESS ########################## ( 57 )
creating file...
EXECUTION OUT:
171, 172, 173, 174, 175, 176, 177, 178, 179, 180
######################  INITIALIZE PROCESS ########################## ( 58 )
creating file...
EXECUTION OUT:
181, 182, 183, 184, 185, 186, 187, 188, 189, 190
######################  INITIALIZE PROCESS ########################## ( 59 )
creating file...
EXECUTION OUT:
191, 192, 193, 194, 195, 196, 197, 198, 199, 200
######################  INITIALIZE PROCESS ########################## ( 60 )
creating file...
EXECUTION OUT:
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 61 )
creating file...
EXECUTION OUT:
3, 6, 9, 12, 15, 18, 21, 24, 27, 30
######################  INITIALIZE PROCESS ########################## ( 62 )
creating file...
EXECUTION OUT:
4, 8, 12, 16, 20, 24, 28, 32, 36, 40
######################  INITIALIZE PROCESS ########################## ( 63 )
creating file...
EXECUTION OUT:
5, 10, 15, 20, 25, 30, 35, 40, 45, 50
######################  INITIALIZE PROCESS ########################## ( 64 )
creating file...
EXECUTION OUT:
6, 12, 18, 24, 30, 36, 42, 48, 54, 60
######################  INITIALIZE PROCESS ########################## ( 65 )
creating file...
EXECUTION OUT:
7, 14, 21, 28, 35, 42, 49, 56, 63, 70
######################  INITIALIZE PROCESS ########################## ( 66 )
creating file...
EXECUTION OUT:
8, 16, 24, 32, 40, 48, 56, 64, 72, 80
######################  INITIALIZE PROCESS ########################## ( 67 )
creating file...
EXECUTION OUT:
9, 18, 27, 36, 45, 54, 63, 72, 81, 90
######################  INITIALIZE PROCESS ########################## ( 68 )
creating file...
EXECUTION OUT:
10, 20, 30, 40, 50, 60, 70, 80, 90, 100
######################  INITIALIZE PROCESS ########################## ( 69 )
creating file...
EXECUTION OUT:
ans =, ,,  1, 3, 5, 7, 9, 11, 13, 15, 17, 19
######################  INITIALIZE PROCESS ########################## ( 70 )
creating file...
EXECUTION OUT:
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 71 )
creating file...
EXECUTION OUT:
11, 12, 13, 14, 15, 16, 17, 18, 19, 20
######################  INITIALIZE PROCESS ########################## ( 72 )
creating file...
EXECUTION OUT:
21, 22, 23, 24, 25, 26, 27, 28, 29, 30
######################  INITIALIZE PROCESS ########################## ( 73 )
creating file...
EXECUTION OUT:
31, 32, 33, 34, 35, 36, 37, 38, 39, 40
######################  INITIALIZE PROCESS ########################## ( 74 )
creating file...
EXECUTION OUT:
41, 42, 43, 44, 45, 46, 47, 48, 49, 50
######################  INITIALIZE PROCESS ########################## ( 75 )
creating file...
EXECUTION OUT:
51, 52, 53, 54, 55, 56, 57, 58, 59, 60
######################  INITIALIZE PROCESS ########################## ( 76 )
creating file...
EXECUTION OUT:
61, 62, 63, 64, 65, 66, 67, 68, 69, 70
######################  INITIALIZE PROCESS ########################## ( 77 )
creating file...
EXECUTION OUT:
71, 72, 73, 74, 75, 76, 77, 78, 79, 80
######################  INITIALIZE PROCESS ########################## ( 78 )
creating file...
EXECUTION OUT:
81, 82, 83, 84, 85, 86, 87, 88, 89, 90
######################  INITIALIZE PROCESS ########################## ( 79 )
creating file...
EXECUTION OUT:
91, 92, 93, 94, 95, 96, 97, 98, 99, 100
######################  INITIALIZE PROCESS ########################## ( 80 )
creating file...
EXECUTION OUT:
101, 102, 103, 104, 105, 106, 107, 108, 109, 110
######################  INITIALIZE PROCESS ########################## ( 81 )
creating file...
EXECUTION OUT:
111, 112, 113, 114, 115, 116, 117, 118, 119, 120
######################  INITIALIZE PROCESS ########################## ( 82 )
creating file...
EXECUTION OUT:
121, 122, 123, 124, 125, 126, 127, 128, 129, 130
######################  INITIALIZE PROCESS ########################## ( 83 )
creating file...
EXECUTION OUT:
131, 132, 133, 134, 135, 136, 137, 138, 139, 140
######################  INITIALIZE PROCESS ########################## ( 84 )
creating file...
EXECUTION OUT:
141, 142, 143, 144, 145, 146, 147, 148, 149, 150
######################  INITIALIZE PROCESS ########################## ( 85 )
creating file...
EXECUTION OUT:
151, 152, 153, 154, 155, 156, 157, 158, 159, 160
######################  INITIALIZE PROCESS ########################## ( 86 )
creating file...
EXECUTION OUT:
161, 162, 163, 164, 165, 166, 167, 168, 169, 170
######################  INITIALIZE PROCESS ########################## ( 87 )
creating file...
EXECUTION OUT:
171, 172, 173, 174, 175, 176, 177, 178, 179, 180
######################  INITIALIZE PROCESS ########################## ( 88 )
creating file...
EXECUTION OUT:
181, 182, 183, 184, 185, 186, 187, 188, 189, 190
######################  INITIALIZE PROCESS ########################## ( 89 )
creating file...
EXECUTION OUT:
191, 192, 193, 194, 195, 196, 197, 198, 199, 200
######################  INITIALIZE PROCESS ########################## ( 90 )
creating file...
EXECUTION OUT:
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 91 )
creating file...
EXECUTION OUT:
3, 6, 9, 12, 15, 18, 21, 24, 27, 30
######################  INITIALIZE PROCESS ########################## ( 92 )
creating file...
EXECUTION OUT:
4, 8, 12, 16, 20, 24, 28, 32, 36, 40
######################  INITIALIZE PROCESS ########################## ( 93 )
creating file...
EXECUTION OUT:
5, 10, 15, 20, 25, 30, 35, 40, 45, 50
######################  INITIALIZE PROCESS ########################## ( 94 )
creating file...
EXECUTION OUT:
6, 12, 18, 24, 30, 36, 42, 48, 54, 60
######################  INITIALIZE PROCESS ########################## ( 95 )
creating file...
EXECUTION OUT:
7, 14, 21, 28, 35, 42, 49, 56, 63, 70
######################  INITIALIZE PROCESS ########################## ( 96 )
creating file...
EXECUTION OUT:
8, 16, 24, 32, 40, 48, 56, 64, 72, 80
######################  INITIALIZE PROCESS ########################## ( 97 )
creating file...
EXECUTION OUT:
9, 18, 27, 36, 45, 54, 63, 72, 81, 90
######################  INITIALIZE PROCESS ########################## ( 98 )
creating file...
EXECUTION OUT:
10, 20, 30, 40, 50, 60, 70, 80, 90, 100
######################  INITIALIZE PROCESS ########################## ( 99 )
creating file...
EXECUTION OUT:
1, 3, 5, 7, 9, 11, 13, 15, 17, 19
######################  INITIALIZE PROCESS ########################## ( 100 )
creating file...
EXECUTION OUT:
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 101 )
creating file...
EXECUTION OUT:
11, 12, 13, 14, 15, 16, 17, 18, 19, 20
######################  INITIALIZE PROCESS ########################## ( 102 )
creating file...
EXECUTION OUT:
21, 22, 23, 24, 25, 26, 27, 28, 29, 30
######################  INITIALIZE PROCESS ########################## ( 103 )
creating file...
EXECUTION OUT:
31, 32, 33, 34, 35, 36, 37, 38, 39, 40
######################  INITIALIZE PROCESS ########################## ( 104 )
creating file...
EXECUTION OUT:
41, 42, 43, 44, 45, 46, 47, 48, 49, 50
######################  INITIALIZE PROCESS ########################## ( 105 )
creating file...
EXECUTION OUT:
51, 52, 53, 54, 55, 56, 57, 58, 59, 60
######################  INITIALIZE PROCESS ########################## ( 106 )
creating file...
EXECUTION OUT:
61, 62, 63, 64, 65, 66, 67, 68, 69, 70
######################  INITIALIZE PROCESS ########################## ( 107 )
creating file...
EXECUTION OUT:
71, 72, 73, 74, 75, 76, 77, 78, 79, 80
######################  INITIALIZE PROCESS ########################## ( 108 )
creating file...
EXECUTION OUT:
81, 82, 83, 84, 85, 86, 87, 88, 89, 90
######################  INITIALIZE PROCESS ########################## ( 109 )
creating file...
EXECUTION OUT:
91, 92, 93, 94, 95, 96, 97, 98, 99, 100
######################  INITIALIZE PROCESS ########################## ( 110 )
creating file...
EXECUTION OUT:
101, 102, 103, 104, 105, 106, 107, 108, 109, 110
######################  INITIALIZE PROCESS ########################## ( 111 )
creating file...
EXECUTION OUT:
111, 112, 113, 114, 115, 116, 117, 118, 119, 120
######################  INITIALIZE PROCESS ########################## ( 112 )
creating file...
EXECUTION OUT:
121, 122, 123, 124, 125, 126, 127, 128, 129, 130
######################  INITIALIZE PROCESS ########################## ( 113 )
creating file...
EXECUTION OUT:
131, 132, 133, 134, 135, 136, 137, 138, 139, 140
######################  INITIALIZE PROCESS ########################## ( 114 )
creating file...
EXECUTION OUT:
141, 142, 143, 144, 145, 146, 147, 148, 149, 150
######################  INITIALIZE PROCESS ########################## ( 115 )
creating file...
EXECUTION OUT:
151, 152, 153, 154, 155, 156, 157, 158, 159, 160
######################  INITIALIZE PROCESS ########################## ( 116 )
creating file...
EXECUTION OUT:
161, 162, 163, 164, 165, 166, 167, 168, 169, 170
######################  INITIALIZE PROCESS ########################## ( 117 )
creating file...
EXECUTION OUT:
171, 172, 173, 174, 175, 176, 177, 178, 179, 180
######################  INITIALIZE PROCESS ########################## ( 118 )
creating file...
EXECUTION OUT:
181, 182, 183, 184, 185, 186, 187, 188, 189, 190
######################  INITIALIZE PROCESS ########################## ( 119 )
creating file...
EXECUTION OUT:
191, 192, 193, 194, 195, 196, 197, 198, 199, 200
######################  INITIALIZE PROCESS ########################## ( 120 )
creating file...
EXECUTION OUT:
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 121 )
creating file...
EXECUTION OUT:
3, 6, 9, 12, 15, 18, 21, 24, 27, 30
######################  INITIALIZE PROCESS ########################## ( 122 )
creating file...
EXECUTION OUT:
4, 8, 12, 16, 20, 24, 28, 32, 36, 40
######################  INITIALIZE PROCESS ########################## ( 123 )
creating file...
EXECUTION OUT:
5, 10, 15, 20, 25, 30, 35, 40, 45, 50
######################  INITIALIZE PROCESS ########################## ( 124 )
creating file...
EXECUTION OUT:
6, 12, 18, 24, 30, 36, 42, 48, 54, 60
######################  INITIALIZE PROCESS ########################## ( 125 )
creating file...
EXECUTION OUT:
7, 14, 21, 28, 35, 42, 49, 56, 63, 70
######################  INITIALIZE PROCESS ########################## ( 126 )
creating file...
EXECUTION OUT:
8, 16, 24, 32, 40, 48, 56, 64, 72, 80
######################  INITIALIZE PROCESS ########################## ( 127 )
creating file...
EXECUTION OUT:
9, 18, 27, 36, 45, 54, 63, 72, 81, 90
######################  INITIALIZE PROCESS ########################## ( 128 )
creating file...
EXECUTION OUT:
10, 20, 30, 40, 50, 60, 70, 80, 90, 100
######################  INITIALIZE PROCESS ########################## ( 129 )
creating file...
EXECUTION OUT:
1, 3, 5, 7, 9, 11, 13, 15, 17, 19
######################  INITIALIZE PROCESS ########################## ( 130 )
creating file...
EXECUTION OUT:
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 131 )
creating file...
EXECUTION OUT:
11, 12, 13, 14, 15, 16, 17, 18, 19, 20
######################  INITIALIZE PROCESS ########################## ( 132 )
creating file...
EXECUTION OUT:
21, 22, 23, 24, 25, 26, 27, 28, 29, 30

In [168]:
exe_outputs

['2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '3, 6, 9, 12, 15, 18, 21, 24, 27, 30',
 '4, 8, 12, 16, 20, 24, 28, 32, 36, 40',
 '5, 10, 15, 20, 25, 30, 35, 40, 45, 50',
 '6, 12, 18, 24, 30, 36, 42, 48, 54, 60',
 '7, 14, 21, 28, 35, 42, 49, 56, 63, 70',
 '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
 '9, 18, 27, 36, 45, 54, 63, 72, 81, 90',
 '10, 20, 30, 40, 50, 60, 70, 80, 90, 100',
 '1, 3, 5, 7, 9, 11, 13, 15, 17, 19',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '11, 12, 13, 14, 15, 16, 17, 18, 19, 20',
 '21, 22, 23, 24, 25, 26, 27, 28, 29, 30',
 '31, 32, 33, 34, 35, 36, 37, 38, 39, 40',
 '41, 42, 43, 44, 45, 46, 47, 48, 49, 50']

In [169]:
correctness_list

[True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True]

In [170]:
levenshtein_list

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [172]:
oct_df["exe_out"] = exe_outputs
oct_df["correct_execution"] = correctness_list
oct_df["Levenshtein"] = levenshtein_list
oct_df

,sequence,complexity,length_type,language,q_length,GPT4_answer,a_length,temperature,real_code,print_code,no_code,explanation,no_sense,exe_out,correct_execution,Levenshtein
7670,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",1.0,0.0,Matlab,168.0,```matlab\ndisp(2:2:20)\n```,26.0,1.000,0.0,0,0.0,0.0,0,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",True,0
7671,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",1.0,0.0,Matlab,169.0,```matlab\nfor i = 3:3:30\n disp(i)\nend\n```,44.0,1.000,0.0,0,0.0,0.0,0,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",True,0
7672,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",1.0,0.0,Matlab,170.0,```matlab\ndisp(4:4:40)\n```,26.0,1.000,0.0,0,0.0,0.0,0,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",True,0
7673,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",1.0,0.0,Matlab,171.0,```matlab\ndisp(5:5:50);\n```,27.0,1.000,0.0,0,0.0,0.0,0,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",True,0
7674,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",1.0,0.0,Matlab,171.0,```matlab\nfor i = 1:10\n disp(6*i);\nend\n```,45.0,1.000,0.0,0,0.0,0.0,0,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8255,"187, 218, 260, 295, 301, 314, 379, 410, 452, 469",4.0,0.0,Matlab,181.0,"```matlab\nsequence = [187, 218, 260, 295, 301...",91.0,0.001,0.0,0,0.0,0.0,0,"187, 218, 260, 295, 301, 314, 379, 410, 452, 469",True,0
8256,"29, 63, 95, 140, 150, 190, 221, 437, 482, 491",4.0,0.0,Matlab,178.0,"```matlab\nsequence = [29, 63, 95, 140, 150, 1...",88.0,0.001,0.0,0,0.0,0.0,0,"29, 63, 95, 140, 150, 190, 221, 437, 482, 491",True,0
8257,"3, 11, 84, 144, 156, 177, 188, 199, 229, 284",4.0,0.0,Matlab,177.0,"```matlab\nsequence = [3, 11, 84, 144, 156, 17...",87.0,0.001,0.0,0,0.0,0.0,0,"3, 11, 84, 144, 156, 177, 188, 199, 229, 284",True,0
8258,"26, 94, 98, 137, 176, 301, 323, 330, 372, 444",4.0,0.0,Matlab,178.0,"```matlab\nsequence = [26, 94, 98, 137, 176, 3...",88.0,0.001,0.0,0,0.0,0.0,0,"26, 94, 98, 137, 176, 301, 323, 330, 372, 444",True,0
8259,"39, 81, 88, 210, 215, 378, 416, 430, 439, 490",4.0,0.0,Matlab,178.0,"```matlab\nsequence = [39, 81, 88, 210, 215, 3...",88.0,0.001,0.0,0,0.0,0.0,0,"39, 81, 88, 210, 215, 378, 416, 430, 439, 490",True,0

In [173]:
oct_df.to_csv("Matlab_evaluation.csv", index=False)

In [174]:
correctness_list

[True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 'False',
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True]

# JAVA

In [175]:
import pandas as pd
import subprocess
import time
import copy
from enchant.utils import levenshtein

In [176]:
OIA_ds = pd.read_csv("/Users/beto/Documents/Projects/medLLM/no_small_seqs_clean.csv")
j_df = copy.deepcopy(OIA_ds[OIA_ds["language"] == "JavaScript"])
original_sequences = j_df["sequence"].values

j_code_list = (OIA_ds[OIA_ds["language"] == "JavaScript"])["GPT4_answer"].values
total_questions = len(j_code_list)

In [177]:
j_df

,sequence,complexity,length_type,language,q_length,GPT4_answer,a_length,temperature,real_code,print_code,no_code,explanation,no_sense,exe_out,correct_execution,Levenshtein
8850,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",1.0,0.0,JavaScript,172.0,```javascript\nfor (let i = 2; i <= 20; i += 2...,72.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
8851,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",1.0,0.0,JavaScript,173.0,```javascript\nfor (let i = 3; i <= 30; i += 3...,74.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
8852,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",1.0,0.0,JavaScript,174.0,```javascript\nfor(let i = 4; i <= 40; i += 4)...,73.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
8853,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",1.0,0.0,JavaScript,175.0,```javascript\nfor (let i = 5; i <= 50; i += 5...,74.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
8854,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",1.0,0.0,JavaScript,175.0,```javascript\nfor (let i = 1; i <= 10; i++) {...,75.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9435,"187, 218, 260, 295, 301, 314, 379, 410, 452, 469",4.0,0.0,JavaScript,185.0,"```javascript\nconsole.log(187, 218, 260, 295,...",80.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN
9436,"29, 63, 95, 140, 150, 190, 221, 437, 482, 491",4.0,0.0,JavaScript,182.0,"```javascript\nlet sequence = [29, 63, 95, 140...",104.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN
9437,"3, 11, 84, 144, 156, 177, 188, 199, 229, 284",4.0,0.0,JavaScript,181.0,```javascript\nlet sequence = [3];\nfor (let i...,730.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN
9438,"26, 94, 98, 137, 176, 301, 323, 330, 372, 444",4.0,0.0,JavaScript,182.0,```javascript\nlet sequence = [];\nlet current...,250.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN
9439,"39, 81, 88, 210, 215, 378, 416, 430, 439, 490",4.0,0.0,JavaScript,182.0,"```javascript\nconsole.log(39, 81, 88, 210, 21...",77.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN

In [178]:
j_code_list[1:5]

array(['```javascript\nfor (let i = 3; i <= 30; i += 3) {\n    console.log(i);\n}\n```',
       '```javascript\nfor(let i = 4; i <= 40; i += 4) {\n    console.log(i);\n}\n```',
       '```javascript\nfor (let i = 5; i <= 50; i += 5) {\n    console.log(i);\n}\n```',
       '```javascript\nfor (let i = 1; i <= 10; i++) {\n    console.log(6 * i);\n}\n```'],
      dtype=object)

In [200]:

counter = -1
exe_outputs = []
levenshtein_list = []
correctness_list = []
test_code = []

for code in j_code_list:
    code = code.replace("```javascript" + "\n","\"")
    code = code.replace("```Javascript" + "\n","\"")
    code = code.replace("\n"+ "```","\"")
    
    
    #print(code)
    counter += 1
    name_file = "j_" + str(counter)
    surname_file =  '.js'
    whole_name = name_file + surname_file
    
    original_seq = original_sequences[counter]
    
    print("######################  INITIALIZE PROCESS ########################## (", str(counter), ")")
    try:
        print("creating file...")
        test_code.append(code)
        ! echo -e {code} > {whole_name}
        
        rough_jar = subprocess.run(["Node", whole_name], capture_output=True, text=True, timeout=10)
        print("EXECUTION OUT: ")
        # print(rough_jar.stdout.strip())
        out = rough_jar.stdout.strip()
        out = out.replace("\n", ", ")
        out = out.replace("\x1b[33m","")
        out = out.replace("\x1b[39m","")
        out = out.replace("[,    ","")
        out = out.replace(", ]", "")
        out = out.replace(",,   ", ", ")
        out = out.replace(",   ", ", ") 
        out = out.replace("[, ", ", ")
        out = out.replace(",  ", ", ")
        out = out.strip()
        out = out.replace("[ ", "")
        fist = out[:2]
        if fist == ", ":
            out = out[2:len(out)-1]
        out = out.replace(" ]", "")
        out = out.replace("\x1b[", "")
        out = out.replace("m''", "")
        out = out.replace("\x1b[32m'", "")
        out = out.replace("'","")
        print(out)
        exe_outputs.append(out)
        correctness_list.append(out==original_seq)
        levenshtein_list.append(levenshtein(out, original_seq))

    except:
        print("**************** execution error ( step 2)")
        print(rough_jar.stderr)
        exe_outputs.append('Execution error')
        correctness_list.append('False')
        levenshtein_list.append(50000)
        pass

######################  INITIALIZE PROCESS ########################## ( 0 )
creating file...

EXECUTION OUT:
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 1 )
creating file...
EXECUTION OUT:
3, 6, 9, 12, 15, 18, 21, 24, 27, 30
######################  INITIALIZE PROCESS ########################## ( 2 )
creating file...
EXECUTION OUT:
4, 8, 12, 16, 20, 24, 28, 32, 36, 40
######################  INITIALIZE PROCESS ########################## ( 3 )
creating file...
EXECUTION OUT:
5, 10, 15, 20, 25, 30, 35, 40, 45, 50
######################  INITIALIZE PROCESS ########################## ( 4 )
creating file...
EXECUTION OUT:
6, 12, 18, 24, 30, 36, 42, 48, 54, 60
######################  INITIALIZE PROCESS ########################## ( 5 )
creating file...
EXECUTION OUT:
7, 14, 21, 28, 35, 42, 49, 56, 63, 70
######################  INITIALIZE PROCESS ########################## ( 6 )
creating file...
EXECUTION OUT:
8, 16, 24, 32, 40, 48, 56, 64, 72, 80
######################  INITIALIZE PROCESS ########################## ( 7 )
creating file...
EXECUTION OUT:
9, 18, 27, 36, 45, 54, 63, 72, 81, 90
######################  INITIALIZE PROCESS ########################## ( 8 )
creating file...
EXECUTION OUT:
10, 20, 30, 40, 50, 60, 70, 80, 90, 100
######################  INITIALIZE PROCESS ########################## ( 9 )
creating file...
EXECUTION OUT:
1, 3, 5, 7, 9, 11, 13, 15, 17, 19
######################  INITIALIZE PROCESS ########################## ( 10 )
creating file...
EXECUTION OUT:
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 11 )
creating file...
EXECUTION OUT:
11, 12, 13, 14, 15, 16, 17, 18, 19, 20
######################  INITIALIZE PROCESS ########################## ( 12 )
creating file...
EXECUTION OUT:
21, 22, 23, 24, 25, 26, 27, 28, 29, 30
######################  INITIALIZE PROCESS ########################## ( 13 )
creating file...
EXECUTION OUT:
31, 32, 33, 34, 35, 36, 37, 38, 39, 40
######################  INITIALIZE PROCESS ########################## ( 14 )
creating file...
EXECUTION OUT:
41, 42, 43, 44, 45, 46, 47, 48, 49, 50
######################  INITIALIZE PROCESS ########################## ( 15 )
creating file...
EXECUTION OUT:
51, 52, 53, 54, 55, 56, 57, 58, 59, 60
######################  INITIALIZE PROCESS ########################## ( 16 )
creating file...
EXECUTION OUT:
61, 62, 63, 64, 65, 66, 67, 68, 69, 70
######################  INITIALIZE PROCESS ########################## ( 17 )
creating file...
EXECUTION OUT:
71, 72, 73, 74, 75, 76, 77, 78, 79, 80
######################  INITIALIZE PROCESS ########################## ( 18 )
creating file...
EXECUTION OUT:
81, 82, 83, 84, 85, 86, 87, 88, 89, 90
######################  INITIALIZE PROCESS ########################## ( 19 )
creating file...
EXECUTION OUT:
91, 92, 93, 94, 95, 96, 97, 98, 99, 100
######################  INITIALIZE PROCESS ########################## ( 20 )
creating file...
EXECUTION OUT:
101, 102, 103, 104, 105, 106, 107, 108, 109, 110
######################  INITIALIZE PROCESS ########################## ( 21 )
creating file...
EXECUTION OUT:
111, 112, 113, 114, 115, 116, 117, 118, 119, 120
######################  INITIALIZE PROCESS ########################## ( 22 )
creating file...
EXECUTION OUT:
121, 122, 123, 124, 125, 126, 127, 128, 129, 130
######################  INITIALIZE PROCESS ########################## ( 23 )
creating file...
EXECUTION OUT:
131, 132, 133, 134, 135, 136, 137, 138, 139, 140
######################  INITIALIZE PROCESS ########################## ( 24 )
creating file...
EXECUTION OUT:
141, 142, 143, 144, 145, 146, 147, 148, 149, 150
######################  INITIALIZE PROCESS ########################## ( 25 )
creating file...
EXECUTION OUT:
151, 152, 153, 154, 155, 156, 157, 158, 159, 160
######################  INITIALIZE PROCESS ########################## ( 26 )
creating file...
EXECUTION OUT:
161, 162, 163, 164, 165, 166, 167, 168, 169, 170
######################  INITIALIZE PROCESS ########################## ( 27 )
creating file...
EXECUTION OUT:
171, 172, 173, 174, 175, 176, 177, 178, 179, 180
######################  INITIALIZE PROCESS ########################## ( 28 )
creating file...
EXECUTION OUT:
181, 182, 183, 184, 185, 186, 187, 188, 189, 190
######################  INITIALIZE PROCESS ########################## ( 29 )
creating file...
EXECUTION OUT:
191, 192, 193, 194, 195, 196, 197, 198, 199, 200
######################  INITIALIZE PROCESS ########################## ( 30 )
creating file...
EXECUTION OUT:
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 31 )
creating file...
EXECUTION OUT:
3, 6, 9, 12, 15, 18, 21, 24, 27, 30
######################  INITIALIZE PROCESS ########################## ( 32 )
creating file...
EXECUTION OUT:
4, 8, 12, 16, 20, 24, 28, 32, 36, 40
######################  INITIALIZE PROCESS ########################## ( 33 )
creating file...
EXECUTION OUT:
5, 10, 15, 20, 25, 30, 35, 40, 45, 50
######################  INITIALIZE PROCESS ########################## ( 34 )
creating file...
EXECUTION OUT:
6, 12, 18, 24, 30, 36, 42, 48, 54, 60
######################  INITIALIZE PROCESS ########################## ( 35 )
creating file...
EXECUTION OUT:
7, 14, 21, 28, 35, 42, 49, 56, 63, 70
######################  INITIALIZE PROCESS ########################## ( 36 )
creating file...
EXECUTION OUT:
8, 16, 24, 32, 40, 48, 56, 64, 72, 80
######################  INITIALIZE PROCESS ########################## ( 37 )
creating file...
EXECUTION OUT:
9, 18, 27, 36, 45, 54, 63, 72, 81, 90
######################  INITIALIZE PROCESS ########################## ( 38 )
creating file...
EXECUTION OUT:
10, 20, 30, 40, 50, 60, 70, 80, 90, 100
######################  INITIALIZE PROCESS ########################## ( 39 )
creating file...
EXECUTION OUT:
1, 3, 5, 7, 9, 11, 13, 15, 17, 19
######################  INITIALIZE PROCESS ########################## ( 40 )
creating file...
EXECUTION OUT:
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 41 )
creating file...
EXECUTION OUT:
11, 12, 13, 14, 15, 16, 17, 18, 19, 20
######################  INITIALIZE PROCESS ########################## ( 42 )
creating file...
EXECUTION OUT:
21, 22, 23, 24, 25, 26, 27, 28, 29, 30
######################  INITIALIZE PROCESS ########################## ( 43 )
creating file...
EXECUTION OUT:
31, 32, 33, 34, 35, 36, 37, 38, 39, 40
######################  INITIALIZE PROCESS ########################## ( 44 )
creating file...
EXECUTION OUT:
41, 42, 43, 44, 45, 46, 47, 48, 49, 50
######################  INITIALIZE PROCESS ########################## ( 45 )
creating file...
EXECUTION OUT:
51, 52, 53, 54, 55, 56, 57, 58, 59, 60
######################  INITIALIZE PROCESS ########################## ( 46 )
creating file...
EXECUTION OUT:
61, 62, 63, 64, 65, 66, 67, 68, 69, 70
######################  INITIALIZE PROCESS ########################## ( 47 )
creating file...
EXECUTION OUT:
71, 72, 73, 74, 75, 76, 77, 78, 79, 80
######################  INITIALIZE PROCESS ########################## ( 48 )
creating file...
EXECUTION OUT:
81, 82, 83, 84, 85, 86, 87, 88, 89, 90
######################  INITIALIZE PROCESS ########################## ( 49 )
creating file...
EXECUTION OUT:
91, 92, 93, 94, 95, 96, 97, 98, 99, 100
######################  INITIALIZE PROCESS ########################## ( 50 )
creating file...
EXECUTION OUT:
101, 102, 103, 104, 105, 106, 107, 108, 109, 110
######################  INITIALIZE PROCESS ########################## ( 51 )
creating file...
EXECUTION OUT:
111, 112, 113, 114, 115, 116, 117, 118, 119, 120
######################  INITIALIZE PROCESS ########################## ( 52 )
creating file...
EXECUTION OUT:
121, 122, 123, 124, 125, 126, 127, 128, 129, 130
######################  INITIALIZE PROCESS ########################## ( 53 )
creating file...
EXECUTION OUT:
131, 132, 133, 134, 135, 136, 137, 138, 139, 140
######################  INITIALIZE PROCESS ########################## ( 54 )
creating file...
EXECUTION OUT:
141, 142, 143, 144, 145, 146, 147, 148, 149, 150
######################  INITIALIZE PROCESS ########################## ( 55 )
creating file...
EXECUTION OUT:
151, 152, 153, 154, 155, 156, 157, 158, 159, 160
######################  INITIALIZE PROCESS ########################## ( 56 )
creating file...
EXECUTION OUT:
161, 162, 163, 164, 165, 166, 167, 168, 169, 170
######################  INITIALIZE PROCESS ########################## ( 57 )
creating file...
EXECUTION OUT:
171, 172, 173, 174, 175, 176, 177, 178, 179, 180
######################  INITIALIZE PROCESS ########################## ( 58 )
creating file...
EXECUTION OUT:
181, 182, 183, 184, 185, 186, 187, 188, 189, 190
######################  INITIALIZE PROCESS ########################## ( 59 )
creating file...
EXECUTION OUT:
191, 192, 193, 194, 195, 196, 197, 198, 199, 200
######################  INITIALIZE PROCESS ########################## ( 60 )
creating file...
EXECUTION OUT:
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 61 )
creating file...
EXECUTION OUT:
3, 6, 9, 12, 15, 18, 21, 24, 27, 30
######################  INITIALIZE PROCESS ########################## ( 62 )
creating file...
EXECUTION OUT:
4, 8, 12, 16, 20, 24, 28, 32, 36, 40
######################  INITIALIZE PROCESS ########################## ( 63 )
creating file...
EXECUTION OUT:
5, 10, 15, 20, 25, 30, 35, 40, 45, 50
######################  INITIALIZE PROCESS ########################## ( 64 )
creating file...
EXECUTION OUT:
6, 12, 18, 24, 30, 36, 42, 48, 54, 60
######################  INITIALIZE PROCESS ########################## ( 65 )
creating file...
EXECUTION OUT:
7, 14, 21, 28, 35, 42, 49, 56, 63, 70
######################  INITIALIZE PROCESS ########################## ( 66 )
creating file...
EXECUTION OUT:
8, 16, 24, 32, 40, 48, 56, 64, 72, 80
######################  INITIALIZE PROCESS ########################## ( 67 )
creating file...
EXECUTION OUT:
9, 18, 27, 36, 45, 54, 63, 72, 81, 90
######################  INITIALIZE PROCESS ########################## ( 68 )
creating file...
EXECUTION OUT:
10, 20, 30, 40, 50, 60, 70, 80, 90, 100
######################  INITIALIZE PROCESS ########################## ( 69 )
creating file...
EXECUTION OUT:
1, 3, 5, 7, 9, 11, 13, 15, 17, 19
######################  INITIALIZE PROCESS ########################## ( 70 )
creating file...
EXECUTION OUT:
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 71 )
creating file...
EXECUTION OUT:
11, 12, 13, 14, 15, 16, 17, 18, 19, 20
######################  INITIALIZE PROCESS ########################## ( 72 )
creating file...
EXECUTION OUT:
21, 22, 23, 24, 25, 26, 27, 28, 29, 30
######################  INITIALIZE PROCESS ########################## ( 73 )
creating file...
EXECUTION OUT:
31, 32, 33, 34, 35, 36, 37, 38, 39, 40
######################  INITIALIZE PROCESS ########################## ( 74 )
creating file...
EXECUTION OUT:
41, 42, 43, 44, 45, 46, 47, 48, 49, 50
######################  INITIALIZE PROCESS ########################## ( 75 )
creating file...
EXECUTION OUT:
51, 52, 53, 54, 55, 56, 57, 58, 59, 60
######################  INITIALIZE PROCESS ########################## ( 76 )
creating file...
EXECUTION OUT:
61, 62, 63, 64, 65, 66, 67, 68, 69, 70
######################  INITIALIZE PROCESS ########################## ( 77 )
creating file...
EXECUTION OUT:
71, 72, 73, 74, 75, 76, 77, 78, 79, 80
######################  INITIALIZE PROCESS ########################## ( 78 )
creating file...
EXECUTION OUT:
81, 82, 83, 84, 85, 86, 87, 88, 89, 90
######################  INITIALIZE PROCESS ########################## ( 79 )
creating file...
EXECUTION OUT:
91, 92, 93, 94, 95, 96, 97, 98, 99, 100
######################  INITIALIZE PROCESS ########################## ( 80 )
creating file...
EXECUTION OUT:
101, 102, 103, 104, 105, 106, 107, 108, 109, 110
######################  INITIALIZE PROCESS ########################## ( 81 )
creating file...
EXECUTION OUT:
111, 112, 113, 114, 115, 116, 117, 118, 119, 120
######################  INITIALIZE PROCESS ########################## ( 82 )
creating file...
EXECUTION OUT:
121, 122, 123, 124, 125, 126, 127, 128, 129, 130
######################  INITIALIZE PROCESS ########################## ( 83 )
creating file...
EXECUTION OUT:
131, 132, 133, 134, 135, 136, 137, 138, 139, 140
######################  INITIALIZE PROCESS ########################## ( 84 )
creating file...
EXECUTION OUT:
141, 142, 143, 144, 145, 146, 147, 148, 149, 150
######################  INITIALIZE PROCESS ########################## ( 85 )
creating file...
EXECUTION OUT:
151, 152, 153, 154, 155, 156, 157, 158, 159, 160
######################  INITIALIZE PROCESS ########################## ( 86 )
creating file...
EXECUTION OUT:
161, 162, 163, 164, 165, 166, 167, 168, 169, 170
######################  INITIALIZE PROCESS ########################## ( 87 )
creating file...
EXECUTION OUT:
171, 172, 173, 174, 175, 176, 177, 178, 179, 180
######################  INITIALIZE PROCESS ########################## ( 88 )
creating file...
EXECUTION OUT:
181, 182, 183, 184, 185, 186, 187, 188, 189, 190
######################  INITIALIZE PROCESS ########################## ( 89 )
creating file...
EXECUTION OUT:
191, 192, 193, 194, 195, 196, 197, 198, 199, 200
######################  INITIALIZE PROCESS ########################## ( 90 )
creating file...
EXECUTION OUT:
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 91 )
creating file...
EXECUTION OUT:
3, 6, 9, 12, 15, 18, 21, 24, 27, 30
######################  INITIALIZE PROCESS ########################## ( 92 )
creating file...
EXECUTION OUT:
4, 8, 12, 16, 20, 24, 28, 32, 36, 40
######################  INITIALIZE PROCESS ########################## ( 93 )
creating file...
EXECUTION OUT:
5, 10, 15, 20, 25, 30, 35, 40, 45, 50
######################  INITIALIZE PROCESS ########################## ( 94 )
creating file...
EXECUTION OUT:
6, 12, 18, 24, 30, 36, 42, 48, 54, 60
######################  INITIALIZE PROCESS ########################## ( 95 )
creating file...
EXECUTION OUT:
7, 14, 21, 28, 35, 42, 49, 56, 63, 70
######################  INITIALIZE PROCESS ########################## ( 96 )
creating file...
EXECUTION OUT:
8, 16, 24, 32, 40, 48, 56, 64, 72, 80
######################  INITIALIZE PROCESS ########################## ( 97 )
creating file...
EXECUTION OUT:
9, 18, 27, 36, 45, 54, 63, 72, 81, 90
######################  INITIALIZE PROCESS ########################## ( 98 )
creating file...
EXECUTION OUT:
10, 20, 30, 40, 50, 60, 70, 80, 90, 100
######################  INITIALIZE PROCESS ########################## ( 99 )
creating file...
EXECUTION OUT:
1, 3, 5, 7, 9, 11, 13, 15, 17, 19
######################  INITIALIZE PROCESS ########################## ( 100 )
creating file...
EXECUTION OUT:
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 101 )
creating file...
EXECUTION OUT:
11, 12, 13, 14, 15, 16, 17, 18, 19, 20
######################  INITIALIZE PROCESS ########################## ( 102 )
creating file...
EXECUTION OUT:
21, 22, 23, 24, 25, 26, 27, 28, 29, 30
######################  INITIALIZE PROCESS ########################## ( 103 )
creating file...
EXECUTION OUT:
31, 32, 33, 34, 35, 36, 37, 38, 39, 40
######################  INITIALIZE PROCESS ########################## ( 104 )
creating file...
EXECUTION OUT:
41, 42, 43, 44, 45, 46, 47, 48, 49, 50
######################  INITIALIZE PROCESS ########################## ( 105 )
creating file...
EXECUTION OUT:
51, 52, 53, 54, 55, 56, 57, 58, 59, 60
######################  INITIALIZE PROCESS ########################## ( 106 )
creating file...
EXECUTION OUT:
61, 62, 63, 64, 65, 66, 67, 68, 69, 70
######################  INITIALIZE PROCESS ########################## ( 107 )
creating file...
EXECUTION OUT:
71, 72, 73, 74, 75, 76, 77, 78, 79, 80
######################  INITIALIZE PROCESS ########################## ( 108 )
creating file...
EXECUTION OUT:
81, 82, 83, 84, 85, 86, 87, 88, 89, 90
######################  INITIALIZE PROCESS ########################## ( 109 )
creating file...
EXECUTION OUT:
91, 92, 93, 94, 95, 96, 97, 98, 99, 100
######################  INITIALIZE PROCESS ########################## ( 110 )
creating file...
EXECUTION OUT:
101, 102, 103, 104, 105, 106, 107, 108, 109, 110
######################  INITIALIZE PROCESS ########################## ( 111 )
creating file...
EXECUTION OUT:
111, 112, 113, 114, 115, 116, 117, 118, 119, 120
######################  INITIALIZE PROCESS ########################## ( 112 )
creating file...
EXECUTION OUT:
121, 122, 123, 124, 125, 126, 127, 128, 129, 130
######################  INITIALIZE PROCESS ########################## ( 113 )
creating file...
EXECUTION OUT:
131, 132, 133, 134, 135, 136, 137, 138, 139, 140
######################  INITIALIZE PROCESS ########################## ( 114 )
creating file...
EXECUTION OUT:
141, 142, 143, 144, 145, 146, 147, 148, 149, 150
######################  INITIALIZE PROCESS ########################## ( 115 )
creating file...
EXECUTION OUT:
151, 152, 153, 154, 155, 156, 157, 158, 159, 160
######################  INITIALIZE PROCESS ########################## ( 116 )
creating file...
EXECUTION OUT:
161, 162, 163, 164, 165, 166, 167, 168, 169, 170
######################  INITIALIZE PROCESS ########################## ( 117 )
creating file...
EXECUTION OUT:
171, 172, 173, 174, 175, 176, 177, 178, 179, 180
######################  INITIALIZE PROCESS ########################## ( 118 )
creating file...
EXECUTION OUT:
181, 182, 183, 184, 185, 186, 187, 188, 189, 190
######################  INITIALIZE PROCESS ########################## ( 119 )
creating file...
EXECUTION OUT:
191, 192, 193, 194, 195, 196, 197, 198, 199, 200
######################  INITIALIZE PROCESS ########################## ( 120 )
creating file...
EXECUTION OUT:
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 121 )
creating file...
EXECUTION OUT:
3, 6, 9, 12, 15, 18, 21, 24, 27, 30
######################  INITIALIZE PROCESS ########################## ( 122 )
creating file...
EXECUTION OUT:
4, 8, 12, 16, 20, 24, 28, 32, 36, 40
######################  INITIALIZE PROCESS ########################## ( 123 )
creating file...
EXECUTION OUT:
5, 10, 15, 20, 25, 30, 35, 40, 45, 50
######################  INITIALIZE PROCESS ########################## ( 124 )
creating file...
EXECUTION OUT:
6, 12, 18, 24, 30, 36, 42, 48, 54, 60
######################  INITIALIZE PROCESS ########################## ( 125 )
creating file...
EXECUTION OUT:
7, 14, 21, 28, 35, 42, 49, 56, 63, 70
######################  INITIALIZE PROCESS ########################## ( 126 )
creating file...
EXECUTION OUT:
8, 16, 24, 32, 40, 48, 56, 64, 72, 80
######################  INITIALIZE PROCESS ########################## ( 127 )
creating file...
EXECUTION OUT:
9, 18, 27, 36, 45, 54, 63, 72, 81, 90
######################  INITIALIZE PROCESS ########################## ( 128 )
creating file...
EXECUTION OUT:
10, 20, 30, 40, 50, 60, 70, 80, 90, 100
######################  INITIALIZE PROCESS ########################## ( 129 )
creating file...
EXECUTION OUT:
1, 3, 5, 7, 9, 11, 13, 15, 17, 19
######################  INITIALIZE PROCESS ########################## ( 130 )
creating file...
EXECUTION OUT:
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 131 )
creating file...
EXECUTION OUT:
11, 12, 13, 14, 15, 16, 17, 18, 19, 20
######################  INITIALIZE PROCESS ########################## ( 132 )
creating file...
EXECUTION OUT:
21, 22, 23, 24, 25, 26, 27, 28, 29, 30
######################  INITIALIZE PROCESS ########################## ( 133 )

In [201]:
exe_outputs

['2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '3, 6, 9, 12, 15, 18, 21, 24, 27, 30',
 '4, 8, 12, 16, 20, 24, 28, 32, 36, 40',
 '5, 10, 15, 20, 25, 30, 35, 40, 45, 50',
 '6, 12, 18, 24, 30, 36, 42, 48, 54, 60',
 '7, 14, 21, 28, 35, 42, 49, 56, 63, 70',
 '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
 '9, 18, 27, 36, 45, 54, 63, 72, 81, 90',
 '10, 20, 30, 40, 50, 60, 70, 80, 90, 100',
 '1, 3, 5, 7, 9, 11, 13, 15, 17, 19',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '11, 12, 13, 14, 15, 16, 17, 18, 19, 20',
 '21, 22, 23, 24, 25, 26, 27, 28, 29, 30',
 '31, 32, 33, 34, 35, 36, 37, 38, 39, 40',
 '41, 42, 43, 44, 45, 46, 47, 48, 49, 50',
 '51, 52, 53, 54, 55, 56, 57, 58, 59, 60',
 '61, 62, 63, 64, 65, 66, 67, 68, 69, 70',
 '71, 72, 73, 74, 75, 76, 77, 78, 79, 80',
 '81, 82, 83, 84, 85, 86, 87, 88, 89, 90',
 '91, 92, 93, 94, 95, 96, 97, 98, 99, 100',
 '101, 102, 103, 104, 105, 106, 107, 108, 109, 110',
 '111, 112, 113, 114, 115, 116, 117, 118, 119, 120',
 '121, 122, 123, 124, 125, 126, 127, 128, 129, 130',
 '131, 132, 133, 134, 135, 136, 137, 138, 139, 140',
 '141, 142, 143, 144, 145, 146, 147, 148, 149, 150',
 '151, 152, 153, 154, 155, 156, 157, 158, 159, 160',
 '161, 162, 163, 164, 165, 166, 167, 168, 169, 170',
 '171, 172, 173, 174, 175, 176, 177, 178, 179, 180',
 '181, 182, 183, 184, 185, 186, 187, 188, 189, 190',
 '191, 192, 193, 194, 195, 196, 197, 198, 199, 200',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '3, 6, 9, 12, 15, 18, 21, 24, 27, 30',
 '4, 8, 12, 16, 20, 24, 28, 32, 36, 40',
 '5, 10, 15, 20, 25, 30, 35, 40, 45, 50',
 '6, 12, 18, 24, 30, 36, 42, 48, 54, 60',
 '7, 14, 21, 28, 35, 42, 49, 56, 63, 70',
 '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
 '9, 18, 27, 36, 45, 54, 63, 72, 81, 90',
 '10, 20, 30, 40, 50, 60, 70, 80, 90, 100',
 '1, 3, 5, 7, 9, 11, 13, 15, 17, 19',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '11, 12, 13, 14, 15, 16, 17, 18, 19, 20',
 '21, 22, 23, 24, 25, 26, 27, 28, 29, 30',
 '31, 32, 33, 34, 35, 36, 37, 38, 39, 40',
 '41, 42, 43, 44, 45, 46, 47, 48, 49, 50',
 '51, 52, 53, 54, 55, 56, 57, 58, 59, 60',
 '61, 62, 63, 64, 65, 66, 67, 68, 69, 70',
 '71, 72, 73, 74, 75, 76, 77, 78, 79, 80',
 '81, 82, 83, 84, 85, 86, 87, 88, 89, 90',
 '91, 92, 93, 94, 95, 96, 97, 98, 99, 100',
 '101, 102, 103, 104, 105, 106, 107, 108, 109, 110',
 '111, 112, 113, 114, 115, 116, 117, 118, 119, 120',
 '121, 122, 123, 124, 125, 126, 127, 128, 129, 130',
 '131, 132, 133, 134, 135, 136, 137, 138, 139, 140',
 '141, 142, 143, 144, 145, 146, 147, 148, 149, 150',
 '151, 152, 153, 154, 155, 156, 157, 158, 159, 160',
 '161, 162, 163, 164, 165, 166, 167, 168, 169, 170',
 '171, 172, 173, 174, 175, 176, 177, 178, 179, 180',
 '181, 182, 183, 184, 185, 186, 187, 188, 189, 190',
 '191, 192, 193, 194, 195, 196, 197, 198, 199, 200',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '3, 6, 9, 12, 15, 18, 21, 24, 27, 30',
 '4, 8, 12, 16, 20, 24, 28, 32, 36, 40',
 '5, 10, 15, 20, 25, 30, 35, 40, 45, 50',
 '6, 12, 18, 24, 30, 36, 42, 48, 54, 60',
 '7, 14, 21, 28, 35, 42, 49, 56, 63, 70',
 '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
 '9, 18, 27, 36, 45, 54, 63, 72, 81, 90',
 '10, 20, 30, 40, 50, 60, 70, 80, 90, 100',
 '1, 3, 5, 7, 9, 11, 13, 15, 17, 19',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '11, 12, 13, 14, 15, 16, 17, 18, 19, 20',
 '21, 22, 23, 24, 25, 26, 27, 28, 29, 30',
 '31, 32, 33, 34, 35, 36, 37, 38, 39, 40',
 '41, 42, 43, 44, 45, 46, 47, 48, 49, 50',
 '51, 52, 53, 54, 55, 56, 57, 58, 59, 60',
 '61, 62, 63, 64, 65, 66, 67, 68, 69, 70',
 '71, 72, 73, 74, 75, 76, 77, 78, 79, 80',
 '81, 82, 83, 84, 85, 86, 87, 88, 89, 90',
 '91, 92, 93, 94, 95, 96, 97, 98, 99, 100',
 '101, 102, 103, 104, 105, 106, 107, 108, 109, 110',
 '111, 112, 113, 114, 115, 116, 117, 118, 119, 120',
 '121, 122, 123, 124, 125, 126, 127, 128, 129, 130',
 '131, 132, 133, 134, 135, 136, 137, 138, 139, 140',
 '141, 142, 143, 144, 145, 146, 147, 148, 149, 150',
 '151, 152, 153, 154, 155, 156, 157, 158, 159, 160',
 '161, 162, 163, 164, 165, 166, 167, 168, 169, 170',
 '171, 172, 173, 174, 175, 176, 177, 178, 179, 180',
 '181, 182, 183, 184, 185, 186, 187, 188, 189, 190',
 '191, 192, 193, 194, 195, 196, 197, 198, 199, 200',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '3, 6, 9, 12, 15, 18, 21, 24, 27, 30',
 '4, 8, 12, 16, 20, 24, 28, 32, 36, 40',
 '5, 10, 15, 20, 25, 30, 35, 40, 45, 50',
 '6, 12, 18, 24, 30, 36, 42, 48, 54, 60',
 '7, 14, 21, 28, 35, 42, 49, 56, 63, 70',
 '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
 '9, 18, 27, 36, 45, 54, 63, 72, 81, 90',
 '10, 20, 30, 40, 50, 60, 70, 80, 90, 100',
 '1, 3, 5, 7, 9, 11, 13, 15, 17, 19',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '11, 12, 13, 14, 15, 16, 17, 18, 19, 20',
 '21, 22, 23, 24, 25, 26, 27, 28, 29, 30',
 '31, 32, 33, 34, 35, 36, 37, 38, 39, 40',
 '41, 42, 43, 44, 45, 46, 47, 48, 49, 50',
 '51, 52, 53, 54, 55, 56, 57, 58, 59, 60',
 '61, 62, 63, 64, 65, 66, 67, 68, 69, 70',
 '71, 72, 73, 74, 75, 76, 77, 78, 79, 80',
 '81, 82, 83, 84, 85, 86, 87, 88, 89, 90',
 '91, 92, 93, 94, 95, 96, 97, 98, 99, 100',
 '101, 102, 103, 104, 105, 106, 107, 108, 109, 110',
 '111, 112, 113, 114, 115, 116, 117, 118, 119, 120',
 '121, 122, 123, 124, 125, 126, 127, 128, 129, 130',
 '131, 132, 133, 134, 135, 136, 137, 138, 139, 140',
 '141, 142, 143, 144, 145, 146, 147, 148, 149, 150',
 '151, 152, 153, 154, 155, 156, 157, 158, 159, 160',
 '161, 162, 163, 164, 165, 166, 167, 168, 169, 170',
 '171, 172, 173, 174, 175, 176, 177, 178, 179, 180',
 '181, 182, 183, 184, 185, 186, 187, 188, 189, 190',
 '191, 192, 193, 194, 195, 196, 197, 198, 199, 200',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '3, 6, 9, 12, 15, 18, 21, 24, 27, 30',
 '4, 8, 12, 16, 20, 24, 28, 32, 36, 40',
 '5, 10, 15, 20, 25, 30, 35, 40, 45, 50',
 '6, 12, 18, 24, 30, 36, 42, 48, 54, 60',
 '7, 14, 21, 28, 35, 42, 49, 56, 63, 70',
 '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
 '9, 18, 27, 36, 45, 54, 63, 72, 81, 90',
 '10, 20, 30, 40, 50, 60, 70, 80, 90, 100',
 '1, 3, 5, 7, 9, 11, 13, 15, 17, 19',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '11, 12, 13, 14, 15, 16, 17, 18, 19, 20',
 '21, 22, 23, 24, 25, 26, 27, 28, 29, 30',
 '31, 32, 33, 34, 35, 36, 37, 38, 39, 40',
 '41, 42, 43, 44, 45, 46, 47, 48, 49, 50',
 '51, 52, 53, 54, 55, 56, 57, 58, 59, 60',
 '61, 62, 63, 64, 65, 66, 67, 68, 69, 70',
 '71, 72, 73, 74, 75, 76, 77, 78, 79, 80',
 '81, 82, 83, 84, 85, 86, 87, 88, 89, 90',
 '91, 92, 93, 94, 95, 96, 97, 98, 99, 100',
 '101, 102, 103, 104, 105, 106, 107, 108, 109, 110',
 '111, 112, 113, 114, 115, 116, 117, 118, 119, 120',
 '121, 122, 123, 124, 125, 126, 127, 128, 129, 130',
 '131, 132, 133, 134, 135, 136, 137, 138, 139, 140',
 '141, 142, 143, 144, 145, 146, 147, 148, 149, 150',
 '151, 152, 153, 154, 155, 156, 157, 158, 159, 160',
 '161, 162, 163, 164, 165, 166, 167, 168, 169, 170',
 '171, 172, 173, 174, 175, 176, 177, 178, 179, 180',
 '181, 182, 183, 184, 185, 186, 187, 188, 189, 190',
 '191, 192, 193, 194, 195, 196, 197, 198, 199, 200',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 1, 2, 3, 5, 8, 13, 21, 34, 5',
 '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
 '1, 3, 9, 27, 81, 243, 729, 2187, 6561, 19683',
 '1, 4, 9, 16, 25, 36, 49, 64, 81, 100',
 '1, 8, 27, 64, 125, 216, 343, 512, 729, 1000',
 '1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880',
 '1, 3, 6, 10, 15, 21, 28, 36, 45, 55',
 '2, 3, 5, 8, 13, 21, 34, 55, 89, 144',
 '0, 1, 1, 2, 3, 5, 8, 13, 21, 34',
 '1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000',
 '1, 2, 5, 14, 42, 132, 429, 1430, 4862, 16796',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '4, 5, 7, 9, 10, 11, 13, 15, 17, 19, 20, 21, 23, 25',
 '1, 10, 11, 100, 101, 110, 111, 1000, 1001, 1010',
 '1, 1, 4, 27, 256, 1, 6, 49, 512, 6561',
 '1, 2, 145, 40585',
 '1, 5, 11, 19, 29, 41, 55, 71, 89, 109',
 '1, 8, 10, 18, 19, 100, 101, 108, 109, 110',
 '3, 7, 31, 127, 8191, 131071, 524287, 536870911',
 '1, 2, 4, 8, 16, 23, 33, 64, 79, 86',
 '1, 1, 1, 2, 3, 6, 10, 17, 29, 4',
 '1, 5, 12, 22, 35, 51, 70, 92, 117, 145',
 '0, 1, 1, 2, 2, 2, 3, 3, 3, 3',
 '1,   2,  11,  78, 695, 7572, 97747, 458640, 699141, 825048',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
 '1, 3, 7, 15, 31, 63, 127, 255, 511, 1023',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 1, 2, 3, 5, 8, 13, 21, 34, 5',
 '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
 '1, 3, 9, 27, 81, 243, 729, 2187, 6561, 19683',
 '1, 4, 9, 16, 25, 36, 49, 64, 81, 100',
 '1, 8, 27, 64, 125, 216, 343, 512, 729, 1000',
 '1, 2, 6, 24, 120, 720, 5040, 40320, 362880, 3628800',
 '1, 3, 6, 10, 15, 21, 28, 36, 45, 55',
 '2, 1, 3, 5, 6, 9, 14, 20, 29, 4',
 '0, 1, 1, 2, 3, 5, 8, 13, 21, 34',
 '1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000',
 '1, 2, 5, 14, 42, 132, 429, 1430, 4862, 16796',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '2, 3, 4, 6, 8, 9, 10, 12, 14, 15, 16, 18, 20, 21, 22, 24, 26',
 '1, 10, 11, 100, 101, 110, 111, 1000, 1001, 1010',
 '1, 1, 4, 27, 256, 1, 6, 49, 512, 6561',
 '1, 2, 145, 40585',
 '2, 5, 10, 17, 26, 37, 50, 65, 82, 101',
 '1, 8, 11, 18, 81, 88',
 '3, 15, 255, 65535, 4294967295, 18446744073709552000, 3.402823669209385e+38, 1.157920892373162e+77, 1.3407807929942597e+154, Infinity',
 '1, 2, 4, 8, 16, 21, 36, 56, 81, 111',
 '1, 2, 4, 8, 13, 23, 40, 68, 118, 203',
 '1, 5, 14, 30, 55, 91, 140, 204, 285, 385',
 '0, 1, 1, 1, 2, 2, 2, 3, 3, 3',
 '1, 1, 4, 18, 88, 462, 2590, 15442, 97558, 650794',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
 '1, 3, 7, 15, 31, 63, 127, 255, 511, 1023',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 1, 2, 3, 5, 8, 13, 21, 34, 5',
 '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
 '1, 3, 9, 27, 81, 243, 729, 2187, 6561, 19683',
 '1, 4, 9, 16, 25, 36, 49, 64, 81, 100',
 '1, 8, 27, 64, 125, 216, 343, 512, 729, 1000',
 '1,    2,   6,   24, 120,  720, 5040, 40320, 362880, 3628800',
 '1, 3, 6, 10, 15, 21, 28, 36, 45, 55',
 '2, 1, 3, 6, 10, 19, 35, 64, 118, 217',
 '0, 1, 1, 2, 3, 5, 8, 13, 21, 34',
 '1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000',
 '1, 1, 2, 5, 14, 42, 132, 429, 1430, 4862',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '2, 3, 4, 6, 8, 9, 10, 12, 14, 15, 16, 18, 20, 21, 22, 24, 26',
 '1, 10, 11, 100, 101, 110, 111, 1000, 1001, 1010',
 '1, 1, 1, 3, 6, 14, 36, 93, 255, 729',
 '',
 '1, 5, 11, 19, 29, 41, 55, 71, 89, 109',
 '1, 8, 11, 18, 81, 88',
 '3, 7, 15, 31, 63, 127, 255, 511, 1023, 2047',
 '1, 2, 2, 7, 4, 14, 8, 23, 16, 34',
 '1, 2, 4, 8, 13, 23, 40, 68, 118, 203',
 '1, 5, 11, 19, 29, 41, 55, 71, 89, 109',
 '-1, -1, 0, 0, 1, 2, 2, 3, 4, 5',
 '1, 1, 4, 22, 162, 1544, 18246, 258906, 4319748, 83404102',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '32m1, 32m11, 32m21, 32m1211, 32m111221',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
 '1, 3, 7, 15, 31, 63, 127, 255, 511, 1023',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 1, 2, 3, 5, 8, 13, 21, 34, 5',
 '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
 '1, 3, 9, 27, 81, 243, 729, 2187, 6561, 19683',
 '1, 4, 9, 16, 25, 36, 49, 64, 81, 100',
 '1, 8, 27, 64, 125, 216, 343, 512, 729, 1000',
 '1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880',
 '1, 3, 6, 10, 15, 21, 28, 36, 45, 55',
 '2, 1, 3, 6, 10, 19, 35, 64, 118, 217',
 '0, 1, 1, 2, 3, 5, 8, 13, 21, 34',
 '1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000',
 '1, 1, 2, 5, 14, 42, 132, 429, 1430, 4862',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '2, 3, 4, 6, 8, 9, 10, 12, 14, 15, 16, 18, 20, 21, 22, 24, 26',
 '1, 10, 11, 100, 101, 110, 111, 1000, 1001, 1010',
 '1, 1, 1, 3, 6, 14, 36, 93, 255, 729',
 '1, 2, 145, 40585',
 '1, 5, 11, 19, 29, 41, 55, 71, 89, 109',
 '1, 8, 10, 18, 19, 100, 101, 108, 109, 110',
 '3, 7, 31, 127, 8191, 131071, 524287, 8388607, 536870911',
 '1, 2, 2, 4, 4, 8, 8, 16, 16, 3',
 '1, 2, 4, 8, 15, 29, 56, 108, 208, 401',
 '2, 8, 20, 40, 70, 112, 168, 240, 330, 440',
 '0, 0, 0, 1, 0, 1, 2, 3, 0, 1',
 '1, 1, 2, 5, 14, 42, 132, 429, 1430, 4862',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
 '1, 3, 7, 15, 31, 63, 127, 255, 511, 1023',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 1, 2, 3, 5, 8, 13, 21, 34, 5',
 '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
 '1, 3, 9, 27, 81, 243, 729, 2187, 6561, 19683',
 '1, 4, 9, 16, 25, 36, 49, 64, 81, 100',
 '1, 8, 27, 64, 125, 216, 343, 512, 729, 1000',
 '1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880',
 '1, 3, 6, 10, 15, 21, 28, 36, 45, 55',
 '2, 1, 3, 6, 10, 19, 35, 64, 118, 217',
 '0, 1, 1, 2, 3, 5, 8, 13, 21, 34',
 '1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000',
 '1, 1, 2, 5, 14, 42, 132, 429, 1430, 4862',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '2, 3, 4, 6, 8, 9, 10, 12, 14, 15, 16, 18, 20, 21, 22, 24, 26',
 '1, 10, 11, 100, 101, 110, 111, 1000, 1001, 1010',
 '1, 1, 4, 27, 256, 1, 6, 49, 512, 6561',
 '1, 2, 145, 40585',
 '1, 5, 11, 19, 29, 41, 55, 71, 89, 109',
 '1, 8, 11, 18, 81, 88',
 '7, 31, 127, 511, 2047, 8191, 32767, 131071, 524287, 2097151',
 '1, 2, 4, 8, 16, 17, 19, 23, 31, 47',
 '1, 2, 4, 8, 13, 23, 40, 68, 118, 203',
 '1, 4, 10, 20, 35, 56, 84, 120, 165, 220',
 '0, 0, 0, 1, 0, 1, 2, 3, 0, 1',
 '1, 2, 5, 15, 52, 203, 877, 4140, 21147, 115975',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 32, 32, 32, 32',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
 '1, 3, 7, 15, 31, 63, 127, 255, 511, 1023',
 '1, 4, 9, 16, 25, 36, 49, 64, 81, 100',
 '1, 8, 27, 64, 125, 216, 343, 512, 729, 1000',
 '2, 1, 1, 2, 1, 1, 2, 1, 1, 2',
 '1, 2, 2, 3, 3, 4, 4, 5, 5, 6',
 '2, 4, 8, 16, 32, 64, 128, 256, 512, 1024',
 '1, 5, 11, 19, 29, 41, 55, 71, 89, 109',
 '7, 11, 13, 17, 19, 23, 29, 31, 37, 41',
 '1, 11, 111, 1111, 11111, 111111, 1111111, 11111111, 111111111, 1111111111',
 '4, 31, 301, 3001, 30001, 300001, 3000001, 30000001',
 '1, 3, 7, 13, 21, 31, 43, 57, 73, 91',
 '1, 6, 28, 120, 496, 2016',
 '',
 '5, 11, 17, 25, 35, 47, 61, 77, 95, 115',
 '1, 2, 145, 40585',
 '19, 31, 61, 89, 107, 127, 521, 607, 1279, 2203',
 '2, 3, 7, 42, 1806, 3263442',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '10, 18, 100',
 '0, 1, 2, 1, 2, 3, 2, 3, 4, 3',
 '0, 2, 3, 4, 6, 8, 9, 10, 12, 14',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1 4 2 1 3 5 9 2 6 5',
 '1, 7, 3, 2, 0, 5, 0, 7, 9, ',
 '1, 0, 1, 2, 3, 1, 6, 11',
 '0, 1, 4, 11, 26, 57, 120, 247',
 '3, 11, 29, 61',
 '1, 2, 3, 5, 8, 11, 14, 1',
 '1, 0, 1, 1, 2, 3, 6, 1',
 '1, 4, 9, 16, 25, 36, 49, 64, 81, 100',
 '1, 8, 27, 64, 125, 216, 343, 512, 729, 1000',
 '1, 2, 2, 1, 2, 2, 1, 2, 2, 1',
 '1, 2, 2, 3, 3, 4, 4, 5, 5, 6',
 '1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024',
 '1, 5, 11, 19, 29, 41, 55, 71, 89, 109',
 '7, 11, 13, 17, 19, 23, 29, 31, 37, 41',
 '1, 11, 111, 1111, 11111, 111111, 1111111, 11111111, 111111111, 1111111111',
 '31, 331, 3331, 33331, 333331, 3333331, 33333331, 333333331',
 '1, 2, 4, 7, 11, 16, 22, 29, 37, 46',
 '1, 6, 28, 120, 496, 2016',
 '0, 0, 2, 7, 18, 41, 86, 172, 334, 636',
 '3, 13, 29, 51, 79, 113, 153, 199, 251, 309',
 '1, 2, 145, 40585',
 '19, 31, 61, 89, 107, 127, 521, 607, 1279, 2203',
 '2, 3, 7, 22, 155, 3411',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 8, 11, 18, 81, 88',
 '0, 0, 0, 1, 0, 1, 2, 3, 0, 1',
 '0, 1, 1, 2, 4, 6, 9, 12, 16, 20',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1 4 2 1 3 5 9 2 6 5',
 '1 7 3 2 0 5 0 7 9 8',
 '0, 1, 2, 2, 2, 6, 12, 20',
 '1, 1, 1, 3, 5, 9, 17, 3',
 '2, 3, 5, 7, 11, 13, 17, 31',
 '1, 1, 2, 3, 4, 6, 8, ',
 '1, 0, 1, 1, 2, 3, 6, 1',
 '1, 4, 9, 16, 25, 36, 49, 64, 81, 100',
 '1, 8, 27, 64, 125, 216, 343, 512, 729, 1000',
 '2, 1, 2, 2, 1, 2, 2, 1, 2, 2',
 '1, 2, 2, 3, 3, 3, 4, 4, 4, 4',
 '1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024',
 '1, 5, 11, 19, 29, 41, 55, 71, 89, 109',
 '7, 11, 13, 17, 19, 23, 29, 31, 37, 41',
 '1, 11, 111, 1111, 11111, 111111, 1111111, 11111111, 111111111, 1111111111',
 '',
 '1, 3, 7, 13, 21, 31, 43, 57, 73, 91',
 '1, 6, 28, 120, 496, 2016',
 '0, 0, 0, 1, 2, 4, 6, 9, 12, 1',
 '5, 8, 12, 18, 24, 30, 36, 42, 52, 60',
 '1, 2, 145, 40585',
 '19, 31, 61, 89, 107, 127, 521, 607, 1279, 2203',
 '2, 3, 7, 43, 1807, 3263443',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 8, 11, 18, 81, 88',
 '2, 1, 2, 1, 2, 2, 1, 2, 1, 2',
 '0, 2, 3, 4, 6, 8, 9, 10, 12, 14',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1 4 2 1 3 5 9 2 6 5',
 '',
 '0, 1, 1, 2, 3, 1, 6, 11',
 '1, 1, 1, 0, -4, -16, -48, -128',
 '2, 5, 11, 23, 47, 191, 383, 6143',
 '1, 2, 3, 4, 6, 8, 9, 1',
 '1, 0, 1, 1, 2, 3, 6, 1',
 '1, 4, 9, 16, 25, 36, 49, 64, 81, 100',
 '1, 8, 27, 64, 125, 216, 343, 512, 729, 1000',
 '1, 1, 2, 1, 1, 2, 1, 1, 2, 1',
 '1, 2, 2, 3, 3, 4, 4, 5, 5, 6',
 '1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024',
 '1, 5, 11, 19, 29, 41, 55, 71, 89, 109',
 '7, 11, 13, 17, 19, 23, 29, 31, 37, 41',
 '1, 11, 111, 1111, 11111, 111111, 1111111, 11111111, 111111111, 1111111111',
 '31, 331, 3331, 33331, 333331, 3333331, 33333331, 333333331',
 '1, 3, 7, 13, 21, 31, 43, 57, 73, 91',
 '1, 6, 28, 120, 496, 2016',
 '0, 0, 1, 2, 4, 6, 9, 12, 16, 2',
 'Execution error',
 '1, 2, 145, 40585',
 '19, 31, 61, 89, 107, 127, 521, 607, 1279, 2203',
 '2, 5, 29, 869, 756029, 571580604869',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 8, 11, 18, 81, 88',
 '0, 0, 1, 1, 1, 1, 2, 2, 3, 3',
 '0, 0, 1, 1, 2, 2, 3, 3, 4, 4',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1 4 2 1 3 5 9 2 6 5',
 '1, 7, 3, 2, 0, 5, 0, 7, 9, 8',
 '1, 0, 1, 2, 3, 1, 6, 1',
 '1, 1, 1, 3, 5, 9, 17, 3',
 '3, 5, 11, 17, 31, 41, 59, 67',
 '2, 4, 7, 8, 11, 13',
 '1, 0, 1, 1, 2, 3, 6, 1',
 '1, 4, 9, 16, 25, 36, 49, 64, 81, 100',
 '1, 8, 27, 64, 125, 216, 343, 512, 729, 1000',
 '1, 1, 1, 2, 2, 2, 1, 1, 1, 2',
 '1, 2, 2, 3, 3, 3, 4, 4, 4, 4',
 '1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024',
 '1, 5, 11, 19, 29, 41, 55, 71, 89, 109',
 '7, 11, 13, 17, 19, 23, 29, 31, 37, 41',
 '1, 11, 111, 1111, 11111, 111111, 1111111, 11111111, 111111111, 1111111111',
 '31, 331, 3331, 33331, 333331, 3333331, 33333331, 333333331',
 '1, 3, 7, 13, 21, 31, 43, 57, 73, 91',
 '1, 6, 28, 120, 496, 2016',
 '0, 0, 0, 1, 4, 10, 20, 35, 56, 84',
 '11, 13, 17, 19, 23, 29, 31, 37, 41, 43',
 '1, 2, 145, 40585',
 '19, 31, 61, 89, 107, 127, 521, 607, 1279, 2203',
 '2, 3, 7, 43, 1807, 3263443',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 8, 11, 18, 81, 88',
 '0, 0, 1, 1, 1, 1, 2, 2, 3, 3',
 '0, 1, 2, 3, 2, 3, 4, 5, 4, 5',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1 4 2 1 3 5 9 2 6 5',
 '1, 7, 3, 2, 0, 5, 0, 7, 9, 8',
 '1, 0, 1, 2, 3, 1, 6, 11',
 '1, 1, 1, 1, 1, 1, 1, 1',
 '2, 5, 11, 23, 47, 191, 383, 6143',
 '1, 1, 2, 3, 5, 7, 10, 1',
 '1, 0, 1, 1, 2, 3, 6, 1',
 '29, 57, 68, 120, 134, 140, 173, 197, 283, 313',
 '24 26 36 40 184 226 244 384 391 423',
 '100, 116, 138, 166, 200, 240, 286, 338, 396, 460',
 '20 48 95 234 282 296 352 402 428 481',
 '62, 98, 130, 154, 290, 315, 324, 385, 408, 447',
 '2, 8, 20, 40, 70, 112, 168, 240, 330, 440',
 '128, 151, 153, 217, 224, 332, 382, 400, 450, 47',
 '3, 13, 28, 50, 79, 113, 154, 201, 254, 314',
 '48 94 176 177 219 276 282 283 459 488',
 '139 252 272 281 304 361 370 415 438 500',
 '6, 15, 30, 54, 90, 141, 210, 300, 414, 555',
 '134, 224, 293, 378, 379, 395, 434, 451, 482, 496',
 '23, 30, 44, 79, 135, 212, 310, 436, 590, 779',
 '18, 34, 58, 94, 148, 229, 351, 534, 808, 1219',
 '9, 84, 144, 170, 325, 393, 401, 405, 435, 497',
 '26, 40, 202, 267, 282, 340, 359, 408, 410, 495',
 '34, 106, 164, 236, 295, 411, 469, 541, 599, 671',
 '16 119 121 123 135 139 285 311 409 412',
 '8, 11, 12, 103, 116, 196, 247, 254, 389, 427',
 '12, 96, 112, 120, 121, 122, 123, 124, 125, 126',
 '38, 144, 303, 356, 465, 624, 677, 786, 945, 998',
 '13, 40, 81, 136, 205, 288, 385, 496, 621, 760',
 '3, 5, 6, 7, 10, 11, 12, 13, 14, 15',
 '4, 20, 60, 420, 840, 909, 922, 924, 986, 1123',
 '72, 106, 139, 165, 171, 192, 199, 429, 453, 477',
 '187, 218, 260, 295, 301, 314, 379, 410, 452, 469',
 '29, 63, 95, 140, 150, 190, 221, 437, 482, 491',
 '3, 6, 14, 30, 55, 91, 141, 206, 288, 390',
 '26, 94, 98, 137, 176, 301, 323, 330, 372, 444',
 '39, 81, 88, 210, 215, 378, 416, 430, 439, 490',
 '',
 '24, 26, 36, 40, 184, 226, 244, 384, 391, 423',
 '100, 119, 146, 181, 224, 275, 334, 401, 476, 559',

In [202]:
correctness_list

[True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 'False',
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False]

In [203]:
levenshtein_list

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 15,
 16,
 0,
 20,
 0,
 20,
 0,
 31,
 0,
 13,
 0,
 15,
 7,
 15,
 0,
 3,
 30,
 0,
 23,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 12,
 0,
 10,
 16,
 0,
 20,
 0,
 26,
 0,
 31,
 0,
 11,
 24,
 97,
 10,
 10,
 15,
 3,
 26,
 0,
 23,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 16,
 0,
 14,
 16,
 0,
 18,
 0,
 26,
 0,
 30,
 16,
 13,
 24,
 38,
 13,
 10,
 15,
 7,
 32,
 0,
 15,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 14,
 16,
 0,
 18,
 0,
 26,
 0,
 30,
 0,
 13,
 0,
 6,
 13,
 12,
 21,
 7,
 24,
 0,
 23,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 14,
 16,
 0,
 18,
 0,
 26,
 0,
 31,
 0,
 13,
 24,
 30,
 10,
 10,
 13,
 7,
 0,
 0,
 12,
 0,
 0,
 0,
 0,
 0,
 7,
 2,
 0,
 13,
 0,
 0,
 30,
 0,
 17,
 32,
 21,
 0,
 0,
 0,
 0,
 30,
 5,
 12,
 0,
 9,
 1,
 0,
 14,
 17,
 6,
 1,
 0,
 0,
 3,
 2,
 3,
 13,
 0,
 0,
 0,
 15,
 17,
 14,
 20,
 0,
 0,
 9,
 0,
 24,
 7,
 9,
 0,
 9,
 9,
 9,
 6,
 12,
 9,
 1,
 0,
 0,
 4,
 3,
 3,
 13,
 0,
 0,
 58,
 0,
 17,
 11,
 23,
 0,
 0,
 3,
 0,
 24,
 7,
 12,
 0,
 9,
 28,
 2,
 12,
 13,
 3,
 1,
 0,
 0,
 4,
 2,
 3,
 13,
 0,
 0,
 0,
 0,
 17,
 11,
 50000,
 0,
 0,
 21,
 0,
 24,
 5,
 6,
 0,
 9,
 0,
 1,
 6,
 0,
 7,
 1,
 0,
 0,
 5,
 3,
 3,
 13,
 0,
 0,
 0,
 0,
 17,
 12,
 21,
 0,
 0,
 3,
 0,
 24,
 5,
 6,
 0,
 9,
 0,
 0,
 6,
 13,
 7,
 1,
 0,
 9,
 23,
 9,
 0,
 21,
 1,
 26,
 9,
 9,
 22,
 0,
 23,
 20,
 0,
 0,
 22,
 9,
 0,
 21,
 26,
 23,
 28,
 26,
 0,
 0,
 0,
 21,
 0,
 0,
 45,
 0,
 26,
 0,
 0,
 22,
 25,
 0,
 9,
 27,
 26,
 24,
 24,
 9,
 0,
 0,
 0,
 9,
 0,
 9,
 0,
 0,
 0,
 0,
 9,
 0,
 0,
 19,
 0,
 9,
 25,
 0,
 24,
 9,
 0,
 21,
 0,
 24,
 9,
 0,
 27,
 9,
 0,
 0,
 0,
 20,
 23,
 9,
 0,
 0,
 0,
 24,
 458,
 0,
 47,
 48,
 0,
 44,
 15,
 9,
 22,
 0,
 22,
 9,
 18,
 22,
 174,
 27,
 0,
 0,
 26,
 27,
 24,
 0,
 9,
 0,
 21,
 9,
 0,
 9,
 0,
 24,
 0,
 0,
 0,
 1,
 19,
 16,
 21,
 0,
 25,
 0,
 22,
 9,
 0,
 23,
 174,
 19,
 9,
 0,
 26,
 34,
 0,
 0,
 9,
 0,
 0,
 9,
 0,
 9,
 0,
 22,
 0,
 0,
 0,
 9,
 0,
 0,
 21,
 9]

In [204]:
j_df["exe_out"] = exe_outputs
j_df["correct_execution"] = correctness_list
j_df["Levenshtein"] = levenshtein_list
j_df

,sequence,complexity,length_type,language,q_length,GPT4_answer,a_length,temperature,real_code,print_code,no_code,explanation,no_sense,exe_out,correct_execution,Levenshtein
8850,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",1.0,0.0,JavaScript,172.0,```javascript\nfor (let i = 2; i <= 20; i += 2...,72.0,1.000,0.0,0,0.0,0.0,0,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",True,0
8851,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",1.0,0.0,JavaScript,173.0,```javascript\nfor (let i = 3; i <= 30; i += 3...,74.0,1.000,0.0,0,0.0,0.0,0,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",True,0
8852,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",1.0,0.0,JavaScript,174.0,```javascript\nfor(let i = 4; i <= 40; i += 4)...,73.0,1.000,0.0,0,0.0,0.0,0,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",True,0
8853,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",1.0,0.0,JavaScript,175.0,```javascript\nfor (let i = 5; i <= 50; i += 5...,74.0,1.000,0.0,0,0.0,0.0,0,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",True,0
8854,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",1.0,0.0,JavaScript,175.0,```javascript\nfor (let i = 1; i <= 10; i++) {...,75.0,1.000,0.0,0,0.0,0.0,0,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9435,"187, 218, 260, 295, 301, 314, 379, 410, 452, 469",4.0,0.0,JavaScript,185.0,"```javascript\nconsole.log(187, 218, 260, 295,...",80.0,0.001,0.0,0,0.0,0.0,0,187 218 260 295 301 314 379 410 452 469,False,9
9436,"29, 63, 95, 140, 150, 190, 221, 437, 482, 491",4.0,0.0,JavaScript,182.0,"```javascript\nlet sequence = [29, 63, 95, 140...",104.0,0.001,0.0,0,0.0,0.0,0,"29, 63, 95, 140, 150, 190, 221, 437, 482, 491",True,0
9437,"3, 11, 84, 144, 156, 177, 188, 199, 229, 284",4.0,0.0,JavaScript,181.0,```javascript\nlet sequence = [3];\nfor (let i...,730.0,0.001,0.0,0,0.0,0.0,0,"3, 11, 84, 144, 156, 177, 188, 199, 229, 284",True,0
9438,"26, 94, 98, 137, 176, 301, 323, 330, 372, 444",4.0,0.0,JavaScript,182.0,```javascript\nlet sequence = [];\nlet current...,250.0,0.001,0.0,0,0.0,0.0,0,"26, 94, 133, 201, 240, 308, 347, 415, 454, 522",False,21
9439,"39, 81, 88, 210, 215, 378, 416, 430, 439, 490",4.0,0.0,JavaScript,182.0,"```javascript\nconsole.log(39, 81, 88, 210, 21...",77.0,0.001,0.0,0,0.0,0.0,0,39 81 88 210 215 378 416 430 439 490,False,9

In [205]:
j_df.to_csv("javascript_evaluation.csv", index=False)

# Mathematica

In [260]:
#####################################################################
# HOW RUN MATHEMATICA CODE FROM PYTHON
# https://reference.wolfram.com/language/WolframClientForPython/
######################################################################

In [206]:
import pandas as pd
import subprocess
import time
import copy
from enchant.utils import levenshtein

In [207]:
OIA_ds = pd.read_csv("/Users/beto/Documents/Projects/medLLM/no_small_seqs_clean.csv")
m_df = copy.deepcopy(OIA_ds[OIA_ds["language"] == "Mathematica"])
original_sequences = m_df["sequence"].values

m_code_list = (OIA_ds[OIA_ds["language"] == "Mathematica"])["GPT4_answer"].values
total_questions = len(m_code_list)

In [208]:
m_df

,sequence,complexity,length_type,language,q_length,GPT4_answer,a_length,temperature,real_code,print_code,no_code,explanation,no_sense,exe_out,correct_execution,Levenshtein
7080,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",1.0,0.0,Mathematica,173.0,"```mathematica\nTable[2 i, {i, 1, 10}]\n```",41.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
7081,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",1.0,0.0,Mathematica,174.0,"```mathematica\nTable[3*n, {n, 1, 10}]\n```",41.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
7082,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",1.0,0.0,Mathematica,175.0,"```mathematica\nRange[4, 40, 4]\n```",34.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
7083,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",1.0,0.0,Mathematica,176.0,"```mathematica\nTable[5*i, {i, 1, 10}]\n```",41.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
7084,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",1.0,0.0,Mathematica,176.0,"```mathematica\nTable[6*i, {i, 1, 10}]\n```",41.0,1.000,0.0,0,0.0,0.0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7665,"187, 218, 260, 295, 301, 314, 379, 410, 452, 469",4.0,0.0,Mathematica,186.0,"```mathematica\nSequence[187, 218, 260, 295, 3...",77.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN
7666,"29, 63, 95, 140, 150, 190, 221, 437, 482, 491",4.0,0.0,Mathematica,183.0,"```mathematica\nSequence[29, 63, 95, 140, 150,...",74.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN
7667,"3, 11, 84, 144, 156, 177, 188, 199, 229, 284",4.0,0.0,Mathematica,182.0,"```mathematica\nSequence[3, 11, 84, 144, 156, ...",73.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN
7668,"26, 94, 98, 137, 176, 301, 323, 330, 372, 444",4.0,0.0,Mathematica,183.0,"```mathematica\nSequence[26, 94, 98, 137, 176,...",74.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN
7669,"39, 81, 88, 210, 215, 378, 416, 430, 439, 490",4.0,0.0,Mathematica,183.0,"```mathematica\nTable[n^3 - n, {n, 4, 13}]\n```",45.0,0.001,0.0,0,0.0,0.0,0,NaN,NaN,NaN

In [209]:
m_code_list[1:5]

array(['```mathematica\nTable[3*n, {n, 1, 10}]\n```',
       '```mathematica\nRange[4, 40, 4]\n```',
       '```mathematica\nTable[5*i, {i, 1, 10}]\n```',
       '```mathematica\nTable[6*i, {i, 1, 10}]\n```'], dtype=object)

In [210]:
len(m_code_list)

590

In [216]:
from wolframclient.evaluation import WolframLanguageSession
from wolframclient.language import wl, wlexpr

session = WolframLanguageSession()

In [285]:
counter = -1
exe_outputs = []
levenshtein_list = []
correctness_list = []
test_code = []

for code in m_code_list:  # [0:15]:
    code = code.replace("```mathematica" + "\n", "")
    code = code.replace("```Mathematica" + "\n", "")
    code = code.replace("\n" + "```", "")

    # print(code)
    counter += 1
    name_file = "m_" + str(counter)
    surname_file = ".m"
    whole_name = name_file + surname_file

    original_seq = original_sequences[counter]

    print(
        "######################  INITIALIZE PROCESS ########################## (",
        str(counter),
        ")",
    )
    try:
        # print(code)
        out = str(session.evaluate(wlexpr(code)))

        # print("creating file...")
        # test_code.append(code)
        # ! echo -e {code} > {whole_name}

        # rough_jar = subprocess.run(["session.evaluate(wlexpr('{}')".format(code)], capture_output=True, text=True, timeout=10)
        # print("EXECUTION OUT: ")
        # # print(rough_jar.stdout.strip())
        # out = rough_jar.stdout.strip()
        out = out.replace("PackedArray([ ", "")
        out = out.replace("], dtype=int8),", "")
        out = out.replace("(", "")
        out = out.replace(")", "")
        out = out.replace("[ ", "")
        out = out.replace("  ", ", ")
        out = out.replace(" ", ", ")
        out = out.replace("]", "")
        out = out.replace("[", "")
        out = out.replace("\n", ", ")
        out = out.replace("FindSequenceFunction", "")
        out = out.replace(",  ", ", ")
        out = out.replace(", , ", ", ")

        fist = out[:2]
        if fist == ", ":
            out = out[2 : len(out) - 1]
        fist = out[:3]
        if fist == ",, ":
            out = out[3 : len(out) - 1]
        out = out.replace(",, ", ", ")
        out = out.replace("BaseForm", "")
        out = out.replace("DirectedInfinity", "")
        out = out.replace("nan,, ", "")
        out = out.replace("TotalTake", "")
        out = out.replace("', '", ", ")
        out = out.replace("Plus", "")
        out = out.replace("Part", "")
        out = out.replace("None", "")
        out = out.replace(", , ", ", ")
        # out = out.replace(",, TotalTakeTotalTakeTotalTake", ", ")
        # out = out(",, TotalTakeTotalTake", ", ")
        print(out)
        exe_outputs.append(out)
        correctness_list.append(out == original_seq)
        levenshtein_list.append(levenshtein(out, original_seq))

    except:
        print("**************** execution error ( step 2)")
        print(rough_jar.stderr)
        exe_outputs.append("Execution error")
        correctness_list.append("False")
        levenshtein_list.append(50000)
        pass

Indeterminate expression Power[0, 0] encountered.
Indeterminate expression Power[0, 0] encountered.

######################  INITIALIZE PROCESS ########################## ( 0 )
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 1 )
3, 6, 9, 12, 15, 18, 21, 24, 27, 30
######################  INITIALIZE PROCESS ########################## ( 2 )
4, 8, 12, 16, 20, 24, 28, 32, 36, 40
######################  INITIALIZE PROCESS ########################## ( 3 )
5, 10, 15, 20, 25, 30, 35, 40, 45, 50
######################  INITIALIZE PROCESS ########################## ( 4 )
6, 12, 18, 24, 30, 36, 42, 48, 54, 60
######################  INITIALIZE PROCESS ########################## ( 5 )
7, 14, 21, 28, 35, 42, 49, 56, 63, 70
######################  INITIALIZE PROCESS ########################## ( 6 )
8, 16, 24, 32, 40, 48, 56, 64, 72, 80
######################  INITIALIZE PROCESS ########################## ( 7 )
9, 18, 27, 36, 45, 54, 63, 72, 81, 90
######################  INITIALIZE PROCESS ########################## ( 8 )
10, 20, 30, 40, 50, 60, 70, 80, 90, 100
######################  INITIALIZE PROCESS ########################## ( 9 )
1, 3, 5, 7, 9, 11, 13, 15, 17, 19
######################  INITIALIZE PROCESS ########################## ( 10 )
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 11 )
11, 12, 13, 14, 15, 16, 17, 18, 19, 20
######################  INITIALIZE PROCESS ########################## ( 12 )
21, 22, 23, 24, 25, 26, 27, 28, 29, 30
######################  INITIALIZE PROCESS ########################## ( 13 )
31, 32, 33, 34, 35, 36, 37, 38, 39, 40
######################  INITIALIZE PROCESS ########################## ( 14 )
41, 42, 43, 44, 45, 46, 47, 48, 49, 50
######################  INITIALIZE PROCESS ########################## ( 15 )
51, 52, 53, 54, 55, 56, 57, 58, 59, 60
######################  INITIALIZE PROCESS ########################## ( 16 )
61, 62, 63, 64, 65, 66, 67, 68, 69, 70
######################  INITIALIZE PROCESS ########################## ( 17 )
71, 72, 73, 74, 75, 76, 77, 78, 79, 80
######################  INITIALIZE PROCESS ########################## ( 18 )
81, 82, 83, 84, 85, 86, 87, 88, 89, 90
######################  INITIALIZE PROCESS ########################## ( 19 )
91, 92, 93, 94, 95, 96, 97, 98, 99, 100
######################  INITIALIZE PROCESS ########################## ( 20 )
101, 102, 103, 104, 105, 106, 107, 108, 109, 110
######################  INITIALIZE PROCESS ########################## ( 21 )
111, 112, 113, 114, 115, 116, 117, 118, 119, 120
######################  INITIALIZE PROCESS ########################## ( 22 )
121, 122, 123, 124, 125, 126, 127, 128, 129, 130
######################  INITIALIZE PROCESS ########################## ( 23 )
131, 132, 133, 134, 135, 136, 137, 138, 139, 140
######################  INITIALIZE PROCESS ########################## ( 24 )
141, 142, 143, 144, 145, 146, 147, 148, 149, 150
######################  INITIALIZE PROCESS ########################## ( 25 )
151, 152, 153, 154, 155, 156, 157, 158, 159, 160
######################  INITIALIZE PROCESS ########################## ( 26 )
161, 162, 163, 164, 165, 166, 167, 168, 169, 170
######################  INITIALIZE PROCESS ########################## ( 27 )
171, 172, 173, 174, 175, 176, 177, 178, 179, 180
######################  INITIALIZE PROCESS ########################## ( 28 )
181, 182, 183, 184, 185, 186, 187, 188, 189, 190
######################  INITIALIZE PROCESS ########################## ( 29 )
191, 192, 193, 194, 195, 196, 197, 198, 199, 200
######################  INITIALIZE PROCESS ########################## ( 30 )
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 31 )
3, 6, 9, 12, 15, 18, 21, 24, 27, 30
######################  INITIALIZE PROCESS ########################## ( 32 )
4, 8, 12, 16, 20, 24, 28, 32, 36, 40
######################  INITIALIZE PROCESS ########################## ( 33 )
5, 10, 15, 20, 25, 30, 35, 40, 45, 50
######################  INITIALIZE PROCESS ########################## ( 34 )
6, 12, 18, 24, 30, 36, 42, 48, 54, 60
######################  INITIALIZE PROCESS ########################## ( 35 )
7, 14, 21, 28, 35, 42, 49, 56, 63, 70
######################  INITIALIZE PROCESS ########################## ( 36 )
8, 16, 24, 32, 40, 48, 56, 64, 72, 80
######################  INITIALIZE PROCESS ########################## ( 37 )
9, 18, 27, 36, 45, 54, 63, 72, 81, 90
######################  INITIALIZE PROCESS ########################## ( 38 )
10, 20, 30, 40, 50, 60, 70, 80, 90, 100
######################  INITIALIZE PROCESS ########################## ( 39 )
1, 3, 5, 7, 9, 11, 13, 15, 17, 19
######################  INITIALIZE PROCESS ########################## ( 40 )
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 41 )
11, 12, 13, 14, 15, 16, 17, 18, 19, 20
######################  INITIALIZE PROCESS ########################## ( 42 )
21, 22, 23, 24, 25, 26, 27, 28, 29, 30
######################  INITIALIZE PROCESS ########################## ( 43 )
31, 32, 33, 34, 35, 36, 37, 38, 39, 40
######################  INITIALIZE PROCESS ########################## ( 44 )
41, 42, 43, 44, 45, 46, 47, 48, 49, 50
######################  INITIALIZE PROCESS ########################## ( 45 )
51, 52, 53, 54, 55, 56, 57, 58, 59, 60
######################  INITIALIZE PROCESS ########################## ( 46 )
61, 62, 63, 64, 65, 66, 67, 68, 69, 70
######################  INITIALIZE PROCESS ########################## ( 47 )
71, 72, 73, 74, 75, 76, 77, 78, 79, 80
######################  INITIALIZE PROCESS ########################## ( 48 )
81, 82, 83, 84, 85, 86, 87, 88, 89, 90
######################  INITIALIZE PROCESS ########################## ( 49 )
91, 92, 93, 94, 95, 96, 97, 98, 99, 100
######################  INITIALIZE PROCESS ########################## ( 50 )
101, 102, 103, 104, 105, 106, 107, 108, 109, 110
######################  INITIALIZE PROCESS ########################## ( 51 )
111, 112, 113, 114, 115, 116, 117, 118, 119, 120
######################  INITIALIZE PROCESS ########################## ( 52 )
121, 122, 123, 124, 125, 126, 127, 128, 129, 130
######################  INITIALIZE PROCESS ########################## ( 53 )
131, 132, 133, 134, 135, 136, 137, 138, 139, 140
######################  INITIALIZE PROCESS ########################## ( 54 )
141, 142, 143, 144, 145, 146, 147, 148, 149, 150
######################  INITIALIZE PROCESS ########################## ( 55 )
151, 152, 153, 154, 155, 156, 157, 158, 159, 160
######################  INITIALIZE PROCESS ########################## ( 56 )
161, 162, 163, 164, 165, 166, 167, 168, 169, 170
######################  INITIALIZE PROCESS ########################## ( 57 )
171, 172, 173, 174, 175, 176, 177, 178, 179, 180
######################  INITIALIZE PROCESS ########################## ( 58 )
181, 182, 183, 184, 185, 186, 187, 188, 189, 190
######################  INITIALIZE PROCESS ########################## ( 59 )
191, 192, 193, 194, 195, 196, 197, 198, 199, 200
######################  INITIALIZE PROCESS ########################## ( 60 )
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 61 )
3, 6, 9, 12, 15, 18, 21, 24, 27, 30
######################  INITIALIZE PROCESS ########################## ( 62 )
4, 8, 12, 16, 20, 24, 28, 32, 36, 40
######################  INITIALIZE PROCESS ########################## ( 63 )
5, 10, 15, 20, 25, 30, 35, 40, 45, 50
######################  INITIALIZE PROCESS ########################## ( 64 )
6, 12, 18, 24, 30, 36, 42, 48, 54, 60
######################  INITIALIZE PROCESS ########################## ( 65 )
7, 14, 21, 28, 35, 42, 49, 56, 63, 70
######################  INITIALIZE PROCESS ########################## ( 66 )
8, 16, 24, 32, 40, 48, 56, 64, 72, 80
######################  INITIALIZE PROCESS ########################## ( 67 )
9, 18, 27, 36, 45, 54, 63, 72, 81, 90
######################  INITIALIZE PROCESS ########################## ( 68 )
10, 20, 30, 40, 50, 60, 70, 80, 90, 100
######################  INITIALIZE PROCESS ########################## ( 69 )
1, 3, 5, 7, 9, 11, 13, 15, 17, 19
######################  INITIALIZE PROCESS ########################## ( 70 )
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 71 )
11, 12, 13, 14, 15, 16, 17, 18, 19, 20
######################  INITIALIZE PROCESS ########################## ( 72 )
21, 22, 23, 24, 25, 26, 27, 28, 29, 30
######################  INITIALIZE PROCESS ########################## ( 73 )
31, 32, 33, 34, 35, 36, 37, 38, 39, 40
######################  INITIALIZE PROCESS ########################## ( 74 )
41, 42, 43, 44, 45, 46, 47, 48, 49, 50
######################  INITIALIZE PROCESS ########################## ( 75 )
51, 52, 53, 54, 55, 56, 57, 58, 59, 60
######################  INITIALIZE PROCESS ########################## ( 76 )
61, 62, 63, 64, 65, 66, 67, 68, 69, 70
######################  INITIALIZE PROCESS ########################## ( 77 )
71, 72, 73, 74, 75, 76, 77, 78, 79, 80
######################  INITIALIZE PROCESS ########################## ( 78 )
81, 82, 83, 84, 85, 86, 87, 88, 89, 90
######################  INITIALIZE PROCESS ########################## ( 79 )
91, 92, 93, 94, 95, 96, 97, 98, 99, 100
######################  INITIALIZE PROCESS ########################## ( 80 )
101, 102, 103, 104, 105, 106, 107, 108, 109, 110
######################  INITIALIZE PROCESS ########################## ( 81 )
111, 112, 113, 114, 115, 116, 117, 118, 119, 120
######################  INITIALIZE PROCESS ########################## ( 82 )
121, 122, 123, 124, 125, 126, 127, 128, 129, 130
######################  INITIALIZE PROCESS ########################## ( 83 )
131, 132, 133, 134, 135, 136, 137, 138, 139, 140
######################  INITIALIZE PROCESS ########################## ( 84 )
141, 142, 143, 144, 145, 146, 147, 148, 149, 150
######################  INITIALIZE PROCESS ########################## ( 85 )
151, 152, 153, 154, 155, 156, 157, 158, 159, 160
######################  INITIALIZE PROCESS ########################## ( 86 )
161, 162, 163, 164, 165, 166, 167, 168, 169, 170
######################  INITIALIZE PROCESS ########################## ( 87 )
171, 172, 173, 174, 175, 176, 177, 178, 179, 180
######################  INITIALIZE PROCESS ########################## ( 88 )
181, 182, 183, 184, 185, 186, 187, 188, 189, 190
######################  INITIALIZE PROCESS ########################## ( 89 )
191, 192, 193, 194, 195, 196, 197, 198, 199, 200
######################  INITIALIZE PROCESS ########################## ( 90 )
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 91 )
3, 6, 9, 12, 15, 18, 21, 24, 27, 30
######################  INITIALIZE PROCESS ########################## ( 92 )
4, 8, 12, 16, 20, 24, 28, 32, 36, 40
######################  INITIALIZE PROCESS ########################## ( 93 )
5, 10, 15, 20, 25, 30, 35, 40, 45, 50
######################  INITIALIZE PROCESS ########################## ( 94 )
6, 12, 18, 24, 30, 36, 42, 48, 54, 60
######################  INITIALIZE PROCESS ########################## ( 95 )
7, 14, 21, 28, 35, 42, 49, 56, 63, 70
######################  INITIALIZE PROCESS ########################## ( 96 )
8, 16, 24, 32, 40, 48, 56, 64, 72, 80
######################  INITIALIZE PROCESS ########################## ( 97 )
9, 18, 27, 36, 45, 54, 63, 72, 81, 90
######################  INITIALIZE PROCESS ########################## ( 98 )
10, 20, 30, 40, 50, 60, 70, 80, 90, 100
######################  INITIALIZE PROCESS ########################## ( 99 )
1, 3, 5, 7, 9, 11, 13, 15, 17, 19
######################  INITIALIZE PROCESS ########################## ( 100 )
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 101 )
11, 12, 13, 14, 15, 16, 17, 18, 19, 20
######################  INITIALIZE PROCESS ########################## ( 102 )
21, 22, 23, 24, 25, 26, 27, 28, 29, 30
######################  INITIALIZE PROCESS ########################## ( 103 )
31, 32, 33, 34, 35, 36, 37, 38, 39, 40
######################  INITIALIZE PROCESS ########################## ( 104 )
41, 42, 43, 44, 45, 46, 47, 48, 49, 50
######################  INITIALIZE PROCESS ########################## ( 105 )
51, 52, 53, 54, 55, 56, 57, 58, 59, 60
######################  INITIALIZE PROCESS ########################## ( 106 )
61, 62, 63, 64, 65, 66, 67, 68, 69, 70
######################  INITIALIZE PROCESS ########################## ( 107 )
71, 72, 73, 74, 75, 76, 77, 78, 79, 80
######################  INITIALIZE PROCESS ########################## ( 108 )
81, 82, 83, 84, 85, 86, 87, 88, 89, 90
######################  INITIALIZE PROCESS ########################## ( 109 )
91, 92, 93, 94, 95, 96, 97, 98, 99, 100
######################  INITIALIZE PROCESS ########################## ( 110 )
101, 102, 103, 104, 105, 106, 107, 108, 109, 110
######################  INITIALIZE PROCESS ########################## ( 111 )
111, 112, 113, 114, 115, 116, 117, 118, 119, 120
######################  INITIALIZE PROCESS ########################## ( 112 )
121, 122, 123, 124, 125, 126, 127, 128, 129, 130
######################  INITIALIZE PROCESS ########################## ( 113 )
131, 132, 133, 134, 135, 136, 137, 138, 139, 140
######################  INITIALIZE PROCESS ########################## ( 114 )
141, 142, 143, 144, 145, 146, 147, 148, 149, 150
######################  INITIALIZE PROCESS ########################## ( 115 )
151, 152, 153, 154, 155, 156, 157, 158, 159, 160
######################  INITIALIZE PROCESS ########################## ( 116 )
161, 162, 163, 164, 165, 166, 167, 168, 169, 170
######################  INITIALIZE PROCESS ########################## ( 117 )
171, 172, 173, 174, 175, 176, 177, 178, 179, 180
######################  INITIALIZE PROCESS ########################## ( 118 )
181, 182, 183, 184, 185, 186, 187, 188, 189, 190
######################  INITIALIZE PROCESS ########################## ( 119 )
191, 192, 193, 194, 195, 196, 197, 198, 199, 200
######################  INITIALIZE PROCESS ########################## ( 120 )
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 121 )
3, 6, 9, 12, 15, 18, 21, 24, 27, 30
######################  INITIALIZE PROCESS ########################## ( 122 )
4, 8, 12, 16, 20, 24, 28, 32, 36, 40
######################  INITIALIZE PROCESS ########################## ( 123 )
5, 10, 15, 20, 25, 30, 35, 40, 45, 50
######################  INITIALIZE PROCESS ########################## ( 124 )
6, 12, 18, 24, 30, 36, 42, 48, 54, 60
######################  INITIALIZE PROCESS ########################## ( 125 )
7, 14, 21, 28, 35, 42, 49, 56, 63, 70
######################  INITIALIZE PROCESS ########################## ( 126 )
8, 16, 24, 32, 40, 48, 56, 64, 72, 80
######################  INITIALIZE PROCESS ########################## ( 127 )
9, 18, 27, 36, 45, 54, 63, 72, 81, 90
######################  INITIALIZE PROCESS ########################## ( 128 )
10, 20, 30, 40, 50, 60, 70, 80, 90, 100
######################  INITIALIZE PROCESS ########################## ( 129 )
1, 3, 5, 7, 9, 11, 13, 15, 17, 19
######################  INITIALIZE PROCESS ########################## ( 130 )
2, 4, 6, 8, 10, 12, 14, 16, 18, 20
######################  INITIALIZE PROCESS ########################## ( 131 )
11, 12, 13, 14, 15, 16, 17, 18, 19, 20
######################  INITIALIZE PROCESS ########################## ( 132 )
21, 22, 23, 24, 25, 26, 27, 28, 29, 30
######################  INITIALIZE PROCESS ########################## ( 133 )
31, 32, 33, 34, 35, 36, 37, 38, 39, 40
######################  INITIALIZE PROCESS ########################## ( 134 )
41, 42, 43, 44, 45, 46, 47, 48, 49, 50
######################  INITIALIZE PROCESS ########################## ( 135 )
51, 52, 53, 54, 55, 56, 57, 58, 59, 60
######################  INITIALIZE PROCESS ########################## ( 136 )
61, 62, 63, 64, 65, 66, 67, 68, 69, 70
######################  INITIALIZE PROCESS ########################## ( 137 )
71, 72, 73, 74, 75, 76, 77, 78, 79, 80
######################  INITIALIZE PROCESS ########################## ( 138 )
81, 82, 83, 84, 85, 86, 87, 88, 89, 90
######################  INITIALIZE PROCESS ########################## ( 139 )
91, 92, 93, 94, 95, 96, 97, 98, 99, 100
######################  INITIALIZE PROCESS ########################## ( 140 )
101, 102, 103, 104, 105, 106, 107, 108, 109, 110
######################  INITIALIZE PROCESS ########################## ( 141 )
111, 112, 113, 114, 115, 116, 117, 118, 119, 120
######################  INITIALIZE PROCESS ########################## ( 142 )
121, 122, 123, 124, 125, 126, 127, 128, 129, 130
######################  INITIALIZE PROCESS ########################## ( 143 )
131, 132, 133, 134, 135, 136, 137, 138, 139, 140
######################  INITIALIZE PROCESS ########################## ( 144 )
141, 142, 143, 144, 145, 146, 147, 148, 149, 150
######################  INITIALIZE PROCESS ########################## ( 145 )
151, 152, 153, 154, 155, 156, 157, 158, 159, 160
######################  INITIALIZE PROCESS ########################## ( 146 )
161, 162, 163, 164, 165, 166, 167, 168, 169, 170
######################  INITIALIZE PROCESS ########################## ( 147 )
171, 172, 173, 174, 175, 176, 177, 178, 179, 180
######################  INITIALIZE PROCESS ########################## ( 148 )
181, 182, 183, 184, 185, 186, 187, 188, 189, 190
######################  INITIALIZE PROCESS ########################## ( 149 )
191, 192, 193, 194, 195, 196, 197, 198, 199, 200
######################  INITIALIZE PROCESS ########################## ( 150 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 151 )
1, 1, 2, 3, 5, 8, 13, 21, 34, 55
######################  INITIALIZE PROCESS ########################## ( 152 )
1, 2, 4, 8, 16, 32, 64, 128, 256, 512
######################  INITIALIZE PROCESS ########################## ( 153 )
1, 3, 9, 27, 81, 243, 729, 2187, 6561, 1968
######################  INITIALIZE PROCESS ########################## ( 154 )
1, 4, 9, 16, 25, 36, 49, 64, 81, 100
######################  INITIALIZE PROCESS ########################## ( 155 )
1, 8, 27, 64, 125, 216, 343, 512, 729, 1000
######################  INITIALIZE PROCESS ########################## ( 156 )
1, 2, 6, 24, 120, 720, 5040, 40320, 362880, 3628800
######################  INITIALIZE PROCESS ########################## ( 157 )
1, 3, 6, 10, 15, 21, 28, 36, 45, 55
######################  INITIALIZE PROCESS ########################## ( 158 )
2, 1, 1, 4, 7, 11, 18, 29, 47, 76
######################  INITIALIZE PROCESS ########################## ( 159 )
0, 1, 4, 12, 33, 88, 232, 609, 1596, 4180
######################  INITIALIZE PROCESS ########################## ( 160 )
1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000
######################  INITIALIZE PROCESS ########################## ( 161 )
1, 1, 4, 30, 336, 5040, 95040, 2162160, 57657600, 1764322560
######################  INITIALIZE PROCESS ########################## ( 162 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 163 )
1, 2, 4, 6, 10, 12, 16, 18, 22, 28, 30
######################  INITIALIZE PROCESS ########################## ( 164 )
1, 2, 2, 2, 3, 2, 4, 2, 5, 2, 6, 2, 7, 2, 8, 2, 9, 2, 10, 2
######################  INITIALIZE PROCESS ########################## ( 165 )
nan, 1, 2, 3, 16, 25, 36, 49, 64, 81
######################  INITIALIZE PROCESS ########################## ( 166 )

Nonatomic expression expected at position 1 in Take[3, -2].
Cannot take positions -2 through -1 in Total[Take[3, -2]].
Cannot take positions -2 through -1 in Total[Take[Total[Take[3, -2]], -2]].
Cannot take positions -2 through -1 in Total[Take[Total[Take[Total[Take[3, -2]], -2]], -2]].
Cannot take positions -2 through -1 in Total[Take[Total[Take[Total[Take[Total[Take[3, -2]], -2]], -2]], -2]].
Cannot take positions -2 through -1 in Total[Take[Total[Take[Total[Take[Total[Take[Total[Take[3, -2]], -2]], -2]], -2]], -2]].
Cannot take positions -2 through -1 in Total[Take[Total[Take[Total[Take[Total[Take[Total[Take[Total[Take[3, -2]], -2]], -2]], -2]], -2]], -2]].
Nonatomic expression expected at position 1 in Take[3, -2].
Cannot take positions -2 through -1 in Total[Take[3, -2]].
Cannot take positions -2 through -1 in Total[Take[Total[Take[3, -2]], -2]].
Cannot take positions -2 through -1 in Total[Take[Total[Take[Total[Take[3, -2]], -2]], -2]].
Cannot take positions -2 through -1 in Total[Take[Total[Take[Total[Take[Total[Take[3, -2]], -2]], -2]], -2]].
Cannot take positions -2 through -1 in Total[Take[Total[Take[Total[Take[Total[Take[Total[Take[3, -2]], -2]], -2]], -2]], -2]].
Cannot take positions -2 through -1 in Total[Take[Total[Take[Total[Take[Total[Take[Total[Take[Total[Take[3, -2]], -2]], -2]], -2]], -2]], -2]].
Indeterminate expression Power[0, 0] encountered.
Indeterminate expression Power[0, 0] encountered.

1, 2, 145, 4058
######################  INITIALIZE PROCESS ########################## ( 167 )
2, 5, 10, 17, 26, 37, 50, 65, 82, 101
######################  INITIALIZE PROCESS ########################## ( 168 )
1, 8, 10, 11, 18, 80, 81, 88, 100, 101, 108, 110, 111, 118, 180, 181, 188, 800, 801, 808, 810, 811, 818, 880, 881, 888, 100
######################  INITIALIZE PROCESS ########################## ( 169 )
3, 7, 31, 127, 2047, 8191, 131071, 524287, 8388607, 536870911
######################  INITIALIZE PROCESS ########################## ( 170 )
1, 2, 1, 4, 7, 11, 18, 29, 47, 76
######################  INITIALIZE PROCESS ########################## ( 171 )
1, 2, 1, 4, 7, 11, 18, 29, 47, 76
######################  INITIALIZE PROCESS ########################## ( 172 )
1, 3, 7, 13, 21, 31, 43, 57, 73, 91
######################  INITIALIZE PROCESS ########################## ( 173 )
1, 0, 1, 0, 2, 0, 1, 0, 3, 0
######################  INITIALIZE PROCESS ########################## ( 174 )
1, 1, 2, 1, 4, 7, 11, 18, 29, 47
######################  INITIALIZE PROCESS ########################## ( 175 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 176 )
'1, 1, 1, 1, 1'
######################  INITIALIZE PROCESS ########################## ( 177 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 178 )
1, 2, 4, 8, 16, 32, 64, 128, 256, 51
######################  INITIALIZE PROCESS ########################## ( 179 )
0, 1, 3, 7, 15, 31, 63, 127, 255, 511
######################  INITIALIZE PROCESS ########################## ( 180 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 181 )
1, 1, 2, 3, 5, 8, 13, 21, 34, 55
######################  INITIALIZE PROCESS ########################## ( 182 )
1, 2, 4, 8, 16, 32, 64, 128, 256, 512
######################  INITIALIZE PROCESS ########################## ( 183 )
1, 3, 9, 27, 81, 243, 729, 2187, 6561, 19683
######################  INITIALIZE PROCESS ########################## ( 184 )
1, 4, 9, 16, 25, 36, 49, 64, 81, 100
######################  INITIALIZE PROCESS ########################## ( 185 )
1, 8, 27, 64, 125, 216, 343, 512, 729, 1000
######################  INITIALIZE PROCESS ########################## ( 186 )
1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880
######################  INITIALIZE PROCESS ########################## ( 187 )
1, 3, 6, 10, 15, 21, 28, 36, 45, 55
######################  INITIALIZE PROCESS ########################## ( 188 )
2, 1, 3, 3, -2, 3, -2, -2, 3, -2, -2, -2, 3, -2, -2, -2, -2, 3, -2, -2, -2, -2, -2, 3, -2, -2, -2, -2, -2, -2, 3, -2, -2, -2, -2, -2, -2, -2
######################  INITIALIZE PROCESS ########################## ( 189 )
0, 1, 5, 14, 30, 55, 91, 140, 204, 285
######################  INITIALIZE PROCESS ########################## ( 190 )
1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000
######################  INITIALIZE PROCESS ########################## ( 191 )
1, 1, 2, 5, 14, 42, 132, 429, 1430, 4862
######################  INITIALIZE PROCESS ########################## ( 192 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 193 )
4, 6, 8, 10, 12, 14, 16, 18, 20, 22
######################  INITIALIZE PROCESS ########################## ( 194 )
'1, 10, 11, 100, 101, 110, 111, 1000, 1001, 1010'
######################  INITIALIZE PROCESS ########################## ( 195 )
nan, 1, 2, 3, 16, 25, 36, 49, 64, 81
######################  INITIALIZE PROCESS ########################## ( 196 )

Part specification Part[4, 2] is longer than depth of object.
Part specification Part[4, 3] is longer than depth of object.
Part 3 of Plus[Part[4, 2], Part[4, 3]] does not exist.
Part 3 of Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]] does not exist.
Part 3 of Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]] does not exist.
Part 3 of Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]] does not exist.
Part 3 of Plus[Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3]] does not exist.
Part 3 of Plus[Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3]], 3]] does not exist.
Part 3 of Plus[Part[Plus[Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3]], 3]], 3]] does not exist.
Part specification Part[{{2, 1, 3}, 4, Plus[Part[4, 2], Part[4, 3]], Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], Plus[Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3]], Plus[Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3]], 3]], Plus[Part[Plus[Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3]], 3]], 3]], Plus[Part[Plus[Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3]], 3]], 3]], 3]]}, All, 1] is longer than depth of object.
Part specification Part[4, 2] is longer than depth of object.
Part specification Part[4, 3] is longer than depth of object.
Part 3 of Plus[Part[4, 2], Part[4, 3]] does not exist.
Part 3 of Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]] does not exist.
Part 3 of Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]] does not exist.
Part 3 of Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]] does not exist.
Part 3 of Plus[Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3]] does not exist.
Part 3 of Plus[Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3]], 3]] does not exist.
Part 3 of Plus[Part[Plus[Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3]], 3]], 3]] does not exist.
Part specification Part[{{2, 1, 3}, 4, Plus[Part[4, 2], Part[4, 3]], Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], Plus[Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3]], Plus[Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3]], 3]], Plus[Part[Plus[Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3]], 3]], 3]], Plus[Part[Plus[Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3], Part[Plus[Part[Plus[Part[4, 2], Part[4, 3]], 3], Part[Plus[Part[4, 3], Part[Plus[Part[4, 2], Part[4, 3]], 3]], 3]], 3]], 3]], 3]], 3]], 3]]}, All, 1] is longer than depth of object.
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -1], GoldenRatio]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Times[-1, Power[GoldenRatio, -2]], Power[GoldenRatio, 2]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -3], Power[GoldenRatio, 3]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Times[-1, Power[GoldenRatio, -4]], Power[GoldenRatio, 4]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -5], Power[GoldenRatio, 5]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Times[-1, Power[GoldenRatio, -6]], Power[GoldenRatio, 6]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -7], Power[GoldenRatio, 7]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Times[-1, Power[GoldenRatio, -8]], Power[GoldenRatio, 8]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -9], Power[GoldenRatio, 9]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -1], GoldenRatio]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Times[-1, Power[GoldenRatio, -2]], Power[GoldenRatio, 2]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -3], Power[GoldenRatio, 3]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Times[-1, Power[GoldenRatio, -4]], Power[GoldenRatio, 4]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -5], Power[GoldenRatio, 5]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Times[-1, Power[GoldenRatio, -6]], Power[GoldenRatio, 6]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -7], Power[GoldenRatio, 7]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Times[-1, Power[GoldenRatio, -8]], Power[GoldenRatio, 8]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -9], Power[GoldenRatio, 9]]]].

1, 2, 145, 4058
######################  INITIALIZE PROCESS ########################## ( 197 )
2, 5, 10, 17, 26, 37, 50, 65, 82, 101
######################  INITIALIZE PROCESS ########################## ( 198 )
1, 8, 10, 11, 18, 20, 21, 28, 30, 31, 38, 40, 41, 48, 50, 51, 58, 60, 61, 68, 70, 71, 78, 80, 81, 88, 90, 91, 98, 100, 101, 108, 11
######################  INITIALIZE PROCESS ########################## ( 199 )
3, 7, 31, 127, 2047, 8191, 131071, 524287, 8388607, 536870911
######################  INITIALIZE PROCESS ########################## ( 200 )
1, 2, 1, 4, 7, 11, 18, 29, 47, 76
######################  INITIALIZE PROCESS ########################## ( 201 )
1, 2, 1, 4, 7, 11, 18, 29, 47, 76
######################  INITIALIZE PROCESS ########################## ( 202 )
1, 4, 10, 20, 35, 56, 84, 120, 165, 220
######################  INITIALIZE PROCESS ########################## ( 203 )
1, 0, 1, 0, 2, 0, 1, 0, 3, 0
######################  INITIALIZE PROCESS ########################## ( 204 )
1, 1, 2, 1, 4, 7, 11, 18, 29, 47
######################  INITIALIZE PROCESS ########################## ( 205 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 206 )
1, '11, 21, 1211, 3112'
######################  INITIALIZE PROCESS ########################## ( 207 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 208 )
1, 2, 4, 8, 16, 32, 64, 128, 256, 512
######################  INITIALIZE PROCESS ########################## ( 209 )
0, 1, 3, 7, 15, 31, 63, 127, 255, 511
######################  INITIALIZE PROCESS ########################## ( 210 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 211 )
1, 1, 2, 3, 5, 8, 13, 21, 34, 55
######################  INITIALIZE PROCESS ########################## ( 212 )
1, 2, 4, 8, 16, 32, 64, 128, 256, 512
######################  INITIALIZE PROCESS ########################## ( 213 )
1, 3, 9, 27, 81, 243, 729, 2187, 6561, 19683
######################  INITIALIZE PROCESS ########################## ( 214 )
1, 4, 9, 16, 25, 36, 49, 64, 81, 100
######################  INITIALIZE PROCESS ########################## ( 215 )
1, 8, 27, 64, 125, 216, 343, 512, 729, 1000
######################  INITIALIZE PROCESS ########################## ( 216 )
1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880
######################  INITIALIZE PROCESS ########################## ( 217 )
1, 3, 6, 10, 15, 21, 28, 36, 45, 55
######################  INITIALIZE PROCESS ########################## ( 218 )
2, 1, 3, 4, 4, 2, 4, 3, 4, 3, 4, 2, 4, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 3, 3, 3, 3, All, 1
######################  INITIALIZE PROCESS ########################## ( 219 )
0, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -1, GoldenRatio, FloorTimesPower5, Rational-1, 2, Times-1, PowerGoldenRatio, -2, PowerGoldenRatio, 2, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -3, PowerGoldenRatio, 3, FloorTimesPower5, Rational-1, 2, Times-1, PowerGoldenRatio, -4, PowerGoldenRatio, 4, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -5, PowerGoldenRatio, 5, FloorTimesPower5, Rational-1, 2, Times-1, PowerGoldenRatio, -6, PowerGoldenRatio, 6, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -7, PowerGoldenRatio, 7, FloorTimesPower5, Rational-1, 2, Times-1, PowerGoldenRatio, -8, PowerGoldenRatio, 8, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -9, PowerGoldenRatio, 9
######################  INITIALIZE PROCESS ########################## ( 220 )
1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000
######################  INITIALIZE PROCESS ########################## ( 221 )
1, 1, 4, 30, 336, 5040, 95040, 2162160, 57657600, 1764322560
######################  INITIALIZE PROCESS ########################## ( 222 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 223 )
4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 25, 26, 28, 30
######################  INITIALIZE PROCESS ########################## ( 224 )
'1, 10, 11, 100, 101, 110, 111, 1000, 1001, 1010'
######################  INITIALIZE PROCESS ########################## ( 225 )
0, 1, 512, 27, 262144, 125, 10077696, 343, 134217728, 729
######################  INITIALIZE PROCESS ########################## ( 226 )

Nonatomic expression expected at position 1 in Split[1].
Nonatomic expression expected at position 1 in Split[0].
Nonatomic expression expected at position 1 in Split[0].
Nonatomic expression expected at position 1 in Split[1].
Nonatomic expression expected at position 1 in Split[0].
Span[1, All, Split[0]] is not a valid Span specification. A Span specification should be 1, 2, or 3 machine-sized integers separated by ;;. (Any of the integers can be omitted or replaced with All.)
List expected at position 1 in Riffle[Split[0], Part[{1}, Span[1, All, Split[0]]]].
String expected at position 1 in StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]].
String expected at position 2 in StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]].
String expected at position 1 in StringJoin[Split[0]].
String expected at position 1 in StringJoin[Part[{1}, Span[1, All, Split[0]]]].
String expected at position 1 in StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]].
String expected at position 2 in StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]].
String expected at position 1 in StringJoin[1, 2].
String expected at position 2 in StringJoin[1, 2].
String expected at position 1 in StringJoin[Split[0]].
String expected at position 1 in StringJoin[Part[{1}, Span[1, All, Split[0]]]].
String expected at position 1 in StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]].
String expected at position 2 in StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]].
String expected at position 1 in StringJoin[1, 2].
String expected at position 2 in StringJoin[1, 2].
Span[1, All, StringJoin[1, 2]] is not a valid Span specification. A Span specification should be 1, 2, or 3 machine-sized integers separated by ;;. (Any of the integers can be omitted or replaced with All.)
List expected at position 1 in Riffle[12, Part[Characters[StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]]], Span[1, All, StringJoin[1, 2]]]].
String expected at position 2 in StringJoin[12, Part[Characters[StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]]], Span[1, All, StringJoin[1, 2]]]].
String expected at position 1 in StringJoin[Part[Characters[StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]]], Span[1, All, StringJoin[1, 2]]]].
String expected at position 2 in StringJoin[12, Part[Characters[StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]]], Span[1, All, StringJoin[1, 2]]]].
String expected at position 1 in StringJoin[0, 2].
String expected at position 2 in StringJoin[0, 2].
String expected at position 1 in StringJoin[Part[Characters[StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]]], Span[1, All, StringJoin[1, 2]]]].
String expected at position 2 in StringJoin[12, Part[Characters[StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]]], Span[1, All, StringJoin[1, 2]]]].
String expected at position 1 in StringJoin[0, 2].
String expected at position 2 in StringJoin[0, 2].
Span[1, All, StringJoin[0, 2]] is not a valid Span specification. A Span specification should be 1, 2, or 3 machine-sized integers separated by ;;. (Any of the integers can be omitted or replaced with All.)
List expected at position 1 in Riffle[02, Part[Characters[StringJoin[12, Part[Characters[StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]]], Span[1, All, StringJoin[1, 2]]]]], Span[1, All, StringJoin[0, 2]]]].
String expected at position 2 in StringJoin[02, Part[Characters[StringJoin[12, Part[Characters[StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]]], Span[1, All, StringJoin[1, 2]]]]], Span[1, All, StringJoin[0, 2]]]].
String expected at position 1 in StringJoin[Part[Characters[StringJoin[12, Part[Characters[StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]]], Span[1, All, StringJoin[1, 2]]]]], Span[1, All, StringJoin[0, 2]]]].
String expected at position 2 in StringJoin[02, Part[Characters[StringJoin[12, Part[Characters[StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]]], Span[1, All, StringJoin[1, 2]]]]], Span[1, All, StringJoin[0, 2]]]].
String expected at position 1 in StringJoin[0, 2].
String expected at position 2 in StringJoin[0, 2].
String expected at position 1 in StringJoin[Part[Characters[StringJoin[12, Part[Characters[StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]]], Span[1, All, StringJoin[1, 2]]]]], Span[1, All, StringJoin[0, 2]]]].
String expected at position 2 in StringJoin[02, Part[Characters[StringJoin[12, Part[Characters[StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]]], Span[1, All, StringJoin[1, 2]]]]], Span[1, All, StringJoin[0, 2]]]].
String expected at position 1 in StringJoin[0, 2].
String expected at position 2 in StringJoin[0, 2].
Span[1, All, StringJoin[0, 2]] is not a valid Span specification. A Span specification should be 1, 2, or 3 machine-sized integers separated by ;;. (Any of the integers can be omitted or replaced with All.)
List expected at position 1 in Riffle[02, Part[Characters[StringJoin[02, Part[Characters[StringJoin[12, Part[Characters[StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]]], Span[1, All, StringJoin[1, 2]]]]], Span[1, All, StringJoin[0, 2]]]]], Span[1, All, StringJoin[0, 2]]]].
String expected at position 2 in StringJoin[02, Part[Characters[StringJoin[02, Part[Characters[StringJoin[12, Part[Characters[StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]]], Span[1, All, StringJoin[1, 2]]]]], Span[1, All, StringJoin[0, 2]]]]], Span[1, All, StringJoin[0, 2]]]].
Nonatomic expression expected at position 1 in Split[1].
Nonatomic expression expected at position 1 in Split[0].
Nonatomic expression expected at position 1 in Split[0].
Nonatomic expression expected at position 1 in Split[1].
Nonatomic expression expected at position 1 in Split[0].
Span[1, All, Split[0]] is not a valid Span specification. A Span specification should be 1, 2, or 3 machine-sized integers separated by ;;. (Any of the integers can be omitted or replaced with All.)
List expected at position 1 in Riffle[Split[0], Part[{1}, Span[1, All, Split[0]]]].
String expected at position 1 in StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]].
String expected at position 2 in StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]].
String expected at position 1 in StringJoin[Split[0]].
String expected at position 1 in StringJoin[Part[{1}, Span[1, All, Split[0]]]].
String expected at position 1 in StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]].
String expected at position 2 in StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]].
String expected at position 1 in StringJoin[1, 2].
String expected at position 2 in StringJoin[1, 2].
String expected at position 1 in StringJoin[Split[0]].
String expected at position 1 in StringJoin[Part[{1}, Span[1, All, Split[0]]]].
String expected at position 1 in StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]].
String expected at position 2 in StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]].
String expected at position 1 in StringJoin[1, 2].
String expected at position 2 in StringJoin[1, 2].
Span[1, All, StringJoin[1, 2]] is not a valid Span specification. A Span specification should be 1, 2, or 3 machine-sized integers separated by ;;. (Any of the integers can be omitted or replaced with All.)
List expected at position 1 in Riffle[12, Part[Characters[StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]]], Span[1, All, StringJoin[1, 2]]]].
String expected at position 2 in StringJoin[12, Part[Characters[StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]]], Span[1, All, StringJoin[1, 2]]]].
String expected at position 1 in StringJoin[Part[Characters[StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]]], Span[1, All, StringJoin[1, 2]]]].
String expected at position 2 in StringJoin[12, Part[Characters[StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]]], Span[1, All, StringJoin[1, 2]]]].
String expected at position 1 in StringJoin[0, 2].
String expected at position 2 in StringJoin[0, 2].
String expected at position 1 in StringJoin[Part[Characters[StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]]], Span[1, All, StringJoin[1, 2]]]].
String expected at position 2 in StringJoin[12, Part[Characters[StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]]], Span[1, All, StringJoin[1, 2]]]].
String expected at position 1 in StringJoin[0, 2].
String expected at position 2 in StringJoin[0, 2].
Span[1, All, StringJoin[0, 2]] is not a valid Span specification. A Span specification should be 1, 2, or 3 machine-sized integers separated by ;;. (Any of the integers can be omitted or replaced with All.)
List expected at position 1 in Riffle[02, Part[Characters[StringJoin[12, Part[Characters[StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]]], Span[1, All, StringJoin[1, 2]]]]], Span[1, All, StringJoin[0, 2]]]].
String expected at position 2 in StringJoin[02, Part[Characters[StringJoin[12, Part[Characters[StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]]], Span[1, All, StringJoin[1, 2]]]]], Span[1, All, StringJoin[0, 2]]]].
String expected at position 1 in StringJoin[Part[Characters[StringJoin[12, Part[Characters[StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]]], Span[1, All, StringJoin[1, 2]]]]], Span[1, All, StringJoin[0, 2]]]].
String expected at position 2 in StringJoin[02, Part[Characters[StringJoin[12, Part[Characters[StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]]], Span[1, All, StringJoin[1, 2]]]]], Span[1, All, StringJoin[0, 2]]]].
String expected at position 1 in StringJoin[0, 2].
String expected at position 2 in StringJoin[0, 2].
String expected at position 1 in StringJoin[Part[Characters[StringJoin[12, Part[Characters[StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]]], Span[1, All, StringJoin[1, 2]]]]], Span[1, All, StringJoin[0, 2]]]].
String expected at position 2 in StringJoin[02, Part[Characters[StringJoin[12, Part[Characters[StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]]], Span[1, All, StringJoin[1, 2]]]]], Span[1, All, StringJoin[0, 2]]]].
String expected at position 1 in StringJoin[0, 2].
String expected at position 2 in StringJoin[0, 2].
Span[1, All, StringJoin[0, 2]] is not a valid Span specification. A Span specification should be 1, 2, or 3 machine-sized integers separated by ;;. (Any of the integers can be omitted or replaced with All.)
List expected at position 1 in Riffle[02, Part[Characters[StringJoin[02, Part[Characters[StringJoin[12, Part[Characters[StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]]], Span[1, All, StringJoin[1, 2]]]]], Span[1, All, StringJoin[0, 2]]]]], Span[1, All, StringJoin[0, 2]]]].
String expected at position 2 in StringJoin[02, Part[Characters[StringJoin[02, Part[Characters[StringJoin[12, Part[Characters[StringJoin[Split[0], Part[{1}, Span[1, All, Split[0]]]]], Span[1, All, StringJoin[1, 2]]]]], Span[1, All, StringJoin[0, 2]]]]], Span[1, All, StringJoin[0, 2]]]].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -1], GoldenRatio]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Times[-1, Power[GoldenRatio, -2]], Power[GoldenRatio, 2]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -3], Power[GoldenRatio, 3]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Times[-1, Power[GoldenRatio, -4]], Power[GoldenRatio, 4]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -5], Power[GoldenRatio, 5]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Times[-1, Power[GoldenRatio, -6]], Power[GoldenRatio, 6]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -7], Power[GoldenRatio, 7]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Times[-1, Power[GoldenRatio, -8]], Power[GoldenRatio, 8]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -9], Power[GoldenRatio, 9]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -1], GoldenRatio]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Times[-1, Power[GoldenRatio, -2]], Power[GoldenRatio, 2]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -3], Power[GoldenRatio, 3]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Times[-1, Power[GoldenRatio, -4]], Power[GoldenRatio, 4]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -5], Power[GoldenRatio, 5]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Times[-1, Power[GoldenRatio, -6]], Power[GoldenRatio, 6]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -7], Power[GoldenRatio, 7]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Times[-1, Power[GoldenRatio, -8]], Power[GoldenRatio, 8]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -9], Power[GoldenRatio, 9]]]].

1, 2, 145, 4058
######################  INITIALIZE PROCESS ########################## ( 227 )
2, 5, 10, 17, 26, 37, 50, 65, 82, 101
######################  INITIALIZE PROCESS ########################## ( 228 )
1, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 28, 30, 31, 38, 40, 41, 48, 50, 51, 58, 60, 61, 68, 70, 71, 78, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 98, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 20
######################  INITIALIZE PROCESS ########################## ( 229 )
3, 7, 31, 127, 2047, 8191, 131071, 524287, 8388607, 536870911
######################  INITIALIZE PROCESS ########################## ( 230 )
1, 2, 4, 4, 7, 11, 18, 29, 47, 76
######################  INITIALIZE PROCESS ########################## ( 231 )
1, 2, 4, 4, 7, 11, 18, 29, 47, 76
######################  INITIALIZE PROCESS ########################## ( 232 )
1, 3, 7, 13, 21, 31, 43, 57, 73, 91
######################  INITIALIZE PROCESS ########################## ( 233 )
1, 0, 1, 0, 2, 0, 1, 0, 3, 0
######################  INITIALIZE PROCESS ########################## ( 234 )
1, 1, 2, 4, 4, 7, 11, 18, 29, 47
######################  INITIALIZE PROCESS ########################## ( 235 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 236 )
'1', StringJoinSplit'0', '1',, Span1, All, Split0, StringJoin'12', CharactersStringJoinSplit'0', '1',, Span1, All, Split0, Span1, All, StringJoin1, 2, StringJoin'02', CharactersStringJoin'12', CharactersStringJoinSplit'0', '1',, Span1, All, Split0, Span1, All, StringJoin1, 2, Span1, All, StringJoin0, 2, StringJoin'02', CharactersStringJoin'02', CharactersStringJoin'12', CharactersStringJoinSplit'0', '1',, Span1, All, Split0, Span1, All, StringJoin1, 2, Span1, All, StringJoin0, 2, Span1, All, StringJoin0, 2
######################  INITIALIZE PROCESS ########################## ( 237 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 238 )
1, 2, 4, 8, 16, 32, 64, 128, 256, 51
######################  INITIALIZE PROCESS ########################## ( 239 )
0, 1, 3, 7, 15, 31, 63, 127, 255, 511
######################  INITIALIZE PROCESS ########################## ( 240 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 241 )
1, 1, 2, 3, 5, 8, 13, 21, 34, 55
######################  INITIALIZE PROCESS ########################## ( 242 )
1, 2, 4, 8, 16, 32, 64, 128, 256, 512
######################  INITIALIZE PROCESS ########################## ( 243 )
1, 3, 9, 27, 81, 243, 729, 2187, 6561, 19683
######################  INITIALIZE PROCESS ########################## ( 244 )
1, 4, 9, 16, 25, 36, 49, 64, 81, 100
######################  INITIALIZE PROCESS ########################## ( 245 )
1, 8, 27, 64, 125, 216, 343, 512, 729, 1000
######################  INITIALIZE PROCESS ########################## ( 246 )
1, 2, 6, 24, 120, 720, 5040, 40320, 362880, 3628800
######################  INITIALIZE PROCESS ########################## ( 247 )
1, 3, 6, 10, 15, 21, 28, 36, 45, 55
######################  INITIALIZE PROCESS ########################## ( 248 )
2, 1, 2, Slot2, 2, Slot2, 2, Slot2, 2, Slot2, 2, Slot2, 2, Slot2, 2, Slot2, 2, Slot2, 2, Slot2
######################  INITIALIZE PROCESS ########################## ( 249 )
0, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -1, GoldenRatio, FloorTimesPower5, Rational-1, 2, Times-1, PowerGoldenRatio, -2, PowerGoldenRatio, 2, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -3, PowerGoldenRatio, 3, FloorTimesPower5, Rational-1, 2, Times-1, PowerGoldenRatio, -4, PowerGoldenRatio, 4, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -5, PowerGoldenRatio, 5, FloorTimesPower5, Rational-1, 2, Times-1, PowerGoldenRatio, -6, PowerGoldenRatio, 6, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -7, PowerGoldenRatio, 7, FloorTimesPower5, Rational-1, 2, Times-1, PowerGoldenRatio, -8, PowerGoldenRatio, 8, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -9, PowerGoldenRatio, 9
######################  INITIALIZE PROCESS ########################## ( 250 )
1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000
######################  INITIALIZE PROCESS ########################## ( 251 )
1, 1, 2, 5, 14, 42, 132, 429, 1430, 4862
######################  INITIALIZE PROCESS ########################## ( 252 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 253 )
1, 2, 3, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 28, 30, 32, 36, 38, 40, 42, 44, 46, 48
######################  INITIALIZE PROCESS ########################## ( 254 )
1, 2, 2, 2, 3, 2, 4, 2, 5, 2, 6, 2, 7, 2, 8, 2, 9, 2, 10, 2
######################  INITIALIZE PROCESS ########################## ( 255 )
0, 1, 512, 27, 262144, 125, 10077696, 343, 134217728, 729
######################  INITIALIZE PROCESS ########################## ( 256 )

Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Nonatomic expression expected at position 1 in Reverse[2].
Slot number 2 in Function[Plus[Slot[1], Slot[2]]] cannot be filled from Function[Plus[Slot[1], Slot[2]]][2].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -1], GoldenRatio]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Times[-1, Power[GoldenRatio, -2]], Power[GoldenRatio, 2]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -3], Power[GoldenRatio, 3]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Times[-1, Power[GoldenRatio, -4]], Power[GoldenRatio, 4]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -5], Power[GoldenRatio, 5]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Times[-1, Power[GoldenRatio, -6]], Power[GoldenRatio, 6]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -7], Power[GoldenRatio, 7]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Times[-1, Power[GoldenRatio, -8]], Power[GoldenRatio, 8]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -9], Power[GoldenRatio, 9]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -1], GoldenRatio]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Times[-1, Power[GoldenRatio, -2]], Power[GoldenRatio, 2]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -3], Power[GoldenRatio, 3]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Times[-1, Power[GoldenRatio, -4]], Power[GoldenRatio, 4]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -5], Power[GoldenRatio, 5]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Times[-1, Power[GoldenRatio, -6]], Power[GoldenRatio, 6]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -7], Power[GoldenRatio, 7]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Times[-1, Power[GoldenRatio, -8]], Power[GoldenRatio, 8]]]].
Internal precision limit $MaxExtraPrecision = 50.0 reached while evaluating Floor[Times[Power[5, -0.5], Plus[Power[GoldenRatio, -9], Power[GoldenRatio, 9]]]].

1, 2, 145, 4058
######################  INITIALIZE PROCESS ########################## ( 257 )
2, 5, 10, 17, 26, 37, 50, 65, 82, 101
######################  INITIALIZE PROCESS ########################## ( 258 )
1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 31, 41, 51, 61, 71, 81, 91, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 19
######################  INITIALIZE PROCESS ########################## ( 259 )
3, 7, 31, 127, 2047, 8191, 131071, 524287, 8388607, 536870911
######################  INITIALIZE PROCESS ########################## ( 260 )
1, 2, 4, 4, 7, 11, 18, 29, 47, 76
######################  INITIALIZE PROCESS ########################## ( 261 )
1, 2, 4, 4, 7, 11, 18, 29, 47, 76
######################  INITIALIZE PROCESS ########################## ( 262 )
1, 4, 10, 20, 35, 56, 84, 120, 165, 220
######################  INITIALIZE PROCESS ########################## ( 263 )
Global`HammingWeight0, Global`HammingWeight1, Global`HammingWeight2, Global`HammingWeight3, Global`HammingWeight4, Global`HammingWeight5, Global`HammingWeight6, Global`HammingWeight7, Global`HammingWeight8, Global`HammingWeight9
######################  INITIALIZE PROCESS ########################## ( 264 )
1, 1, 2, 4, 4, 7, 11, 18, 29, 47
######################  INITIALIZE PROCESS ########################## ( 265 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 266 )
'1, 1, 1, 1, 1'
######################  INITIALIZE PROCESS ########################## ( 267 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 268 )
1, 2, 4, 8, 16, 32, 64, 128, 256, 512
######################  INITIALIZE PROCESS ########################## ( 269 )
0, 1, 3, 7, 15, 31, 63, 127, 255, 511
######################  INITIALIZE PROCESS ########################## ( 270 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 271 )
1, 1, 2, 3, 5, 8, 13, 21, 34, 55
######################  INITIALIZE PROCESS ########################## ( 272 )
1, 2, 4, 8, 16, 32, 64, 128, 256, 512
######################  INITIALIZE PROCESS ########################## ( 273 )
1, 3, 9, 27, 81, 243, 729, 2187, 6561, 19683
######################  INITIALIZE PROCESS ########################## ( 274 )
1, 4, 9, 16, 25, 36, 49, 64, 81, 100
######################  INITIALIZE PROCESS ########################## ( 275 )
1, 8, 27, 64, 125, 216, 343, 512, 729, 1000
######################  INITIALIZE PROCESS ########################## ( 276 )
1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880
######################  INITIALIZE PROCESS ########################## ( 277 )
1, 3, 6, 10, 15, 21, 28, 36, 45, 55
######################  INITIALIZE PROCESS ########################## ( 278 )
2, 1, 2, Slot2, 2, Slot2, 2, Slot2, 2, Slot2, 2, Slot2, 2, Slot2, 2, Slot2, 2, Slot2, 2, Slot2
######################  INITIALIZE PROCESS ########################## ( 279 )
0, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -1, GoldenRatio, FloorTimesPower5, Rational-1, 2, Times-1, PowerGoldenRatio, -2, PowerGoldenRatio, 2, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -3, PowerGoldenRatio, 3, FloorTimesPower5, Rational-1, 2, Times-1, PowerGoldenRatio, -4, PowerGoldenRatio, 4, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -5, PowerGoldenRatio, 5, FloorTimesPower5, Rational-1, 2, Times-1, PowerGoldenRatio, -6, PowerGoldenRatio, 6, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -7, PowerGoldenRatio, 7, FloorTimesPower5, Rational-1, 2, Times-1, PowerGoldenRatio, -8, PowerGoldenRatio, 8, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -9, PowerGoldenRatio, 9
######################  INITIALIZE PROCESS ########################## ( 280 )
1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000
######################  INITIALIZE PROCESS ########################## ( 281 )
1, 1, 2, 5, 14, 42, 132, 429, 1430, 4862
######################  INITIALIZE PROCESS ########################## ( 282 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 283 )
1, 2, 3, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 28, 30, 32, 36, 38, 40, 42, 44, 46, 48
######################  INITIALIZE PROCESS ########################## ( 284 )
1, 2, 2, 2, 3, 2, 4, 2, 5, 2, 6, 2, 7, 2, 8, 2, 9, 2, 10, 2
######################  INITIALIZE PROCESS ########################## ( 285 )
0, 1, 512, 27, 262144, 125, 10077696, 343, 134217728, 729
######################  INITIALIZE PROCESS ########################## ( 286 )

11 cannot be used as a variable.
11 cannot be used as a variable.
Depth of object {3, 5, 11, 17, 29, 41, 59, 71, 101, 107, 137, 149, 179, 191, 197, 227} is not sufficient for the given part specification.
Part specification Part[{3, 5, 11, 17, 29, 41, 59, 71, 101, 107, 137, 149, 179, 191, 197, 227}, All, 1] is longer than depth of object.
Depth of object {3, 5, 11, 17, 29, 41, 59, 71, 101, 107, 137, 149, 179, 191, 197, 227} is not sufficient for the given part specification.
Part specification Part[{3, 5, 11, 17, 29, 41, 59, 71, 101, 107, 137, 149, 179, 191, 197, 227}, All, 1] is longer than depth of object.

1, 2, 145, 4058
######################  INITIALIZE PROCESS ########################## ( 287 )
2, 5, 10, 17, 26, 37, 50, 65, 82, 101
######################  INITIALIZE PROCESS ########################## ( 288 )
1, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 28, 30, 31, 38, 40, 41, 48, 50, 51, 58, 60, 61, 68, 70, 71, 78, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 98, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 20
######################  INITIALIZE PROCESS ########################## ( 289 )
3, 7, 31, 127, 2047, 8191, 131071, 524287, 8388607, 536870911
######################  INITIALIZE PROCESS ########################## ( 290 )
1, 2, 4, 4, 7, 11, 18, 29, 47, 76
######################  INITIALIZE PROCESS ########################## ( 291 )
1, 2, 4, 4, 7, 11, 18, 29, 47, 76
######################  INITIALIZE PROCESS ########################## ( 292 )
1, 3, 7, 13, 21, 31, 43, 57, 73, 91
######################  INITIALIZE PROCESS ########################## ( 293 )
1, 0, 1, 0, 2, 0, 1, 0, 3, 0
######################  INITIALIZE PROCESS ########################## ( 294 )
1, 1, 2, 4, 4, 7, 11, 18, 29, 47
######################  INITIALIZE PROCESS ########################## ( 295 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 296 )
'1, 1, 1, 1, 1'
######################  INITIALIZE PROCESS ########################## ( 297 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 298 )
1, 2, 4, 8, 16, 32, 64, 128, 256, 512
######################  INITIALIZE PROCESS ########################## ( 299 )
0, 1, 3, 7, 15, 31, 63, 127, 255, 511
######################  INITIALIZE PROCESS ########################## ( 300 )
1, 4, 9, 16, 25, 36, 49, 64, 81, 100
######################  INITIALIZE PROCESS ########################## ( 301 )
1, 8, 27, 64, 125, 216, 343, 512, 729, 1000
######################  INITIALIZE PROCESS ########################## ( 302 )
2, 0, 1, 2, 0, 1, 2, 0, 1, 2
######################  INITIALIZE PROCESS ########################## ( 303 )
2, 3, 3, 4, 4, 4, 5, 5, 5, 5
######################  INITIALIZE PROCESS ########################## ( 304 )
2, 4, 8, 16, 32, 64, 128, 256, 512, 1024
######################  INITIALIZE PROCESS ########################## ( 305 )
2, 5, 10, 17, 26, 37, 50, 65, 82, 101
######################  INITIALIZE PROCESS ########################## ( 306 )
7, 11, 13, 17, 19, 23, 29, 31, 37, 41
######################  INITIALIZE PROCESS ########################## ( 307 )
1, 11, 111, 1111, 11111, 111111, 1111111, 11111111, 111111111, 1111111111
######################  INITIALIZE PROCESS ########################## ( 308 )
31, 331, 3331, 33331, 333331, 3333331, 33333331, 333333331
######################  INITIALIZE PROCESS ########################## ( 309 )
$Failed
######################  INITIALIZE PROCESS ########################## ( 310 )
6, 28, 496, 8128, 2096128, 33550336
######################  INITIALIZE PROCESS ########################## ( 311 )
RecurrenceTableFalse, False, False, Global`a, 11, 10
######################  INITIALIZE PROCESS ########################## ( 312 )
2, 3, 5, 11, 17, 29, 41, 59, 71, 101, 107, 137, 149, 179, 191, 197, 227, All, 1
######################  INITIALIZE PROCESS ########################## ( 313 )
1, 2, 145, 4058
######################  INITIALIZE PROCESS ########################## ( 314 )

NestWhileList called with 1 argument; between 3 and 6 arguments are expected.
NestWhileList called with 1 argument; between 3 and 6 arguments are expected.
NestWhileList called with 1 argument; between 3 and 6 arguments are expected.
NestWhileList called with 1 argument; between 3 and 6 arguments are expected.
NestWhileList called with 1 argument; between 3 and 6 arguments are expected.
NestWhileList called with 1 argument; between 3 and 6 arguments are expected.
NestWhileList called with 1 argument; between 3 and 6 arguments are expected.
NestWhileList called with 1 argument; between 3 and 6 arguments are expected.
NestWhileList called with 1 argument; between 3 and 6 arguments are expected.
NestWhileList called with 1 argument; between 3 and 6 arguments are expected.
NestWhileList called with 1 argument; between 3 and 6 arguments are expected.
NestWhileList called with 1 argument; between 3 and 6 arguments are expected.
NestWhileList called with 1 argument; between 3 and 6 arguments are expected.
NestWhileList called with 1 argument; between 3 and 6 arguments are expected.

2, 3, 5, 7, 13, 17, 19, 31, 61, 89
######################  INITIALIZE PROCESS ########################## ( 315 )
2, 3, 7, 22, 89, 446
######################  INITIALIZE PROCESS ########################## ( 316 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 317 )
1, 8, 10, 11, 18, 80, 81, 88, 100, 101, 108, 110, 111, 118, 180, 181, 18
######################  INITIALIZE PROCESS ########################## ( 318 )
1, 0, 1, 0, 2, 0, 1, 0, 3, 0
######################  INITIALIZE PROCESS ########################## ( 319 )
0, 1, 1, 1, 2, 2, 3, 3, 4, 5
######################  INITIALIZE PROCESS ########################## ( 320 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 321 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 322 )
1, 7, 3, 2, 0, 5, 0, 7, 9, 8
######################  INITIALIZE PROCESS ########################## ( 323 )
1, 2, 3, 4, 5, 6, 7, 8
######################  INITIALIZE PROCESS ########################## ( 324 )
0, 1, 3, 7, 15, 31, 63, 127
######################  INITIALIZE PROCESS ########################## ( 325 )
3, 5, 11, 23, 29, 41, 53, 83, 89
######################  INITIALIZE PROCESS ########################## ( 326 )
1, 1, 4, 4, 7, 11, 18, 29
######################  INITIALIZE PROCESS ########################## ( 327 )
1, 0, 1, 4, 4, 7, 11, 18
######################  INITIALIZE PROCESS ########################## ( 328 )
1, 4, 9, 16, 25, 36, 49, 64, 81, 100
######################  INITIALIZE PROCESS ########################## ( 329 )
1, 8, 27, 64, 125, 216, 343, 512, 729, 1000
######################  INITIALIZE PROCESS ########################## ( 330 )
2, 1, 2, 1, 1, 2, 1, 1, 1
######################  INITIALIZE PROCESS ########################## ( 331 )
2, 3, 3, 4, 4, 4, 5, 5, 5, 5
######################  INITIALIZE PROCESS ########################## ( 332 )
2, 4, 8, 16, 32, 64, 128, 256, 512, 1024
######################  INITIALIZE PROCESS ########################## ( 333 )
2, 5, 10, 17, 26, 37, 50, 65, 82, 101
######################  INITIALIZE PROCESS ########################## ( 334 )
7, 11, 13, 17, 19, 23, 29, 31, 37, 41
######################  INITIALIZE PROCESS ########################## ( 335 )
1, 11, 111, 1111, 11111, 111111, 1111111, 11111111, 111111111, 1111111111
######################  INITIALIZE PROCESS ########################## ( 336 )
31, 331, 3331, 33331, 333331, 3333331, 33333331, 333333331
######################  INITIALIZE PROCESS ########################## ( 337 )
1, 5, 11, 19, 29, 41, 55, 71, 89, 109
######################  INITIALIZE PROCESS ########################## ( 338 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 339 )
0, 0, 4, 4, 7, 11, 18, 29, 47, 76
######################  INITIALIZE PROCESS ########################## ( 340 )
3, 5, 9, 11, 15, 17, 21, 27, 29, 35, 39, 41, 45, 51, 57, 59, 65, 69, 71, 77, 81, 87, 95, 99, 101, 105, 107, 111, 125, 129, 135, 137, 147, 149, 155, 161, 165, 171, 177, 179, 189, 191, 195, 197, 209, 221, 225, 227, 231, 237, 239, 249, 255, 261, 267, 269, 275, 279, 281, 291, 305, 309, 311, 315, 329, 335, 345, 347, 351, 357, 365, 371, 377, 381, 387, 395, 39
######################  INITIALIZE PROCESS ########################## ( 341 )
1, 2, 145, 4058
######################  INITIALIZE PROCESS ########################## ( 342 )
2, 3, 5, 7, 13, 17, 19, 31, 61, 89, 107, 127, 521, 607, 1279, 2203, 228
######################  INITIALIZE PROCESS ########################## ( 343 )
2, 6, 42, 1806, 3263442, 10650056950806
######################  INITIALIZE PROCESS ########################## ( 344 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 345 )
1, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 28, 30, 31, 38, 40, 41, 48, 50, 51, 58, 60, 61, 68, 70, 71, 78, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 98, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 20
######################  INITIALIZE PROCESS ########################## ( 346 )
0, 1, 2, 3, 0, 1, 2, 3, 0, 1
######################  INITIALIZE PROCESS ########################## ( 347 )
0, 0, 0, 0, 0, 0, 0, 0, 0, 0
######################  INITIALIZE PROCESS ########################## ( 348 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 349 )
1, 4, 3, 0, 1, 4, 3, 0, 1, 4
######################  INITIALIZE PROCESS ########################## ( 350 )

######################  INITIALIZE PROCESS ########################## ( 351 )
1, 2, 4, 9, 4, 9, 4, 9
######################  INITIALIZE PROCESS ########################## ( 352 )
1, 1, 1, 7, 15, 31, 63, 127
######################  INITIALIZE PROCESS ########################## ( 353 )
3, 5, 7, 13, 17, 19, 31, 61, 89
######################  INITIALIZE PROCESS ########################## ( 354 )
1, 0, 4, 4, 7, 11, 18, 29
######################  INITIALIZE PROCESS ########################## ( 355 )
1, 0, 1, 4, 7, 11, 18, 29
######################  INITIALIZE PROCESS ########################## ( 356 )
1, 4, 9, 16, 25, 36, 49, 64, 81, 100
######################  INITIALIZE PROCESS ########################## ( 357 )
1, 8, 27, 64, 125, 216, 343, 512, 729, 1000
######################  INITIALIZE PROCESS ########################## ( 358 )
2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2
######################  INITIALIZE PROCESS ########################## ( 359 )
2, 3, 3, 4, 4, 4, 5, 5, 5, 5
######################  INITIALIZE PROCESS ########################## ( 360 )
2, 4, 8, 16, 32, 64, 128, 256, 512, 1024
######################  INITIALIZE PROCESS ########################## ( 361 )
2, 5, 10, 17, 26, 37, 50, 65, 82, 101
######################  INITIALIZE PROCESS ########################## ( 362 )
2, 3, 7, 11, 19, 23, 31, 43, 47
######################  INITIALIZE PROCESS ########################## ( 363 )
1, 11, 111, 1111, 11111, 111111, 1111111, 11111111, 111111111, 1111111111
######################  INITIALIZE PROCESS ########################## ( 364 )
1, 31, 331, 3331, 33331, 333331, 3333331, 33333331
######################  INITIALIZE PROCESS ########################## ( 365 )
1, 5, 11, 19, 29, 41, 55, 71, 89, 109
######################  INITIALIZE PROCESS ########################## ( 366 )
6, 28, 496, 8128, 2096128, 33550336
######################  INITIALIZE PROCESS ########################## ( 367 )
0, 0, 2, 4, 7, 11, 18, 29, 47, 76
######################  INITIALIZE PROCESS ########################## ( 368 )
3, 5, 6, 8, 9, 11, 14, 15, 18, 20, 21, 23, 26, 29, 30, 33, 35, 36, 39, 41, 44, 48, 50, 51, 53, 54, 56, 63, 65, 68, 69, 74, 75, 78, 81, 83, 86, 89, 90, 95, 96, 98, 99, 105, 111, 113, 114, 116, 119, 120, 125, 128, 131, 134, 135, 138, 140, 141, 146, 153, 155, 156, 158, 165, 168, 173, 174, 176, 179, 183, 186, 189, 191, 194, 198, 200, 204, 209, 210, 215, 216, 219, 221, 224, 228, 230, 231, 233, 239, 243, 245, 249, 251, 254, 260, 261, 270, 273, 278, 281, 284, 285, 288, 293, 296, 299, 300, 303, 306, 308, 309, 315, 320, 321, 323, 326, 329, 330, 336, 338, 341, 345, 350, 354, 359, 363, 366, 369, 371, 375, 378, 380, 384, 386, 393, 39
######################  INITIALIZE PROCESS ########################## ( 369 )
1, 2, 145, 4058
######################  INITIALIZE PROCESS ########################## ( 370 )
2, 3, 5, 7, 13, 17, 19, 31, 61, 89, 107, 127, 521, 607, 1279, 2203, 228
######################  INITIALIZE PROCESS ########################## ( 371 )
2, 3, 7, 22, 89, 446
######################  INITIALIZE PROCESS ########################## ( 372 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 373 )
1, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 28, 30, 31, 38, 40, 41, 48, 50, 51, 58, 60, 61, 68, 70, 71, 78, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 98, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 20
######################  INITIALIZE PROCESS ########################## ( 374 )
1, 0, 1, 0, 2, 0, 1, 0, 3, 0
######################  INITIALIZE PROCESS ########################## ( 375 )
0, 0, 0, 0, 0, 0, 0, 0, 0, 0
######################  INITIALIZE PROCESS ########################## ( 376 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 377 )
1, 4, 3, 0, 1, 4, 3, 0, 1, 4
######################  INITIALIZE PROCESS ########################## ( 378 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 379 )
0, 1, 2, 0, 3, 0, 4, 0
######################  INITIALIZE PROCESS ########################## ( 380 )
0, 1, 3, 7, 15, 31, 63, 127
######################  INITIALIZE PROCESS ########################## ( 381 )
3, 5, 7, 13, 17, 19, 31, 61
######################  INITIALIZE PROCESS ########################## ( 382 )
1, 0, 2, 4, 7, 11, 18, 29
######################  INITIALIZE PROCESS ########################## ( 383 )
1, 0, 1, 4, 7, 11, 18, 29
######################  INITIALIZE PROCESS ########################## ( 384 )
1, 4, 9, 16, 25, 36, 49, 64, 81, 100
######################  INITIALIZE PROCESS ########################## ( 385 )
1, 8, 27, 64, 125, 216, 343, 512, 729, 1000
######################  INITIALIZE PROCESS ########################## ( 386 )
2, 0, 1, 2, 0, 1, 2, 0, 1, 2
######################  INITIALIZE PROCESS ########################## ( 387 )
2, 3, 3, 4, 4, 4, 5, 5, 5, 5
######################  INITIALIZE PROCESS ########################## ( 388 )
2, 4, 8, 16, 32, 64, 128, 256, 512, 1024
######################  INITIALIZE PROCESS ########################## ( 389 )
2, 5, 10, 17, 26, 37, 50, 65, 82, 101
######################  INITIALIZE PROCESS ########################## ( 390 )
7, 11, 13, 17, 19, 23, 29, 31, 37, 41
######################  INITIALIZE PROCESS ########################## ( 391 )
1, 11, 111, 1111, 11111, 111111, 1111111, 11111111, 111111111, 1111111111
######################  INITIALIZE PROCESS ########################## ( 392 )
31, 331, 3331, 33331, 333331, 3333331, 33333331, 333333331
######################  INITIALIZE PROCESS ########################## ( 393 )
1, 5, 11, 19, 29, 41, 55, 71, 89, 109
######################  INITIALIZE PROCESS ########################## ( 394 )
6, 28, 496, 8128, 2096128, 33550336
######################  INITIALIZE PROCESS ########################## ( 395 )
0, 0, 1, 4, 7, 11, 18, 29, 47, 76
######################  INITIALIZE PROCESS ########################## ( 396 )
3, 5, 9, 11, 15, 17, 21, 27, 29, 35, 39, 41, 45, 51, 57, 59, 65, 69, 71, 77, 81, 87, 95, 99, 101, 105, 107, 111, 125, 129, 135, 137, 147, 149, 155, 161, 165, 171, 177, 179, 189, 191, 195, 197, 209, 221, 225, 227, 231, 237, 239, 249, 255, 261, 267, 269, 275, 279, 281, 291, 305, 309, 311, 315, 329, 335, 345, 347, 351, 357, 365, 371, 377, 381, 387, 395, 39
######################  INITIALIZE PROCESS ########################## ( 397 )

######################  INITIALIZE PROCESS ########################## ( 398 )
2, 3, 5, 7, 13, 17, 19, 31, 61, 89, 107, 127, 521, 607, 1279, 2203, 228
######################  INITIALIZE PROCESS ########################## ( 399 )
2, 3, 7, 22, 89, 446
######################  INITIALIZE PROCESS ########################## ( 400 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 401 )
1, 8, 10, 11, 18, 20, 21, 28, 30, 31, 38, 40, 41, 48, 50, 51, 58, 60, 61, 68, 70, 71, 78, 80, 81, 88, 90, 91, 98, 100, 101, 108, 110, 111, 118, 120, 121, 128, 130, 131, 138, 140, 141, 148, 150, 151, 158, 160, 161, 168, 170, 171, 178, 180, 181, 188, 190, 191, 198, 20
######################  INITIALIZE PROCESS ########################## ( 402 )
0, 1, 2, 3, 0, 1, 2, 3, 0, 1
######################  INITIALIZE PROCESS ########################## ( 403 )
0, 0, 0, 0, 0, 0, 0, 0, 0, 0
######################  INITIALIZE PROCESS ########################## ( 404 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 405 )
1, 4, 3, 0, 1, 4, 3, 0, 1, 4
######################  INITIALIZE PROCESS ########################## ( 406 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 407 )
1,, 2,, 3,, 4,, 5,, 6,, 7,, 8,
######################  INITIALIZE PROCESS ########################## ( 408 )
0, 1, 3, 7, 15, 31, 63, 127
######################  INITIALIZE PROCESS ########################## ( 409 )
3, 5, 7, 13, 17, 19, 31, 61
######################  INITIALIZE PROCESS ########################## ( 410 )
1, 1, 1, 1, 1, 1, 1, 1
######################  INITIALIZE PROCESS ########################## ( 411 )
1, 0, 1, 4, 7, 11, 18, 29
######################  INITIALIZE PROCESS ########################## ( 412 )
1, 4, 9, 16, 25, 36, 49, 64, 81, 100
######################  INITIALIZE PROCESS ########################## ( 413 )
1, 8, 27, 64, 125, 216, 343, 512, 729, 1000
######################  INITIALIZE PROCESS ########################## ( 414 )
2, 0, 1, 2, 0, 1, 2, 0, 1, 2
######################  INITIALIZE PROCESS ########################## ( 415 )
2, 3, 3, 4, 4, 4, 5, 5, 5, 5
######################  INITIALIZE PROCESS ########################## ( 416 )
2, 4, 8, 16, 32, 64, 128, 256, 512, 1024
######################  INITIALIZE PROCESS ########################## ( 417 )
2, 5, 10, 17, 26, 37, 50, 65, 82, 101
######################  INITIALIZE PROCESS ########################## ( 418 )
7, 11, 13, 17, 19, 23, 29, 31, 37, 41
######################  INITIALIZE PROCESS ########################## ( 419 )
1, 11, 111, 1111, 11111, 111111, 1111111, 11111111, 111111111, 1111111111
######################  INITIALIZE PROCESS ########################## ( 420 )
31, 331, 3331, 33331, 333331, 3333331, 33333331, 333333331
######################  INITIALIZE PROCESS ########################## ( 421 )
1, 5, 11, 19, 29, 41, 55, 71, 89, 109
######################  INITIALIZE PROCESS ########################## ( 422 )
6, 28, 496, 8128, 2096128, 33550336
######################  INITIALIZE PROCESS ########################## ( 423 )
0, 0, 1, 4, 7, 11, 18, 29, 47, 76
######################  INITIALIZE PROCESS ########################## ( 424 )
3, 5, 9, 11, 15, 17, 21, 27, 29, 35, 39, 41, 45, 51, 57, 59, 65, 69, 71, 77, 81, 87, 95, 99, 101, 105, 107, 111, 125, 129, 135, 137, 147, 149, 155, 161, 165, 171, 177, 179, 189, 191, 195, 197, 209, 221, 225, 227, 231, 237, 239, 249, 255, 261, 267, 269, 275, 279, 281, 291, 305, 309, 311, 315, 329, 335, 345, 347, 351, 357, 365, 371, 377, 381, 387, 395, 39
######################  INITIALIZE PROCESS ########################## ( 425 )
1, 2, 145, 4058
######################  INITIALIZE PROCESS ########################## ( 426 )

Incomplete expression; more input is needed
.
Incomplete expression; more input is needed
.

2, 3, 5, 7, 13, 17, 19, 31, 61, 89, 107, 127, 521, 607, 1279, 2203, 228
######################  INITIALIZE PROCESS ########################## ( 427 )
2, 1, 1, 2, 7, 34
######################  INITIALIZE PROCESS ########################## ( 428 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 429 )
1, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 28, 30, 31, 38, 40, 41, 48, 50, 51, 58, 60, 61, 68, 70, 71, 78, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 98, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 20
######################  INITIALIZE PROCESS ########################## ( 430 )
1, 0, 1, 0, 2, 0, 1, 0, 3, 0
######################  INITIALIZE PROCESS ########################## ( 431 )
0, 0, 0, 0, 0, 0, 0, 0, 0, 0
######################  INITIALIZE PROCESS ########################## ( 432 )
2, 3, 5, 7, 11, 13, 17, 19, 23, 29
######################  INITIALIZE PROCESS ########################## ( 433 )
1, 4, 2, 1, 4, 2, 1, 4, 2, 1
######################  INITIALIZE PROCESS ########################## ( 434 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 435 )
$Failed
######################  INITIALIZE PROCESS ########################## ( 436 )
1, 1, 1, 7, 15, 31, 63, 127
######################  INITIALIZE PROCESS ########################## ( 437 )
3, 5, 7, 13, 17, 19, 31, 61
######################  INITIALIZE PROCESS ########################## ( 438 )
1, 1, 1, 4, 7, 11, 18, 29
######################  INITIALIZE PROCESS ########################## ( 439 )
1, 0, 1, 4, 7, 11, 18, 29
######################  INITIALIZE PROCESS ########################## ( 440 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 441 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 442 )
90, 204, 320, 438, 558, 680, 804, 930, 1058, 1188
######################  INITIALIZE PROCESS ########################## ( 443 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 444 )

######################  INITIALIZE PROCESS ########################## ( 445 )
6, 24, 60, 120, 210, 336, 504, 720, 990, 1320
######################  INITIALIZE PROCESS ########################## ( 446 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 447 )
26, 50, 114, 148, 160, 170, 274, 347, 432, 497
######################  INITIALIZE PROCESS ########################## ( 448 )
52, 60, 72, 88, 96, 100, 108, 112, 136, 148, 156, 172, 180, 192, 196, 228, 232, 240, 256, 268, 276, 280, 292, 312, 316, 336, 348, 352, 372, 388, 396, 400, 408, 420, 432, 448, 456, 460
######################  INITIALIZE PROCESS ########################## ( 449 )
105, 115, 125, 135, 145, 150, 151, 152, 153, 154, 155, 205, 215, 225, 235, 245, 250, 251, 252, 253, 254, 255, 305, 315, 325, 335, 345, 350, 351, 352, 353, 354, 355, 405, 415, 425, 435, 445, 450, 451, 452, 453, 454, 455, 500, 501, 502, 503, 504, 505, 510, 511, 512, 513, 514, 515, 520, 521, 522, 523, 524, 525, 530, 531, 532, 533, 534, 535, 540, 541, 542, 543, 544, 545, 550, 551, 552, 553, 554, 555
######################  INITIALIZE PROCESS ########################## ( 450 )
24, 31, 18, 39, 20, 42, 32, 36, 24, 60, 31, 42, 40, 56, 30, 72, 32, 63, 48, 54, 48, 91, 38, 60, 56, 90, 42, 96, 44, 84, 78, 72, 48, 124, 57, 93, 72, 98, 54, 120, 72, 120, 80, 90, 60, 168, 62, 96, 104, 127, 84, 144, 68, 126, 96, 144, 72, 195, 74, 114, 124, 140, 96, 168, 80, 186, 121, 126, 84, 224, 108, 132, 120, 180, 90, 234, 112, 168, 128, 144, 120, 252, 98, 171, 156, 217, 102, 216, 104, 210, 192, 162, 108, 280, 110, 216, 152, 248, 114, 240, 144, 210, 182, 180, 144, 360, 133, 186, 168, 224, 156, 312, 128, 255, 176, 252, 132, 336, 160, 204, 240, 270, 138, 288, 140, 336, 192, 216, 168, 403, 180, 222, 228, 266, 150, 372, 152, 300, 234, 288, 192, 392, 158, 240, 216, 378, 192, 363, 164, 294, 288, 252, 168, 480, 183, 324, 260, 308, 174, 360, 248, 372, 240, 270, 180, 546, 182, 336, 248, 360, 228, 384, 216, 336, 320, 360, 192, 508, 194, 294, 336, 399, 198, 468, 200, 465, 272, 306, 240, 504, 252, 312, 312, 434, 240, 576, 212, 378, 288, 324, 264, 600, 256, 330, 296, 504, 252, 456, 224, 504, 403, 342, 228, 560, 230, 432, 384, 450, 234, 546, 288, 420, 320, 432, 240, 744, 242, 399, 364, 434, 342, 504, 280, 480, 336, 468, 252, 728, 288, 384, 432, 511, 258, 528, 304, 588, 390, 396, 264, 720, 324, 480, 360, 476, 270, 720, 272, 558, 448, 414, 372, 672, 278, 420, 416, 720, 282, 576, 284, 504, 480, 504, 336, 819, 307, 540, 392, 518, 294, 684, 360, 570, 480, 450, 336, 868, 352, 456, 408, 620, 372, 702, 308, 672, 416, 576, 312, 840, 314, 474, 624, 560, 318, 648, 360, 762, 432, 576, 360, 847, 434, 492, 440, 630, 384, 864, 332, 588, 494, 504, 408, 992, 338, 549, 456, 756, 384, 780, 400, 660, 576, 522, 348, 840, 350, 744, 560, 756, 354, 720, 432, 630, 576, 540, 360, 1170, 381, 546, 532, 784, 444, 744, 368, 744, 546, 684, 432, 896, 374, 648, 624, 720, 420, 960, 380, 840, 512, 576, 384, 1020, 576, 582, 572, 686, 390, 1008, 432, 855, 528, 594, 480, 1092, 398, 600, 640, 961, 402, 816, 448, 714, 726, 720, 456, 1080, 410, 756, 552, 728, 480, 936, 504, 882, 560, 720, 420, 1344, 422, 636, 624, 810, 558, 864, 496, 756, 672, 792, 432, 1240, 434, 768, 720, 770, 480, 888, 440, 1080, 741, 756, 444, 1064, 540, 672, 600, 1016, 450, 120
######################  INITIALIZE PROCESS ########################## ( 451 )

######################  INITIALIZE PROCESS ########################## ( 452 )
3, 5, 16, 33, 96, 133, 240, 297, 448, 741
######################  INITIALIZE PROCESS ########################## ( 453 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 454 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 455 )
1, 3, 9, 15, 21, 33, 39, 45, 57, 81, 99, 105, 111, 117, 123, 147, 171, 219, 225, 237, 243, 249, 255, 273, 297, 303, 309, 321, 345, 351, 363, 369, 375, 387, 417, 423, 429, 441, 447, 453, 47
######################  INITIALIZE PROCESS ########################## ( 456 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 457 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 458 )

######################  INITIALIZE PROCESS ########################## ( 459 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 460 )

######################  INITIALIZE PROCESS ########################## ( 461 )
14, 21, 35, 49, 77, 91, 119, 133, 161, 203
######################  INITIALIZE PROCESS ########################## ( 462 )
3, 7, 9, 13, 15, 19, 21, 23, 24, 28, 29, 31, 33, 37, 39, 43, 45, 49, 55, 57, 63, 67, 69, 73, 79, 85, 87, 93, 97, 99, 105, 109, 115, 123, 127, 129, 133, 135, 139, 153, 157, 163, 165, 175, 177, 183, 189, 193, 199, 205, 207, 217, 219, 223, 225, 237, 249, 253, 255, 259, 265, 267, 277, 283, 289, 295, 297, 303, 307, 309, 319, 333, 337, 339, 343, 357, 363, 373, 375, 379, 385, 393, 399, 405, 409, 415, 423, 427, 435, 445, 447, 457, 459, 465, 469, 475, 483, 487, 489, 49
######################  INITIALIZE PROCESS ########################## ( 463 )

######################  INITIALIZE PROCESS ########################## ( 464 )
9, 15, 33, 69, 87, 123, 159, 249, 267, 33
######################  INITIALIZE PROCESS ########################## ( 465 )

######################  INITIALIZE PROCESS ########################## ( 466 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 467 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 468 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 469 )

######################  INITIALIZE PROCESS ########################## ( 470 )
2, 3, 5, 17, 23, 29, 47, 59, 83, 89, 107, 113, 149, 167, 173, 227, 233, 239, 29
######################  INITIALIZE PROCESS ########################## ( 471 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 472 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 473 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 474 )

######################  INITIALIZE PROCESS ########################## ( 475 )
1, 0, 1, 4, 7, 11, 18, 29, 47, 76
######################  INITIALIZE PROCESS ########################## ( 476 )

######################  INITIALIZE PROCESS ########################## ( 477 )
26, 50, 114, 148, 160, 170, 274, 347, 432, 497, 11
######################  INITIALIZE PROCESS ########################## ( 478 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 479 )
100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500
######################  INITIALIZE PROCESS ########################## ( 480 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 481 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 482 )
3, 7, 22, 45, 116, 163, 282, 353, 520, 831
######################  INITIALIZE PROCESS ########################## ( 483 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 484 )
9, 84, 144, 170, 325, 393, 401, 405, 435, 497, 11
######################  INITIALIZE PROCESS ########################## ( 485 )
30, 32, 38, 42, 44, 48, 54, 60, 62, 68, 72, 74, 80, 84, 90, 98, 102, 104, 108, 110, 114, 128, 132, 138, 140, 150, 152, 158, 164, 168, 174, 180, 182, 192, 194, 198, 200, 212, 224, 228, 230, 234, 240, 242, 252, 258, 264, 270, 272, 278, 282, 284, 294, 308, 312, 314, 318, 332, 338, 348, 350, 354, 360, 368, 374, 380, 384, 390, 398, 402, 410, 420, 422, 432, 434, 440, 444, 450, 458, 462, 464, 468, 480, 488, 492, 500
######################  INITIALIZE PROCESS ########################## ( 486 )

######################  INITIALIZE PROCESS ########################## ( 487 )
7, 14, 32, 60, 134, 186, 308, 384, 558, 872
######################  INITIALIZE PROCESS ########################## ( 488 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 489 )
12, 36, 96, 119, 171, 213, 221, 232, 363, 451, 11
######################  INITIALIZE PROCESS ########################## ( 490 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 491 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 492 )
1, 3, 5, 9, 11, 15, 17, 21, 27, 29, 35, 39, 41, 45, 51, 57, 59, 65, 69, 71, 77, 81, 87, 95, 99, 101, 105, 107, 111, 125, 129, 135, 137, 147, 149, 155, 161, 165, 171, 177, 179, 189, 191, 195, 197, 209, 221, 225, 227, 231, 237, 239, 249, 255, 261, 267, 269, 275, 279, 281, 291, 305, 309, 311, 315, 329, 335, 345, 347, 351, 357, 365, 371, 377, 381, 387, 395, 399, 407, 417, 419, 429, 431, 437, 441, 447, 455, 459, 461, 465, 477, 485, 489, 49
######################  INITIALIZE PROCESS ########################## ( 493 )
4, 11, 18, 39, 81, 165, 333, 669, 1341, 2685
######################  INITIALIZE PROCESS ########################## ( 494 )
72, 106, 139, 165, 171, 192, 199, 429, 453, 477, 11
######################  INITIALIZE PROCESS ########################## ( 495 )

######################  INITIALIZE PROCESS ########################## ( 496 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 497 )

######################  INITIALIZE PROCESS ########################## ( 498 )
26, 94, 98, 137, 176, 301, 323, 330, 372, 444, 11
######################  INITIALIZE PROCESS ########################## ( 499 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 500 )
2, 3, 5, 7, 13, 17, 19, 31, 61, 89, 107, 12
######################  INITIALIZE PROCESS ########################## ( 501 )
20, 120, 40, 336, 68, 720, 104, 1320, 148, 2184
######################  INITIALIZE PROCESS ########################## ( 502 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 503 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 504 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 505 )
2, 42, 66, 102, 153, 195, 201, 252, 306, 396, 11
######################  INITIALIZE PROCESS ########################## ( 506 )

######################  INITIALIZE PROCESS ########################## ( 507 )
26, 50, 114, 148, 160, 170, 274, 347, 432, 497, 11
######################  INITIALIZE PROCESS ########################## ( 508 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 509 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 510 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 511 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 512 )
23, 27, 41, 71, 123, 203, 317, 471, 671, 923
######################  INITIALIZE PROCESS ########################## ( 513 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 514 )
73, 183, 343, 553, 813, 1123, 1483, 1893, 2353
######################  INITIALIZE PROCESS ########################## ( 515 )
1, 2, 4, 6, 10, 12, 16, 18, 22, 28, 30, 36, 40, 42, 46, 52, 58, 60, 66, 70, 72, 78, 82, 88, 96, 100, 102, 106, 108, 112, 126, 130, 136, 138, 148, 150, 156, 162, 166, 172, 178, 180, 190, 192, 196, 198, 210, 222, 226, 228, 232, 238, 240, 250, 256, 262, 268, 270, 276, 280, 282, 292, 306, 310, 312, 316, 330, 336, 346, 348, 352, 358, 366, 372, 378, 382, 388, 396, 400, 408, 418, 420, 430, 432, 438, 442, 448, 456, 460, 462, 466, 478, 486, 490, 49
######################  INITIALIZE PROCESS ########################## ( 516 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 517 )
15, 40, 85, 156, 259, 400, 585, 820, 1111, 1464
######################  INITIALIZE PROCESS ########################## ( 518 )
8, 11, 12, 103, 116, 196, 247, 254, 389, 427, 11
######################  INITIALIZE PROCESS ########################## ( 519 )
12, 36, 96, 119, 171, 213, 221, 232, 363, 451, 11
######################  INITIALIZE PROCESS ########################## ( 520 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 521 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 522 )
1, 2, 4, 6, 10, 12, 16, 18, 22, 28, 30, 36, 40, 42, 46, 52, 58, 60, 66, 70, 72, 78, 82, 88, 96, 100, 102, 106, 108, 112, 126, 130, 136, 138, 148, 150, 156, 162, 166, 172, 178, 180, 190, 192, 196, 198, 210, 222, 226, 228, 232, 238, 240, 250, 256, 262, 268, 270, 276, 280, 282, 292, 306, 310, 312, 316, 330, 336, 346, 348, 352, 358, 366, 372, 378, 382, 388, 396, 400, 408, 418, 420, 430, 432, 438, 442, 448, 456, 460, 462, 466, 478, 486, 490, 49
######################  INITIALIZE PROCESS ########################## ( 523 )
1, 0, 1, 4, 7, 11, 18, 29, 47, 76
######################  INITIALIZE PROCESS ########################## ( 524 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 525 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 526 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 527 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 528 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 529 )
60, 120, 210, 336, 504, 720, 990, 1320, 1716, 2184
######################  INITIALIZE PROCESS ########################## ( 530 )
2, 3, 5, 7, 13, 17, 19, 31, 61, 89, 107, 12
######################  INITIALIZE PROCESS ########################## ( 531 )
2, 4, 10, 16, 28, 40, 58, 70, 100, 106, 136, 148, 178, 190, 196, 226, 238, 268, 280, 310, 346, 418, 430, 460, 520, 568, 598, 616, 640, 658, 808, 820, 826, 856, 88
######################  INITIALIZE PROCESS ########################## ( 532 )
90, 95, 110, 141, 194, 275, 390, 545, 746, 999
######################  INITIALIZE PROCESS ########################## ( 533 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 534 )

Tensors {2} and {1, 0, 1} have incompatible shapes.
Tensors {3} and {1, 0, 1} have incompatible shapes.
Tensors {5} and {1, 0, 1} have incompatible shapes.
Tensors {7} and {1, 0, 1} have incompatible shapes.
Tensors {1, 1} and {1, 0, 1} have incompatible shapes.
Tensors {1, 3} and {1, 0, 1} have incompatible shapes.
Tensors {1, 7} and {1, 0, 1} have incompatible shapes.
Tensors {1, 9} and {1, 0, 1} have incompatible shapes.
Tensors {2, 3} and {1, 0, 1} have incompatible shapes.
Tensors {2, 9} and {1, 0, 1} have incompatible shapes.
Tensors {3, 1} and {1, 0, 1} have incompatible shapes.
Tensors {3, 7} and {1, 0, 1} have incompatible shapes.
Tensors {4, 1} and {1, 0, 1} have incompatible shapes.
Tensors {4, 3} and {1, 0, 1} have incompatible shapes.
Tensors {4, 7} and {1, 0, 1} have incompatible shapes.
Tensors {5, 3} and {1, 0, 1} have incompatible shapes.
Tensors {5, 9} and {1, 0, 1} have incompatible shapes.
Tensors {6, 1} and {1, 0, 1} have incompatible shapes.
Tensors {6, 7} and {1, 0, 1} have incompatible shapes.
Tensors {7, 1} and {1, 0, 1} have incompatible shapes.
Tensors {7, 3} and {1, 0, 1} have incompatible shapes.
Tensors {7, 9} and {1, 0, 1} have incompatible shapes.
Tensors {8, 3} and {1, 0, 1} have incompatible shapes.
Tensors {8, 9} and {1, 0, 1} have incompatible shapes.
Tensors {9, 7} and {1, 0, 1} have incompatible shapes.
Tensors {2} and {1, 0, 1} have incompatible shapes.
Tensors {3} and {1, 0, 1} have incompatible shapes.
Tensors {5} and {1, 0, 1} have incompatible shapes.
Tensors {7} and {1, 0, 1} have incompatible shapes.
Tensors {1, 1} and {1, 0, 1} have incompatible shapes.
Tensors {1, 3} and {1, 0, 1} have incompatible shapes.
Tensors {1, 7} and {1, 0, 1} have incompatible shapes.
Tensors {1, 9} and {1, 0, 1} have incompatible shapes.
Tensors {2, 3} and {1, 0, 1} have incompatible shapes.
Tensors {2, 9} and {1, 0, 1} have incompatible shapes.
Tensors {3, 1} and {1, 0, 1} have incompatible shapes.
Tensors {3, 7} and {1, 0, 1} have incompatible shapes.
Tensors {4, 1} and {1, 0, 1} have incompatible shapes.
Tensors {4, 3} and {1, 0, 1} have incompatible shapes.
Tensors {4, 7} and {1, 0, 1} have incompatible shapes.
Tensors {5, 3} and {1, 0, 1} have incompatible shapes.
Tensors {5, 9} and {1, 0, 1} have incompatible shapes.
Tensors {6, 1} and {1, 0, 1} have incompatible shapes.
Tensors {6, 7} and {1, 0, 1} have incompatible shapes.
Tensors {7, 1} and {1, 0, 1} have incompatible shapes.
Tensors {7, 3} and {1, 0, 1} have incompatible shapes.
Tensors {7, 9} and {1, 0, 1} have incompatible shapes.
Tensors {8, 3} and {1, 0, 1} have incompatible shapes.
Tensors {8, 9} and {1, 0, 1} have incompatible shapes.
Tensors {9, 7} and {1, 0, 1} have incompatible shapes.

**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 547 )
339, 413, 500
######################  INITIALIZE PROCESS ########################## ( 548 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 549 )
12, 14, 16, 20, 21, 23, 25, 29, 30, 32, 34, 38, 41, 43, 47, 49, 50, 52, 56, 58, 61, 65, 67, 70, 74, 76, 83, 85, 89, 92, 94, 98, 101, 102, 104, 106, 110, 111, 113, 115, 119, 120, 122, 124, 128, 131, 133, 137, 139, 140, 142, 146, 148, 151, 155, 157, 160, 164, 166, 173, 175, 179, 182, 184, 188, 191, 193, 197, 199, 200, 201, 203, 205, 209, 210, 212, 214, 218, 221, 223, 227, 229, 230, 232, 236, 238, 241, 245, 247, 250, 254, 256, 263, 265, 269, 272, 274, 278, 281, 283, 287, 289, 290, 292, 296, 298, 300, 302, 304, 308, 311, 313, 317, 319, 320, 322, 326, 328, 331, 335, 337, 340, 344, 346, 353, 355, 359, 362, 364, 368, 371, 373, 377, 379, 380, 382, 386, 388, 391, 395, 397, 401, 403, 407, 409, 410, 412, 416, 418, 421, 425, 427, 430, 434, 436, 443, 445, 449, 452, 454, 458, 461, 463, 467, 469, 470, 472, 476, 478, 481, 485, 487, 490, 494, 496, 500
######################  INITIALIZE PROCESS ########################## ( 550 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 551 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 552 )
1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 43, 44, 46, 47, 48, 49, 51, 52, 53, 54, 55, 56, 58, 59, 60, 61, 62, 63, 64, 65, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 78, 79, 80, 81, 84, 86, 87, 89, 91, 93, 94, 95, 96, 98, 99, 100, 101, 102, 104, 106, 107, 108, 109, 111, 112, 113, 114, 115, 116, 117, 119, 120, 121, 125, 126, 129, 130, 132, 133, 134, 135, 136, 138, 140, 142, 143, 145, 146, 147, 149, 150, 151, 152, 153, 154, 155, 157, 158, 159, 161, 166, 167, 168, 169, 170, 172, 175, 176, 177, 178, 180, 181, 182, 183, 184, 189, 190, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 203, 204, 207, 211, 212, 213, 215, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 234, 236, 239, 241, 242, 244, 248, 251, 254, 255, 258, 259, 261, 263, 264, 265, 268, 270, 273, 274, 275, 276, 277, 278, 281, 282, 283, 286, 289, 291, 293, 294, 295, 298, 304, 305, 306, 307, 308, 309, 311, 312, 314, 316, 317, 318, 319, 320, 321, 323, 324, 325, 333, 334, 336, 338, 340, 341, 342, 344, 347, 349, 351, 352, 353, 354, 355, 356, 357, 359, 360, 363, 364, 366, 367, 372, 373, 376, 377, 378, 380, 383, 385, 387, 388, 391, 392, 393, 394, 395, 397, 398, 399, 401, 404, 405, 406, 412, 413, 414, 415, 416, 418, 420, 424, 425, 427, 430, 431, 434, 435, 436, 437, 438, 439, 440, 442, 445, 447, 448, 449, 453, 454, 456, 457, 458, 459, 462, 463, 465, 466, 469, 470, 471, 476, 477, 479, 480, 483, 485, 486, 487, 489, 491, 494, 496, 498, 499, 50
######################  INITIALIZE PROCESS ########################## ( 553 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 554 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 555 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 556 )
101, 131, 151, 181, 191, 211, 223, 229, 233, 239, 241, 251, 263, 269, 271, 281, 283, 293, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499
######################  INITIALIZE PROCESS ########################## ( 557 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 558 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 559 )
60, 120, 210, 336, 504, 720, 990, 1320, 1716, 2184
######################  INITIALIZE PROCESS ########################## ( 560 )
2, 3, 5, 7, 13, 17, 19, 31, 61, 89, 107, 12
######################  INITIALIZE PROCESS ########################## ( 561 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 562 )
90, 95, 110, 141, 194, 275, 390, 545, 746, 999
######################  INITIALIZE PROCESS ########################## ( 563 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 564 )
62, 98, 130, 154, 290, 315, 324, 385, 408, 447, 11
######################  INITIALIZE PROCESS ########################## ( 565 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 566 )
153, 370, 371, 407
######################  INITIALIZE PROCESS ########################## ( 567 )
1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 43, 44, 46, 47, 48, 49, 51, 52, 53, 54, 55, 56, 58, 59, 60, 61, 62, 63, 64, 65, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 78, 79, 80, 81, 84, 86, 87, 89, 91, 93, 94, 95, 96, 98, 99, 100, 101, 102, 104, 106, 107, 108, 109, 111, 112, 113, 114, 115, 116, 117, 119, 120, 121, 125, 126, 129, 130, 132, 133, 134, 135, 136, 138, 140, 142, 143, 145, 146, 147, 149, 150, 151, 152, 153, 154, 155, 157, 158, 159, 161, 166, 167, 168, 169, 170, 172, 175, 176, 177, 178, 180, 181, 182, 183, 184, 189, 190, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 203, 204, 207, 211, 212, 213, 215, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 234, 236, 239, 241, 242, 244, 248, 251, 254, 255, 258, 259, 261, 263, 264, 265, 268, 270, 273, 274, 275, 276, 277, 278, 281, 282, 283, 286, 289, 291, 293, 294, 295, 298, 304, 305, 306, 307, 308, 309, 311, 312, 314, 316, 317, 318, 319, 320, 321, 323, 324, 325, 333, 334, 336, 338, 340, 341, 342, 344, 347, 349, 351, 352, 353, 354, 355, 356, 357, 359, 360, 363, 364, 366, 367, 372, 373, 376, 377, 378, 380, 383, 385, 387, 388, 391, 392, 393, 394, 395, 397, 398, 399, 401, 404, 405, 406, 412, 413, 414, 415, 416, 418, 420, 424, 425, 427, 430, 431, 434, 435, 436, 437, 438, 439, 440, 442, 445, 447, 448, 449, 453, 454, 456, 457, 458, 459, 462, 463, 465, 466, 469, 470, 471, 476, 477, 479, 480, 483, 485, 486, 487, 489, 491, 494, 496, 498, 499, 50
######################  INITIALIZE PROCESS ########################## ( 568 )
2, 3, 5, 11, 23, 29, 41, 53, 83, 89, 113, 131, 173, 179, 191, 233, 239, 251, 281, 293, 359, 419, 431, 443, 49
######################  INITIALIZE PROCESS ########################## ( 569 )

######################  INITIALIZE PROCESS ########################## ( 570 )
24, 31, 18, 39, 20, 42, 32, 36, 24, 60, 31, 42, 40, 56, 30, 72, 32, 63, 48, 54, 48, 91, 38, 60, 56, 90, 42, 96, 44, 84, 78, 72, 48, 124, 57, 93, 72, 98, 54, 120, 72, 120, 80, 90, 60, 168, 62, 96, 104, 127, 84, 144, 68, 126, 96, 144, 72, 195, 74, 114, 124, 140, 96, 168, 80, 186, 121, 126, 84, 224, 108, 132, 120, 180, 90, 234, 112, 168, 128, 144, 120, 252, 98, 171, 156, 217, 102, 216, 104, 210, 192, 162, 108, 280, 110, 216, 152, 248, 114, 240, 144, 210, 182, 180, 144, 360, 133, 186, 168, 224, 156, 312, 128, 255, 176, 252, 132, 336, 160, 204, 240, 270, 138, 288, 140, 336, 192, 216, 168, 403, 180, 222, 228, 266, 150, 372, 152, 300, 234, 288, 192, 392, 158, 240, 216, 378, 192, 363, 164, 294, 288, 252, 168, 480, 183, 324, 260, 308, 174, 360, 248, 372, 240, 270, 180, 546, 182, 336, 248, 360, 228, 384, 216, 336, 320, 360, 192, 508, 194, 294, 336, 399, 198, 468, 200, 465, 272, 306, 240, 504, 252, 312, 312, 434, 240, 576, 212, 378, 288, 324, 264, 600, 256, 330, 296, 504, 252, 456, 224, 504, 403, 342, 228, 560, 230, 432, 384, 450, 234, 546, 288, 420, 320, 432, 240, 744, 242, 399, 364, 434, 342, 504, 280, 480, 336, 468, 252, 728, 288, 384, 432, 511, 258, 528, 304, 588, 390, 396, 264, 720, 324, 480, 360, 476, 270, 720, 272, 558, 448, 414, 372, 672, 278, 420, 416, 720, 282, 576, 284, 504, 480, 504, 336, 819, 307, 540, 392, 518, 294, 684, 360, 570, 480, 450, 336, 868, 352, 456, 408, 620, 372, 702, 308, 672, 416, 576, 312, 840, 314, 474, 624, 560, 318, 648, 360, 762, 432, 576, 360, 847, 434, 492, 440, 630, 384, 864, 332, 588, 494, 504, 408, 992, 338, 549, 456, 756, 384, 780, 400, 660, 576, 522, 348, 840, 350, 744, 560, 756, 354, 720, 432, 630, 576, 540, 360, 1170, 381, 546, 532, 784, 444, 744, 368, 744, 546, 684, 432, 896, 374, 648, 624, 720, 420, 960, 380, 840, 512, 576, 384, 1020, 576, 582, 572, 686, 390, 1008, 432, 855, 528, 594, 480, 1092, 398, 600, 640, 961, 402, 816, 448, 714, 726, 720, 456, 1080, 410, 756, 552, 728, 480, 936, 504, 882, 560, 720, 420, 1344, 422, 636, 624, 810, 558, 864, 496, 756, 672, 792, 432, 1240, 434, 768, 720, 770, 480, 888, 440, 1080, 741, 756, 444, 1064, 540, 672, 600, 1016, 450, 120
######################  INITIALIZE PROCESS ########################## ( 571 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 572 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 573 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 574 )
9, 84, 144, 170, 325, 393, 401, 405, 435, 497, 11
######################  INITIALIZE PROCESS ########################## ( 575 )
1, 2, 4, 6, 10, 12, 16, 18, 22, 28, 30, 36, 40, 42, 46, 52, 58, 60, 66, 70, 72, 78, 82, 88, 96, 100, 102, 106, 108, 112, 126, 130, 136, 138, 148, 150, 156, 162, 166, 172, 178, 180, 190, 192, 196, 198, 210, 222, 226, 228, 232, 238, 240, 250, 256, 262, 268, 270, 276, 280, 282, 292, 306, 310, 312, 316, 330, 336, 346, 348, 352, 358, 366, 372, 378, 382, 388, 396, 400, 408, 418, 420, 430, 432, 438, 442, 448, 456, 460, 462, 466, 478, 486, 490, 49
######################  INITIALIZE PROCESS ########################## ( 576 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 577 )
65, 146, 205, 338, 425, 610, 941, 1082, 1513, 1850
######################  INITIALIZE PROCESS ########################## ( 578 )
8, 11, 12, 103, 116, 196, 247, 254, 389, 427, 11
######################  INITIALIZE PROCESS ########################## ( 579 )
12, 14, 16, 20, 21, 23, 25, 29, 30, 32, 34, 38, 41, 43, 47, 49, 50, 52, 56, 58, 61, 65, 67, 70, 74, 76, 83, 85, 89, 92, 94, 98, 101, 102, 104, 106, 110, 111, 113, 115, 119, 120, 122, 124, 128, 131, 133, 137, 139, 140, 142, 146, 148, 151, 155, 157, 160, 164, 166, 173, 175, 179, 182, 184, 188, 191, 193, 197, 199, 200, 201, 203, 205, 209, 210, 212, 214, 218, 221, 223, 227, 229, 230, 232, 236, 238, 241, 245, 247, 250, 254, 256, 263, 265, 269, 272, 274, 278, 281, 283, 287, 289, 290, 292, 296, 298, 300, 302, 304, 308, 311, 313, 317, 319, 320, 322, 326, 328, 331, 335, 337, 340, 344, 346, 353, 355, 359, 362, 364, 368, 371, 373, 377, 379, 380, 382, 386, 388, 391, 395, 397, 401, 403, 407, 409, 410, 412, 416, 418, 421, 425, 427, 430, 434, 436, 443, 445, 449, 452, 454, 458, 461, 463, 467, 469, 470, 472, 476, 478, 481, 485, 487, 490, 494, 496, 500
######################  INITIALIZE PROCESS ########################## ( 580 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 581 )
307, 462, 663, 916, 1227, 1602, 2047, 2568, 3171, 3862
######################  INITIALIZE PROCESS ########################## ( 582 )
1, 3, 5, 9, 11, 15, 17, 21, 27, 29, 35, 39, 41, 45, 51, 57, 59, 65, 69, 71, 77, 81, 87, 95, 99, 101, 105, 107, 111, 125, 129, 135, 137, 147, 149, 155, 161, 165, 171, 177, 179, 189, 191, 195, 197, 209, 221, 225, 227, 231, 237, 239, 249, 255, 261, 267, 269, 275, 279, 281, 291, 305, 309, 311, 315, 329, 335, 345, 347, 351, 357, 365, 371, 377, 381, 387, 395, 399, 407, 417, 419, 429, 431, 437, 441, 447, 455, 459, 461, 465, 477, 485, 489, 49
######################  INITIALIZE PROCESS ########################## ( 583 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 584 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 585 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 586 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 587 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 588 )
**************** execution error ( step 2)

######################  INITIALIZE PROCESS ########################## ( 589 )
60, 120, 210, 336, 504, 720, 990, 1320, 1716, 2184

In [286]:
exe_outputs

['2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '3, 6, 9, 12, 15, 18, 21, 24, 27, 30',
 '4, 8, 12, 16, 20, 24, 28, 32, 36, 40',
 '5, 10, 15, 20, 25, 30, 35, 40, 45, 50',
 '6, 12, 18, 24, 30, 36, 42, 48, 54, 60',
 '7, 14, 21, 28, 35, 42, 49, 56, 63, 70',
 '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
 '9, 18, 27, 36, 45, 54, 63, 72, 81, 90',
 '10, 20, 30, 40, 50, 60, 70, 80, 90, 100',
 '1, 3, 5, 7, 9, 11, 13, 15, 17, 19',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '11, 12, 13, 14, 15, 16, 17, 18, 19, 20',
 '21, 22, 23, 24, 25, 26, 27, 28, 29, 30',
 '31, 32, 33, 34, 35, 36, 37, 38, 39, 40',
 '41, 42, 43, 44, 45, 46, 47, 48, 49, 50',
 '51, 52, 53, 54, 55, 56, 57, 58, 59, 60',
 '61, 62, 63, 64, 65, 66, 67, 68, 69, 70',
 '71, 72, 73, 74, 75, 76, 77, 78, 79, 80',
 '81, 82, 83, 84, 85, 86, 87, 88, 89, 90',
 '91, 92, 93, 94, 95, 96, 97, 98, 99, 100',
 '101, 102, 103, 104, 105, 106, 107, 108, 109, 110',
 '111, 112, 113, 114, 115, 116, 117, 118, 119, 120',
 '121, 122, 123, 124, 125, 126, 127, 128, 129, 130',
 '131, 132, 133, 134, 135, 136, 137, 138, 139, 140',
 '141, 142, 143, 144, 145, 146, 147, 148, 149, 150',
 '151, 152, 153, 154, 155, 156, 157, 158, 159, 160',
 '161, 162, 163, 164, 165, 166, 167, 168, 169, 170',
 '171, 172, 173, 174, 175, 176, 177, 178, 179, 180',
 '181, 182, 183, 184, 185, 186, 187, 188, 189, 190',
 '191, 192, 193, 194, 195, 196, 197, 198, 199, 200',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '3, 6, 9, 12, 15, 18, 21, 24, 27, 30',
 '4, 8, 12, 16, 20, 24, 28, 32, 36, 40',
 '5, 10, 15, 20, 25, 30, 35, 40, 45, 50',
 '6, 12, 18, 24, 30, 36, 42, 48, 54, 60',
 '7, 14, 21, 28, 35, 42, 49, 56, 63, 70',
 '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
 '9, 18, 27, 36, 45, 54, 63, 72, 81, 90',
 '10, 20, 30, 40, 50, 60, 70, 80, 90, 100',
 '1, 3, 5, 7, 9, 11, 13, 15, 17, 19',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '11, 12, 13, 14, 15, 16, 17, 18, 19, 20',
 '21, 22, 23, 24, 25, 26, 27, 28, 29, 30',
 '31, 32, 33, 34, 35, 36, 37, 38, 39, 40',
 '41, 42, 43, 44, 45, 46, 47, 48, 49, 50',
 '51, 52, 53, 54, 55, 56, 57, 58, 59, 60',
 '61, 62, 63, 64, 65, 66, 67, 68, 69, 70',
 '71, 72, 73, 74, 75, 76, 77, 78, 79, 80',
 '81, 82, 83, 84, 85, 86, 87, 88, 89, 90',
 '91, 92, 93, 94, 95, 96, 97, 98, 99, 100',
 '101, 102, 103, 104, 105, 106, 107, 108, 109, 110',
 '111, 112, 113, 114, 115, 116, 117, 118, 119, 120',
 '121, 122, 123, 124, 125, 126, 127, 128, 129, 130',
 '131, 132, 133, 134, 135, 136, 137, 138, 139, 140',
 '141, 142, 143, 144, 145, 146, 147, 148, 149, 150',
 '151, 152, 153, 154, 155, 156, 157, 158, 159, 160',
 '161, 162, 163, 164, 165, 166, 167, 168, 169, 170',
 '171, 172, 173, 174, 175, 176, 177, 178, 179, 180',
 '181, 182, 183, 184, 185, 186, 187, 188, 189, 190',
 '191, 192, 193, 194, 195, 196, 197, 198, 199, 200',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '3, 6, 9, 12, 15, 18, 21, 24, 27, 30',
 '4, 8, 12, 16, 20, 24, 28, 32, 36, 40',
 '5, 10, 15, 20, 25, 30, 35, 40, 45, 50',
 '6, 12, 18, 24, 30, 36, 42, 48, 54, 60',
 '7, 14, 21, 28, 35, 42, 49, 56, 63, 70',
 '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
 '9, 18, 27, 36, 45, 54, 63, 72, 81, 90',
 '10, 20, 30, 40, 50, 60, 70, 80, 90, 100',
 '1, 3, 5, 7, 9, 11, 13, 15, 17, 19',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '11, 12, 13, 14, 15, 16, 17, 18, 19, 20',
 '21, 22, 23, 24, 25, 26, 27, 28, 29, 30',
 '31, 32, 33, 34, 35, 36, 37, 38, 39, 40',
 '41, 42, 43, 44, 45, 46, 47, 48, 49, 50',
 '51, 52, 53, 54, 55, 56, 57, 58, 59, 60',
 '61, 62, 63, 64, 65, 66, 67, 68, 69, 70',
 '71, 72, 73, 74, 75, 76, 77, 78, 79, 80',
 '81, 82, 83, 84, 85, 86, 87, 88, 89, 90',
 '91, 92, 93, 94, 95, 96, 97, 98, 99, 100',
 '101, 102, 103, 104, 105, 106, 107, 108, 109, 110',
 '111, 112, 113, 114, 115, 116, 117, 118, 119, 120',
 '121, 122, 123, 124, 125, 126, 127, 128, 129, 130',
 '131, 132, 133, 134, 135, 136, 137, 138, 139, 140',
 '141, 142, 143, 144, 145, 146, 147, 148, 149, 150',
 '151, 152, 153, 154, 155, 156, 157, 158, 159, 160',
 '161, 162, 163, 164, 165, 166, 167, 168, 169, 170',
 '171, 172, 173, 174, 175, 176, 177, 178, 179, 180',
 '181, 182, 183, 184, 185, 186, 187, 188, 189, 190',
 '191, 192, 193, 194, 195, 196, 197, 198, 199, 200',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '3, 6, 9, 12, 15, 18, 21, 24, 27, 30',
 '4, 8, 12, 16, 20, 24, 28, 32, 36, 40',
 '5, 10, 15, 20, 25, 30, 35, 40, 45, 50',
 '6, 12, 18, 24, 30, 36, 42, 48, 54, 60',
 '7, 14, 21, 28, 35, 42, 49, 56, 63, 70',
 '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
 '9, 18, 27, 36, 45, 54, 63, 72, 81, 90',
 '10, 20, 30, 40, 50, 60, 70, 80, 90, 100',
 '1, 3, 5, 7, 9, 11, 13, 15, 17, 19',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '11, 12, 13, 14, 15, 16, 17, 18, 19, 20',
 '21, 22, 23, 24, 25, 26, 27, 28, 29, 30',
 '31, 32, 33, 34, 35, 36, 37, 38, 39, 40',
 '41, 42, 43, 44, 45, 46, 47, 48, 49, 50',
 '51, 52, 53, 54, 55, 56, 57, 58, 59, 60',
 '61, 62, 63, 64, 65, 66, 67, 68, 69, 70',
 '71, 72, 73, 74, 75, 76, 77, 78, 79, 80',
 '81, 82, 83, 84, 85, 86, 87, 88, 89, 90',
 '91, 92, 93, 94, 95, 96, 97, 98, 99, 100',
 '101, 102, 103, 104, 105, 106, 107, 108, 109, 110',
 '111, 112, 113, 114, 115, 116, 117, 118, 119, 120',
 '121, 122, 123, 124, 125, 126, 127, 128, 129, 130',
 '131, 132, 133, 134, 135, 136, 137, 138, 139, 140',
 '141, 142, 143, 144, 145, 146, 147, 148, 149, 150',
 '151, 152, 153, 154, 155, 156, 157, 158, 159, 160',
 '161, 162, 163, 164, 165, 166, 167, 168, 169, 170',
 '171, 172, 173, 174, 175, 176, 177, 178, 179, 180',
 '181, 182, 183, 184, 185, 186, 187, 188, 189, 190',
 '191, 192, 193, 194, 195, 196, 197, 198, 199, 200',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '3, 6, 9, 12, 15, 18, 21, 24, 27, 30',
 '4, 8, 12, 16, 20, 24, 28, 32, 36, 40',
 '5, 10, 15, 20, 25, 30, 35, 40, 45, 50',
 '6, 12, 18, 24, 30, 36, 42, 48, 54, 60',
 '7, 14, 21, 28, 35, 42, 49, 56, 63, 70',
 '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
 '9, 18, 27, 36, 45, 54, 63, 72, 81, 90',
 '10, 20, 30, 40, 50, 60, 70, 80, 90, 100',
 '1, 3, 5, 7, 9, 11, 13, 15, 17, 19',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '11, 12, 13, 14, 15, 16, 17, 18, 19, 20',
 '21, 22, 23, 24, 25, 26, 27, 28, 29, 30',
 '31, 32, 33, 34, 35, 36, 37, 38, 39, 40',
 '41, 42, 43, 44, 45, 46, 47, 48, 49, 50',
 '51, 52, 53, 54, 55, 56, 57, 58, 59, 60',
 '61, 62, 63, 64, 65, 66, 67, 68, 69, 70',
 '71, 72, 73, 74, 75, 76, 77, 78, 79, 80',
 '81, 82, 83, 84, 85, 86, 87, 88, 89, 90',
 '91, 92, 93, 94, 95, 96, 97, 98, 99, 100',
 '101, 102, 103, 104, 105, 106, 107, 108, 109, 110',
 '111, 112, 113, 114, 115, 116, 117, 118, 119, 120',
 '121, 122, 123, 124, 125, 126, 127, 128, 129, 130',
 '131, 132, 133, 134, 135, 136, 137, 138, 139, 140',
 '141, 142, 143, 144, 145, 146, 147, 148, 149, 150',
 '151, 152, 153, 154, 155, 156, 157, 158, 159, 160',
 '161, 162, 163, 164, 165, 166, 167, 168, 169, 170',
 '171, 172, 173, 174, 175, 176, 177, 178, 179, 180',
 '181, 182, 183, 184, 185, 186, 187, 188, 189, 190',
 '191, 192, 193, 194, 195, 196, 197, 198, 199, 200',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 1, 2, 3, 5, 8, 13, 21, 34, 55',
 '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
 '1, 3, 9, 27, 81, 243, 729, 2187, 6561, 1968',
 '1, 4, 9, 16, 25, 36, 49, 64, 81, 100',
 '1, 8, 27, 64, 125, 216, 343, 512, 729, 1000',
 '1, 2, 6, 24, 120, 720, 5040, 40320, 362880, 3628800',
 '1, 3, 6, 10, 15, 21, 28, 36, 45, 55',
 '2, 1, 1, 4, 7, 11, 18, 29, 47, 76',
 '0, 1, 4, 12, 33, 88, 232, 609, 1596, 4180',
 '1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000',
 '1, 1, 4, 30, 336, 5040, 95040, 2162160, 57657600, 1764322560',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 2, 4, 6, 10, 12, 16, 18, 22, 28, 30',
 '1, 2, 2, 2, 3, 2, 4, 2, 5, 2, 6, 2, 7, 2, 8, 2, 9, 2, 10, 2',
 'nan, 1, 2, 3, 16, 25, 36, 49, 64, 81',
 '1, 2, 145, 4058',
 '2, 5, 10, 17, 26, 37, 50, 65, 82, 101',
 '1, 8, 10, 11, 18, 80, 81, 88, 100, 101, 108, 110, 111, 118, 180, 181, 188, 800, 801, 808, 810, 811, 818, 880, 881, 888, 100',
 '3, 7, 31, 127, 2047, 8191, 131071, 524287, 8388607, 536870911',
 '1, 2, 1, 4, 7, 11, 18, 29, 47, 76',
 '1, 2, 1, 4, 7, 11, 18, 29, 47, 76',
 '1, 3, 7, 13, 21, 31, 43, 57, 73, 91',
 '1, 0, 1, 0, 2, 0, 1, 0, 3, 0',
 '1, 1, 2, 1, 4, 7, 11, 18, 29, 47',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 "'1, 1, 1, 1, 1'",
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 2, 4, 8, 16, 32, 64, 128, 256, 51',
 '0, 1, 3, 7, 15, 31, 63, 127, 255, 511',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 1, 2, 3, 5, 8, 13, 21, 34, 55',
 '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
 '1, 3, 9, 27, 81, 243, 729, 2187, 6561, 19683',
 '1, 4, 9, 16, 25, 36, 49, 64, 81, 100',
 '1, 8, 27, 64, 125, 216, 343, 512, 729, 1000',
 '1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880',
 '1, 3, 6, 10, 15, 21, 28, 36, 45, 55',
 '2, 1, 3, 3, -2, 3, -2, -2, 3, -2, -2, -2, 3, -2, -2, -2, -2, 3, -2, -2, -2, -2, -2, 3, -2, -2, -2, -2, -2, -2, 3, -2, -2, -2, -2, -2, -2, -2',
 '0, 1, 5, 14, 30, 55, 91, 140, 204, 285',
 '1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000',
 '1, 1, 2, 5, 14, 42, 132, 429, 1430, 4862',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '4, 6, 8, 10, 12, 14, 16, 18, 20, 22',
 "'1, 10, 11, 100, 101, 110, 111, 1000, 1001, 1010'",
 'nan, 1, 2, 3, 16, 25, 36, 49, 64, 81',
 '1, 2, 145, 4058',
 '2, 5, 10, 17, 26, 37, 50, 65, 82, 101',
 '1, 8, 10, 11, 18, 20, 21, 28, 30, 31, 38, 40, 41, 48, 50, 51, 58, 60, 61, 68, 70, 71, 78, 80, 81, 88, 90, 91, 98, 100, 101, 108, 11',
 '3, 7, 31, 127, 2047, 8191, 131071, 524287, 8388607, 536870911',
 '1, 2, 1, 4, 7, 11, 18, 29, 47, 76',
 '1, 2, 1, 4, 7, 11, 18, 29, 47, 76',
 '1, 4, 10, 20, 35, 56, 84, 120, 165, 220',
 '1, 0, 1, 0, 2, 0, 1, 0, 3, 0',
 '1, 1, 2, 1, 4, 7, 11, 18, 29, 47',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 "1, '11, 21, 1211, 3112'",
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
 '0, 1, 3, 7, 15, 31, 63, 127, 255, 511',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 1, 2, 3, 5, 8, 13, 21, 34, 55',
 '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
 '1, 3, 9, 27, 81, 243, 729, 2187, 6561, 19683',
 '1, 4, 9, 16, 25, 36, 49, 64, 81, 100',
 '1, 8, 27, 64, 125, 216, 343, 512, 729, 1000',
 '1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880',
 '1, 3, 6, 10, 15, 21, 28, 36, 45, 55',
 '2, 1, 3, 4, 4, 2, 4, 3, 4, 3, 4, 2, 4, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 4, 2, 4, 3, 3, 4, 3, 4, 2, 4, 3, 3, 3, 3, 3, 3, 3, 3, All, 1',
 '0, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -1, GoldenRatio, FloorTimesPower5, Rational-1, 2, Times-1, PowerGoldenRatio, -2, PowerGoldenRatio, 2, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -3, PowerGoldenRatio, 3, FloorTimesPower5, Rational-1, 2, Times-1, PowerGoldenRatio, -4, PowerGoldenRatio, 4, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -5, PowerGoldenRatio, 5, FloorTimesPower5, Rational-1, 2, Times-1, PowerGoldenRatio, -6, PowerGoldenRatio, 6, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -7, PowerGoldenRatio, 7, FloorTimesPower5, Rational-1, 2, Times-1, PowerGoldenRatio, -8, PowerGoldenRatio, 8, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -9, PowerGoldenRatio, 9',
 '1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000',
 '1, 1, 4, 30, 336, 5040, 95040, 2162160, 57657600, 1764322560',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 25, 26, 28, 30',
 "'1, 10, 11, 100, 101, 110, 111, 1000, 1001, 1010'",
 '0, 1, 512, 27, 262144, 125, 10077696, 343, 134217728, 729',
 '1, 2, 145, 4058',
 '2, 5, 10, 17, 26, 37, 50, 65, 82, 101',
 '1, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 28, 30, 31, 38, 40, 41, 48, 50, 51, 58, 60, 61, 68, 70, 71, 78, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 98, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 20',
 '3, 7, 31, 127, 2047, 8191, 131071, 524287, 8388607, 536870911',
 '1, 2, 4, 4, 7, 11, 18, 29, 47, 76',
 '1, 2, 4, 4, 7, 11, 18, 29, 47, 76',
 '1, 3, 7, 13, 21, 31, 43, 57, 73, 91',
 '1, 0, 1, 0, 2, 0, 1, 0, 3, 0',
 '1, 1, 2, 4, 4, 7, 11, 18, 29, 47',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 "'1', StringJoinSplit'0', '1',, Span1, All, Split0, StringJoin'12', CharactersStringJoinSplit'0', '1',, Span1, All, Split0, Span1, All, StringJoin1, 2, StringJoin'02', CharactersStringJoin'12', CharactersStringJoinSplit'0', '1',, Span1, All, Split0, Span1, All, StringJoin1, 2, Span1, All, StringJoin0, 2, StringJoin'02', CharactersStringJoin'02', CharactersStringJoin'12', CharactersStringJoinSplit'0', '1',, Span1, All, Split0, Span1, All, StringJoin1, 2, Span1, All, StringJoin0, 2, Span1, All, StringJoin0, 2",
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 2, 4, 8, 16, 32, 64, 128, 256, 51',
 '0, 1, 3, 7, 15, 31, 63, 127, 255, 511',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 1, 2, 3, 5, 8, 13, 21, 34, 55',
 '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
 '1, 3, 9, 27, 81, 243, 729, 2187, 6561, 19683',
 '1, 4, 9, 16, 25, 36, 49, 64, 81, 100',
 '1, 8, 27, 64, 125, 216, 343, 512, 729, 1000',
 '1, 2, 6, 24, 120, 720, 5040, 40320, 362880, 3628800',
 '1, 3, 6, 10, 15, 21, 28, 36, 45, 55',
 '2, 1, 2, Slot2, 2, Slot2, 2, Slot2, 2, Slot2, 2, Slot2, 2, Slot2, 2, Slot2, 2, Slot2, 2, Slot2',
 '0, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -1, GoldenRatio, FloorTimesPower5, Rational-1, 2, Times-1, PowerGoldenRatio, -2, PowerGoldenRatio, 2, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -3, PowerGoldenRatio, 3, FloorTimesPower5, Rational-1, 2, Times-1, PowerGoldenRatio, -4, PowerGoldenRatio, 4, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -5, PowerGoldenRatio, 5, FloorTimesPower5, Rational-1, 2, Times-1, PowerGoldenRatio, -6, PowerGoldenRatio, 6, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -7, PowerGoldenRatio, 7, FloorTimesPower5, Rational-1, 2, Times-1, PowerGoldenRatio, -8, PowerGoldenRatio, 8, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -9, PowerGoldenRatio, 9',
 '1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000',
 '1, 1, 2, 5, 14, 42, 132, 429, 1430, 4862',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 2, 3, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 28, 30, 32, 36, 38, 40, 42, 44, 46, 48',
 '1, 2, 2, 2, 3, 2, 4, 2, 5, 2, 6, 2, 7, 2, 8, 2, 9, 2, 10, 2',
 '0, 1, 512, 27, 262144, 125, 10077696, 343, 134217728, 729',
 '1, 2, 145, 4058',
 '2, 5, 10, 17, 26, 37, 50, 65, 82, 101',
 '1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 31, 41, 51, 61, 71, 81, 91, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 19',
 '3, 7, 31, 127, 2047, 8191, 131071, 524287, 8388607, 536870911',
 '1, 2, 4, 4, 7, 11, 18, 29, 47, 76',
 '1, 2, 4, 4, 7, 11, 18, 29, 47, 76',
 '1, 4, 10, 20, 35, 56, 84, 120, 165, 220',
 'Global`HammingWeight0, Global`HammingWeight1, Global`HammingWeight2, Global`HammingWeight3, Global`HammingWeight4, Global`HammingWeight5, Global`HammingWeight6, Global`HammingWeight7, Global`HammingWeight8, Global`HammingWeight9',
 '1, 1, 2, 4, 4, 7, 11, 18, 29, 47',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 "'1, 1, 1, 1, 1'",
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
 '0, 1, 3, 7, 15, 31, 63, 127, 255, 511',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 1, 2, 3, 5, 8, 13, 21, 34, 55',
 '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
 '1, 3, 9, 27, 81, 243, 729, 2187, 6561, 19683',
 '1, 4, 9, 16, 25, 36, 49, 64, 81, 100',
 '1, 8, 27, 64, 125, 216, 343, 512, 729, 1000',
 '1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880',
 '1, 3, 6, 10, 15, 21, 28, 36, 45, 55',
 '2, 1, 2, Slot2, 2, Slot2, 2, Slot2, 2, Slot2, 2, Slot2, 2, Slot2, 2, Slot2, 2, Slot2, 2, Slot2',
 '0, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -1, GoldenRatio, FloorTimesPower5, Rational-1, 2, Times-1, PowerGoldenRatio, -2, PowerGoldenRatio, 2, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -3, PowerGoldenRatio, 3, FloorTimesPower5, Rational-1, 2, Times-1, PowerGoldenRatio, -4, PowerGoldenRatio, 4, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -5, PowerGoldenRatio, 5, FloorTimesPower5, Rational-1, 2, Times-1, PowerGoldenRatio, -6, PowerGoldenRatio, 6, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -7, PowerGoldenRatio, 7, FloorTimesPower5, Rational-1, 2, Times-1, PowerGoldenRatio, -8, PowerGoldenRatio, 8, FloorTimesPower5, Rational-1, 2, PowerGoldenRatio, -9, PowerGoldenRatio, 9',
 '1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000',
 '1, 1, 2, 5, 14, 42, 132, 429, 1430, 4862',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 2, 3, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 28, 30, 32, 36, 38, 40, 42, 44, 46, 48',
 '1, 2, 2, 2, 3, 2, 4, 2, 5, 2, 6, 2, 7, 2, 8, 2, 9, 2, 10, 2',
 '0, 1, 512, 27, 262144, 125, 10077696, 343, 134217728, 729',
 '1, 2, 145, 4058',
 '2, 5, 10, 17, 26, 37, 50, 65, 82, 101',
 '1, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 28, 30, 31, 38, 40, 41, 48, 50, 51, 58, 60, 61, 68, 70, 71, 78, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 98, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 20',
 '3, 7, 31, 127, 2047, 8191, 131071, 524287, 8388607, 536870911',
 '1, 2, 4, 4, 7, 11, 18, 29, 47, 76',
 '1, 2, 4, 4, 7, 11, 18, 29, 47, 76',
 '1, 3, 7, 13, 21, 31, 43, 57, 73, 91',
 '1, 0, 1, 0, 2, 0, 1, 0, 3, 0',
 '1, 1, 2, 4, 4, 7, 11, 18, 29, 47',
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 "'1, 1, 1, 1, 1'",
 '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
 '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
 '0, 1, 3, 7, 15, 31, 63, 127, 255, 511',
 '1, 4, 9, 16, 25, 36, 49, 64, 81, 100',
 '1, 8, 27, 64, 125, 216, 343, 512, 729, 1000',
 '2, 0, 1, 2, 0, 1, 2, 0, 1, 2',
 '2, 3, 3, 4, 4, 4, 5, 5, 5, 5',
 '2, 4, 8, 16, 32, 64, 128, 256, 512, 1024',
 '2, 5, 10, 17, 26, 37, 50, 65, 82, 101',
 '7, 11, 13, 17, 19, 23, 29, 31, 37, 41',
 '1, 11, 111, 1111, 11111, 111111, 1111111, 11111111, 111111111, 1111111111',
 '31, 331, 3331, 33331, 333331, 3333331, 33333331, 333333331',
 '$Failed',

In [287]:
correctness_list

[True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 'False',
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 'False',
 'False',
 False,
 'False',
 False,
 False,
 'False',
 True,
 False,
 False,
 False,
 False,
 False,
 'False',
 'False',
 False,
 'False',
 'False',
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 False,
 'False',
 'False',
 'False',
 False,
 False,
 'False',
 'False',
 'False',
 False,
 False,
 False,
 False,
 'False',
 False,
 'False',
 'False',
 False,
 'False',
 False,
 False,
 False,
 False,
 'False',
 False,
 'False',
 'False',
 False,
 False,
 False,
 False,
 'False',
 False,
 False,
 'False',
 False,
 False,
 'False',
 'False',
 'False',
 False,
 False,
 False,
 'False',
 'False',
 'False',
 'False',
 False,
 'False',
 False,
 False,
 'False',
 False,
 False,
 False,
 'False',
 'False',
 False,
 False,
 'False',
 'False',
 'False',
 'False',
 'False',
 False,
 False,
 False,
 False,
 'False',
 False,
 False,
 False,
 False,
 'False',
 False,
 False,
 'False',
 'False',
 'False',
 'False',
 False,
 'False',
 False,
 'False',
 False,
 'False',
 'False',
 False,
 'False',
 'False',
 'False',
 False,
 'False',
 'False',
 False,
 False,
 'False',
 False,
 'False',
 False,
 'False',
 False,
 False,
 False,
 False,
 False,
 'False',
 'False',
 'False',
 False,
 False,
 'False',
 False,
 False,
 False,
 'False',
 False,
 False,
 'False',
 'False',
 'False',
 'False',
 'False',
 'False',
 False]

In [288]:
m_df["exe_out"] = exe_outputs
m_df["correct_execution"] = correctness_list
m_df["Levenshtein"] = levenshtein_list
m_df

,sequence,complexity,length_type,language,q_length,GPT4_answer,a_length,temperature,real_code,print_code,no_code,explanation,no_sense,exe_out,correct_execution,Levenshtein
7080,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",1.0,0.0,Mathematica,173.0,"```mathematica\nTable[2 i, {i, 1, 10}]\n```",41.0,1.000,0.0,0,0.0,0.0,0,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",True,0
7081,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",1.0,0.0,Mathematica,174.0,"```mathematica\nTable[3*n, {n, 1, 10}]\n```",41.0,1.000,0.0,0,0.0,0.0,0,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",True,0
7082,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",1.0,0.0,Mathematica,175.0,"```mathematica\nRange[4, 40, 4]\n```",34.0,1.000,0.0,0,0.0,0.0,0,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",True,0
7083,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",1.0,0.0,Mathematica,176.0,"```mathematica\nTable[5*i, {i, 1, 10}]\n```",41.0,1.000,0.0,0,0.0,0.0,0,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",True,0
7084,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",1.0,0.0,Mathematica,176.0,"```mathematica\nTable[6*i, {i, 1, 10}]\n```",41.0,1.000,0.0,0,0.0,0.0,0,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7665,"187, 218, 260, 295, 301, 314, 379, 410, 452, 469",4.0,0.0,Mathematica,186.0,"```mathematica\nSequence[187, 218, 260, 295, 3...",77.0,0.001,0.0,0,0.0,0.0,0,Execution error,False,50000
7666,"29, 63, 95, 140, 150, 190, 221, 437, 482, 491",4.0,0.0,Mathematica,183.0,"```mathematica\nSequence[29, 63, 95, 140, 150,...",74.0,0.001,0.0,0,0.0,0.0,0,Execution error,False,50000
7667,"3, 11, 84, 144, 156, 177, 188, 199, 229, 284",4.0,0.0,Mathematica,182.0,"```mathematica\nSequence[3, 11, 84, 144, 156, ...",73.0,0.001,0.0,0,0.0,0.0,0,Execution error,False,50000
7668,"26, 94, 98, 137, 176, 301, 323, 330, 372, 444",4.0,0.0,Mathematica,183.0,"```mathematica\nSequence[26, 94, 98, 137, 176,...",74.0,0.001,0.0,0,0.0,0.0,0,Execution error,False,50000
7669,"39, 81, 88, 210, 215, 378, 416, 430, 439, 490",4.0,0.0,Mathematica,183.0,"```mathematica\nTable[n^3 - n, {n, 4, 13}]\n```",45.0,0.001,0.0,0,0.0,0.0,0,"60, 120, 210, 336, 504, 720, 990, 1320, 1716, ...",False,30

In [289]:
m_df.to_csv("mathematica_evaluation.csv", index=True)

In [3]:
import re


def find_matlab_programs(matlab_code_list):
    # Regular expression pattern
    pattern = r"\b(?:\w+\s*=\s*\[?\d+(?:,\s*\d+)*\]?;|\bdisp\s*\([\w\s,]+\);)+"

    # List to store all matching MATLAB programs
    matching_programs = []

    # Iterate over each MATLAB code string
    for matlab_code in matlab_code_list:
        # Find all matches in the current MATLAB code string
        matches = re.findall(pattern, matlab_code)

        # If matches are found, add the MATLAB code string to the list of matching programs
        if matches:
            matching_programs.append(matlab_code)

    return matching_programs


# Example list of MATLAB code strings
matlab_code_list = [
    "x = [1, 2, 3]; disp(x);",
    "y = [10, 20, 30]; disp(y);",
    "disp([5, 6, 7]);",
    "z = 100; disp(z);",
    "disp('Hello, world!');",
    "disp(1, 2, 3);",
    "disp(x, y);",
]

# Find MATLAB programs containing sequences of numbers and disp instructions
matching_programs = find_matlab_programs(matlab_code_list)

# Print matching MATLAB programs
print("Matching MATLAB programs:")
for program in matching_programs:
    print(program)

Matching MATLAB programs:
x = [1, 2, 3]; disp(x);
y = [10, 20, 30]; disp(y);
z = 100; disp(z);
disp(1, 2, 3);
disp(x, y);

In [113]:
total_df = pd.concat([mathe_df, matlab_df, py_df, arnoldC_df, js_df, cpp_df, r_df])
total_df

,sequence,complexity,length_type,language,q_length,GPT4_answer,a_length,temperature,real_code,print_code,no_code,explanation,no_sense,exe_out,correct_execution,Levenshtein
0,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",1,0,Mathematica,173,"```mathematica\nTable[2 i, {i, 1, 10}]\n```",41,1.000,0,0,0,0,0,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",True,0
1,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",1,0,Mathematica,174,"```mathematica\nTable[3*n, {n, 1, 10}]\n```",41,1.000,0,0,0,0,0,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",True,0
2,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",1,0,Mathematica,175,"```mathematica\nRange[4, 40, 4]\n```",34,1.000,0,0,0,0,0,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",True,0
3,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",1,0,Mathematica,176,"```mathematica\nTable[5*i, {i, 1, 10}]\n```",41,1.000,0,0,0,0,0,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",True,0
4,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",1,0,Mathematica,176,"```mathematica\nTable[6*i, {i, 1, 10}]\n```",41,1.000,0,0,0,0,0,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
585,"187, 218, 260, 295, 301, 314, 379, 410, 452, 469",4,0,R,176,"```r\nseq <- c(187, 218, 260, 295, 301, 314, 3...",78,0.001,0,1,0,0,0,"187, 218, 260, 295, 301, 314, 379, 410, 452, 469",True,0
586,"29, 63, 95, 140, 150, 190, 221, 437, 482, 491",4,0,R,173,"```r\nsequence <- c(29, 63, 95, 140, 150, 190,...",85,0.001,0,1,0,0,0,"29, 63, 95, 140, 150, 190, 221, 437, 482, 491",True,0
587,"3, 11, 84, 144, 156, 177, 188, 199, 229, 284",4,0,R,172,"```r\nsequence <- c(3, 11, 84, 144, 156, 177, ...",84,0.001,0,1,0,0,0,", 3, 11, 84, 144, 156, 177, 188, 199, 229, 284",False,2
588,"26, 94, 98, 137, 176, 301, 323, 330, 372, 444",4,0,R,173,"```r\nsequence <- c(26, 94, 98, 137, 176, 301,...",85,0.001,0,1,0,0,0,"26, 94, 98, 137, 176, 301, 323, 330, 372, 444",True,0
589,"39, 81, 88, 210, 215, 378, 416, 430, 439, 490",4,0,R,173,"```r\nseq <- c(39, 81, 88, 210, 215, 378, 416,...",75,0.001,0,1,0,0,0,"39, 81, 88, 210, 215, 378, 416, 430, 439, 490",True,0

# Python comments

In [60]:
import pandas as pd
import re

# Read the CSV file into a pandas DataFrame
df = pd.read_csv("automatic_python.csv")


# Function to remove comments from Python code
def remove_comments(python_code):
    # Regular expression to remove comments
    return re.sub(r'(?<!["\'])(?<!\\)#.*$', "", python_code, flags=re.MULTILINE)


# Apply the function to the 'GPT4_answer' column
df["GPT4_answer"] = df["GPT4_answer"].apply(remove_comments)

# Save the processed DataFrame to a new CSV file
df.to_csv("automatic_python_no_comments.csv", index=False)

print(
    "Processing completed. The processed file has been saved as 'automatic_python_no_comments.csv'"
)

Processing completed. The processed file has been saved as 'automatic_python_no_comments.csv'

In [61]:
matlab_comments = pd.read_csv("automatic_python.csv")
matlab_no_comments = pd.read_csv("automatic_python_no_comments.csv")

code_with_comments = list(matlab_comments["GPT4_answer"].values)
code_without_comments = list(matlab_no_comments["GPT4_answer"].values)

for i in range(len(code_with_comments)):
    original = code_with_comments[i]
    modified = code_without_comments[i]
    if original != modified:
        print("******************************(", str(i), ")")
        print("original: ", original)
        print("modified: ", modified)

******************************( 312 )
original:  ```python
# Calculate and print the specified sequence
def special_sequence(n):
    primes = []
    i = 2  # First prime number
    while len(primes) < n:
        for p in primes:
            if i % p == 0 or i <= 1:
                break
        else:
            primes.append(i)
        i += 1
    for j in range(n):
        print(primes[j] + 2*j**2)

n = 10  # Number of elements in the sequence
special_sequence(n)
```
modified:  ```python

def special_sequence(n):
    primes = []
    i = 2
    while len(primes) < n:
        for p in primes:
            if i % p == 0 or i <= 1:
                break
        else:
            primes.append(i)
        i += 1
    for j in range(n):
        print(primes[j] + 2*j**2)

n = 10
special_sequence(n)
```
******************************( 321 )
original:  ```python
# Python program to produce the given sequence
sequence = [1, 4, 2, 1, 3, 5, 9, 2, 6, 5]
print(sequence)
```
modified:  ```python

sequence = [1, 4, 2, 1, 3, 5, 9, 2, 6, 5]
print(sequence)
```
******************************( 323 )
original:  ```python
# Python program to produce the sequence 1, 0, 1, 2, 3, 1, 6, 11

# Initialize the sequence list with the given elements
sequence = [1, 0, 1, 2, 3, 1, 6, 11]

# Print each element in the sequence
for number in sequence:
    print(number, end=', ')
```
modified:  ```python



sequence = [1, 0, 1, 2, 3, 1, 6, 11]


for number in sequence:
    print(number, end=', ')
```
******************************( 325 )
original:  ```python
# Sequence generation
n = 8  # Desired sequence length
sequence = []  # Store sequence
i = 2  # Starting number for prime checking

# Function to check if a number is prime
def is_prime(x):
    if x < 2:
        return False
    for n in range(2, int(x**0.5) + 1):
        if x % n == 0:
            return False
    return True

# Generate sequence
while len(sequence) < n:
    if is_prime(i):
        # Bitwise OR the prime number with 2, then append to sequence.
        sequence.append(i | 2)
    i += 1

# Display the sequence
print(sequence)
```
modified:  ```python

n = 8
sequence = []
i = 2


def is_prime(x):
    if x < 2:
        return False
    for n in range(2, int(x**0.5) + 1):
        if x % n == 0:
            return False
    return True


while len(sequence) < n:
    if is_prime(i):

        sequence.append(i | 2)
    i += 1


print(sequence)
```
******************************( 351 )
original:  ```python
# Python 3.x code to produce the specified sequence
sequence = [1, 0, 1, 2, 3, 1, 6, 11]
print(sequence)
```
modified:  ```python

sequence = [1, 0, 1, 2, 3, 1, 6, 11]
print(sequence)
```
******************************( 379 )
original:  ```python
# Python code to produce the sequence 1, 0, 1, 2, 3, 1, 6, 11
sequence = [1, 0]
for i in range(2, 8):
    if i % 2 == 0:
        sequence.append(sequence[i-2] + 1)
    else:
        sequence.append(sequence[i-1] + sequence[i-2])
print(sequence)
```
modified:  ```python

sequence = [1, 0]
for i in range(2, 8):
    if i % 2 == 0:
        sequence.append(sequence[i-2] + 1)
    else:
        sequence.append(sequence[i-1] + sequence[i-2])
print(sequence)
```
******************************( 398 )
original:  ```python
# Python program to produce the specified sequence
sequence = [19, 31, 61, 89, 107, 127, 521, 607, 1279, 2203]

# Printing the sequence
for num in sequence:
    print(num)
```
modified:  ```python

sequence = [19, 31, 61, 89, 107, 127, 521, 607, 1279, 2203]


for num in sequence:
    print(num)
```
******************************( 426 )
original:  ```python
# Python code to produce the specified sequence
sequence = [19, 31, 61, 89, 107, 127, 521, 607, 1279, 2203]
print(sequence)
```
modified:  ```python

sequence = [19, 31, 61, 89, 107, 127, 521, 607, 1279, 2203]
print(sequence)
```
******************************( 440 )
original:  ```python
# Code to produce the given sequence
sequence = [29, 57, 68, 120, 134, 140, 173, 197, 283, 313]
print(sequence)
```
modified:  ```python

sequence = [29, 57, 68, 120, 134, 140, 173, 197, 283, 313]
print(sequence)
```
******************************( 444 )
original:  ```python
# Python code to produce the given sequence
sequence = [62, 98, 130, 154, 290, 315, 324, 385, 408, 447]
print(sequence)
```
modified:  ```python

sequence = [62, 98, 130, 154, 290, 315, 324, 385, 408, 447]
print(sequence)
```
******************************( 449 )
original:  ```python
# Python code to produce the specified sequence
sequence = []

# Since a direct formula or pattern is not provided, hardcoding the values
sequence = [139, 252, 272, 281, 304, 361, 370, 415, 438, 500]

# To display the sequence
print(sequence)
```
modified:  ```python

sequence = []


sequence = [139, 252, 272, 281, 304, 361, 370, 415, 438, 500]


print(sequence)
```
******************************( 457 )
original:  ```python
# Sequence generator
sequence = [16, 119, 121, 123, 135, 139, 285, 311, 409, 412]
print(sequence)
```
modified:  ```python

sequence = [16, 119, 121, 123, 135, 139, 285, 311, 409, 412]
print(sequence)
```
******************************( 459 )
original:  ```python
# Python code to produce the specified sequence
sequence = [12, 36, 96, 119, 171, 213, 221, 232, 363, 451]
for num in sequence:
    print(num)
```
modified:  ```python

sequence = [12, 36, 96, 119, 171, 213, 221, 232, 363, 451]
for num in sequence:
    print(num)
```
******************************( 462 )
original:  ```python
# Python code to produce the specified sequence
sequence = [27, 101, 105, 164, 245, 290, 304, 441, 449, 490]
print(sequence)
```
modified:  ```python

sequence = [27, 101, 105, 164, 245, 290, 304, 441, 449, 490]
print(sequence)
```
******************************( 466 )
original:  ```python
# Python code to print the specified sequence
sequence = [29, 63, 95, 140, 150, 190, 221, 437, 482, 491]
for number in sequence:
    print(number)
```
modified:  ```python

sequence = [29, 63, 95, 140, 150, 190, 221, 437, 482, 491]
for number in sequence:
    print(number)
```
******************************( 470 )
original:  ```python
# Python code to produce the specified sequence
print([29, 57, 68, 120, 134, 140, 173, 197, 283, 313])
```
modified:  ```python

print([29, 57, 68, 120, 134, 140, 173, 197, 283, 313])
```
******************************( 471 )
original:  ```python
# Python code to produce the specified sequence
sequence = [24, 26, 36, 40, 184, 226, 244, 384, 391, 423]
print(sequence)
```
modified:  ```python

sequence = [24, 26, 36, 40, 184, 226, 244, 384, 391, 423]
print(sequence)
```
******************************( 476 )
original:  ```python
# Python program to produce the specified sequence
sequence = [128, 151, 153, 217, 224, 332, 382, 400, 450, 478]
print(sequence)
```
modified:  ```python

sequence = [128, 151, 153, 217, 224, 332, 382, 400, 450, 478]
print(sequence)
```
******************************( 493 )
original:  ```python
# Python code to produce the specified sequence
sequence = [4, 11, 29, 106, 214, 283, 296, 298, 360, 497]

for number in sequence:
    print(number)
```
modified:  ```python

sequence = [4, 11, 29, 106, 214, 283, 296, 298, 360, 497]

for number in sequence:
    print(number)
```
******************************( 497 )
original:  ```python
# Python code to produce the specified sequence
sequence = [3, 11, 84, 144, 156, 177, 188, 199, 229, 284]
print(sequence)
```
modified:  ```python

sequence = [3, 11, 84, 144, 156, 177, 188, 199, 229, 284]
print(sequence)
```
******************************( 499 )
original:  ```python
# Python code to produce the specified sequence
sequence = [39, 81, 88, 210, 215, 378, 416, 430, 439, 490]
print(sequence)
```
modified:  ```python

sequence = [39, 81, 88, 210, 215, 378, 416, 430, 439, 490]
print(sequence)
```
******************************( 501 )
original:  ```python
# Python code to produce the specified sequence
sequence = [24, 26, 36, 40, 184, 226, 244, 384, 391, 423]
print(sequence)
```
modified:  ```python

sequence = [24, 26, 36, 40, 184, 226, 244, 384, 391, 423]
print(sequence)
```
******************************( 505 )
original:  ```python
# Python code to produce the specified sequence
sequence = [2, 42, 66, 102, 153, 195, 201, 252, 306, 396]
print(sequence)
```
modified:  ```python

sequence = [2, 42, 66, 102, 153, 195, 201, 252, 306, 396]
print(sequence)
```
******************************( 521 )
original:  ```python
# Python code to produce the specified sequence
sequence = [7, 42, 147, 201, 213, 248, 310, 332, 436, 479]
print(sequence)
```
modified:  ```python

sequence = [7, 42, 147, 201, 213, 248, 310, 332, 436, 479]
print(sequence)
```
******************************( 522 )
original:  ```python
# Python code to produce the specified sequence
sequence = [27, 101, 105, 164, 245, 290, 304, 441, 449, 490]
print(sequence)
```
modified:  ```python

sequence = [27, 101, 105, 164, 245, 290, 304, 441, 449, 490]
print(sequence)
```
******************************( 535 )
original:  ```python
# Python code to produce the specified sequence
sequence = [2, 42, 66, 102, 153, 195, 201, 252, 306, 396]
print(sequence)
```
modified:  ```python

sequence = [2, 42, 66, 102, 153, 195, 201, 252, 306, 396]
print(sequence)
```
******************************( 562 )
original:  ```python
# Python code to produce the specified sequence
sequence = [90, 203, 212, 235, 270, 324, 342, 352, 371, 417]
print(sequence)
```
modified:  ```python

sequence = [90, 203, 212, 235, 270, 324, 342, 352, 371, 417]
print(sequence)
```

# C++

In [62]:
import pandas as pd
import re

# Read the CSV file into a pandas DataFrame
df = pd.read_csv("Cpp_evaluation.csv")


# Function to remove comments from C++ code
def remove_comments(cpp_code):
    # Regular expression to remove comments
    return re.sub(r"//.*$", "", cpp_code, flags=re.MULTILINE)


# Apply the function to the 'GPT4_answer' column
df["GPT4_answer"] = df["GPT4_answer"].apply(remove_comments)

# Save the processed DataFrame to a new CSV file
df.to_csv("Cpp_evaluation_no_comments.csv", index=False)

print(
    "Processing completed. The processed file has been saved as 'Cpp_evaluation_no_comments.csv'"
)

Processing completed. The processed file has been saved as 'Cpp_evaluation_no_comments.csv'

In [64]:
matlab_comments = pd.read_csv("Cpp_evaluation.csv")
matlab_no_comments = pd.read_csv("Cpp_evaluation_no_comments.csv")

code_with_comments = list(matlab_comments["GPT4_answer"].values)
code_without_comments = list(matlab_no_comments["GPT4_answer"].values)

for i in range(len(code_with_comments)):
    original = code_with_comments[i]
    modified = code_without_comments[i]
    if original != modified:
        print("******************************(", str(i), ")")
        print("original: ", original)
        print("modified: ", modified)

******************************( 197 )
original:  ```cpp
#include <iostream>
using namespace std;

int main() {
    int n = 10; // Number of terms
    for(int i = 1, current = 2; i <= n; i++) {
        cout << current << " ";
        current += i + 2;
    }
    return 0;
}
```
modified:  ```cpp
#include <iostream>
using namespace std;

int main() {
    int n = 10;
    for(int i = 1, current = 2; i <= n; i++) {
        cout << current << " ";
        current += i + 2;
    }
    return 0;
}
```
******************************( 202 )
original:  ```cpp
#include <iostream>

int main() {
    int n = 10; // Number of terms
    for (int i = 1; i <= n; ++i) {
        std::cout << i * i + i - 1 << " ";
    }
    return 0;
}
```
modified:  ```cpp
#include <iostream>

int main() {
    int n = 10;
    for (int i = 1; i <= n; ++i) {
        std::cout << i * i + i - 1 << " ";
    }
    return 0;
}
```
******************************( 217 )
original:  ```cpp
#include <iostream>

int main() {
    int n = 10; // Number of terms
    int sum = 0;
    for(int i = 1; i <= n; i++) {
        sum += i;
        std::cout << sum;
        if(i < n) std::cout << ", ";
    }
    return 0;
}
```
modified:  ```cpp
#include <iostream>

int main() {
    int n = 10;
    int sum = 0;
    for(int i = 1; i <= n; i++) {
        sum += i;
        std::cout << sum;
        if(i < n) std::cout << ", ";
    }
    return 0;
}
```
******************************( 221 )
original:  ```cpp
#include <iostream>
using namespace std;

int main() {
    int n = 10; // Number of terms to generate
    for (int i = 1; i <= n; i++) {
        long long term = 1;
        for (int j = 0; j < i; j++) {
            term *= (4 * i - 2 - j);
            term /= (j + 1);
        }
        term /= i;
        cout << term;
        if (i < n) cout << ", ";
    }
    return 0;
}
```
modified:  ```cpp
#include <iostream>
using namespace std;

int main() {
    int n = 10;
    for (int i = 1; i <= n; i++) {
        long long term = 1;
        for (int j = 0; j < i; j++) {
            term *= (4 * i - 2 - j);
            term /= (j + 1);
        }
        term /= i;
        cout << term;
        if (i < n) cout << ", ";
    }
    return 0;
}
```
******************************( 226 )
original:  ```cpp
#include <iostream>
#include <vector>

// Function to calculate factorial
int factorial(int n) {
    return (n == 0) ? 1 : n * factorial(n - 1);
}

int main() {
    std::vector<int> sequence = {1, 2, 145, 40585};

    for (int num : sequence) {
        std::cout << num << std::endl;
    }

    return 0;
}
```
modified:  ```cpp
#include <iostream>
#include <vector>


int factorial(int n) {
    return (n == 0) ? 1 : n * factorial(n - 1);
}

int main() {
    std::vector<int> sequence = {1, 2, 145, 40585};

    for (int num : sequence) {
        std::cout << num << std::endl;
    }

    return 0;
}
```
******************************( 249 )
original:  ```cpp
#include <iostream>

int main() {
    int n = 10; // Number of sequence elements to generate
    long long a = 0, b = 1, c;
    for(int i = 0; i < n; ++i) {
        if(i == 0) std::cout << a << ", ";
        else if(i == 1) std::cout << b << ", ";
        else {
            c = a + b;
            a = b;
            b = c;
            if(i < 3) std::cout << c * i << ", ";
            else std::cout << c * (i - 1) << (i < n-1 ? ", " : "");
        }
    }
    return 0;
}
```
modified:  ```cpp
#include <iostream>

int main() {
    int n = 10;
    long long a = 0, b = 1, c;
    for(int i = 0; i < n; ++i) {
        if(i == 0) std::cout << a << ", ";
        else if(i == 1) std::cout << b << ", ";
        else {
            c = a + b;
            a = b;
            b = c;
            if(i < 3) std::cout << c * i << ", ";
            else std::cout << c * (i - 1) << (i < n-1 ? ", " : "");
        }
    }
    return 0;
}
```
******************************( 279 )
original:  ```cpp
#include <iostream>

int main() {
    int n = 10; // Number of sequence elements to generate
    long long a = 0, b = 1, c;
    for (int i = 0; i < n; ++i) {
        if (i == 0) {
            std::cout << a << ", ";
        } else if (i == 1) {
            std::cout << b << ", ";
        } else {
            c = a + b;
            a = b;
            b = c;
            if (i < n - 1) {
                std::cout << c * i << ", ";
            } else {
                std::cout << c * i;
            }
        }
    }
    return 0;
}
```
modified:  ```cpp
#include <iostream>

int main() {
    int n = 10;
    long long a = 0, b = 1, c;
    for (int i = 0; i < n; ++i) {
        if (i == 0) {
            std::cout << a << ", ";
        } else if (i == 1) {
            std::cout << b << ", ";
        } else {
            c = a + b;
            a = b;
            b = c;
            if (i < n - 1) {
                std::cout << c * i << ", ";
            } else {
                std::cout << c * i;
            }
        }
    }
    return 0;
}
```
******************************( 312 )
original:  ```cpp
#include <iostream>

int main() {
    int primes[10] = {2, 17, 19, 23, 29, 41, 47, 31, 37, 29};
    int sum = 3; // Starting number

    for (int i = 0; i < 10; ++i) {
        std::cout << sum << ", ";
        sum += primes[i] * 2;
    }

    return 0;
}
```
modified:  ```cpp
#include <iostream>

int main() {
    int primes[10] = {2, 17, 19, 23, 29, 41, 47, 31, 37, 29};
    int sum = 3;

    for (int i = 0; i < 10; ++i) {
        std::cout << sum << ", ";
        sum += primes[i] * 2;
    }

    return 0;
}
```
******************************( 313 )
original:  ```cpp
#include <iostream>
#include <vector>

int factorial(int n) {
    if(n == 0 || n == 1) return 1;
    else return n * factorial(n - 1);
}

bool isCurious(int n) {
    int sum = 0, original = n;
    while(n > 0) {
        int digit = n % 10;
        sum += factorial(digit);
        n /= 10;
    }
    return sum == original;
}

int main() {
    for(int i = 1; i <= 40585; ++i) { // Upper bound given by problem
        if(isCurious(i)) std::cout << i << ", ";
    }
}
```
modified:  ```cpp
#include <iostream>
#include <vector>

int factorial(int n) {
    if(n == 0 || n == 1) return 1;
    else return n * factorial(n - 1);
}

bool isCurious(int n) {
    int sum = 0, original = n;
    while(n > 0) {
        int digit = n % 10;
        sum += factorial(digit);
        n /= 10;
    }
    return sum == original;
}

int main() {
    for(int i = 1; i <= 40585; ++i) {
        if(isCurious(i)) std::cout << i << ", ";
    }
}
```
******************************( 324 )
original:  ```cpp
#include <iostream>
using namespace std;

int main() {
    int n = 8; // size of sequence
    int a = 1;
    for(int i = 0; i < n; i++) {
        if(i < 3) cout << a << ", ";
        else {
            a = (a * 2) + 1;
            cout << a;
            if(i < n-1) cout << ", ";
        }
    }
    return 0;
}
```
modified:  ```cpp
#include <iostream>
using namespace std;

int main() {
    int n = 8;
    int a = 1;
    for(int i = 0; i < n; i++) {
        if(i < 3) cout << a << ", ";
        else {
            a = (a * 2) + 1;
            cout << a;
            if(i < n-1) cout << ", ";
        }
    }
    return 0;
}
```
******************************( 325 )
original:  ```cpp
#include <iostream>
#include <vector>

bool isPrime(int n) {
    if(n <= 1) return false;
    if(n == 2) return true;
    if(n % 2 == 0) return false;
    for(int i = 3; i * i <= n; i += 2) {
        if(n % i == 0) return false;
    }
    return true;
}

bool satisfiesCondition(int n) {
    return isPrime(n) && isPrime(n + 2);
}

int main() {
    int count = 0;
    int number = 3;
    while(count < 8) {
        if(satisfiesCondition(number)) {
            std::cout << number << " ";
            count++;
            number += 2; // skip even numbers
        } else {
            number++;
        }
    }
    return 0;
}
```
modified:  ```cpp
#include <iostream>
#include <vector>

bool isPrime(int n) {
    if(n <= 1) return false;
    if(n == 2) return true;
    if(n % 2 == 0) return false;
    for(int i = 3; i * i <= n; i += 2) {
        if(n % i == 0) return false;
    }
    return true;
}

bool satisfiesCondition(int n) {
    return isPrime(n) && isPrime(n + 2);
}

int main() {
    int count = 0;
    int number = 3;
    while(count < 8) {
        if(satisfiesCondition(number)) {
            std::cout << number << " ";
            count++;
            number += 2;
        } else {
            number++;
        }
    }
    return 0;
}
```
******************************( 380 )
original:  ```cpp
#include <iostream>

int main() {
    int n = 8; // Number of terms in the sequence
    for(int i = 0; i < n; i++) {
        if(i < 3) {
            std::cout << "1, ";
        } else {
            std::cout << (1 << i) - 1;
            if(i < n - 1) std::cout << ", ";
        }
    }
    return 0;
}
```
modified:  ```cpp
#include <iostream>

int main() {
    int n = 8;
    for(int i = 0; i < n; i++) {
        if(i < 3) {
            std::cout << "1, ";
        } else {
            std::cout << (1 << i) - 1;
            if(i < n - 1) std::cout << ", ";
        }
    }
    return 0;
}
```
******************************( 383 )
original:  ```cpp
#include <iostream>

int main() {
    int n = 8; // Length of the sequence
    int a = 1, b = 0, c = 1;
    int next;

    for(int i = 0; i < n; i++) {
        if(i == 0) {
            std::cout << a << " ";
        } else if(i == 1) {
            std::cout << b << " ";
        } else if(i == 2) {
            std::cout << c << " ";
        } else {
            next = a + b + c;
            std::cout << next << " ";
            a = b;
            b = c;
            c = next;
        }
    }
    return 0;
}
```
modified:  ```cpp
#include <iostream>

int main() {
    int n = 8;
    int a = 1, b = 0, c = 1;
    int next;

    for(int i = 0; i < n; i++) {
        if(i == 0) {
            std::cout << a << " ";
        } else if(i == 1) {
            std::cout << b << " ";
        } else if(i == 2) {
            std::cout << c << " ";
        } else {
            next = a + b + c;
            std::cout << next << " ";
            a = b;
            b = c;
            c = next;
        }
    }
    return 0;
}
```
******************************( 408 )
original:  ```cpp
#include <iostream>

int main() {
    int n = 8; // Number of elements in the sequence
    for(int i = 0; i < n; i++) {
        if(i < 3) {
            std::cout << 1;
        } else {
            std::cout << (1 << i) - 1;
        }
        if(i < n - 1) std::cout << ", ";
    }
    return 0;
}
```
modified:  ```cpp
#include <iostream>

int main() {
    int n = 8;
    for(int i = 0; i < n; i++) {
        if(i < 3) {
            std::cout << 1;
        } else {
            std::cout << (1 << i) - 1;
        }
        if(i < n - 1) std::cout << ", ";
    }
    return 0;
}
```
******************************( 411 )
original:  ```cpp
#include <iostream>

int main() {
    int n = 8; // Sequence length
    int a = 1, b = 0, c = 1, d; // Initial values
    std::cout << a << ", " << b << ", " << c; // Print initial values
    for(int i = 3; i < n; i++) {
        d = a + b + c; // Calculate next value
        std::cout << ", " << d; // Print next value
        a = b; // Shift values for the next iteration
        b = c;
        c = d;
    }
    return 0;
}
```
modified:  ```cpp
#include <iostream>

int main() {
    int n = 8;
    int a = 1, b = 0, c = 1, d;
    std::cout << a << ", " << b << ", " << c;
    for(int i = 3; i < n; i++) {
        d = a + b + c;
        std::cout << ", " << d;
        a = b;
        b = c;
        c = d;
    }
    return 0;
}
```
******************************( 436 )
original:  ```cpp
#include <iostream>

int main() {
    int n = 8; // Number of elements in the sequence
    for(int i = 0; i < n; i++) {
        if(i < 3) {
            std::cout << 1;
        } else {
            std::cout << (1 << i) - 1;
        }
        if(i < n - 1) std::cout << ", ";
    }
    return 0;
}
```
modified:  ```cpp
#include <iostream>

int main() {
    int n = 8;
    for(int i = 0; i < n; i++) {
        if(i < 3) {
            std::cout << 1;
        } else {
            std::cout << (1 << i) - 1;
        }
        if(i < n - 1) std::cout << ", ";
    }
    return 0;
}
```
******************************( 439 )
original:  ```cpp
#include <iostream>

int main() {
    int n = 8; // Length of the sequence
    int sequence[n] = {1, 0, 1, 1}; // Initial values

    for(int i = 4; i < n; i++) {
        sequence[i] = sequence[i-1] + sequence[i-2] + sequence[i-3] + sequence[i-4];
    }

    for(int i = 0; i < n; i++) {
        std::cout << sequence[i] << " ";
    }

    return 0;
}
```
modified:  ```cpp
#include <iostream>

int main() {
    int n = 8;
    int sequence[n] = {1, 0, 1, 1};

    for(int i = 4; i < n; i++) {
        sequence[i] = sequence[i-1] + sequence[i-2] + sequence[i-3] + sequence[i-4];
    }

    for(int i = 0; i < n; i++) {
        std::cout << sequence[i] << " ";
    }

    return 0;
}
```

# JAVA

In [65]:
import pandas as pd
import re

# Read the CSV file into a pandas DataFrame
df = pd.read_csv("javascript_evaluation.csv")


# Function to remove comments from JavaScript code
def remove_comments(js_code):
    # Regular expression to remove comments
    return re.sub(r"//.*$", "", js_code, flags=re.MULTILINE)


# Apply the function to the 'GPT4_answer' column
df["GPT4_answer"] = df["GPT4_answer"].apply(remove_comments)

# Save the processed DataFrame to a new CSV file
df.to_csv("javascript_evaluation_no_comments.csv", index=False)

print(
    "Processing completed. The processed file has been saved as 'javascript_evaluation_no_comments.csv'"
)

Processing completed. The processed file has been saved as 'javascript_evaluation_no_comments.csv'

In [66]:
matlab_comments = pd.read_csv("javascript_evaluation.csv")
matlab_no_comments = pd.read_csv("javascript_evaluation_no_comments.csv")

code_with_comments = list(matlab_comments["GPT4_answer"].values)
code_without_comments = list(matlab_no_comments["GPT4_answer"].values)

for i in range(len(code_with_comments)):
    original = code_with_comments[i]
    modified = code_without_comments[i]
    if original != modified:
        print("******************************(", str(i), ")")
        print("original: ", original)
        print("modified: ", modified)

******************************( 325 )
original:  ```javascript
function getNextPrime(n) {
    while (true) {
        n += 1;
        let isPrime = true;
        for (let i = 2; i * i <= n; i++) {
            if (n % i === 0) {
                isPrime = false;
                break;
            }
        }
        if (isPrime) return n;
    }
}

function generateSequence(length) {
    let sequence = [];
    let number = 2; // Start searching for primes from 3
    for (let i = 0; i < length; i++) {
        number = getNextPrime(number);
        if (i % 2 === 0) { // Add only for even indices
            sequence.push(number);
            number *= 2; // Double the number to ensure the next number added is odd
        }
    }
    return sequence;
}

console.log(generateSequence(8));
```
modified:  ```javascript
function getNextPrime(n) {
    while (true) {
        n += 1;
        let isPrime = true;
        for (let i = 2; i * i <= n; i++) {
            if (n % i === 0) {
                isPrime = false;
                break;
            }
        }
        if (isPrime) return n;
    }
}

function generateSequence(length) {
    let sequence = [];
    let number = 2;
    for (let i = 0; i < length; i++) {
        number = getNextPrime(number);
        if (i % 2 === 0) {
            sequence.push(number);
            number *= 2;
        }
    }
    return sequence;
}

console.log(generateSequence(8));
```
******************************( 456 )
original:  ```javascript
let sequence = [];
let current = 34;
sequence.push(current);

while(sequence.length < 10) {
    if(sequence.length % 2 === 0) {
        current += 58;
    } else {
        current += 72;
    }
    sequence.push(current);

    // Custom adjustments to match the sequence exactly
    if(sequence.length === 4) {
        current++; // To get 165 instead of 164
    } else if(sequence.length == 5) {
        current += 44; // Adjusting for the sequence
    }
}

console.log(sequence);
```
modified:  ```javascript
let sequence = [];
let current = 34;
sequence.push(current);

while(sequence.length < 10) {
    if(sequence.length % 2 === 0) {
        current += 58;
    } else {
        current += 72;
    }
    sequence.push(current);


    if(sequence.length === 4) {
        current++;
    } else if(sequence.length == 5) {
        current += 44;
    }
}

console.log(sequence);
```
******************************( 463 )
original:  ```javascript
let sequence = [];
let value = 4;
sequence.push(value); // 4
value *= 2 + 3; // 11
sequence.push(value);
value *= 2 + 1; // 29
sequence.push(value);
value *= 3 + 4; // 106
sequence.push(value);
value = (value / 2) * 4; // 214
sequence.push(value);
value += 69; // 283
sequence.push(value);
value += 13; // 296
sequence.push(value);
value += 2; // 298
sequence.push(value);
value += 62; // 360
sequence.push(value);
value += 137; // 497
sequence.push(value);
console.log(sequence);
```
modified:  ```javascript
let sequence = [];
let value = 4;
sequence.push(value);
value *= 2 + 3;
sequence.push(value);
value *= 2 + 1;
sequence.push(value);
value *= 3 + 4;
sequence.push(value);
value = (value / 2) * 4;
sequence.push(value);
value += 69;
sequence.push(value);
value += 13;
sequence.push(value);
value += 2;
sequence.push(value);
value += 62;
sequence.push(value);
value += 137;
sequence.push(value);
console.log(sequence);
```

# R

In [67]:
import pandas as pd
import re

# Read the CSV file into a pandas DataFrame
df = pd.read_csv("R_evaluation.csv")


# Function to remove comments from R script
def remove_comments(r_code):
    # Regular expression to remove comments
    return re.sub(r"#.*$", "", r_code, flags=re.MULTILINE)


# Apply the function to the 'GPT4_answer' column
df["GPT4_answer"] = df["GPT4_answer"].apply(remove_comments)

# Save the processed DataFrame to a new CSV file
df.to_csv("R_evaluation_no_comments.csv", index=False)

print(
    "Processing completed. The processed file has been saved as 'R_evaluation_no_comments.csv'"
)

Processing completed. The processed file has been saved as 'R_evaluation_no_comments.csv'

In [68]:
matlab_comments = pd.read_csv("R_evaluation.csv")
matlab_no_comments = pd.read_csv("R_evaluation_no_comments.csv")

code_with_comments = list(matlab_comments["GPT4_answer"].values)
code_without_comments = list(matlab_no_comments["GPT4_answer"].values)

for i in range(len(code_with_comments)):
    original = code_with_comments[i]
    modified = code_without_comments[i]
    if original != modified:
        print("******************************(", str(i), ")")
        print("original: ", original)
        print("modified: ", modified)

******************************( 158 )
original:  ```r
# R code to produce the specific sequence
n <- 10
sequence <- numeric(n)
sequence[1:3] <- c(2, 1, 3)

for(i in 4:n){
  sequence[i] <- sequence[i-1] + sequence[i-2] + sequence[i-3]
}

print(sequence)
```
modified:  ```r

n <- 10
sequence <- numeric(n)
sequence[1:3] <- c(2, 1, 3)

for(i in 4:n){
  sequence[i] <- sequence[i-1] + sequence[i-2] + sequence[i-3]
}

print(sequence)
```
******************************( 176 )
original:  ```r
produce_sequence <- function(n) {
  curr_seq <- "1"
  for (i in 2:n) {
    curr_seq <- gsub("((.)\\2*)", "\\1 ", curr_seq)
    curr_seq <- gsub(" ", "", sprintf("%s%s ", nchar(strsplit(curr_seq, " ")[[1]]), unlist(strsplit(curr_seq, " ")[[1]]))))
  }
  return(curr_seq)
}

# Producing the sequence
n <- 5
sequence <- character(n)
for (i in 1:n) {
  sequence[i] <- produce_sequence(i)
}

print(sequence)
```
modified:  ```r
produce_sequence <- function(n) {
  curr_seq <- "1"
  for (i in 2:n) {
    curr_seq <- gsub("((.)\\2*)", "\\1 ", curr_seq)
    curr_seq <- gsub(" ", "", sprintf("%s%s ", nchar(strsplit(curr_seq, " ")[[1]]), unlist(strsplit(curr_seq, " ")[[1]]))))
  }
  return(curr_seq)
}


n <- 5
sequence <- character(n)
for (i in 1:n) {
  sequence[i] <- produce_sequence(i)
}

print(sequence)
```
******************************( 260 )
original:  ```r
# R code to produce the specified sequence
sequence <- c(1, 2, 4, 8, 16, 23, 28, 38, 58, 89)
print(sequence)
```
modified:  ```r

sequence <- c(1, 2, 4, 8, 16, 23, 28, 38, 58, 89)
print(sequence)
```
******************************( 311 )
original:  ```r
n <- 10 # length of sequence
sequence <- integer(n)
sequence[1:2] <- 0

for (i in 3:n) {
  if (i == 3) {
    sequence[i] <- 2
  } else {
    sequence[i] <- sequence[i - 1] + sequence[i - 2] + i - 2
  }
}

print(sequence)
```
modified:  ```r
n <- 10
sequence <- integer(n)
sequence[1:2] <- 0

for (i in 3:n) {
  if (i == 3) {
    sequence[i] <- 2
  } else {
    sequence[i] <- sequence[i - 1] + sequence[i - 2] + i - 2
  }
}

print(sequence)
```
******************************( 320 )
original:  ```r
primes <- function(n) {
  if (n >= 1) {
    primes_vec <- 2:10000 # Generating a large vector to ensure we cover enough primes
    p <- 2:which(primes_vec == max(primes_vec))
    for (i in primes_vec) {
      p <- p[p == i | p %% i != 0]
      if (i >= sqrt(max(primes_vec))) break
    }
    return(p[1:n])
  } else {
    return(integer(0)) # Return an empty integer vector if n < 1
  }
}
primes(10)
```
modified:  ```r
primes <- function(n) {
  if (n >= 1) {
    primes_vec <- 2:10000
    p <- 2:which(primes_vec == max(primes_vec))
    for (i in primes_vec) {
      p <- p[p == i | p %% i != 0]
      if (i >= sqrt(max(primes_vec))) break
    }
    return(p[1:n])
  } else {
    return(integer(0))
  }
}
primes(10)
```
******************************( 340 )
original:  ```r
n <- 10  # Number of terms
a <- numeric(n)
a[1] <- 3
for (i in 2:n) {
  a[i] <- a[i-1] + 2*i^2 + 30
}
print(a)
```
modified:  ```r
n <- 10
a <- numeric(n)
a[1] <- 3
for (i in 2:n) {
  a[i] <- a[i-1] + 2*i^2 + 30
}
print(a)
```