In [30]:
import pandas as pd
import copy

In [8]:
OIA_ds = pd.read_csv("data_no_small_seqs.csv")
OIA_ds

,sequence,complexity,length_type,language,q_length,answer,a_length,temperature,real_code,print_code,...,no_sense,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,"Complexity: 1[ 2, 4, 6, 8, 10, 12, 14, 16, 18, 2]",1.0,0.0,Brainfuck,171.0,```brainfuck\n++++++++++[>+++++>++++<<-]>[>.+<...,56.0,1.000,0.0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Complexity: 1[ 3, 6, 9, 12, 15, 18, 21, 24, 27...",1.0,0.0,Brainfuck,172.0,```brainfuck\n++++++++++[>+++++<-]>[<+++++>-]+...,116.0,1.000,0.0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Complexity: 1[ 4, 8, 12, 16, 20, 24, 28, 32, 3...",1.0,0.0,Brainfuck,173.0,```brainfuck\n++++++++[->++++<]>[.>+++++>+++++...,139.0,1.000,0.0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Complexity: 1[ 5, 10, 15, 20, 25, 30, 35, 40, ...",1.0,0.0,Brainfuck,174.0,```brainfuck\n+++++>+>+++>++++>+++++>++++++>++...,316.0,1.000,0.0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Complexity: 1[ 6, 12, 18, 24, 30, 36, 42, 48, ...",1.0,0.0,Brainfuck,174.0,```brainfuck\n++++++++++[>+++++++<-]>[<++++++>...,170.0,1.000,0.0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26008,"Complexity: 3[ 1, 1, 1, 3, 7, 15, 31, 6]",3.0,0.0,TrollScript,164.0,```\n++++++++[>++++++++<-]>[>+>+>+<<<-]>>>++++...,85.0,0.001,0.0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26009,"Complexity: 3[ 3, 5, 11, 17, 31, 41, 59, 6]",3.0,0.0,TrollScript,167.0,```\ntroooolololoolooloolooloolooloolooloolool...,1812.0,0.001,0.0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26010,"Complexity: 3[ 1, 2, 3, 4, 6, 8, 11, 1]",3.0,0.0,TrollScript,163.0,```trollscript\noooOoOoOoOoOoOoOoOoOoOoOoOoOoO...,1218.0,0.001,0.0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26011,"Complexity: 3[ 1, 0, 1, 1, 2, 3, 6, 1]",3.0,0.0,TrollScript,162.0,```\ntro\nooo\nolo\nllo\nooo\nllo\nooo\nllo\no...,6556.0,0.001,0.0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26012,"Complexity: 3[ 5, 13, 56]",3.0,0.0,TrollScript,149.0,```\ntro\nooo\nooo\nooo\nooo\nrll\nooo\nooo\no...,2424.0,0.001,0.0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
all_seq_definitions = OIA_ds['sequence'].unique()
len(all_seq_definitions)

1622

In [22]:
all_seq_definitions[8]

'Complexity: 1[ 10, 20, 30, 40, 50, 60, 70, 80, 90, 10]'

In [ ]:
def create_short_length_test_pool(language_name: str):
    short_seq_prompts_level_1 = [
        
    ]
    short_seq_prompts_level_2 = [
        
    ]
    short_seq_prompts_level_3 = [
        
    ]

    short_seq_prompts_random = [
        
    ]

In [25]:
def sequences_definitons():
    short_seq_prompts_level_1 = [
        "1, 2, 3, 4, 5, 6, 7, 8, 9",
        "0, 2, 4, 6, 8, 10, 12",
        "1, 3, 5, 7, 9, 11, 13",
        "101, 103, 105, 107, 109",
        "2, 3, 5, 7, 11, 13, 17, 19, 23",
        "10, 20 ,30 ,40 ,50 ,60",
        "4, 8, 12, 16, 20, 24, 28, 32",
        "3, 6, 9, 12, 15, 18, 21",
        "1, 2, 3",
        "1, 2, 3, 4, 5",
        "2, 4, 6, 8, 10, 12, 14, 16, 18, 20", 
        "3, 6, 9, 12, 15, 18, 21, 24, 27, 30",
        "4, 8, 12, 16, 20, 24, 28, 32, 36, 40",
        "5, 10, 15, 20, 25, 30, 35, 40, 45, 50",
        "6, 12, 18, 24, 30, 36, 42, 48, 54, 60",
        "7, 14, 21, 28, 35, 42, 49, 56, 63, 70",
        "8, 16, 24, 32, 40, 48, 56, 64, 72, 80",
        "9, 18, 27, 36, 45, 54, 63, 72, 81, 90",
        "10, 20, 30, 40, 50, 60, 70, 80, 90, 100",
        "1, 3, 5, 7, 9, 11, 13, 15, 17, 19",
        "2, 4, 6, 8, 10, 12, 14, 16, 18, 20",
        "11, 12, 13, 14, 15, 16, 17, 18, 19, 20",
        "21, 22, 23, 24, 25, 26, 27, 28, 29, 30",
        "31, 32, 33, 34, 35, 36, 37, 38, 39, 40",
        "41, 42, 43, 44, 45, 46, 47, 48, 49, 50",
        "51, 52, 53, 54, 55, 56, 57, 58, 59, 60",
        "61, 62, 63, 64, 65, 66, 67, 68, 69, 70",
        "71, 72, 73, 74, 75, 76, 77, 78, 79, 80",
        "81, 82, 83, 84, 85, 86, 87, 88, 89, 90",
        "91, 92, 93, 94, 95, 96, 97, 98, 99, 100",
        "101, 102, 103, 104, 105, 106, 107, 108, 109, 110",
        "111, 112, 113, 114, 115, 116, 117, 118, 119, 120",
        "121, 122, 123, 124, 125, 126, 127, 128, 129, 130",
        "131, 132, 133, 134, 135, 136, 137, 138, 139, 140",
        "141, 142, 143, 144, 145, 146, 147, 148, 149, 150",
        "151, 152, 153, 154, 155, 156, 157, 158, 159, 160",
        "161, 162, 163, 164, 165, 166, 167, 168, 169, 170",
        "171, 172, 173, 174, 175, 176, 177, 178, 179, 180",
        "181, 182, 183, 184, 185, 186, 187, 188, 189, 190",
        "191, 192, 193, 194, 195, 196, 197, 198, 199, 200",
    ]
    
    short_seq_prompts_level_2 = [
        "0, 1, 1, 2, 3, 5, 8, 13",
        "0, 6, 9, 3, 1, 4, 7",
        "0, 0, 0, 0, 0, 0",
        "0, 1, 2, 4, 8, 16",
        "1, 2, 4, 7, 11, 16, 22, 29",
        "1, 1, 1, 2, 3, 4, 6, 9",
        "30, 42, 66, 70, 78, 102",
        "0, 1, 4, 9, 16, 25, 36",
        "0, 1, 8, 27, 64, 125, 216, 343, 512",
        "4, 6, 9, 10, 14, 15, 21, 22, 25, 26",
        "2, 3, 5, 7, 11, 13, 17, 19, 23, 29",
        "1, 1, 2, 3, 5, 8, 13, 21, 34, 55",
        "1, 2, 4, 8, 16, 32, 64, 128, 256, 512",
        "1, 3, 9, 27, 81, 243, 729, 2187, 6561, 19683",
        "1, 4, 9, 16, 25, 36, 49, 64, 81, 100",
        "1, 8, 27, 64, 125, 216, 343, 512, 729, 1000",
        "1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880",
        "1, 3, 6, 10, 15, 21, 28, 36, 45, 55",
        "2, 1, 3, 4, 7, 11, 18, 29, 47, 76",
        "0, 1, 2, 5, 12, 29, 70, 169, 408, 985",
        "1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000",
        "1, 2, 6, 20, 70, 252, 924, 3432, 12870, 48620",
        "2, 3, 5, 7, 11, 13, 17, 19, 23, 29",
        "4, 6, 9, 10, 14, 15, 21, 22, 25, 26",
        "1, 10, 11, 100, 101, 110, 111, 1000, 1001, 1010",
        "0, 1, 81, 512, 2401, 4913, 5832, 17576, 19683, 234256",
        "1, 2, 145, 40585",
        "2, 5, 12, 20, 29, 39, 50, 62, 75, 89",
        "1, 8, 10, 18, 19, 100, 101, 108, 109, 110",
        "3, 7, 31, 127, 2047, 8191, 131071, 524287, 8388607, 536870911",
        "1, 2, 4, 8, 16, 23, 28, 38, 58, 89",
        "1, 2, 4, 8, 15, 26, 42, 64, 93, 129",
        "1, 5, 12, 22, 35, 51, 70, 92, 117, 145",
        "0, 1, 1, 2, 1, 2, 2, 3, 1, 3",
        "1, 2, 5, 15, 52, 203, 877, 4140, 21147, 115975",
        "2, 3, 5, 7, 11, 13, 17, 19, 23, 29",
        "1, 11, 21, 1211, 111221",
        "2, 3, 5, 7, 11, 13, 17, 19, 23, 29",
        "1, 2, 4, 8, 16, 32, 64, 128, 256, 512",
        "1, 3, 7, 15, 31, 63, 127, 255, 511, 1023",
    ]
    
    short_seq_prompts_level_3 = [
        "3, 1, 4 ,1 ,5 ,9 ,2 ,6 , 5",
        "1, 1, 2, 2, 4, 2, 6, 4, 6, 4, 10",
        "1, 6, 1, 8, 0, 3, 3, 9, 8, 8, 7",
        "1, 1, 4, 9, 4, 2, 0, 4, 4, 8, 5",
        "2, 0, 9, 4, 5, 5, 1, 4, 8, 1, 5",
        "1, 11, 21, 1211, 111221, 312211, 13112221, 1113213211",
        "2, 3, 5, 11, 23, 29, 41, 53, 83, 89, 113, 131",
        "1, 7, 10, 13, 19, 23, 28, 31, 32, 44",
        "0, 1, 4, 10, 20, 35, 56, 84, 120, 165",
        "1, 2, 5, 13, 29, 34, 89, 169, 194",
        "1, 4, 9, 16, 25, 36, 49, 64, 81, 100",
        "1, 8, 27, 64, 125, 216, 343, 512, 729, 1000",
        "2, 1, 2, 1, 2, 2, 1, 2, 2, 2",
        "1, 2, 2, 3, 3, 4, 4, 4, 5, 5",
        "2, 4, 8, 16, 32, 64, 128, 256, 512, 1024",
        "2, 5, 12, 20, 29, 39, 50, 62, 75, 89",
        "7, 11, 13, 17, 19, 23, 29, 31, 37, 41",
        "1, 11, 111, 1111, 11111, 111111, 1111111, 11111111, 111111111, 1111111111",
        "31, 331, 3331, 33331, 333331, 3333331, 33333331, 333333331",
        "1, 3, 7, 13, 21, 31, 43, 57, 73, 91",
        "6, 28, 496, 8128, 130816, 2096128",
        "0, 0, 2, 3, 5, 7, 11, 15, 22, 30",
        "3, 37, 67, 101, 137, 199, 269, 307, 353, 389",
        "1, 2, 145, 40585",
        "19, 31, 61, 89, 107, 127, 521, 607, 1279, 2203",
        "2, 3, 7, 42, 1806, 3263442",
        "2, 3, 5, 7, 11, 13, 17, 19, 23, 29",
        "1, 8, 10, 18, 19, 100, 101, 108, 109, 110",
        "0, 1, 1, 2, 1, 2, 2, 3, 1, 3",
        "0, 1, 1, 2, 2, 4, 2, 6, 4, 6",
        "2, 3, 5, 7, 11, 13, 17, 19, 23, 29",
        "1, 4, 2, 1, 3, 5, 9, 2, 6, 5",
        "1, 7, 3, 2, 0, 5, 0, 7, 9, 8",
        "1, 0, 1, 2, 3, 1, 6, 11",
        "1, 1, 1, 3, 7, 15, 31, 63",
        "3, 5, 11, 17, 31, 41, 59, 67",
        "1, 2, 3, 4, 6, 8, 11, 13",
        "1, 0, 1, 1, 2, 3, 6, 11",
        "1093, 3511",
        "5, 13, 563",
    ]
    short_seq_prompts_random = [
        "2, 6, 8, 5, 0, 3, 7, 4, 5, 6, 7, 8, 9, 0",
        "62, 76, 58, 75, 90, 33, 77, 94, 65, 56, 27",
        "6, 7, 27, 58, 544, 695, 578, 4726, 8878, 12472, 89098",
        "29, 57, 68, 120, 134, 140, 173, 197, 283, 313",
        "24, 26, 36, 40, 184, 226, 244, 384, 391, 423",
        "90, 203, 212, 235, 270, 324, 342, 352, 371, 417",
        "20, 48, 95, 234, 282, 296, 352, 402, 428, 481",
        "62, 98, 130, 154, 290, 315, 324, 385, 408, 447",
        "2, 42, 66, 102, 153, 195, 201, 252, 306, 396",
        "128, 151, 153, 217, 224, 332, 382, 400, 450, 478",
        "26, 50, 114, 148, 160, 170, 274, 347, 432, 497",
        "48, 94, 176, 177, 219, 276, 282, 283, 459, 488",
        "139, 252, 272, 281, 304, 361, 370, 415, 438, 500",
        "15, 95, 115, 195, 240, 318, 326, 350, 432, 450",
        "134, 224, 293, 378, 379, 395, 434, 451, 482, 496",
        "23, 93, 142, 145, 245, 266, 296, 317, 428, 495",
        "18, 39, 71, 194, 197, 219, 263, 270, 416, 473",
        "9, 84, 144, 170, 325, 393, 401, 405, 435, 497",
        "26, 40, 202, 267, 282, 340, 359, 408, 410, 495",
        "34, 92, 164, 165, 209, 296, 414, 456, 467, 494",
        "16, 119, 121, 123, 135, 139, 285, 311, 409, 412",
        "8, 11, 12, 103, 116, 196, 247, 254, 389, 427",
        "12, 36, 96, 119, 171, 213, 221, 232, 363, 451",
        "38, 91, 142, 197, 215, 313, 316, 319, 423, 466",
        "7, 42, 147, 201, 213, 248, 310, 332, 436, 479",
        "27, 101, 105, 164, 245, 290, 304, 441, 449, 490",
        "4, 11, 29, 106, 214, 283, 296, 298, 360, 497",
        "72, 106, 139, 165, 171, 192, 199, 429, 453, 477",
        "187, 218, 260, 295, 301, 314, 379, 410, 452, 469",
        "29, 63, 95, 140, 150, 190, 221, 437, 482, 491",
        "3, 11, 84, 144, 156, 177, 188, 199, 229, 284",
        "26, 94, 98, 137, 176, 301, 323, 330, 372, 444",
        "39, 81, 88, 210, 215, 378, 416, 430, 439, 490",

    ]
    
    return [short_seq_prompts_level_1, short_seq_prompts_level_2, short_seq_prompts_level_3, short_seq_prompts_random]

In [37]:
seq_1, seq_2, seq_3, seq_4 = sequences_definitons()

In [27]:


# Importing the libraries
import pandas as pd
import numpy as np
 
# data
Student = {
    'Name': ['John', 'Jay', 'sachin', 'Geetha', 'Amutha', 'ganesh'],
    'gender': ['male', 'male', 'male', 'female', 'female', 'male'],
    'math score': [50, 100, 70, 80, 75, 40],
    'test preparation': ['none', 'completed', 'none', 'completed',
                         'completed', 'none'],
}
 
# creating a Dataframe object
df = pd.DataFrame(Student)
 
df

     Name  gender  math score test preparation
0    John    male          50             none
1     Jay    male         100        completed
2  sachin    male          70             none
3  Geetha  female          80        completed
4  Amutha  female          75        completed
5  ganesh    male          40             none

In [28]:
# Applying the condition
df.loc[df["gender"] == "male", "gender"] = 1
print(df)

     Name  gender  math score test preparation
0    John       1          50             none
1     Jay       1         100        completed
2  sachin       1          70             none
3  Geetha  female          80        completed
4  Amutha  female          75        completed
5  ganesh       1          40             none

In [29]:
OIA_ds

,sequence,complexity,length_type,language,q_length,answer,a_length,temperature,real_code,print_code,...,no_sense,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,"Complexity: 1[ 2, 4, 6, 8, 10, 12, 14, 16, 18, 2]",1.0,0.0,Brainfuck,171.0,```brainfuck\n++++++++++[>+++++>++++<<-]>[>.+<...,56.0,1.000,0.0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Complexity: 1[ 3, 6, 9, 12, 15, 18, 21, 24, 27...",1.0,0.0,Brainfuck,172.0,```brainfuck\n++++++++++[>+++++<-]>[<+++++>-]+...,116.0,1.000,0.0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Complexity: 1[ 4, 8, 12, 16, 20, 24, 28, 32, 3...",1.0,0.0,Brainfuck,173.0,```brainfuck\n++++++++[->++++<]>[.>+++++>+++++...,139.0,1.000,0.0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Complexity: 1[ 5, 10, 15, 20, 25, 30, 35, 40, ...",1.0,0.0,Brainfuck,174.0,```brainfuck\n+++++>+>+++>++++>+++++>++++++>++...,316.0,1.000,0.0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Complexity: 1[ 6, 12, 18, 24, 30, 36, 42, 48, ...",1.0,0.0,Brainfuck,174.0,```brainfuck\n++++++++++[>+++++++<-]>[<++++++>...,170.0,1.000,0.0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26008,"Complexity: 3[ 1, 1, 1, 3, 7, 15, 31, 6]",3.0,0.0,TrollScript,164.0,```\n++++++++[>++++++++<-]>[>+>+>+<<<-]>>>++++...,85.0,0.001,0.0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26009,"Complexity: 3[ 3, 5, 11, 17, 31, 41, 59, 6]",3.0,0.0,TrollScript,167.0,```\ntroooolololoolooloolooloolooloolooloolool...,1812.0,0.001,0.0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26010,"Complexity: 3[ 1, 2, 3, 4, 6, 8, 11, 1]",3.0,0.0,TrollScript,163.0,```trollscript\noooOoOoOoOoOoOoOoOoOoOoOoOoOoO...,1218.0,0.001,0.0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26011,"Complexity: 3[ 1, 0, 1, 1, 2, 3, 6, 1]",3.0,0.0,TrollScript,162.0,```\ntro\nooo\nolo\nllo\nooo\nllo\nooo\nllo\no...,6556.0,0.001,0.0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26012,"Complexity: 3[ 5, 13, 56]",3.0,0.0,TrollScript,149.0,```\ntro\nooo\nooo\nooo\nooo\nrll\nooo\nooo\no...,2424.0,0.001,0.0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
working_df = copy.deepcopy(OIA_ds)

In [36]:

for s in seq_1:
    old_str = "Complexity: 1[ " + s[:-1] + "]"
    # print(old_str)
    working_df.loc[working_df["sequence"] == old_str, "sequence"] = s

print(working_df[working_df['complexity']==1])
working_df.to_csv("first_try.csv", index=False)

                                               sequence  complexity  \
0                    2, 4, 6, 8, 10, 12, 14, 16, 18, 20         1.0
1                   3, 6, 9, 12, 15, 18, 21, 24, 27, 30         1.0
2                  4, 8, 12, 16, 20, 24, 28, 32, 36, 40         1.0
3                 5, 10, 15, 20, 25, 30, 35, 40, 45, 50         1.0
4                 6, 12, 18, 24, 30, 36, 42, 48, 54, 60         1.0
...                                                 ...         ...
25711  151, 152, 153, 154, 155, 156, 157, 158, 159, 160         1.0
25712  161, 162, 163, 164, 165, 166, 167, 168, 169, 170         1.0
25713  171, 172, 173, 174, 175, 176, 177, 178, 179, 180         1.0
25714  181, 182, 183, 184, 185, 186, 187, 188, 189, 190         1.0
25715  191, 192, 193, 194, 195, 196, 197, 198, 199, 200         1.0

       length_type     language  q_length  \
0              0.0    Brainfuck     171.0
1              0.0    Brainfuck     172.0
2              0.0    Brainfuck     173.0
3              0.0    Brainfuck     174.0
4              0.0    Brainfuck     174.0
...            ...          ...       ...
25711          0.0  TrollScript     187.0
25712          0.0  TrollScript     187.0
25713          0.0  TrollScript     187.0
25714          0.0  TrollScript     187.0
25715          0.0  TrollScript     187.0

                                                  answer  a_length  \
0      ```brainfuck\n++++++++++[>+++++>++++<<-]>[>.+<...      56.0
1      ```brainfuck\n++++++++++[>+++++<-]>[<+++++>-]+...     116.0
2      ```brainfuck\n++++++++[->++++<]>[.>+++++>+++++...     139.0
3      ```brainfuck\n+++++>+>+++>++++>+++++>++++++>++...     316.0
4      ```brainfuck\n++++++++++[>+++++++<-]>[<++++++>...     170.0
...                                                  ...       ...
25711  ```\n++++++++++[>++++++++++<-]>+++++.--.+.+.+....      63.0
25712  ```\n+++++++++[>++++++++++<-]>+++++.+.+.+.+.+....      57.0
25713  ```\n++++++++++[>++++++++++<-]>+++++----.+.+.+...      64.0
25714  ```trollscript\noooOoOoOoOoOoOoOoOoOoOoOoOoOoO...    1218.0
25715  ```\n++++++++++[>++++++++++<-]>+++++>+++++++++...    6635.0

       temperature  real_code print_code  ...  no_sense  Unnamed: 13  \
0            1.000        0.0          0  ...         0          NaN
1            1.000        0.0          0  ...         0          NaN
2            1.000        0.0          0  ...         0          NaN
3            1.000        0.0          0  ...         0          NaN
4            1.000        0.0          0  ...         0          NaN
...            ...        ...        ...  ...       ...          ...
25711        0.001        0.0          0  ...         0          NaN
25712        0.001        0.0          0  ...         0          NaN
25713        0.001        0.0          0  ...         0          NaN
25714        0.001        0.0          0  ...         0          NaN
25715        0.001        0.0          0  ...         0          NaN

      Unnamed: 14  Unnamed: 15 Unnamed: 16  Unnamed: 17  Unnamed: 18  \
0             NaN          NaN         NaN          NaN          NaN
1             NaN          NaN         NaN          NaN          NaN
2             NaN          NaN         NaN          NaN          NaN
3             NaN          NaN         NaN          NaN          NaN
4             NaN          NaN         NaN          NaN          NaN
...           ...          ...         ...          ...          ...
25711         NaN          NaN         NaN          NaN          NaN
25712         NaN          NaN         NaN          NaN          NaN
25713         NaN          NaN         NaN          NaN          NaN
25714         NaN          NaN         NaN          NaN          NaN
25715         NaN          NaN         NaN          NaN          NaN

       Unnamed: 19  Unnamed: 20  Unnamed: 21
0              NaN          NaN          NaN
1              NaN          NaN          NaN
2              NaN          NaN          NaN
3              NaN          NaN          NaN
4              NaN          NaN          NaN
...            ...          ...          ...
25711          NaN          NaN          NaN
25712          NaN          NaN          NaN
25713          NaN          NaN          NaN
25714          NaN          NaN          NaN
25715          NaN          NaN          NaN

[3147 rows x 22 columns]

In [38]:
for s in seq_2:
    old_str = "Complexity: 2[ " + s[:-1] + "]"
    # print(old_str)
    working_df.loc[working_df["sequence"] == old_str, "sequence"] = s

print(working_df[working_df['complexity']==2])
working_df.to_csv("first_try.csv", index=False)

                                               sequence  complexity  \
0                    2, 4, 6, 8, 10, 12, 14, 16, 18, 20         1.0
1                   3, 6, 9, 12, 15, 18, 21, 24, 27, 30         1.0
2                  4, 8, 12, 16, 20, 24, 28, 32, 36, 40         1.0
3                 5, 10, 15, 20, 25, 30, 35, 40, 45, 50         1.0
4                 6, 12, 18, 24, 30, 36, 42, 48, 54, 60         1.0
...                                                 ...         ...
25711  151, 152, 153, 154, 155, 156, 157, 158, 159, 160         1.0
25712  161, 162, 163, 164, 165, 166, 167, 168, 169, 170         1.0
25713  171, 172, 173, 174, 175, 176, 177, 178, 179, 180         1.0
25714  181, 182, 183, 184, 185, 186, 187, 188, 189, 190         1.0
25715  191, 192, 193, 194, 195, 196, 197, 198, 199, 200         1.0

       length_type     language  q_length  \
0              0.0    Brainfuck     171.0
1              0.0    Brainfuck     172.0
2              0.0    Brainfuck     173.0
3              0.0    Brainfuck     174.0
4              0.0    Brainfuck     174.0
...            ...          ...       ...
25711          0.0  TrollScript     187.0
25712          0.0  TrollScript     187.0
25713          0.0  TrollScript     187.0
25714          0.0  TrollScript     187.0
25715          0.0  TrollScript     187.0

                                                  answer  a_length  \
0      ```brainfuck\n++++++++++[>+++++>++++<<-]>[>.+<...      56.0
1      ```brainfuck\n++++++++++[>+++++<-]>[<+++++>-]+...     116.0
2      ```brainfuck\n++++++++[->++++<]>[.>+++++>+++++...     139.0
3      ```brainfuck\n+++++>+>+++>++++>+++++>++++++>++...     316.0
4      ```brainfuck\n++++++++++[>+++++++<-]>[<++++++>...     170.0
...                                                  ...       ...
25711  ```\n++++++++++[>++++++++++<-]>+++++.--.+.+.+....      63.0
25712  ```\n+++++++++[>++++++++++<-]>+++++.+.+.+.+.+....      57.0
25713  ```\n++++++++++[>++++++++++<-]>+++++----.+.+.+...      64.0
25714  ```trollscript\noooOoOoOoOoOoOoOoOoOoOoOoOoOoO...    1218.0
25715  ```\n++++++++++[>++++++++++<-]>+++++>+++++++++...    6635.0

       temperature  real_code print_code  ...  no_sense  Unnamed: 13  \
0            1.000        0.0          0  ...         0          NaN
1            1.000        0.0          0  ...         0          NaN
2            1.000        0.0          0  ...         0          NaN
3            1.000        0.0          0  ...         0          NaN
4            1.000        0.0          0  ...         0          NaN
...            ...        ...        ...  ...       ...          ...
25711        0.001        0.0          0  ...         0          NaN
25712        0.001        0.0          0  ...         0          NaN
25713        0.001        0.0          0  ...         0          NaN
25714        0.001        0.0          0  ...         0          NaN
25715        0.001        0.0          0  ...         0          NaN

      Unnamed: 14  Unnamed: 15 Unnamed: 16  Unnamed: 17  Unnamed: 18  \
0             NaN          NaN         NaN          NaN          NaN
1             NaN          NaN         NaN          NaN          NaN
2             NaN          NaN         NaN          NaN          NaN
3             NaN          NaN         NaN          NaN          NaN
4             NaN          NaN         NaN          NaN          NaN
...           ...          ...         ...          ...          ...
25711         NaN          NaN         NaN          NaN          NaN
25712         NaN          NaN         NaN          NaN          NaN
25713         NaN          NaN         NaN          NaN          NaN
25714         NaN          NaN         NaN          NaN          NaN
25715         NaN          NaN         NaN          NaN          NaN

       Unnamed: 19  Unnamed: 20  Unnamed: 21
0              NaN          NaN          NaN
1              NaN          NaN          NaN
2              NaN          NaN          NaN
3              NaN          NaN          NaN
4              NaN          NaN          NaN
...            ...          ...          ...
25711          NaN          NaN          NaN
25712          NaN          NaN          NaN
25713          NaN          NaN          NaN
25714          NaN          NaN          NaN
25715          NaN          NaN          NaN

[3147 rows x 22 columns]

In [39]:
for s in seq_3:
    old_str = "Complexity: 3[ " + s[:-1] + "]"
    # print(old_str)
    working_df.loc[working_df["sequence"] == old_str, "sequence"] = s

print(working_df[working_df['complexity']==3])
working_df.to_csv("first_try.csv", index=False)

                                               sequence  complexity  \
0                    2, 4, 6, 8, 10, 12, 14, 16, 18, 20         1.0
1                   3, 6, 9, 12, 15, 18, 21, 24, 27, 30         1.0
2                  4, 8, 12, 16, 20, 24, 28, 32, 36, 40         1.0
3                 5, 10, 15, 20, 25, 30, 35, 40, 45, 50         1.0
4                 6, 12, 18, 24, 30, 36, 42, 48, 54, 60         1.0
...                                                 ...         ...
25711  151, 152, 153, 154, 155, 156, 157, 158, 159, 160         1.0
25712  161, 162, 163, 164, 165, 166, 167, 168, 169, 170         1.0
25713  171, 172, 173, 174, 175, 176, 177, 178, 179, 180         1.0
25714  181, 182, 183, 184, 185, 186, 187, 188, 189, 190         1.0
25715  191, 192, 193, 194, 195, 196, 197, 198, 199, 200         1.0

       length_type     language  q_length  \
0              0.0    Brainfuck     171.0
1              0.0    Brainfuck     172.0
2              0.0    Brainfuck     173.0
3              0.0    Brainfuck     174.0
4              0.0    Brainfuck     174.0
...            ...          ...       ...
25711          0.0  TrollScript     187.0
25712          0.0  TrollScript     187.0
25713          0.0  TrollScript     187.0
25714          0.0  TrollScript     187.0
25715          0.0  TrollScript     187.0

                                                  answer  a_length  \
0      ```brainfuck\n++++++++++[>+++++>++++<<-]>[>.+<...      56.0
1      ```brainfuck\n++++++++++[>+++++<-]>[<+++++>-]+...     116.0
2      ```brainfuck\n++++++++[->++++<]>[.>+++++>+++++...     139.0
3      ```brainfuck\n+++++>+>+++>++++>+++++>++++++>++...     316.0
4      ```brainfuck\n++++++++++[>+++++++<-]>[<++++++>...     170.0
...                                                  ...       ...
25711  ```\n++++++++++[>++++++++++<-]>+++++.--.+.+.+....      63.0
25712  ```\n+++++++++[>++++++++++<-]>+++++.+.+.+.+.+....      57.0
25713  ```\n++++++++++[>++++++++++<-]>+++++----.+.+.+...      64.0
25714  ```trollscript\noooOoOoOoOoOoOoOoOoOoOoOoOoOoO...    1218.0
25715  ```\n++++++++++[>++++++++++<-]>+++++>+++++++++...    6635.0

       temperature  real_code print_code  ...  no_sense  Unnamed: 13  \
0            1.000        0.0          0  ...         0          NaN
1            1.000        0.0          0  ...         0          NaN
2            1.000        0.0          0  ...         0          NaN
3            1.000        0.0          0  ...         0          NaN
4            1.000        0.0          0  ...         0          NaN
...            ...        ...        ...  ...       ...          ...
25711        0.001        0.0          0  ...         0          NaN
25712        0.001        0.0          0  ...         0          NaN
25713        0.001        0.0          0  ...         0          NaN
25714        0.001        0.0          0  ...         0          NaN
25715        0.001        0.0          0  ...         0          NaN

      Unnamed: 14  Unnamed: 15 Unnamed: 16  Unnamed: 17  Unnamed: 18  \
0             NaN          NaN         NaN          NaN          NaN
1             NaN          NaN         NaN          NaN          NaN
2             NaN          NaN         NaN          NaN          NaN
3             NaN          NaN         NaN          NaN          NaN
4             NaN          NaN         NaN          NaN          NaN
...           ...          ...         ...          ...          ...
25711         NaN          NaN         NaN          NaN          NaN
25712         NaN          NaN         NaN          NaN          NaN
25713         NaN          NaN         NaN          NaN          NaN
25714         NaN          NaN         NaN          NaN          NaN
25715         NaN          NaN         NaN          NaN          NaN

       Unnamed: 19  Unnamed: 20  Unnamed: 21
0              NaN          NaN          NaN
1              NaN          NaN          NaN
2              NaN          NaN          NaN
3              NaN          NaN          NaN
4              NaN          NaN          NaN
...            ...          ...          ...
25711          NaN          NaN          NaN
25712          NaN          NaN          NaN
25713          NaN          NaN          NaN
25714          NaN          NaN          NaN
25715          NaN          NaN          NaN

[3147 rows x 22 columns]

In [40]:
for s in seq_4:
    old_str = "Complexity: 4[ " + s[:-1] + "]"
    # print(old_str)
    working_df.loc[working_df["sequence"] == old_str, "sequence"] = s

print(working_df[working_df['complexity']==4])
working_df.to_csv("first_try.csv", index=False)

                                               sequence  complexity  \
440       29, 57, 68, 120, 134, 140, 173, 197, 283, 313         4.0
441        24, 26, 36, 40, 184, 226, 244, 384, 391, 423         4.0
442     90, 203, 212, 235, 270, 324, 342, 352, 371, 417         4.0
443       20, 48, 95, 234, 282, 296, 352, 402, 428, 481         4.0
444      62, 98, 130, 154, 290, 315, 324, 385, 408, 447         4.0
...                                                 ...         ...
24214  187, 218, 260, 295, 301, 314, 379, 410, 452, 469         4.0
24215     29, 63, 95, 140, 150, 190, 221, 437, 482, 491         4.0
24216      3, 11, 84, 144, 156, 177, 188, 199, 229, 284         4.0
24217     26, 94, 98, 137, 176, 301, 323, 330, 372, 444         4.0
24218     39, 81, 88, 210, 215, 378, 416, 430, 439, 490         4.0

       length_type     language  q_length  \
440            0.0    Brainfuck     181.0
441            0.0    Brainfuck     180.0
442            0.0    Brainfuck     183.0
443            0.0    Brainfuck     181.0
444            0.0    Brainfuck     182.0
...            ...          ...       ...
24214          0.0  TrollScript     186.0
24215          0.0  TrollScript     183.0
24216          0.0  TrollScript     182.0
24217          0.0  TrollScript     183.0
24218          0.0  TrollScript     183.0

                                                  answer  a_length  \
440    ```brainfuck\n++++++++++[>+++++++>++++++++++>+...     127.0
441    ```brainfuck\n++++++++++++[->++++++++++++<]>-....     251.0
442    ```bf\n++++++++++[>+++++++>++++++++++>++++++++...     244.0
443    ```brainfuck\n++++++++++[>+++++++<-]>+++.<++++...     360.0
444    ```brainfuck\n++++++++++[>+++++++<-]>+.-.+.---...     114.0
...                                                  ...       ...
24214  ```\n+++++++++[>++++++++<-]>+.-[>+<-]>++.---[>...     149.0
24215  ```\n+++++++++[>+++++++++<-]>++++.>++++++++++[...     566.0
24216  ```\n+++++++++[>++++++++<-]>[>++++++++<-]>++++...   12293.0
24217  ```\n++++++++[>++++++++<-]>[>++++++++<-]>+++++...     267.0
24218  ```\n+++++++++[>++++++++<-]>+.<++++++++++[>+++...     445.0

       temperature  real_code print_code  ...  no_sense  Unnamed: 13  \
440          1.000        0.0          0  ...         0          NaN
441          1.000        0.0          0  ...         0          NaN
442          1.000        0.0          0  ...         0          NaN
443          1.000        0.0          0  ...         0          NaN
444          1.000        0.0          0  ...         0          NaN
...            ...        ...        ...  ...       ...          ...
24214        0.001        0.0          0  ...         0          NaN
24215        0.001        0.0          0  ...         0          NaN
24216        0.001        0.0          0  ...         0          NaN
24217        0.001        0.0          0  ...         0          NaN
24218        0.001        0.0          0  ...         0          NaN

      Unnamed: 14  Unnamed: 15 Unnamed: 16  Unnamed: 17  Unnamed: 18  \
440           NaN          NaN         NaN          NaN          NaN
441           NaN          NaN         NaN          NaN          NaN
442           NaN          NaN         NaN          NaN          NaN
443           NaN          NaN         NaN          NaN          NaN
444           NaN          NaN         NaN          NaN          NaN
...           ...          ...         ...          ...          ...
24214         NaN          NaN         NaN          NaN          NaN
24215         NaN          NaN         NaN          NaN          NaN
24216         NaN          NaN         NaN          NaN          NaN
24217         NaN          NaN         NaN          NaN          NaN
24218         NaN          NaN         NaN          NaN          NaN

       Unnamed: 19  Unnamed: 20  Unnamed: 21
440            NaN          NaN          NaN
441            NaN          NaN          NaN
442            NaN          NaN          NaN
443            NaN          NaN          NaN
444            NaN          NaN          NaN
...            ...          ...          ...
24214          NaN          NaN          NaN
24215          NaN          NaN          NaN
24216          NaN          NaN          NaN
24217          NaN          NaN          NaN
24218          NaN          NaN          NaN

[3147 rows x 22 columns]

In [42]:
OIA_clean_df = pd.read_csv("no_small_seqs_clean.csv")
OIA_clean_df

,sequence,complexity,length_type,language,q_length,answer,a_length,temperature,real_code,print_code,no_code,explanation,no_sense
0,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",1.0,0.0,Brainfuck,171.0,```brainfuck\n++++++++++[>+++++>++++<<-]>[>.+<...,56.0,1.000,0.0,0,0.0,0.0,0
1,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",1.0,0.0,Brainfuck,172.0,```brainfuck\n++++++++++[>+++++<-]>[<+++++>-]+...,116.0,1.000,0.0,0,0.0,0.0,0
2,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",1.0,0.0,Brainfuck,173.0,```brainfuck\n++++++++[->++++<]>[.>+++++>+++++...,139.0,1.000,0.0,0,0.0,0.0,0
3,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",1.0,0.0,Brainfuck,174.0,```brainfuck\n+++++>+>+++>++++>+++++>++++++>++...,316.0,1.000,0.0,0,0.0,0.0,0
4,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",1.0,0.0,Brainfuck,174.0,```brainfuck\n++++++++++[>+++++++<-]>[<++++++>...,170.0,1.000,0.0,0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
26068,"1, 1, 1, 3, 7, 15, 31, 63",3.0,0.0,TrollScript,164.0,```\n++++++++[>++++++++<-]>[>+>+>+<<<-]>>>++++...,85.0,0.001,0.0,0,0.0,0.0,0
26069,"3, 5, 11, 17, 31, 41, 59, 67",3.0,0.0,TrollScript,167.0,```\ntroooolololoolooloolooloolooloolooloolool...,1812.0,0.001,0.0,0,0.0,0.0,0
26070,"1, 2, 3, 4, 6, 8, 11, 13",3.0,0.0,TrollScript,163.0,```trollscript\noooOoOoOoOoOoOoOoOoOoOoOoOoOoO...,1218.0,0.001,0.0,0,0.0,0.0,0
26071,"1, 0, 1, 1, 2, 3, 6, 11",3.0,0.0,TrollScript,162.0,```\ntro\nooo\nolo\nllo\nooo\nllo\nooo\nllo\no...,6556.0,0.001,0.0,0,0.0,0.0,0
26072,"5, 13, 563",3.0,0.0,TrollScript,149.0,```\ntro\nooo\nooo\nooo\nooo\nrll\nooo\nooo\no...,2424.0,0.001,0.0,0,0.0,0.0,0

In [ ]:
fig, ax = plt.subplots()
sns.countplot(x="real_code", hue="complexity", data=no_tuning_python_short_df, palette="RdBu_r", ax=ax)
ax.set_ylim(0, 80)
plt.show()