# MATLAB

In [1]:
import pandas as pd
import re

In [2]:
matlab_df = pd.read_csv("Matlab_evaluation.csv")
matlab_df

,sequence,complexity,length_type,language,q_length,GPT4_answer,a_length,temperature,real_code,print_code,no_code,explanation,no_sense,exe_out,correct_execution,Levenshtein
0,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",1,0,Matlab,168,```matlab\ndisp(2:2:20)\n```,26,1.000,1,0,0,0,0,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",True,0
1,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",1,0,Matlab,169,```matlab\nfor i = 3:3:30\n disp(i)\nend\n```,44,1.000,1,0,0,0,0,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",True,0
2,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",1,0,Matlab,170,```matlab\ndisp(4:4:40)\n```,26,1.000,1,0,0,0,0,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",True,0
3,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",1,0,Matlab,171,```matlab\ndisp(5:5:50);\n```,27,1.000,1,0,0,0,0,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",True,0
4,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",1,0,Matlab,171,```matlab\nfor i = 1:10\n disp(6*i);\nend\n```,45,1.000,1,0,0,0,0,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
585,"187, 218, 260, 295, 301, 314, 379, 410, 452, 469",4,0,Matlab,181,"```matlab\nsequence = [187, 218, 260, 295, 301...",91,0.001,0,0,0,0,0,"187, 218, 260, 295, 301, 314, 379, 410, 452, 469",True,0
586,"29, 63, 95, 140, 150, 190, 221, 437, 482, 491",4,0,Matlab,178,"```matlab\nsequence = [29, 63, 95, 140, 150, 1...",88,0.001,0,0,0,0,0,"29, 63, 95, 140, 150, 190, 221, 437, 482, 491",True,0
587,"3, 11, 84, 144, 156, 177, 188, 199, 229, 284",4,0,Matlab,177,"```matlab\nsequence = [3, 11, 84, 144, 156, 17...",87,0.001,0,0,0,0,0,"3, 11, 84, 144, 156, 177, 188, 199, 229, 284",True,0
588,"26, 94, 98, 137, 176, 301, 323, 330, 372, 444",4,0,Matlab,178,"```matlab\nsequence = [26, 94, 98, 137, 176, 3...",88,0.001,0,0,0,0,0,"26, 94, 98, 137, 176, 301, 323, 330, 372, 444",True,0
589,"39, 81, 88, 210, 215, 378, 416, 430, 439, 490",4,0,Matlab,178,"```matlab\nsequence = [39, 81, 88, 210, 215, 3...",88,0.001,0,0,0,0,0,"39, 81, 88, 210, 215, 378, 416, 430, 439, 490",True,0

In [3]:
answers = list(matlab_df["GPT4_answer"].values)
# answers_test = answers[450:590]
# answers_test
answers

['```matlab\ndisp(2:2:20)\n```',
 '```matlab\nfor i = 3:3:30\n    disp(i)\nend\n```',
 '```matlab\ndisp(4:4:40)\n```',
 '```matlab\ndisp(5:5:50);\n```',
 '```matlab\nfor i = 1:10\n    disp(6*i);\nend\n```',
 '```matlab\nfor i=1:10\n    disp(7*i);\nend\n```',
 '```matlab\nfor i = 1:10\n    disp(8 * i);\nend\n```',
 '```matlab\nfor i=1:10\n    disp(9*i);\nend\n```',
 '```matlab\nfor i = 10:10:100\n    disp(i)\nend\n```',
 '```matlab\ndisp(1:2:19)\n```',
 '```matlab\ndisp(2:2:20)\n```',
 '```matlab\nfor i = 11:20\n    disp(i)\nend\n```',
 '```matlab\ndisp(21:30)\n```',
 '```matlab\nfor i=31:40\n    disp(i)\nend\n```',
 '```matlab\nfor i=41:50\n    disp(i)\nend\n```',
 '```matlab\nfor i = 51:60\n    disp(i)\nend\n```',
 '```matlab\nfor i = 61:70\n    disp(i)\nend\n```',
 '```matlab\nfor i = 71:80\n    disp(i)\nend\n```',
 '```matlab\nfor i = 81:90\n    disp(i)\nend\n```',
 '```matlab\nfor i = 91:100\n    disp(i)\nend\n```',
 '```matlab\ndisp(101:110)\n```',
 '```matlab\nfor i = 111:120\n    disp(i)\nend\n```',
 '```matlab\nfor i=121:130\n    disp(i)\nend\n```',
 '```matlab\ndisp(131:140)\n```',
 '```matlab\nfor i=141:150\n    disp(i)\nend\n```',
 '```matlab\nfor i = 151:160\n    disp(i)\nend\n```',
 '```matlab\nfor i = 161:170\n    disp(i)\nend\n```',
 '```matlab\nfor i = 171:180\n    disp(i)\nend\n```',
 '```matlab\nfor i=181:190\n    disp(i)\nend\n```',
 '```matlab\nfor i=191:200\n    disp(i)\nend\n```',
 '```matlab\ndisp(2:2:20)\n```',
 '```matlab\nfor i=1:10\n    disp(3*i);\nend\n```',
 '```matlab\nfor i=1:10\n    disp(4*i);\nend\n```',
 '```matlab\ndisp(5:5:50)\n```',
 '```matlab\nfor i = 1:10\n    disp(6*i);\nend\n```',
 '```matlab\nfor i=1:10\n    disp(7*i);\nend\n```',
 '```matlab\nfor i = 8:8:80\n    disp(i)\nend\n```',
 '```matlab\nfor i = 1:10\n    disp(9 * i);\nend\n```',
 '```matlab\nfor i = 10:10:100\n    disp(i)\nend\n```',
 '```matlab\n1:2:19\n```',
 '```matlab\ndisp(2:2:20)\n```',
 '```matlab\nfor i = 11:20\n    disp(i)\nend\n```',
 '```matlab\nfor i=21:30\n    disp(i)\nend\n```',
 '```matlab\nfor i = 31:40\n    disp(i)\nend\n```',
 '```matlab\nfor i=41:50\n    disp(i)\nend\n```',
 '```matlab\nfor i = 51:60\n    disp(i)\nend\n```',
 '```matlab\nfor i = 61:70\n    disp(i)\nend\n```',
 '```matlab\nfor i = 71:80\n    disp(i)\nend\n```',
 '```matlab\nfor i = 81:90\n    disp(i)\nend\n```',
 '```matlab\nfor i = 91:100\n    disp(i)\nend\n```',
 '```matlab\nfor i=101:110\n    disp(i)\nend\n```',
 '```matlab\nfor i=111:120\n    disp(i);\nend\n```',
 '```matlab\nfor i = 121:130\n    disp(i)\nend\n```',
 '```matlab\nfor i=131:140\n    disp(i)\nend\n```',
 '```matlab\nfor i = 141:150\n    disp(i);\nend\n```',
 '```matlab\nfor i = 151:160\n    disp(i)\nend\n```',
 '```matlab\nfor i = 161:170\n    disp(i)\nend\n```',
 '```matlab\nfor i=171:180\n    disp(i)\nend\n```',
 '```matlab\nfor i=181:190\n    disp(i)\nend\n```',
 '```matlab\nfor i = 191:200\n    disp(i)\nend\n```',
 '```matlab\ndisp(2:2:20)\n```',
 '```matlab\ndisp(3:3:30)\n```',
 '```matlab\nfor i=1:10\n    disp(4*i);\nend\n```',
 '```matlab\nfor i = 5:5:50\n    disp(i)\nend\n```',
 '```matlab\nfor i = 1:10\n    disp(6*i);\nend\n```',
 '```matlab\nfor i = 1:10\n    disp(7*i);\nend\n```',
 '```matlab\nfor i = 1:10\n    disp(i*8);\nend\n```',
 '```matlab\nfor i = 1:10\n    disp(9*i);\nend\n```',
 '```matlab\ndisp(10:10:100)\n```',
 '```matlab\n1:2:19\n```',
 '```matlab\ndisp(2:2:20)\n```',
 '```matlab\ndisp(11:20)\n```',
 '```matlab\nfor i=21:30\n    disp(i)\nend\n```',
 '```matlab\nfor i=31:40\n    disp(i)\nend\n```',
 '```matlab\nfor i = 41:50\n    disp(i)\nend\n```',
 '```matlab\nfor i = 51:60\n    disp(i)\nend\n```',
 '```matlab\nfor i = 61:70\n    disp(i)\nend\n```',
 '```matlab\nfor i = 71:80\n    disp(i)\nend\n```',
 '```matlab\nfor i = 81:90\n    disp(i)\nend\n```',
 '```matlab\nfor i = 91:100\n    disp(i)\nend\n```',
 '```matlab\nfor i = 101:110\n    disp(i)\nend\n```',
 '```matlab\nfor i=111:120\n    disp(i)\nend\n```',
 '```matlab\nfor i=121:130\n    disp(i)\nend\n```',
 '```matlab\nfor i = 131:140\n    disp(i)\nend\n```',
 '```matlab\nfor i = 141:150\n    disp(i)\nend\n```',
 '```matlab\nfor i = 151:160\n    disp(i)\nend\n```',
 '```matlab\nfor i = 161:170\n    disp(i)\nend\n```',
 '```matlab\nfor i=171:180\n    disp(i)\nend\n```',
 '```matlab\nfor i=181:190\n    disp(i)\nend\n```',
 '```matlab\nfor i = 191:200\n    disp(i)\nend\n```',
 '```matlab\ndisp(2:2:20)\n```',
 '```matlab\ndisp(3:3:30)\n```',
 '```matlab\nfor i=1:10\n    disp(4*i);\nend\n```',
 '```matlab\nfor i = 5:5:50\n    disp(i)\nend\n```',
 '```matlab\nfor i = 1:10\n    disp(6*i);\nend\n```',
 '```matlab\nfor i = 1:10\n    disp(7*i);\nend\n```',
 '```matlab\nfor i = 1:10\n    disp(8 * i);\nend\n```',
 '```matlab\nfor i = 1:10\n    disp(9*i);\nend\n```',
 '```matlab\nfor i = 10:10:100\n    disp(i)\nend\n```',
 '```matlab\ndisp(1:2:19)\n```',
 '```matlab\ndisp(2:2:20)\n```',
 '```matlab\ndisp(11:20)\n```',
 '```matlab\nfor i = 21:30\n    disp(i)\nend\n```',
 '```matlab\nfor i = 31:40\n    disp(i)\nend\n```',
 '```matlab\nfor i = 41:50\n    disp(i)\nend\n```',
 '```matlab\nfor i = 51:60\n    disp(i)\nend\n```',
 '```matlab\nfor i = 61:70\n    disp(i)\nend\n```',
 '```matlab\nfor i = 71:80\n    disp(i)\nend\n```',
 '```matlab\nfor i = 81:90\n    disp(i)\nend\n```',
 '```matlab\nfor i = 91:100\n    disp(i)\nend\n```',
 '```matlab\nfor i = 101:110\n    disp(i)\nend\n```',
 '```matlab\nfor i=111:120\n    disp(i)\nend\n```',
 '```matlab\nfor i = 121:130\n    disp(i)\nend\n```',
 '```matlab\nfor i = 131:140\n    disp(i)\nend\n```',
 '```matlab\nfor i=141:150\n    disp(i)\nend\n```',
 '```matlab\nfor i = 151:160\n    disp(i)\nend\n```',
 '```matlab\nfor i = 161:170\n    disp(i)\nend\n```',
 '```matlab\nfor i = 171:180\n    disp(i)\nend\n```',
 '```matlab\nfor i = 181:190\n    disp(i)\nend\n```',
 '```matlab\nfor i = 191:200\n    disp(i)\nend\n```',
 '```matlab\ndisp(2:2:20)\n```',
 '```matlab\nfor i = 1:10\n    disp(3*i);\nend\n```',
 '```matlab\nfor i = 1:10\n    disp(4*i);\nend\n```',
 '```matlab\nfor i = 5:5:50\n    disp(i)\nend\n```',
 '```matlab\nfor i = 1:10\n    disp(6*i);\nend\n```',
 '```matlab\nfor i = 1:10\n    disp(7 * i);\nend\n```',
 '```matlab\nfor i = 1:10\n    disp(8 * i);\nend\n```',
 '```matlab\nfor i = 1:10\n    disp(9*i);\nend\n```',
 '```matlab\nfor i = 10:10:100\n    disp(i)\nend\n```',
 '```matlab\nfor i = 1:10\n    disp(2*i-1);\nend\n```',
 '```matlab\ndisp(2:2:20)\n```',
 '```matlab\nfor i = 11:20\n    disp(i)\nend\n```',
 '```matlab\nfor i=21:30\n    disp(i)\nend\n```',
 '```matlab\nfor i = 31:40\n    disp(i)\nend\n```',
 '```matlab\nfor i = 41:50\n    disp(i)\nend\n```',
 '```matlab\nfor i = 51:60\n    disp(i)\nend\n```',
 '```matlab\nfor i = 61:70\n    disp(i)\nend\n```',
 '```matlab\nfor i = 71:80\n    disp(i)\nend\n```',
 '```matlab\nfor i = 81:90\n    disp(i)\nend\n```',
 '```matlab\nfor i = 91:100\n    disp(i)\nend\n```',
 '```matlab\nfor i = 101:110\n    disp(i)\nend\n```',
 '```matlab\nfor i = 111:120\n    disp(i)\nend\n```',
 '```matlab\nfor i = 121:130\n    disp(i)\nend\n```',
 '```matlab\nfor i = 131:140\n    disp(i)\nend\n```',
 '```matlab\nfor i=141:150\n    disp(i)\nend\n```',
 '```matlab\nfor i = 151:160\n    disp(i)\nend\n```',
 '```matlab\nfor i = 161:170\n    disp(i)\nend\n```',
 '```matlab\nfor i=171:180\n    disp(i)\nend\n```',
 '```matlab\nfor i = 181:190\n    disp(i)\nend\n```',
 '```matlab\nfor i = 191:200\n    disp(i)\nend\n```',
 '```matlab\nN = 10; % Number of primes\np = zeros(1, N); % Preallocate array\ncnt = 1;\nnum = 2;\nwhile cnt <= N\n    if isprime(num)\n        p(cnt) = num;\n        cnt = cnt + 1;\n    end\n    num = num + 1;\nend\ndisp(p);\n```',
 '```matlab\nfunction fibSeq = fibonacciSequence(n)\n    if n <= 0\n        fibSeq = [];\n    else\n        fibSeq = zeros(1, n);\n        fibSeq(1) = 1;\n        if n > 1\n            fibSeq(2) = 1;\n            for i = 3:n\n                fibSeq(i) = fibSeq(i-1) + fibSeq(i-2);\n            end\n        end\n    end\nend\n\nsequence = fibonacciSequence(10);\ndisp(sequence);\n```',
 '```matlab\nfor i = 0:9\n    disp(2^i);\nend\n```',
 '```matlab\nfor i=0:9\n    disp(3^i)\nend\n```',
 "```matlab\nfor n = 1:10\n    fprintf('%d, ', n^2);\nend\n```",
 '```matlab\nfor n = 1:10\n    disp(n^3);\nend\n```',
 '```matlab\nfact = 1;\nfor i=1:10\n    if i > 1\n        fact = fact * (i-1);\n    end\n    disp(fact);\nend\n```',
 '```matlab\nn = 10;\na = zeros(1, n);\nfor i = 1:n\n    a(i) = i*(i+1)/2;\nend\ndisp(a)\n```',
 "```matlab\na = 2;\nb = 1;\nfprintf('%d, ', a);\nfor i = 1:9\n    if i == 1\n        fprintf('%d, ', b);\n    else\n        c = a + b;\n        fprintf('%d', c);\n        if i < 9\n            fprintf(', ');\n        end\n        a = b;\n        b = c;\n    end\nend\n```",
 '```matlab\na(1) = 0;\na(2) = 1;\nfor n = 3:10\n    a(n) = a(n-1)*2 + a(n-2);\nend\ndisp(a)\n```',
 '```matlab\nfor n = 1:10\n    disp(n^2^n)\nend\n```',
 '```matlab\nn = 10;\nseq = zeros(1, n);\nfor i=1:n\n   seq(i) = nchoosek(2*i, i) / (i + 1);\nend\ndisp(seq);\n```',
 '```matlab\nn = 10; % Number of primes\nprimes = zeros(1,n);\ncount = 1;\ni = 2;\nwhile count <= n\n    isPrime = true;\n    for j = 2:sqrt(i)\n        if mod(i,j) == 0\n            isPrime = false;\n            break;\n        end\n    end\n    if isPrime\n        primes(count) = i;\n        count = count + 1;\n    end\n    i = i + 1;\nend\ndisp(primes);\n```',
 '```matlab\nA = [4, 6, 9, 10, 14, 15, 21, 22, 25, 26];\ndisp(A)\n```',
 '```matlab\nfor i=1:10\n    disp(dec2bin(i))\nend\n```',
 '```matlab\nA = [0, 1, 81, 512, 2401, 4913, 5832, 17576, 19683, 234256];\ndisp(A)\n```',
 "```matlab\nfor n = 1:5e4\n    if sum(factorial(num2str(n)-'0')) == n\n        disp(n)\n    end\nend\n```",
 '```matlab\nn = 10; \nseq = zeros(1, n); \nfor i = 1:n \n    if i == 1\n        seq(i) = 2; \n    else\n        seq(i) = seq(i-1) + (i-1) + 3;\n    end\nend\ndisp(seq);\n```',
 '```matlab\nseq = [1, 8, 10, 18, 19, 100, 101, 108, 109, 110];\ndisp(seq);\n```',
 '```matlab\nfor n=1:10\n    disp(2^(2^n) - 1);\nend\n```',
 '```matlab\na = [1, 2];\nfor i = 3:10\n    if mod(i, 2) == 0\n        a(i) = a(i-1) * 2;\n    else\n        if i <= 5\n            a(i) = a(i-1) + 7;\n        else\n            a(i) = a(i-1) + a(i-2);\n        end\n    end\nend\ndisp(a)\n```',
 '```matlab\na = [1, 1, 1, 2]; % Starting values\nfor i = 5:14 % Generate sequence from position 5 to 14\n    a(i) = a(i-1) + a(i-2) + a(i-3) + a(i-4);\nend\ndisp(a(2:end)); % Display the sequence starting from the second element\n```',
 '```matlab\nn = 10;\nseq = zeros(1, n);\nfor i = 1:n\n    seq(i) = i^3 - i + 1;\nend\ndisp(seq)\n```',
 "```matlab\nseq = []; for n = 0:9, seq = [seq, sum(dec2bin(n)=='1')]; end, disp(seq)\n```",
 "```matlab\nn = 9; % Desired index for the sequence, where n = 0 corresponds to the sequence's first element\na = zeros(1,n+1);\na(1) = 1; % Initial value\n\nfor i = 2:n+1\n    a(i) = ((6*i-9)*a(i-1))/(i-1);\nend\n\ndisp(a);\n```",
 '```matlab\nN = 10; % Number of primes\nprimes = zeros(1,N);\ncount = 1;\nnum = 2;\nwhile count <= N\n    isprime = true;\n    for i = 2:sqrt(num)\n        if mod(num, i) == 0\n            isprime = false;\n            break;\n        end\n    end\n    if isprime\n        primes(count) = num;\n        count = count + 1;\n    end\n    num = num + 1;\nend\ndisp(primes);\n```',
 "```matlab\ns = '1';\nfor n = 1:4\n    s = regexprep(s, '(\\d)\\1*', '${num2str(length($0))}$1');\nend\ndisp(s);\n```",
 '```matlab\nn = 10; % Number of primes required\nprimesList = zeros(1, n); % Initialize vector for primes\ncount = 1;\nnum = 2;\nwhile count <= n\n    isPrime = true;\n    for i = 2:sqrt(num)\n        if mod(num, i) == 0\n            isPrime = false;\n            break;\n        end\n    end\n    if isPrime\n        primesList(count) = num;\n        count = count + 1;\n    end\n    num = num + 1;\nend\ndisp(primesList);\n```',
 '```matlab\nfor i = 0:9\n    disp(2^i)\nend\n```',
 '```matlab\nfor i=0:9\n    disp(2^i*2-1);\nend\n```',
 '```matlab\nn = 10;\nprimes = zeros(1, n);\ncount = 1;\nnum = 2;\nwhile count <= n\n    isPrime = true;\n    for i = 2:sqrt(num)\n        if mod(num, i) == 0\n            isPrime = false;\n            break;\n        end\n    end\n    if isPrime\n        primes(count) = num;\n        count = count + 1;\n    end\n    num = num + 1;\nend\ndisp(primes);\n```',
 '```matlab\nn = 10;\nf = zeros(1, n);\nf(1:2) = [1 1];\nfor i = 3:n\n    f(i) = f(i-1) + f(i-2);\nend\ndisp(f);\n```',
 '```matlab\ndisp(2.^(0:9))\n```',
 '```matlab\nfor i = 0:9\n    disp(3^i);\nend\n```',
 '```matlab\nfor n = 1:10\n    disp(n^2)\nend\n```',
 '```matlab\nfor n = 1:10\n    disp(n^3);\nend\n```',
 '```matlab\nn = 10;\nseq = zeros(1, n);\nfor i = 1:n\n    if i == 1 || i == 2\n        seq(i) = 1;\n    else\n        seq(i) = seq(i-1) * (i-1);\n    end\nend\ndisp(seq)\n```',
 '```matlab\nn = 10;\nseq = zeros(1, n);\nfor i = 1:n\n    if i == 1\n        seq(i) = 1;\n    else\n        seq(i) = seq(i-1) + i;\n    end\nend\ndisp(seq);\n```',
 '```matlab\na = [2, 1]; % Initialize the sequence with the first two numbers\nfor i = 3:10 % Loop to generate the next 8 numbers\n    a(i) = a(i-1) + a(i-2); % Each number is the sum of the previous two\nend\ndisp(a); % Display the sequence\n```',
 '```matlab\na(1) = 0; a(2) = 1;\nfor n = 3:10\n    a(n) = a(n-1)*2 + a(n-2);\nend\ndisp(a);\n```',
 '```matlab\nfor n = 1:10\n    disp(n^3^n);\nend\n```',
 '```matlab\nn = 10; % Length of sequence\nseq = zeros(1, n); % Initialize sequence array\nfor i = 1:n\n    seq(i) = nchoosek(2*i-2, i-1);\nend\ndisp(seq);\n```',
 '```matlab\nn = 10;\np = primes(100);\ndisp(p(1:n));\n```',
 '```matlab\nn = [4, 6, 9, 10, 14, 15, 21, 22, 25, 26];\ndisp(n)\n```',
 '```matlab\nfor i = 1:10\n    disp(dec2bin(i))\nend\n```',
 '```matlab\nA = [0, 1, 3, 8, 7, 17, 18, 26, 27, 44];\nB = A.^3;\ndisp(B);\n```',
 '```matlab\nn = [1, 2, 145, 40585];\ndisp(n)\n```',
 '```matlab\nn = 10; % Number of elements in the sequence\nsequence = zeros(1, n);\nfor i = 1:n\n    if i == 1\n        sequence(i) = 2;\n    else\n        sequence(i) = sequence(i-1) + (i-1) + 3;\n    end\nend\ndisp(sequence)\n```',
 '```matlab\nfor n = 1:110\n    if mod(n,10) == 1 || mod(n,10) == 8 || mod(n,10) == 9 || mod(n,10) == 0\n        disp(n)\n    end\nend\n```',
 '```matlab\nfor i = 1:10\n    disp(2^(2^i-1)-1)\nend\n```',
 '```matlab\nsequence = zeros(1,10);\nsequence(1) = 1;\nfor i = 2:10\n    if mod(i,2) == 0\n        sequence(i) = sequence(i-1) * 2;\n    else\n        if i < 6\n            sequence(i) = sequence(i-1) + 7;\n        else\n            sequence(i) = sequence(i-1) + i*5;\n        end\n    end\nend\ndisp(sequence);\n```',
 '```matlab\na = zeros(1,10);\na(1) = 1; a(2) = 2;\nfor i=3:10\n    if i == 3 || i == 4\n        a(i) = a(i-1) * 2;\n    else\n        a(i) = a(i-1) + a(i-2) + a(i-3);\n    end\nend\ndisp(a)\n```',
 '```matlab\nfor n = 1:10\n    a(n) = n^3 - n^2 + n;\nend\ndisp(a);\n```',
 "```matlab\nseq = []; % Initialize empty sequence\nfor i = 0:9 % Loop through the first 10 numbers (0 to 9)\n    seq = [seq, sum(dec2bin(i)=='1')]; % Convert number to binary, count the ones, and append to the sequence\nend\ndisp(seq); % Display the sequence\n```",
 '```matlab\na = zeros(1,10);\na(1) = 1;\nfor i = 2:10\n    a(i) = 0;\n    for j = 1:i-1\n        a(i) = a(i) + nchoosek(i-1,j-1) * a(j);\n    end\nend\ndisp(a)\n```',
 '```matlab\nN = 10;\np = primes(100);\ndisp(p(1:N))\n```',
 "```matlab\ncurrent = '1';\nfprintf('%s\\n', current);\nfor i = 1:4\n    next = '';\n    count = 1;\n    for j = 2:length(current) + 1\n        if j <= length(current) && current(j) == current(j-1)\n            count = count + 1;\n        else\n            next = [next, num2str(count), current(j-1)];\n            count = 1;\n        end\n    end\n    current = next;\n    fprintf('%s\\n', current);\nend\n```",
 '```matlab\nN = 10; \np = primes(100);\ndisp(p(1:N));\n```',
 '```matlab\nsequence = 2.^(0:9)\n```',
 '```matlab\nfor i=0:9\n    disp(2^(i+1)-1)\nend\n```',
 '```matlab\nN = 10; % Number of primes\np = primes(100); % Generate a list of primes\ndisp(p(1:N)); % Display the first N primes\n```',
 '```matlab\nfunction fibSeq = generateFibonacci(n)\n    fibSeq = zeros(1, n);\n    fibSeq(1) = 1;\n    if n > 1\n        fibSeq(2) = 1;\n        for i = 3:n\n            fibSeq(i) = fibSeq(i-1) + fibSeq(i-2);\n        end\n    end\nend\n\n% Generate first 10 Fibonacci numbers\nfibSequence = generateFibonacci(10);\ndisp(fibSequence);\n```',
 '```matlab\nfor i = 0:9\n    disp(2^i);\nend\n```',
 '```matlab\nfor i = 0:9\n    disp(3^i);\nend\n```',
 '```matlab\nfor i = 1:10\n    disp(i^2)\nend\n```',
 '```matlab\nfor n = 1:10\n    disp(n^3)\nend\n```',
 '```matlab\nn = 10;\nseq = zeros(1, n);\nseq(1) = 1;\nfor i = 2:n\n    seq(i) = seq(i-1) * i;\nend\ndisp(seq)\n```',
 '```matlab\nn = 10; % Number of terms\nsequence = zeros(1, n);\nfor i = 1:n\n    if i == 1\n        sequence(i) = 1;\n    else\n        sequence(i) = sequence(i-1) + i;\n    end\nend\ndisp(sequence)\n```',
 "```matlab\na = 2; b = 1; fprintf('%d, ', a);\nfor i=1:8\n    fprintf('%d, ', b);\n    c = a + b; a = b; b = c;\nend\nfprintf('%d\\n', b);\n```",
 '```matlab\na(1) = 0;\na(2) = 1;\nfor n = 3:10\n    a(n) = a(n-1) + 2*a(n-2);\nend\ndisp(a);\n```',
 '```matlab\nfor n = 1:10\n    disp(n^3^n)\nend\n```',
 '```matlab\nn = 10; % Number of terms in the sequence\nsequence = zeros(1, n);\nfor i = 1:n\n    sequence(i) = nchoosek(2*i-2, i-1);\nend\ndisp(sequence)\n```',
 'ERROR!!!',
 '```matlab\nA = [4, 6, 9, 10, 14, 15, 21, 22, 25, 26];\ndisp(A)\n```',
 '```matlab\nfor i = 1:10\n    disp(dec2bin(i))\nend\n```',
 '```matlab\nA = [0, 1, 81, 512, 2401, 4913, 5832, 17576, 19683, 234256];\ndisp(A)\n```',
 "```matlab\nfor n = 1:100000\n    s = sum(factorial(str2double(regexp(num2str(n),'\\d','match'))));\n    if n == s\n        disp(n)\n    end\nend\n```",
 '```matlab\nn = 10; % Number of elements in the sequence\na = zeros(1, n);\nfor i = 1:n\n    if i == 1\n        a(i) = 2;\n    else\n        a(i) = a(i-1) + (i+2);\n    end\nend\ndisp(a);\n```',
 '```matlab\nseq = [1, 8, 10, 18, 19, 100, 101, 108, 109, 110];\ndisp(seq)\n```',
 '```matlab\nfor i = 1:10\n    disp(2^(2^i - 1) - 1)\nend\n```',
 '```matlab\nsequence = zeros(1,10);\nsequence(1) = 1;\nfor i = 2:10\n    if mod(i, 2) == 0\n        sequence(i) = sequence(i-1) * 2;\n    else\n        if i <= 5\n            sequence(i) = sequence(i-1) + 7;\n        else\n            sequence(i) = sequence(i-1) + 10;\n        end\n    end\nend\ndisp(sequence)\n```',
 '```matlab\nn = 10; % Desired length of sequence\nseq = zeros(1, n);\nseq(1:3) = [1, 2, 4]; % Initial values\nfor i = 4:n\n    seq(i) = seq(i-1) + seq(i-2) + seq(i-3);\nend\ndisp(seq);\n```',
 '```matlab\nn = 10; % Number of terms\na = 1; % First term\nfor i = 1:n\n    disp(a);\n    a = a + 4*i;\nend\n```',
 "```matlab\nn = 10; % Desired length of sequence\nseq = zeros(1, n); % Initialize sequence\nfor i = 2:n\n    seq(i) = sum(dec2bin(i-1)=='1');\nend\ndisp(seq)\n```",
 '```matlab\na(1) = 1;\nfor n = 2:10\n    a(n) = 0;\n    for k = 0:n-2\n        a(n) = a(n) + nchoosek(n-1, k) * a(k+1);\n    end\nend\ndisp(a);\n```',
 '```matlab\nN = 10; % Number of primes\np = primes(100); % Generate a list of primes, assuming the first N primes are within the first 100 natural numbers\ndisp(p(1:N)); % Display the first N primes\n```',
 "```matlab\ncurrent = '1';\ndisp(current);\nfor i=1:4\n    next = '';\n    j = 1;\n    while j <= length(current)\n        count = 1;\n        while j+1 <= length(current) && current(j) == current(j+1)\n            j = j+1;\n            count = count+1;\n        end\n        next = [next, num2str(count), current(j)];\n        j = j+1;\n    end\n    disp(next);\n    current = next;\nend\n```",
 '```matlab\nn = 10;\np = primes(100);\ndisp(p(1:n))\n```',
 '```matlab\nfor i = 0:9\n    disp(2^i)\nend\n```',
 '```matlab\nfor n = 0:9\n    disp(2^n - 1)\nend\n```',

In [4]:
def preprocess_code(code):
    # Remove leading and trailing substrings
    code = re.sub(r'^```(?:Matlab|matlab)?\n|\n```$', '', code)
    return code

def find_matched_programs(matlab_programs):
    # Regular expression pattern
    pattern = r'^(?!.*(?:\bfor\b|\bwhile\b|\bdo\b|\brepeat\b))(?!.*[-+*/^:])(?!.*\bprime\b).*(?:\bdisp\s*\(\s*(?:\w+\s*=\s*\[?\d+(?:,\s*\d+)*\]?|\[\s*\d+(?:,\s*\d+)*\s*\]|\d+(?:,\s*\d+)*)\s*\)|\w+\s*=\s*\[?\d+(?:,\s*\d+)*\]?;\s*disp\(\w+\)\s*)\s*;?$'
    
    # List to store matched programs and their indices
    matched_programs = []
    indexes = []

    # Iterate over each MATLAB code string
    for i, program in enumerate(matlab_programs):
        # Preprocess the code string
        program = preprocess_code(program)
        # Check if the program matches the pattern
        if re.match(pattern, program):
            matched_programs.append(program)
            indexes.append(i)
    
    return matched_programs, indexes

In [5]:
# Find MATLAB programs containing sequences of numbers and disp instructions
matches, indexes= find_matched_programs(answers)

# Print matching MATLAB programs and their corresponding index
print("Matching MATLAB programs:")
for i in range(len(matches)):
    print(f"Index: {indexes[i]}, Code: {matches[i]}")

Matching MATLAB programs:
Index: 163, Code: A = [4, 6, 9, 10, 14, 15, 21, 22, 25, 26];
disp(A)
Index: 165, Code: A = [0, 1, 81, 512, 2401, 4913, 5832, 17576, 19683, 234256];
disp(A)
Index: 168, Code: seq = [1, 8, 10, 18, 19, 100, 101, 108, 109, 110];
disp(seq);
Index: 193, Code: n = [4, 6, 9, 10, 14, 15, 21, 22, 25, 26];
disp(n)
Index: 196, Code: n = [1, 2, 145, 40585];
disp(n)
Index: 223, Code: A = [4, 6, 9, 10, 14, 15, 21, 22, 25, 26];
disp(A)
Index: 225, Code: A = [0, 1, 81, 512, 2401, 4913, 5832, 17576, 19683, 234256];
disp(A)
Index: 228, Code: seq = [1, 8, 10, 18, 19, 100, 101, 108, 109, 110];
disp(seq)
Index: 255, Code: A = [0, 1, 81, 512, 2401, 4913, 5832, 17576, 19683, 234256];
disp(A)
Index: 285, Code: A = [0, 1, 81, 512, 2401, 4913, 5832, 17576, 19683, 234256];
disp(A)
Index: 288, Code: seq = [1, 8, 10, 18, 19, 100, 101, 108, 109, 110];
disp(seq);
Index: 313, Code: n = [1, 2, 145, 40585];
disp(n);
Index: 314, Code: primes_larger = [19, 31, 61, 89, 107, 127, 521, 607, 1279, 2203];
disp(primes_larger);
Index: 321, Code: seq = [1, 4, 2, 1, 3, 5, 9, 2, 6, 5];
disp(seq);
Index: 322, Code: sequence = [1, 7, 3, 2, 0, 5, 0, 7, 9, 8];
disp(sequence);
Index: 342, Code: sequence = [19, 31, 61, 89, 107, 127, 521, 607, 1279, 2203];
disp(sequence)
Index: 345, Code: seq = [1, 8, 10, 18, 19, 100, 101, 108, 109, 110];
disp(seq)
Index: 349, Code: sequence = [1, 4, 2, 1, 3, 5, 9, 2, 6, 5];
disp(sequence);
Index: 350, Code: sequence = [1, 7, 3, 2, 0, 5, 0, 7, 9, 8];
disp(sequence)
Index: 370, Code: sequence = [19, 31, 61, 89, 107, 127, 521, 607, 1279, 2203];
disp(sequence)
Index: 373, Code: seq = [1, 8, 10, 18, 19, 100, 101, 108, 109, 110];
disp(seq)
Index: 377, Code: seq = [1, 4, 2, 1, 3, 5, 9, 2, 6, 5];
disp(seq);
Index: 378, Code: sequence = [1, 7, 3, 2, 0, 5, 0, 7, 9, 8];
disp(sequence);
Index: 381, Code: sequence = [3, 5, 11, 17, 31, 41, 59, 67];
disp(sequence)
Index: 398, Code: sequence = [19, 31, 61, 89, 107, 127, 521, 607, 1279, 2203];
disp(sequence);
Index: 405, Code: sequence = [1, 4, 2, 1, 3, 5, 9, 2, 6, 5];
disp(sequence);
Index: 406, Code: sequence = [1, 7, 3, 2, 0, 5, 0, 7, 9, 8];
disp(sequence);
Index: 407, Code: seq = [1, 0, 1, 2, 3, 1, 6, 11];
disp(seq);
Index: 409, Code: sequence = [3, 5, 11, 17, 31, 41, 59, 67];
disp(sequence)
Index: 426, Code: sequence = [19, 31, 61, 89, 107, 127, 521, 607, 1279, 2203];
disp(sequence)
Index: 429, Code: seq = [1, 8, 10, 18, 19, 100, 101, 108, 109, 110];
disp(seq);
Index: 433, Code: sequence = [1, 4, 2, 1, 3, 5, 9, 2, 6, 5];
disp(sequence);
Index: 434, Code: sequence = [1, 7, 3, 2, 0, 5, 0, 7, 9, 8];
disp(sequence);
Index: 437, Code: sequence = [3, 5, 11, 17, 31, 41, 59, 67];
disp(sequence)
Index: 440, Code: seq = [29, 57, 68, 120, 134, 140, 173, 197, 283, 313];
disp(seq);
Index: 441, Code: sequence = [24, 26, 36, 40, 184, 226, 244, 384, 391, 423];
disp(sequence)
Index: 442, Code: seq = [90, 203, 212, 235, 270, 324, 342, 352, 371, 417];
disp(seq);
Index: 443, Code: sequence = [20, 48, 95, 234, 282, 296, 352, 402, 428, 481];
disp(sequence)
Index: 444, Code: A=[62, 98, 130, 154, 290, 315, 324, 385, 408, 447];
disp(A)
Index: 446, Code: sequence = [128, 151, 153, 217, 224, 332, 382, 400, 450, 478];
disp(sequence);
Index: 447, Code: sequence = [26, 50, 114, 148, 160, 170, 274, 347, 432, 497];
disp(sequence);
Index: 448, Code: A = [48, 94, 176, 177, 219, 276, 282, 283, 459, 488];
disp(A);
Index: 449, Code: seq = [139, 252, 272, 281, 304, 361, 370, 415, 438, 500];
disp(seq);
Index: 450, Code: sequence = [15, 95, 115, 195, 240, 318, 326, 350, 432, 450];
disp(sequence)
Index: 451, Code: seq = [134, 224, 293, 378, 379, 395, 434, 451, 482, 496];
disp(seq);
Index: 452, Code: sequence = [23, 93, 142, 145, 245, 266, 296, 317, 428, 495];
disp(sequence)
Index: 453, Code: sequence = [18, 39, 71, 194, 197, 219, 263, 270, 416, 473];
disp(sequence);
Index: 454, Code: sequence = [9, 84, 144, 170, 325, 393, 401, 405, 435, 497];
disp(sequence)
Index: 455, Code: seq = [26, 40, 202, 267, 282, 340, 359, 408, 410, 495];
disp(seq)
Index: 456, Code: sequence = [34, 92, 164, 165, 209, 296, 414, 456, 467, 494];
disp(sequence)
Index: 457, Code: sequence = [16, 119, 121, 123, 135, 139, 285, 311, 409, 412];
disp(sequence)
Index: 458, Code: seq = [8, 11, 12, 103, 116, 196, 247, 254, 389, 427];
disp(seq)
Index: 459, Code: sequence = [12, 36, 96, 119, 171, 213, 221, 232, 363, 451];
disp(sequence);
Index: 460, Code: sequence = [38, 91, 142, 197, 215, 313, 316, 319, 423, 466];
disp(sequence);
Index: 461, Code: sequence = [7, 42, 147, 201, 213, 248, 310, 332, 436, 479];
disp(sequence)
Index: 462, Code: A = [27, 101, 105, 164, 245, 290, 304, 441, 449, 490];
disp(A)
Index: 463, Code: sequence = [4, 11, 29, 106, 214, 283, 296, 298, 360, 497];
disp(sequence)
Index: 464, Code: sequence = [72, 106, 139, 165, 171, 192, 199, 429, 453, 477];
disp(sequence)
Index: 465, Code: sequence = [187, 218, 260, 295, 301, 314, 379, 410, 452, 469];
disp(sequence);
Index: 466, Code: A = [29, 63, 95, 140, 150, 190, 221, 437, 482, 491];
disp(A)
Index: 467, Code: sequence = [3, 11, 84, 144, 156, 177, 188, 199, 229, 284];
disp(sequence);
Index: 468, Code: sequence = [26, 94, 98, 137, 176, 301, 323, 330, 372, 444];
disp(sequence)
Index: 469, Code: sequence = [39, 81, 88, 210, 215, 378, 416, 430, 439, 490];
disp(sequence);
Index: 470, Code: sequence = [29, 57, 68, 120, 134, 140, 173, 197, 283, 313];
disp(sequence)
Index: 471, Code: A = [24, 26, 36, 40, 184, 226, 244, 384, 391, 423];
disp(A)
Index: 472, Code: sequence = [90, 203, 212, 235, 270, 324, 342, 352, 371, 417];
disp(sequence)
Index: 473, Code: sequence = [20, 48, 95, 234, 282, 296, 352, 402, 428, 481];
disp(sequence)
Index: 474, Code: sequence = [62, 98, 130, 154, 290, 315, 324, 385, 408, 447];
disp(sequence)
Index: 475, Code: A = [2, 42, 66, 102, 153, 195, 201, 252, 306, 396];
disp(A)
Index: 476, Code: sequence = [128, 151, 153, 217, 224, 332, 382, 400, 450, 478];
disp(sequence);
Index: 477, Code: sequence = [26, 50, 114, 148, 160, 170, 274, 347, 432, 497];
disp(sequence)
Index: 478, Code: sequence = [48, 94, 176, 177, 219, 276, 282, 283, 459, 488];
disp(sequence)
Index: 479, Code: sequence = [139, 252, 272, 281, 304, 361, 370, 415, 438, 500];
disp(sequence)
Index: 480, Code: A = [15, 95, 115, 195, 240, 318, 326, 350, 432, 450];
disp(A);
Index: 481, Code: sequence = [134, 224, 293, 378, 379, 395, 434, 451, 482, 496];
disp(sequence);
Index: 482, Code: sequence = [23, 93, 142, 145, 245, 266, 296, 317, 428, 495];
disp(sequence);
Index: 483, Code: sequence = [18, 39, 71, 194, 197, 219, 263, 270, 416, 473];
disp(sequence);
Index: 484, Code: sequence = [9, 84, 144, 170, 325, 393, 401, 405, 435, 497];
disp(sequence)
Index: 485, Code: sequence = [26, 40, 202, 267, 282, 340, 359, 408, 410, 495];
disp(sequence);
Index: 486, Code: sequence = [34, 92, 164, 165, 209, 296, 414, 456, 467, 494];
disp(sequence);
Index: 487, Code: sequence = [16, 119, 121, 123, 135, 139, 285, 311, 409, 412];
disp(sequence);
Index: 488, Code: sequence = [8, 11, 12, 103, 116, 196, 247, 254, 389, 427];
disp(sequence);
Index: 489, Code: sequence = [12, 36, 96, 119, 171, 213, 221, 232, 363, 451];
disp(sequence);
Index: 490, Code: sequence = [38, 91, 142, 197, 215, 313, 316, 319, 423, 466];
disp(sequence)
Index: 491, Code: sequence = [7, 42, 147, 201, 213, 248, 310, 332, 436, 479];
disp(sequence)
Index: 492, Code: A = [27, 101, 105, 164, 245, 290, 304, 441, 449, 490];
disp(A)
Index: 493, Code: sequence = [4, 11, 29, 106, 214, 283, 296, 298, 360, 497];
disp(sequence)
Index: 494, Code: sequence = [72, 106, 139, 165, 171, 192, 199, 429, 453, 477];
disp(sequence)
Index: 495, Code: sequence = [187, 218, 260, 295, 301, 314, 379, 410, 452, 469];
disp(sequence);
Index: 496, Code: sequence = [29, 63, 95, 140, 150, 190, 221, 437, 482, 491];
disp(sequence);
Index: 497, Code: sequence = [3, 11, 84, 144, 156, 177, 188, 199, 229, 284];
disp(sequence)
Index: 498, Code: sequence = [26, 94, 98, 137, 176, 301, 323, 330, 372, 444];
disp(sequence)
Index: 499, Code: sequence = [39, 81, 88, 210, 215, 378, 416, 430, 439, 490];
disp(sequence);
Index: 500, Code: A = [29, 57, 68, 120, 134, 140, 173, 197, 283, 313];
disp(A)
Index: 501, Code: sequence = [24, 26, 36, 40, 184, 226, 244, 384, 391, 423];
disp(sequence);
Index: 502, Code: sequence = [90, 203, 212, 235, 270, 324, 342, 352, 371, 417];
disp(sequence)
Index: 503, Code: sequence = [20, 48, 95, 234, 282, 296, 352, 402, 428, 481];
disp(sequence);
Index: 504, Code: sequence = [62, 98, 130, 154, 290, 315, 324, 385, 408, 447];
disp(sequence);
Index: 505, Code: sequence = [2, 42, 66, 102, 153, 195, 201, 252, 306, 396];
disp(sequence)
Index: 506, Code: sequence = [128, 151, 153, 217, 224, 332, 382, 400, 450, 478];
disp(sequence);
Index: 507, Code: A = [26, 50, 114, 148, 160, 170, 274, 347, 432, 497];
disp(A)
Index: 508, Code: sequence = [48, 94, 176, 177, 219, 276, 282, 283, 459, 488];
disp(sequence)
Index: 509, Code: sequence = [139, 252, 272, 281, 304, 361, 370, 415, 438, 500];
disp(sequence)
Index: 510, Code: A = [15, 95, 115, 195, 240, 318, 326, 350, 432, 450];
disp(A)
Index: 511, Code: sequence = [134, 224, 293, 378, 379, 395, 434, 451, 482, 496];
disp(sequence)
Index: 512, Code: sequence = [23, 93, 142, 145, 245, 266, 296, 317, 428, 495];
disp(sequence);
Index: 513, Code: sequence = [18, 39, 71, 194, 197, 219, 263, 270, 416, 473];
disp(sequence)
Index: 514, Code: sequence = [9, 84, 144, 170, 325, 393, 401, 405, 435, 497];
disp(sequence)
Index: 515, Code: sequence = [26, 40, 202, 267, 282, 340, 359, 408, 410, 495];
disp(sequence);
Index: 516, Code: sequence = [34, 92, 164, 165, 209, 296, 414, 456, 467, 494];
disp(sequence)
Index: 517, Code: sequence = [16, 119, 121, 123, 135, 139, 285, 311, 409, 412];
disp(sequence)
Index: 518, Code: sequence = [8, 11, 12, 103, 116, 196, 247, 254, 389, 427];
disp(sequence);
Index: 519, Code: sequence = [12, 36, 96, 119, 171, 213, 221, 232, 363, 451];
disp(sequence);
Index: 520, Code: sequence = [38, 91, 142, 197, 215, 313, 316, 319, 423, 466];
disp(sequence)
Index: 521, Code: A = [7, 42, 147, 201, 213, 248, 310, 332, 436, 479];
disp(A)
Index: 522, Code: sequence = [27, 101, 105, 164, 245, 290, 304, 441, 449, 490];
disp(sequence);
Index: 523, Code: sequence = [4, 11, 29, 106, 214, 283, 296, 298, 360, 497];
disp(sequence);
Index: 524, Code: sequence = [72, 106, 139, 165, 171, 192, 199, 429, 453, 477];
disp(sequence);
Index: 525, Code: sequence = [187, 218, 260, 295, 301, 314, 379, 410, 452, 469];
disp(sequence);
Index: 526, Code: sequence = [29, 63, 95, 140, 150, 190, 221, 437, 482, 491];
disp(sequence);
Index: 527, Code: sequence = [3, 11, 84, 144, 156, 177, 188, 199, 229, 284];
disp(sequence);
Index: 528, Code: sequence = [26, 94, 98, 137, 176, 301, 323, 330, 372, 444];
disp(sequence)
Index: 529, Code: A = [39, 81, 88, 210, 215, 378, 416, 430, 439, 490];
disp(A)
Index: 530, Code: A = [29, 57, 68, 120, 134, 140, 173, 197, 283, 313];
disp(A)
Index: 531, Code: sequence = [24, 26, 36, 40, 184, 226, 244, 384, 391, 423];
disp(sequence)
Index: 532, Code: A = [90, 203, 212, 235, 270, 324, 342, 352, 371, 417];
disp(A)
Index: 533, Code: sequence = [20, 48, 95, 234, 282, 296, 352, 402, 428, 481];
disp(sequence)
Index: 534, Code: sequence = [62, 98, 130, 154, 290, 315, 324, 385, 408, 447];
disp(sequence)
Index: 535, Code: A = [2, 42, 66, 102, 153, 195, 201, 252, 306, 396];
disp(A)
Index: 536, Code: sequence = [128, 151, 153, 217, 224, 332, 382, 400, 450, 478];
disp(sequence);
Index: 537, Code: sequence = [26, 50, 114, 148, 160, 170, 274, 347, 432, 497];
disp(sequence)
Index: 538, Code: sequence = [48, 94, 176, 177, 219, 276, 282, 283, 459, 488];
disp(sequence)
Index: 539, Code: sequence = [139, 252, 272, 281, 304, 361, 370, 415, 438, 500];
disp(sequence)
Index: 540, Code: A = [15, 95, 115, 195, 240, 318, 326, 350, 432, 450];
disp(A)
Index: 541, Code: sequence = [134, 224, 293, 378, 379, 395, 434, 451, 482, 496];
disp(sequence)
Index: 542, Code: sequence = [23, 93, 142, 145, 245, 266, 296, 317, 428, 495];
disp(sequence);
Index: 543, Code: sequence = [18, 39, 71, 194, 197, 219, 263, 270, 416, 473];
disp(sequence)
Index: 544, Code: sequence = [9, 84, 144, 170, 325, 393, 401, 405, 435, 497];
disp(sequence)
Index: 545, Code: sequence = [26, 40, 202, 267, 282, 340, 359, 408, 410, 495];
disp(sequence)
Index: 546, Code: sequence = [34, 92, 164, 165, 209, 296, 414, 456, 467, 494];
disp(sequence)
Index: 547, Code: sequence = [16, 119, 121, 123, 135, 139, 285, 311, 409, 412];
disp(sequence)
Index: 548, Code: sequence = [8, 11, 12, 103, 116, 196, 247, 254, 389, 427];
disp(sequence)
Index: 549, Code: sequence = [12, 36, 96, 119, 171, 213, 221, 232, 363, 451];
disp(sequence)
Index: 550, Code: sequence = [38, 91, 142, 197, 215, 313, 316, 319, 423, 466];
disp(sequence);
Index: 551, Code: sequence = [7, 42, 147, 201, 213, 248, 310, 332, 436, 479];
disp(sequence)
Index: 552, Code: sequence = [27, 101, 105, 164, 245, 290, 304, 441, 449, 490];
disp(sequence)
Index: 553, Code: sequence = [4, 11, 29, 106, 214, 283, 296, 298, 360, 497];
disp(sequence)
Index: 554, Code: sequence = [72, 106, 139, 165, 171, 192, 199, 429, 453, 477];
disp(sequence)
Index: 555, Code: sequence = [187, 218, 260, 295, 301, 314, 379, 410, 452, 469];
disp(sequence)
Index: 556, Code: sequence = [29, 63, 95, 140, 150, 190, 221, 437, 482, 491];
disp(sequence)
Index: 557, Code: sequence = [3, 11, 84, 144, 156, 177, 188, 199, 229, 284];
disp(sequence)
Index: 558, Code: sequence = [26, 94, 98, 137, 176, 301, 323, 330, 372, 444];
disp(sequence)
Index: 559, Code: sequence = [39, 81, 88, 210, 215, 378, 416, 430, 439, 490];
disp(sequence);
Index: 560, Code: A = [29, 57, 68, 120, 134, 140, 173, 197, 283, 313];
disp(A)
Index: 561, Code: sequence = [24, 26, 36, 40, 184, 226, 244, 384, 391, 423];
disp(sequence)
Index: 562, Code: sequence = [90, 203, 212, 235, 270, 324, 342, 352, 371, 417];
disp(sequence)
Index: 563, Code: sequence = [20, 48, 95, 234, 282, 296, 352, 402, 428, 481];
disp(sequence)
Index: 564, Code: sequence = [62, 98, 130, 154, 290, 315, 324, 385, 408, 447];
disp(sequence)
Index: 565, Code: sequence = [2, 42, 66, 102, 153, 195, 201, 252, 306, 396];
disp(sequence)
Index: 566, Code: sequence = [128, 151, 153, 217, 224, 332, 382, 400, 450, 478];
disp(sequence)
Index: 567, Code: sequence = [26, 50, 114, 148, 160, 170, 274, 347, 432, 497];
disp(sequence)
Index: 568, Code: sequence = [48, 94, 176, 177, 219, 276, 282, 283, 459, 488];
disp(sequence)
Index: 569, Code: sequence = [139, 252, 272, 281, 304, 361, 370, 415, 438, 500];
disp(sequence)
Index: 570, Code: A = [15, 95, 115, 195, 240, 318, 326, 350, 432, 450];
disp(A)
Index: 571, Code: sequence = [134, 224, 293, 378, 379, 395, 434, 451, 482, 496];
disp(sequence)
Index: 572, Code: sequence = [23, 93, 142, 145, 245, 266, 296, 317, 428, 495];
disp(sequence)
Index: 573, Code: sequence = [18, 39, 71, 194, 197, 219, 263, 270, 416, 473];
disp(sequence)
Index: 574, Code: sequence = [9, 84, 144, 170, 325, 393, 401, 405, 435, 497];
disp(sequence)
Index: 575, Code: sequence = [26, 40, 202, 267, 282, 340, 359, 408, 410, 495];
disp(sequence)
Index: 576, Code: sequence = [34, 92, 164, 165, 209, 296, 414, 456, 467, 494];
disp(sequence)
Index: 577, Code: sequence = [16, 119, 121, 123, 135, 139, 285, 311, 409, 412];
disp(sequence)
Index: 578, Code: sequence = [8, 11, 12, 103, 116, 196, 247, 254, 389, 427];
disp(sequence)
Index: 579, Code: sequence = [12, 36, 96, 119, 171, 213, 221, 232, 363, 451];
disp(sequence)
Index: 580, Code: sequence = [38, 91, 142, 197, 215, 313, 316, 319, 423, 466];
disp(sequence)
Index: 581, Code: sequence = [7, 42, 147, 201, 213, 248, 310, 332, 436, 479];
disp(sequence)
Index: 582, Code: A = [27, 101, 105, 164, 245, 290, 304, 441, 449, 490];
disp(A)
Index: 583, Code: sequence = [4, 11, 29, 106, 214, 283, 296, 298, 360, 497];
disp(sequence)
Index: 584, Code: sequence = [72, 106, 139, 165, 171, 192, 199, 429, 453, 477];
disp(sequence)
Index: 585, Code: sequence = [187, 218, 260, 295, 301, 314, 379, 410, 452, 469];
disp(sequence)
Index: 586, Code: sequence = [29, 63, 95, 140, 150, 190, 221, 437, 482, 491];
disp(sequence)
Index: 587, Code: sequence = [3, 11, 84, 144, 156, 177, 188, 199, 229, 284];
disp(sequence)
Index: 588, Code: sequence = [26, 94, 98, 137, 176, 301, 323, 330, 372, 444];
disp(sequence)
Index: 589, Code: sequence = [39, 81, 88, 210, 215, 378, 416, 430, 439, 490];
disp(sequence)

In [6]:
indexes

[163,
 165,
 168,
 193,
 196,
 223,
 225,
 228,
 255,
 285,
 288,
 313,
 314,
 321,
 322,
 342,
 345,
 349,
 350,
 370,
 373,
 377,
 378,
 381,
 398,
 405,
 406,
 407,
 409,
 426,
 429,
 433,
 434,
 437,
 440,
 441,
 442,
 443,
 444,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589]

In [7]:
matlab_df.loc[indexes, 'print_code'] = 1
matlab_df

,sequence,complexity,length_type,language,q_length,GPT4_answer,a_length,temperature,real_code,print_code,no_code,explanation,no_sense,exe_out,correct_execution,Levenshtein
0,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",1,0,Matlab,168,```matlab\ndisp(2:2:20)\n```,26,1.000,1,0,0,0,0,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",True,0
1,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",1,0,Matlab,169,```matlab\nfor i = 3:3:30\n disp(i)\nend\n```,44,1.000,1,0,0,0,0,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",True,0
2,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",1,0,Matlab,170,```matlab\ndisp(4:4:40)\n```,26,1.000,1,0,0,0,0,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",True,0
3,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",1,0,Matlab,171,```matlab\ndisp(5:5:50);\n```,27,1.000,1,0,0,0,0,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",True,0
4,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",1,0,Matlab,171,```matlab\nfor i = 1:10\n disp(6*i);\nend\n```,45,1.000,1,0,0,0,0,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
585,"187, 218, 260, 295, 301, 314, 379, 410, 452, 469",4,0,Matlab,181,"```matlab\nsequence = [187, 218, 260, 295, 301...",91,0.001,0,1,0,0,0,"187, 218, 260, 295, 301, 314, 379, 410, 452, 469",True,0
586,"29, 63, 95, 140, 150, 190, 221, 437, 482, 491",4,0,Matlab,178,"```matlab\nsequence = [29, 63, 95, 140, 150, 1...",88,0.001,0,1,0,0,0,"29, 63, 95, 140, 150, 190, 221, 437, 482, 491",True,0
587,"3, 11, 84, 144, 156, 177, 188, 199, 229, 284",4,0,Matlab,177,"```matlab\nsequence = [3, 11, 84, 144, 156, 17...",87,0.001,0,1,0,0,0,"3, 11, 84, 144, 156, 177, 188, 199, 229, 284",True,0
588,"26, 94, 98, 137, 176, 301, 323, 330, 372, 444",4,0,Matlab,178,"```matlab\nsequence = [26, 94, 98, 137, 176, 3...",88,0.001,0,1,0,0,0,"26, 94, 98, 137, 176, 301, 323, 330, 372, 444",True,0
589,"39, 81, 88, 210, 215, 378, 416, 430, 439, 490",4,0,Matlab,178,"```matlab\nsequence = [39, 81, 88, 210, 215, 3...",88,0.001,0,1,0,0,0,"39, 81, 88, 210, 215, 378, 416, 430, 439, 490",True,0

In [8]:
matlab_df.to_csv("automatic_matlab.csv", index=False)

# Python

In [18]:
python_df = pd.read_csv("python_evaluation.csv")
answers = list(python_df["GPT4_answer"].values)
answers

['```python\nfor i in range(2, 21, 2):\n    print(i)\n```',
 '```python\nfor i in range(3, 31, 3):\n    print(i)\n```',
 '```python\nfor i in range(4, 41, 4):\n    print(i)\n```',
 '```python\nfor i in range(5, 55, 5):\n    print(i)\n```',
 '```python\nfor i in range(1, 11):\n    print(i * 6)\n```',
 '```python\nfor i in range(1, 11):\n    print(i * 7)\n```',
 '```python\nfor i in range(1, 11):\n    print(i * 8)\n```',
 '```python\nfor i in range(1, 11):\n    print(i * 9)\n```',
 '```python\nfor i in range(1, 11):\n    print(i*10)\n```',
 '```python\nfor i in range(1, 20, 2):\n    print(i)\n```',
 '```python\nfor i in range(2, 21, 2):\n    print(i)\n```',
 '```python\nfor i in range(11, 21):\n    print(i)\n```',
 '```python\nfor i in range(21, 31):\n    print(i)\n```',
 '```python\nfor i in range(31, 41):\n    print(i)\n```',
 '```python\nfor i in range(41, 51):\n    print(i)\n```',
 '```python\nfor i in range(51, 61):\n    print(i)\n```',
 '```python\nfor i in range(61, 71):\n    print(i)\n```',
 '```python\nfor i in range(71, 81):\n    print(i)\n```',
 '```python\nfor i in range(81, 91):\n    print(i)\n```',
 '```python\nfor i in range(91, 101):\n    print(i)\n```',
 '```python\nfor i in range(101, 111):\n    print(i)\n```',
 '```python\nfor i in range(111, 121):\n    print(i)\n```',
 '```python\nfor i in range(121, 131):\n    print(i)\n```',
 '```python\nfor i in range(131, 141):\n    print(i)\n```',
 '```python\nfor i in range(141, 151):\n    print(i)\n```',
 '```python\nfor i in range(151, 161):\n    print(i)\n```',
 '```python\nfor i in range(161, 171):\n    print(i)\n```',
 '```python\nfor i in range(171, 181):\n    print(i)\n```',
 '```python\nfor i in range(181, 191):\n    print(i)\n```',
 '```python\nfor i in range(191, 201):\n    print(i)\n```',
 '```python\nfor i in range(2, 21, 2):\n    print(i)\n```',
 '```python\nfor i in range(3, 31, 3):\n    print(i)\n```',
 '```python\nfor i in range(4, 41, 4):\n    print(i)\n```',
 '```python\nfor i in range(5, 55, 5):\n    print(i)\n```',
 '```python\nfor i in range(6, 61, 6):\n    print(i)\n```',
 '```python\nfor i in range(1, 11):\n    print(i * 7)\n```',
 '```python\nfor i in range(8, 81, 8):\n    print(i)\n```',
 '```python\nfor i in range(1, 11):\n    print(i * 9)\n```',
 '```python\nfor i in range(10, 101, 10):\n    print(i)\n```',
 '```python\nfor i in range(1, 20, 2):\n    print(i)\n```',
 '```python\nfor i in range(2, 21, 2):\n    print(i)\n```',
 '```python\nfor i in range(11, 21):\n    print(i)\n```',
 '```python\nfor i in range(21, 31):\n    print(i)\n```',
 '```python\nfor i in range(31, 41):\n    print(i)\n```',
 '```python\nfor i in range(41, 51):\n    print(i)\n```',
 '```python\nfor i in range(51, 61):\n    print(i)\n```',
 '```python\nfor i in range(61, 71):\n    print(i)\n```',
 '```python\nfor i in range(71, 81):\n    print(i)\n```',
 '```python\nfor i in range(81, 91):\n    print(i)\n```',
 '```python\nfor i in range(91, 101):\n    print(i)\n```',
 '```python\nfor i in range(101, 111):\n    print(i)\n```',
 '```python\nfor i in range(111, 121):\n    print(i)\n```',
 '```python\nfor i in range(121, 131):\n    print(i)\n```',
 '```python\nfor i in range(131, 141):\n    print(i)\n```',
 '```python\nfor i in range(141, 151):\n    print(i)\n```',
 '```python\nfor i in range(151, 161):\n    print(i)\n```',
 '```python\nfor i in range(161, 171):\n    print(i)\n```',
 '```python\nfor i in range(171, 181):\n    print(i)\n```',
 '```python\nfor i in range(181, 191):\n    print(i)\n```',
 '```python\nfor i in range(191, 201):\n    print(i)\n```',
 '```python\nfor i in range(2, 21, 2):\n    print(i)\n```',
 '```python\nfor i in range(3, 31, 3):\n    print(i)\n```',
 '```python\nfor i in range(4, 41, 4):\n    print(i)\n```',
 '```python\nfor i in range(5, 51, 5):\n    print(i)\n```',
 '```python\nfor i in range(6, 61, 6):\n    print(i)\n```',
 '```python\nfor i in range(1, 11):\n    print(i * 7)\n```',
 '```python\nfor i in range(1, 11):\n    print(i * 8)\n```',
 '```python\nfor i in range(1, 11):\n    print(9 * i)\n```',
 '```python\nfor i in range(10, 101, 10):\n    print(i)\n```',
 '```python\nfor i in range(1, 20, 2):\n    print(i)\n```',
 '```python\nfor i in range(1, 11):\n    print(i*2)\n```',
 '```python\nfor i in range(11, 21):\n    print(i)\n```',
 '```python\nfor i in range(21, 31):\n    print(i)\n```',
 '```python\nfor i in range(31, 41):\n    print(i)\n```',
 '```python\nfor i in range(41, 51):\n    print(i)\n```',
 '```python\nfor i in range(51, 61):\n    print(i)\n```',
 '```python\nfor i in range(61, 71):\n    print(i)\n```',
 '```python\nfor i in range(71, 81):\n    print(i)\n```',
 '```python\nfor i in range(81, 91):\n    print(i)\n```',
 '```python\nfor i in range(91, 101):\n    print(i)\n```',
 '```python\nfor i in range(101, 111):\n    print(i)\n```',
 '```python\nfor i in range(111, 121):\n    print(i)\n```',
 '```python\nfor i in range(121, 131):\n    print(i)\n```',
 '```python\nfor i in range(131, 141):\n    print(i)\n```',
 '```python\nfor i in range(141, 151):\n    print(i)\n```',
 '```python\nfor i in range(151, 161):\n    print(i)\n```',
 '```python\nfor i in range(161, 171):\n    print(i)\n```',
 '```python\nfor i in range(171, 181):\n    print(i)\n```',
 '```python\nfor i in range(181, 191):\n    print(i)\n```',
 '```python\nfor i in range(191, 201):\n    print(i)\n```',
 '```python\nfor i in range(2, 21, 2):\n    print(i)\n```',
 '```python\nfor i in range(3, 31, 3):\n    print(i)\n```',
 '```python\nfor i in range(4, 41, 4):\n    print(i)\n```',
 '```python\nfor i in range(5, 55, 5):\n    print(i)\n```',
 '```python\nfor i in range(6, 61, 6):\n    print(i)\n```',
 '```python\nfor i in range(1, 11):\n    print(i * 7)\n```',
 '```python\nfor i in range(8, 81, 8):\n    print(i)\n```',
 '```python\nfor i in range(1, 11):\n    print(i * 9)\n```',
 '```python\nfor i in range(10, 101, 10):\n    print(i)\n```',
 '```python\nfor i in range(1, 20, 2):\n    print(i)\n```',
 '```python\nfor i in range(2, 21, 2):\n    print(i)\n```',
 '```python\nfor i in range(11, 21):\n    print(i)\n```',
 '```python\nfor i in range(21, 31):\n    print(i)\n```',
 '```python\nfor i in range(31, 41):\n    print(i)\n```',
 '```python\nfor i in range(41, 51):\n    print(i)\n```',
 '```python\nfor i in range(51, 61):\n    print(i)\n```',
 '```python\nfor i in range(61, 71):\n    print(i)\n```',
 '```python\nfor i in range(71, 81):\n    print(i)\n```',
 '```python\nfor i in range(81, 91):\n    print(i)\n```',
 '```python\nfor i in range(91, 101):\n    print(i)\n```',
 '```python\nfor i in range(101, 111):\n    print(i)\n```',
 '```python\nfor i in range(111, 121):\n    print(i)\n```',
 '```python\nfor i in range(121, 131):\n    print(i)\n```',
 '```python\nfor i in range(131, 141):\n    print(i)\n```',
 '```python\nfor i in range(141, 151):\n    print(i)\n```',
 '```python\nfor i in range(151, 161):\n    print(i)\n```',
 '```python\nfor i in range(161, 171):\n    print(i)\n```',
 '```python\nfor i in range(171, 181):\n    print(i)\n```',
 '```python\nfor i in range(181, 191):\n    print(i)\n```',
 '```python\nfor i in range(191, 201):\n    print(i)\n```',
 '```python\nfor i in range(2, 21, 2):\n    print(i)\n```',
 '```python\nfor i in range(3, 31, 3):\n    print(i)\n```',
 '```python\nfor i in range(4, 41, 4):\n    print(i)\n```',
 '```python\nfor i in range(5, 55, 5):\n    print(i)\n```',
 '```python\nfor i in range(6, 61, 6):\n    print(i)\n```',
 '```python\nfor i in range(1, 11):\n    print(i * 7)\n```',
 '```python\nfor i in range(8, 81, 8):\n    print(i)\n```',
 '```python\nfor i in range(1, 11):\n    print(i * 9)\n```',
 '```python\nfor i in range(10, 101, 10):\n    print(i)\n```',
 '```python\nfor i in range(1, 20, 2):\n    print(i)\n```',
 '```python\nfor i in range(2, 21, 2):\n    print(i)\n```',
 '```python\nfor i in range(11, 21):\n    print(i)\n```',
 '```python\nfor i in range(21, 31):\n    print(i)\n```',
 '```python\nfor i in range(31, 41):\n    print(i)\n```',
 '```python\nfor i in range(41, 51):\n    print(i)\n```',
 '```python\nfor i in range(51, 61):\n    print(i)\n```',
 '```python\nfor i in range(61, 71):\n    print(i)\n```',
 '```python\nfor i in range(71, 81):\n    print(i)\n```',
 '```python\nfor i in range(81, 91):\n    print(i)\n```',
 '```python\nfor i in range(91, 101):\n    print(i)\n```',
 '```python\nfor i in range(101, 111):\n    print(i)\n```',
 '```python\nfor i in range(111, 121):\n    print(i)\n```',
 '```python\nfor i in range(121, 131):\n    print(i)\n```',
 '```python\nfor i in range(131, 141):\n    print(i)\n```',
 '```python\nfor i in range(141, 151):\n    print(i)\n```',
 '```python\nfor i in range(151, 161):\n    print(i)\n```',
 '```python\nfor i in range(161, 171):\n    print(i)\n```',
 '```python\nfor i in range(171, 181):\n    print(i)\n```',
 '```python\nfor i in range(181, 191):\n    print(i)\n```',
 '```python\nfor i in range(191, 201):\n    print(i)\n```',
 '```python\ndef is_prime(n):\n    if n <= 1:\n        return False\n    for i in range(2, int(n**0.5) + 1):\n        if n % i == 0:\n            return False\n    return True\n\ndef generate_primes(n):\n    primes = []\n    num = 2\n    while len(primes) < n:\n        if is_prime(num):\n            primes.append(num)\n        num += 1\n    return primes\n\nprint(generate_primes(10))\n```',
 '```python\ndef fibonacci_sequence(n):\n    sequence = [1, 1]\n    while len(sequence) < n:\n        sequence.append(sequence[-1] + sequence[-2])\n    return sequence[:n]\n\nprint(fibonacci_sequence(10))\n```',
 '```python\nfor i in range(10):\n    print(2**i)\n```',
 '```python\nfor i in range(10):\n    print(3**i)\n```',
 '```python\nfor i in range(1, 11):\n    print(i**2)\n```',
 '```python\nfor i in range(1, 11):\n    print(i**3)\n```',
 '```python\ndef sequence(n):\n    result = 1\n    for i in range(1, n+1):\n        result *= i\n        print(result)\n\nsequence(10)\n```',
 '```python\nfor i in range(1, 11):\n    print(i * (i + 1) // 2, end=", ")\n```',
 '```python\na, b, c = 2, 1, 3\nprint(a, b, end=", ")\nfor _ in range(8):\n    print(c, end=", ")\n    a, b, c = b, c, a + b + c\n```',
 '```python\nfor n in range(10):\n    print(((1+5**0.5)/2)**n/5**0.5 - ((1-5**0.5)/2)**n/5**0.5)\n```',
 '```python\nfor i in range(1, 11):\n    print(i**i)\n```',
 '```python\ndef sequence(n):\n    return [int((2 * i)! / (i! * (i + 1)!)) for i in range(n)]\n\nprint(sequence(10))\n```',
 '```python\ndef is_prime(n):\n    if n <= 1:\n        return False\n    for i in range(2, int(n**0.5) + 1):\n        if n % i == 0:\n            return False\n    return True\n\ndef generate_primes(n):\n    count, num = 0, 2\n    while count < n:\n        if is_prime(num):\n            print(num, end=", ")\n            count += 1\n        num += 1\n\ngenerate_primes(10)\n```',
 "```python\nfor n in range(1, 28):\n    if n % 2 == 0 or n % 3 == 0:\n        print(n, end=', ')\n```",
 '```python\nfor i in range(1, 11):\n    print(bin(i)[2:])\n```',
 '```python\nfor n in range(10):\n    print([0, 1, 81, 512, 2401, 4913, 5832, 17576, 19683, 234256][n])\n```',
 '```python\nfact = [1]\nfor i in range(1, 10):\n    fact.append(fact[-1] * i)\n \ndef is_curious(n):\n    return n == sum(fact[int(d)] for d in str(n))\n \nprint([n for n in range(1, 100000) if is_curious(n)])\n```',
 '```python\nfor i in range(1, 11):\n    print((i ** 2) + i - 1)\n```',
 "```python\nfor i in range(1, 111):\n    if '8' in str(i) or '9' in str(i):\n        print(i)\n```",
 '```python\nfor x in range(2, 12):\n    print(2**(2**x) + 1)\n```',
 '```python\nsequence = [1, 2]\nwhile len(sequence) < 10:\n    new_element = sequence[-1] + sequence[-2]\n    if len(sequence) % 2 == 0:\n        new_element -= len(sequence)//2\n    else:\n        new_element += sequence[-2]\n    sequence.append(new_element)\nprint(sequence)\n```',
 '```python\ndef generate_sequence(n):\n    if n < 3:\n        return [1, 2][:n]\n    seq = [1, 2, 4]\n    for i in range(3, n):\n        next_value = seq[-1] + seq[-2] + (seq[-3] if i % 2 == 0 else -seq[-3])\n        seq.append(next_value)\n    return seq\n\nprint(generate_sequence(10))\n```',
 '```python\nfor i in range(1, 11):\n    print(i**3 - (i-1)**3)\n```',
 '```python\nfor i in range(10):\n    print(bin(i).count("1"))\n```',
 '```python\ndef sequence(n):\n    if n < 2:\n        return n + 1\n    if n == 2:\n        return 5\n    seq = [1, 2, 5]\n    for i in range(3, n+1):\n        term = ((i+2) * seq[-1] - (i-1) * seq[-2] + (i-3) * seq[-3]) // i\n        seq.append(term)\n    return seq\n\nprint(sequence(9))\n```',
 '```python\ndef is_prime(n):\n    if n <= 1:\n        return False\n    for i in range(2, int(n**0.5) + 1):\n        if n % i == 0:\n            return False\n    return True\n\ndef generate_primes(n):\n    primes = []\n    num = 2\n    while len(primes) < n:\n        if is_prime(num):\n            primes.append(num)\n        num += 1\n    return primes\n\nprint(generate_primes(10))\n```',
 "```python\ndef describe(number):\n    result = ''\n    last_char = number[0]\n    count = 0\n    for char in number:\n        if char == last_char:\n            count += 1\n        else:\n            result += str(count) + last_char\n            count = 1\n            last_char = char\n    result += str(count) + last_char\n    return result\n\nnumber = '1'\nfor _ in range(5):\n    print(number)\n    number = describe(number)\n```",
 '```python\ndef is_prime(num):\n    if num < 2:\n        return False\n    for i in range(2, int(num**0.5) + 1):\n        if num % i == 0:\n            return False\n    return True\n\ndef generate_primes(n):\n    primes = []\n    num = 2\n    while len(primes) < n:\n        if is_prime(num):\n            primes.append(num)\n        num += 1\n    return primes\n\nprint(generate_primes(10))\n```',
 '```python\nfor i in range(10):\n    print(2**i)\n```',
 '```python\nfor i in range(10):\n    print(2**(i+1) - 1)\n```',
 "```python\ndef is_prime(n):\n    if n <= 1:\n        return False\n    for i in range(2, int(n**0.5) + 1):\n        if n % i == 0:\n            return False\n    return True\n\ndef generate_primes(n):\n    count, num = 0, 2\n    while count < n:\n        if is_prime(num):\n            print(num, end=', ' if count < n - 1 else '')\n            count += 1\n        num += 1\n\ngenerate_primes(10)\n```",
 '```python\ndef fibonacci(n):\n    a, b = 0, 1\n    sequence = []\n    while len(sequence) < n:\n        sequence.append(b)\n        a, b = b, a + b\n    return sequence\n\nprint(fibonacci(10))\n```',
 '```python\nfor i in range(10):\n    print(2**i)\n```',
 '```python\nfor i in range(10):\n    print(3**i)\n```',
 '```python\nfor i in range(1, 11):\n    print(i**2)\n```',
 '```python\nfor i in range(1, 11):\n    print(i**3)\n```',
 '```python\ndef sequence(n):\n    if n == 1:\n        return 1\n    else:\n        return n * sequence(n-1)\n\nfor i in range(1, 11):\n    print(sequence(i), end=", " if i < 10 else "")\n```',
 '```python\nfor i in range(1, 11):\n    print(int(i*(i+1)/2))\n```',
 '```python\ndef sequence(n):\n    if n == 1:\n        return 2\n    elif n == 2:\n        return 1\n    elif n == 3:\n        return 3\n    else:\n        return sequence(n-1) + sequence(n-2) + sequence(n-3)\n\nfor i in range(1, 11):\n    print(sequence(i), end=", " if i < 10 else "")\n```',
 '```python\ndef sequence(n):\n    if n == 0:\n        return 0\n    elif n == 1:\n        return 1\n    else:\n        return sequence(n-1)*2 + sequence(n-2)\n\nfor i in range(10):\n    print(sequence(i))\n```',
 '```python\nfor i in range(1, 11):\n    print(i**i)\n```',
 '```python\ndef sequence(n):\n    return [int(1 * 2 ** i * 5 ** (n - i) / (i + 1) / (n - i)) for i in range(n)]\n\nprint(sequence(10))\n```',
 '```python\ndef is_prime(n):\n    if n <= 1:\n        return False\n    for i in range(2, int(n**0.5) + 1):\n        if n % i == 0:\n            return False\n    return True\n\ndef generate_primes(n):\n    primes = []\n    num = 2\n    while len(primes) < n:\n        if is_prime(num):\n            primes.append(num)\n        num += 1\n    return primes\n\nprint(generate_primes(10))\n```',
 '```python\nfor i in range(1, 27):\n    if i % 2 == 0 or i % 3 == 0 or i % 5 == 0:\n        print(i)\n```',
 '```python\nfor i in range(1, 11):\n    print(bin(i)[2:])\n```',
 '```python\nfor i in range(10):\n    print(i**i if i in [0,1] else (i-1)**i)\n```',
 '```python\ndef factorial(n):\n    if n == 0:\n        return 1\n    else:\n        return n * factorial(n-1)\n\ndef is_curious(n):\n    return n == sum(factorial(int(digit)) for digit in str(n))\n\ncurious_numbers = [n for n in range(1, 50000) if is_curious(n)]\n\nprint(curious_numbers)\n```',
 '```python\nfor i in range(1, 11):\n    print((i**3) - (i**2) + i)\n```',
 "```python\nprint([x for x in range(1, 111) if '8' in str(x) or '9' in str(x)])\n```",
 '```python\nfor i in range(2, 12):\n    print(2**(2**i)-1)\n```',
 '```python\ndef sequence(n):\n    if n == 1: return 1\n    if n == 2: return 2\n    if n in [3, 4]: return sequence(n - 1) * 2\n    if n == 5: return sequence(n - 1) + 1\n    if n == 6: return sequence(n - 1) + 5\n    if n == 7: return sequence(n - 1) + 10\n    if n == 8: return sequence(n - 1) + 20\n    if n == 9: return sequence(n - 1) + 31\n    if n == 10: return sequence(n - 1) + 31\n\nfor i in range(1, 11):\n    print(sequence(i), end=", ")\n```',
 "```python\ndef sequence(n):\n    if n == 1: return 1\n    if n == 2: return 2\n    if n == 3: return 4\n    a, b, c = 1, 2, 4\n    for _ in range(4, n + 1):\n        a, b, c = b, c, a + b + c\n    return c\n\nfor i in range(1, 11):\n    print(sequence(i), end=', ')\n```",
 '```python\nfor n in range(1, 11):\n    print(int(n * (n + 1) * 1.5))\n```',
 "```python\nsequence = [bin(i).count('1') for i in range(10)]\nprint(sequence)\n```",
 '```python\ndef sequence(n):\n    if n == 0:\n        return 1\n    else:\n        return sequence(n-1) * (4*n-2) // (n+1)\n\nfor i in range(10):\n    print(sequence(i))\n```',
 '```python\ndef is_prime(n):\n    if n <= 1:\n        return False\n    for i in range(2, int(n**0.5) + 1):\n        if n % i == 0:\n            return False\n    return True\n\ndef generate_primes(n):\n    primes = []\n    num = 2\n    while len(primes) < n:\n        if is_prime(num):\n            primes.append(num)\n        num += 1\n    return primes\n\nprint(generate_primes(10))\n```',
 '```python\ndef look_and_say_sequence(n):\n    result = "1"\n    for _ in range(n - 1):\n        current = result[0]\n        count = 1\n        temp_result = ""\n        for char in result[1:]:\n            if char == current:\n                count += 1\n            else:\n                temp_result += str(count) + current\n                current = char\n                count = 1\n        temp_result += str(count) + current\n        result = temp_result\n    return result\n\nfor i in range(1, 6):\n    print(look_and_say_sequence(i))\n```',
 '```python\ndef is_prime(n):\n    if n <= 1:\n        return False\n    for i in range(2, int(n**0.5) + 1):\n        if n % i == 0:\n            return False\n    return True\n\ndef generate_primes(n):\n    primes = []\n    num = 2\n    while len(primes) < n:\n        if is_prime(num):\n            primes.append(num)\n        num += 1\n    return primes\n\nprint(generate_primes(10))\n```',
 '```python\nfor i in range(10):\n    print(2 ** i)\n```',
 '```python\nfor i in range(10):\n    print((2 ** (i + 1)) - 1)\n```',
 '```python\ndef is_prime(n):\n    if n <= 1:\n        return False\n    for i in range(2, int(n**0.5) + 1):\n        if n % i == 0:\n            return False\n    return True\n\ndef generate_primes(n):\n    primes = []\n    num = 2\n    while len(primes) < n:\n        if is_prime(num):\n            primes.append(num)\n        num += 1\n    return primes\n\nprint(generate_primes(10))\n```',
 '```python\ndef fib(n):\n    a, b = 0, 1\n    for _ in range(n):\n        yield b\n        a, b = b, a + b\n\nprint(list(fib(10)))\n```',

In [35]:
def preprocess_code_p(code):
    # Remove leading and trailing substrings
    code = re.sub(r'^```(?:Python|python)?\n|\n```$', '', code)
    return code

def find_matched_programs_p(python_programs):
    # Regular expressions for each rule
    patterns = [
        # Rule: Declaration of a variable as a list of numbers and then print of such variable
        r'^(?!.*(?:for|while|import|def))(?!.*[-+*/^:])(?!.*:).*\bsequence\s*=\s*\[\s*\d+(?:,\s*\d+)*\s*\]\s*;?\s*\bprint\s*\(\s*sequence\s*\)\s*$',
        # Rule: Declaration of a variable as a list or sequence of numbers and then print of such variable
        r'^(?!.*(?:for|while|import|def))(?!.*[-+*/^:])(?!.*:).*\bprint\s*\(\s*\w+\s*=\s*\[\s*\d+(?:,\s*\d+)*\s*\]\s*\)\s*$',
        # Rule: List of variables to represent a sequence of numbers and then print such list of variables
        r'^(?!.*(?:for|while|import|def))(?!.*[-+*/^:])(?!.*:).*\bprint\s*\(\s*(?:\w+(?:\s*,\s*\w+)*)\s*\)\s*$',
        # Rule: Program that prints a list or sequence of numbers
        r'^(?!.*(?:for|while|import|def))(?!.*[-+*/^:])(?!.*:).*\bprint\s*\(\s*(?:\[\s*\d+(?:,\s*\d+)*\s*\]|\d+(?:,\s*\d+)*)\s*\)\s*$',
    ]
    
    # List to store matched programs and their indices
    matched_programs = []
    indexes = []

    # Iterate over each Python code string
    for i, program in enumerate(python_programs):
        # Preprocess the code string
        program = preprocess_code_p(program)
        # Flag to track if program has been matched by any rule
        matched = False
        # Iterate over each rule
        for pattern in patterns:
            # Check if the program matches the pattern
            if re.match(pattern, program, re.MULTILINE):
                matched_programs.append(program)
                indexes.append(i)
                matched = True
                break  # Move to the next program if a match is found
        # If no match is found, print a message
        if not matched:
            print(f"No match found for program at index {i}")
    
    return matched_programs, indexes

In [36]:
matched, indexes = find_matched_programs_p(answers)

for i in range(len(matched)):
    print(f"Match found at index {indexes[i]}:")
    print(matched[i])

No match found for program at index 0
No match found for program at index 1
No match found for program at index 2
No match found for program at index 3
No match found for program at index 4
No match found for program at index 5
No match found for program at index 6
No match found for program at index 7
No match found for program at index 8
No match found for program at index 9
No match found for program at index 10
No match found for program at index 11
No match found for program at index 12
No match found for program at index 13
No match found for program at index 14
No match found for program at index 15
No match found for program at index 16
No match found for program at index 17
No match found for program at index 18
No match found for program at index 19
No match found for program at index 20
No match found for program at index 21
No match found for program at index 22
No match found for program at index 23
No match found for program at index 24
No match found for program at index 25
No match found for program at index 26
No match found for program at index 27
No match found for program at index 28
No match found for program at index 29
No match found for program at index 30
No match found for program at index 31
No match found for program at index 32
No match found for program at index 33
No match found for program at index 34
No match found for program at index 35
No match found for program at index 36
No match found for program at index 37
No match found for program at index 38
No match found for program at index 39
No match found for program at index 40
No match found for program at index 41
No match found for program at index 42
No match found for program at index 43
No match found for program at index 44
No match found for program at index 45
No match found for program at index 46
No match found for program at index 47
No match found for program at index 48
No match found for program at index 49
No match found for program at index 50
No match found for program at index 51
No match found for program at index 52
No match found for program at index 53
No match found for program at index 54
No match found for program at index 55
No match found for program at index 56
No match found for program at index 57
No match found for program at index 58
No match found for program at index 59
No match found for program at index 60
No match found for program at index 61
No match found for program at index 62
No match found for program at index 63
No match found for program at index 64
No match found for program at index 65
No match found for program at index 66
No match found for program at index 67
No match found for program at index 68
No match found for program at index 69
No match found for program at index 70
No match found for program at index 71
No match found for program at index 72
No match found for program at index 73
No match found for program at index 74
No match found for program at index 75
No match found for program at index 76
No match found for program at index 77
No match found for program at index 78
No match found for program at index 79
No match found for program at index 80
No match found for program at index 81
No match found for program at index 82
No match found for program at index 83
No match found for program at index 84
No match found for program at index 85
No match found for program at index 86
No match found for program at index 87
No match found for program at index 88
No match found for program at index 89
No match found for program at index 90
No match found for program at index 91
No match found for program at index 92
No match found for program at index 93
No match found for program at index 94
No match found for program at index 95
No match found for program at index 96
No match found for program at index 97
No match found for program at index 98
No match found for program at index 99
No match found for program at index 100
No match found for program at index 101
No match found for program at index 102
No match found for program at index 103
No match found for program at index 104
No match found for program at index 105
No match found for program at index 106
No match found for program at index 107
No match found for program at index 108
No match found for program at index 109
No match found for program at index 110
No match found for program at index 111
No match found for program at index 112
No match found for program at index 113
No match found for program at index 114
No match found for program at index 115
No match found for program at index 116
No match found for program at index 117
No match found for program at index 118
No match found for program at index 119
No match found for program at index 120
No match found for program at index 121
No match found for program at index 122
No match found for program at index 123
No match found for program at index 124
No match found for program at index 125
No match found for program at index 126
No match found for program at index 127
No match found for program at index 128
No match found for program at index 129
No match found for program at index 130
No match found for program at index 131
No match found for program at index 132
No match found for program at index 133
No match found for program at index 134
No match found for program at index 135
No match found for program at index 136
No match found for program at index 137
No match found for program at index 138
No match found for program at index 139
No match found for program at index 140
No match found for program at index 141
No match found for program at index 142
No match found for program at index 143
No match found for program at index 144
No match found for program at index 145
No match found for program at index 146
No match found for program at index 147
No match found for program at index 148
No match found for program at index 149
No match found for program at index 150
No match found for program at index 151
No match found for program at index 152
No match found for program at index 153
No match found for program at index 154
No match found for program at index 155
No match found for program at index 156
No match found for program at index 157
No match found for program at index 158
No match found for program at index 159
No match found for program at index 160
No match found for program at index 161
No match found for program at index 162
No match found for program at index 163
No match found for program at index 164
No match found for program at index 165
No match found for program at index 166
No match found for program at index 167
No match found for program at index 168
No match found for program at index 169
No match found for program at index 170
No match found for program at index 171
No match found for program at index 172
No match found for program at index 173
No match found for program at index 174
No match found for program at index 175
No match found for program at index 176
No match found for program at index 177
No match found for program at index 178
No match found for program at index 179
No match found for program at index 180
No match found for program at index 181
No match found for program at index 182
No match found for program at index 183
No match found for program at index 184
No match found for program at index 185
No match found for program at index 186
No match found for program at index 187
No match found for program at index 188
No match found for program at index 189
No match found for program at index 190
No match found for program at index 191
No match found for program at index 192
No match found for program at index 193
No match found for program at index 194
No match found for program at index 195
No match found for program at index 196
No match found for program at index 197
No match found for program at index 198
No match found for program at index 199
No match found for program at index 200
No match found for program at index 201
No match found for program at index 202
No match found for program at index 203
No match found for program at index 204
No match found for program at index 205
No match found for program at index 206
No match found for program at index 207
No match found for program at index 208
No match found for program at index 209
No match found for program at index 210
No match found for program at index 211
No match found for program at index 212
No match found for program at index 213
No match found for program at index 214
No match found for program at index 215
No match found for program at index 216
No match found for program at index 217
No match found for program at index 218
No match found for program at index 219
No match found for program at index 220
No match found for program at index 221
No match found for program at index 222
No match found for program at index 223
No match found for program at index 224
No match found for program at index 225
No match found for program at index 226
No match found for program at index 227
No match found for program at index 228
No match found for program at index 229
No match found for program at index 230
No match found for program at index 231
No match found for program at index 232
No match found for program at index 233
No match found for program at index 234
No match found for program at index 235
No match found for program at index 236
No match found for program at index 237
No match found for program at index 238
No match found for program at index 239
No match found for program at index 240
No match found for program at index 241
No match found for program at index 242
No match found for program at index 243
No match found for program at index 244
No match found for program at index 245
No match found for program at index 246
No match found for program at index 247
No match found for program at index 248
No match found for program at index 249
No match found for program at index 250
No match found for program at index 251
No match found for program at index 252
No match found for program at index 253
No match found for program at index 254
No match found for program at index 255
No match found for program at index 256
No match found for program at index 257
No match found for program at index 258
No match found for program at index 259
No match found for program at index 260
No match found for program at index 261
No match found for program at index 262
No match found for program at index 263
No match found for program at index 264
No match found for program at index 265
No match found for program at index 266
No match found for program at index 267
No match found for program at index 268
No match found for program at index 269
No match found for program at index 270
No match found for program at index 271
No match found for program at index 272
No match found for program at index 273
No match found for program at index 274
No match found for program at index 275
No match found for program at index 276
No match found for program at index 277
No match found for program at index 278
No match found for program at index 279
No match found for program at index 280
No match found for program at index 281
No match found for program at index 282
No match found for program at index 283
No match found for program at index 284
No match found for program at index 285
No match found for program at index 286
No match found for program at index 287
No match found for program at index 288
No match found for program at index 289
No match found for program at index 290
No match found for program at index 291
No match found for program at index 292
No match found for program at index 293
No match found for program at index 294
No match found for program at index 295
No match found for program at index 296
No match found for program at index 297
No match found for program at index 298
No match found for program at index 299
No match found for program at index 300
No match found for program at index 301
No match found for program at index 302
No match found for program at index 303
No match found for program at index 304
No match found for program at index 305
No match found for program at index 306
No match found for program at index 307
No match found for program at index 308
No match found for program at index 309
No match found for program at index 310
No match found for program at index 311
No match found for program at index 312
No match found for program at index 313
No match found for program at index 314
No match found for program at index 315
No match found for program at index 316
No match found for program at index 318
No match found for program at index 319
No match found for program at index 320
No match found for program at index 321
No match found for program at index 323
No match found for program at index 324
No match found for program at index 325
No match found for program at index 326
No match found for program at index 327
No match found for program at index 328
No match found for program at index 329
No match found for program at index 330
No match found for program at index 331
No match found for program at index 332
No match found for program at index 333
No match found for program at index 334
No match found for program at index 335
No match found for program at index 336
No match found for program at index 337
No match found for program at index 338
No match found for program at index 339
No match found for program at index 340
No match found for program at index 341
No match found for program at index 342
No match found for program at index 343
No match found for program at index 344
No match found for program at index 345
No match found for program at index 346
No match found for program at index 347
No match found for program at index 348
No match found for program at index 351
No match found for program at index 352
No match found for program at index 353
No match found for program at index 354
No match found for program at index 355
No match found for program at index 356
No match found for program at index 357
No match found for program at index 358
No match found for program at index 359
No match found for program at index 360
No match found for program at index 361
No match found for program at index 362
No match found for program at index 363
No match found for program at index 364
No match found for program at index 365
No match found for program at index 366
No match found for program at index 367
No match found for program at index 368
No match found for program at index 369
No match found for program at index 370
No match found for program at index 371
No match found for program at index 372
No match found for program at index 373
No match found for program at index 374
No match found for program at index 375
No match found for program at index 376
No match found for program at index 378
No match found for program at index 379
No match found for program at index 380
No match found for program at index 381
No match found for program at index 382
No match found for program at index 383
No match found for program at index 384
No match found for program at index 385
No match found for program at index 386
No match found for program at index 387
No match found for program at index 388
No match found for program at index 389
No match found for program at index 390
No match found for program at index 391
No match found for program at index 392
No match found for program at index 393
No match found for program at index 394
No match found for program at index 395
No match found for program at index 396
No match found for program at index 397
No match found for program at index 398
No match found for program at index 399
No match found for program at index 400
No match found for program at index 401
No match found for program at index 402
No match found for program at index 403
No match found for program at index 404
No match found for program at index 408
No match found for program at index 409
No match found for program at index 410
No match found for program at index 411
No match found for program at index 412
No match found for program at index 413
No match found for program at index 414
No match found for program at index 415
No match found for program at index 416
No match found for program at index 417
No match found for program at index 418
No match found for program at index 419
No match found for program at index 420
No match found for program at index 421
No match found for program at index 422
No match found for program at index 423
No match found for program at index 424
No match found for program at index 425
No match found for program at index 426
No match found for program at index 427
No match found for program at index 428
No match found for program at index 429
No match found for program at index 430
No match found for program at index 431
No match found for program at index 432
No match found for program at index 436
No match found for program at index 437
No match found for program at index 438
No match found for program at index 439
No match found for program at index 440
No match found for program at index 444
No match found for program at index 445
No match found for program at index 446
No match found for program at index 449
No match found for program at index 451
No match found for program at index 457
No match found for program at index 459
No match found for program at index 460
No match found for program at index 462
No match found for program at index 464
No match found for program at index 466
No match found for program at index 468
No match found for program at index 469
No match found for program at index 470
No match found for program at index 471
No match found for program at index 472
No match found for program at index 475
No match found for program at index 476
No match found for program at index 478
No match found for program at index 482
No match found for program at index 484
No match found for program at index 492
No match found for program at index 493
No match found for program at index 495
No match found for program at index 497
No match found for program at index 499
No match found for program at index 500
No match found for program at index 501
No match found for program at index 502
No match found for program at index 505
No match found for program at index 511
No match found for program at index 512
No match found for program at index 521
No match found for program at index 522
No match found for program at index 532
No match found for program at index 535
No match found for program at index 541
No match found for program at index 562
No match found for program at index 565
No match found for program at index 582
Match found at index 317:
sequence = [1, 8, 10, 18, 19, 100, 101, 108, 109, 110]
print(sequence)
Match found at index 322:
sequence = [1, 7, 3, 2, 0, 5, 0, 7, 9, 8]
print(sequence)
Match found at index 349:
sequence = [1, 4, 2, 1, 3, 5, 9, 2, 6, 5]
print(sequence)
Match found at index 350:
sequence = [1, 7, 3, 2, 0, 5, 0, 7, 9, 8]
print(sequence)
Match found at index 377:
sequence = [1, 4, 2, 1, 3, 5, 9, 2, 6, 5]
print(sequence)
Match found at index 405:
sequence = [1, 4, 2, 1, 3, 5, 9, 2, 6, 5]
print(sequence)
Match found at index 406:
sequence = [1, 7, 3, 2, 0, 5, 0, 7, 9, 8]
print(sequence)
Match found at index 407:
sequence = [1, 0, 1, 2, 3, 1, 6, 11]
print(sequence)
Match found at index 433:
sequence = [1, 4, 2, 1, 3, 5, 9, 2, 6, 5]
print(sequence)
Match found at index 434:
sequence = [1, 7, 3, 2, 0, 5, 0, 7, 9, 8]
print(sequence)
Match found at index 435:
sequence = [1, 0, 1, 2, 3, 1, 6, 11]
print(sequence)
Match found at index 441:
print([24, 26, 36, 40, 184, 226, 244, 384, 391, 423])
Match found at index 442:
print([90, 203, 212, 235, 270, 324, 342, 352, 371, 417])
Match found at index 443:
sequence = [20, 48, 95, 234, 282, 296, 352, 402, 428, 481]
print(sequence)
Match found at index 447:
sequence = [26, 50, 114, 148, 160, 170, 274, 347, 432, 497]
print(sequence)

In [38]:
len(indexes)

120

In [39]:
python_df.loc[indexes, 'print_code'] = 1
python_df

,sequence,complexity,length_type,language,q_length,GPT4_answer,a_length,temperature,real_code,print_code,no_code,explanation,no_sense,exe_out,correct_execution,Levenshtein
0,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",1.0,0.0,Python,168.0,"```python\nfor i in range(2, 21, 2):\n prin...",52.0,1.000,0.0,0,0.0,0.0,0,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",True,0
1,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",1.0,0.0,Python,169.0,"```python\nfor i in range(3, 31, 3):\n prin...",52.0,1.000,0.0,0,0.0,0.0,0,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",True,0
2,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",1.0,0.0,Python,170.0,"```python\nfor i in range(4, 41, 4):\n prin...",52.0,1.000,0.0,0,0.0,0.0,0,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",True,0
3,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",1.0,0.0,Python,171.0,"```python\nfor i in range(5, 55, 5):\n prin...",52.0,1.000,0.0,0,0.0,0.0,0,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",True,0
4,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",1.0,0.0,Python,171.0,"```python\nfor i in range(1, 11):\n print(i...",53.0,1.000,0.0,0,0.0,0.0,0,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
585,"187, 218, 260, 295, 301, 314, 379, 410, 452, 469",4.0,0.0,Python,181.0,"```python\nsequence = [187, 218, 260, 295, 301...",91.0,0.001,0.0,1,0.0,0.0,0,"[187, 218, 260, 295, 301, 314, 379, 410, 452, ...",False,2
586,"29, 63, 95, 140, 150, 190, 221, 437, 482, 491",4.0,0.0,Python,178.0,"```python\nsequence = [29, 63, 95, 140, 150, 1...",88.0,0.001,0.0,1,0.0,0.0,0,"[29, 63, 95, 140, 150, 190, 221, 437, 482, 491]",False,2
587,"3, 11, 84, 144, 156, 177, 188, 199, 229, 284",4.0,0.0,Python,177.0,"```python\nsequence = [3, 11, 84, 144, 156, 17...",87.0,0.001,0.0,1,0.0,0.0,0,"[3, 11, 84, 144, 156, 177, 188, 199, 229, 284]",False,2
588,"26, 94, 98, 137, 176, 301, 323, 330, 372, 444",4.0,0.0,Python,178.0,"```python\nprint([26, 94, 98, 137, 176, 301, 3...",68.0,0.001,0.0,1,0.0,0.0,0,"[26, 94, 98, 137, 176, 301, 323, 330, 372, 444]",False,2
589,"39, 81, 88, 210, 215, 378, 416, 430, 439, 490",4.0,0.0,Python,178.0,"```python\nsequence = [39, 81, 88, 210, 215, 3...",88.0,0.001,0.0,1,0.0,0.0,0,"[39, 81, 88, 210, 215, 378, 416, 430, 439, 490]",False,2

In [40]:
python_df.to_csv("automatic_python.csv", index=False)

# Mathematica

In [63]:
mathe_df = pd.read_csv("mathematica_evaluation.csv")
answers = list(mathe_df["GPT4_answer"].values)
answers

['```mathematica\nTable[2 i, {i, 1, 10}]\n```',
 '```mathematica\nTable[3*n, {n, 1, 10}]\n```',
 '```mathematica\nRange[4, 40, 4]\n```',
 '```mathematica\nTable[5*i, {i, 1, 10}]\n```',
 '```mathematica\nTable[6*i, {i, 1, 10}]\n```',
 '```mathematica\nTable[7*n, {n, 1, 10}]\n```',
 '```mathematica\nTable[8*n, {n, 1, 10}]\n```',
 '```mathematica\nTable[9*i, {i, 1, 10}]\n```',
 '```mathematica\nRange[10, 100, 10]\n```',
 '```mathematica\nRange[1, 19, 2]\n```',
 '```mathematica\nTable[2*n, {n, 1, 10}]\n```',
 '```mathematica\nRange[11, 20]\n```',
 '```mathematica\nRange[21, 30]\n```',
 '```mathematica\nRange[31, 40]\n```',
 '```mathematica\nRange[41, 50]\n```',
 '```mathematica\nRange[51, 60]\n```',
 '```mathematica\nRange[61, 70]\n```',
 '```mathematica\nRange[71, 80]\n```',
 '```mathematica\nRange[81, 90]\n```',
 '```mathematica\nRange[91, 100]\n```',
 '```mathematica\nRange[101, 110]\n```',
 '```mathematica\nRange[111, 120]\n```',
 '```mathematica\nRange[121, 130]\n```',
 '```mathematica\nRange[131, 140]\n```',
 '```mathematica\nRange[141, 150]\n```',
 '```mathematica\nRange[151, 160]\n```',
 '```mathematica\nRange[161, 170]\n```',
 '```mathematica\nRange[171, 180]\n```',
 '```mathematica\nRange[181, 190]\n```',
 '```mathematica\nRange[191, 200]\n```',
 '```mathematica\nRange[2, 20, 2]\n```',
 '```mathematica\nRange[3, 30, 3]\n```',
 '```mathematica\nRange[4, 40, 4]\n```',
 '```mathematica\nRange[5, 50, 5]\n```',
 '```mathematica\nTable[6*n, {n, 1, 10}]\n```',
 '```mathematica\nTable[7*n, {n, 1, 10}]\n```',
 '```mathematica\nTable[8*i, {i, 1, 10}]\n```',
 '```mathematica\nTable[9*i, {i, 1, 10}]\n```',
 '```mathematica\nRange[10, 100, 10]\n```',
 '```mathematica\nRange[1, 19, 2]\n```',
 '```mathematica\nRange[2, 20, 2]\n```',
 '```mathematica\nRange[11, 20]\n```',
 '```mathematica\nRange[21, 30]\n```',
 '```mathematica\nRange[31, 40]\n```',
 '```mathematica\nRange[41, 50]\n```',
 '```mathematica\nRange[51, 60]\n```',
 '```mathematica\nRange[61, 70]\n```',
 '```mathematica\nRange[71, 80]\n```',
 '```mathematica\nRange[81, 90]\n```',
 '```mathematica\nRange[91, 100]\n```',
 '```mathematica\nRange[101, 110]\n```',
 '```mathematica\nRange[111, 120]\n```',
 '```mathematica\nRange[121, 130]\n```',
 '```mathematica\nRange[131, 140]\n```',
 '```mathematica\nRange[141, 150]\n```',
 '```mathematica\nRange[151, 160]\n```',
 '```mathematica\nRange[161, 170]\n```',
 '```mathematica\nRange[171, 180]\n```',
 '```mathematica\nRange[181, 190]\n```',
 '```mathematica\nRange[191, 200]\n```',
 '```mathematica\nRange[2, 20, 2]\n```',
 '```mathematica\nRange[3, 30, 3]\n```',
 '```mathematica\nRange[4, 40, 4]\n```',
 '```mathematica\nRange[5, 50, 5]\n```',
 '```mathematica\nTable[6*i, {i, 1, 10}]\n```',
 '```mathematica\nTable[7*i, {i, 1, 10}]\n```',
 '```mathematica\nTable[8*i, {i, 1, 10}]\n```',
 '```mathematica\nTable[9*i, {i, 1, 10}]\n```',
 '```mathematica\nRange[10, 100, 10]\n```',
 '```mathematica\nRange[1, 19, 2]\n```',
 '```mathematica\nRange[2, 20, 2]\n```',
 '```mathematica\nRange[11, 20]\n```',
 '```mathematica\nRange[21, 30]\n```',
 '```mathematica\nRange[31, 40]\n```',
 '```mathematica\nRange[41, 50]\n```',
 '```mathematica\nRange[51, 60]\n```',
 '```mathematica\nRange[61, 70]\n```',
 '```mathematica\nRange[71, 80]\n```',
 '```mathematica\nRange[81, 90]\n```',
 '```mathematica\nRange[91, 100]\n```',
 '```mathematica\nRange[101, 110]\n```',
 '```mathematica\nTable[111 + i, {i, 0, 9}]\n```',
 '```mathematica\nRange[121, 130]\n```',
 '```mathematica\nRange[131, 140]\n```',
 '```mathematica\nRange[141, 150]\n```',
 '```mathematica\nRange[151, 160]\n```',
 '```mathematica\nRange[161, 170]\n```',
 '```mathematica\nRange[171, 180]\n```',
 '```mathematica\nRange[181, 190]\n```',
 '```mathematica\nRange[191, 200]\n```',
 '```mathematica\nRange[2, 20, 2]\n```',
 '```mathematica\nRange[3, 30, 3]\n```',
 '```mathematica\nTable[4*i, {i, 1, 10}]\n```',
 '```mathematica\nRange[5, 50, 5]\n```',
 '```mathematica\nTable[6*n, {n, 1, 10}]\n```',
 '```mathematica\nTable[7*n, {n, 1, 10}]\n```',
 '```mathematica\nTable[8*i, {i, 1, 10}]\n```',
 '```mathematica\nTable[9*i, {i, 1, 10}]\n```',
 '```mathematica\nRange[10, 100, 10]\n```',
 '```mathematica\nRange[1, 19, 2]\n```',
 '```mathematica\nRange[2, 20, 2]\n```',
 '```mathematica\nRange[11, 20]\n```',
 '```mathematica\nRange[21, 30]\n```',
 '```mathematica\nRange[31, 40]\n```',
 '```mathematica\nRange[41, 50]\n```',
 '```mathematica\nRange[51, 60]\n```',
 '```mathematica\nRange[61, 70]\n```',
 '```mathematica\nRange[71, 80]\n```',
 '```mathematica\nRange[81, 90]\n```',
 '```mathematica\nRange[91, 100]\n```',
 '```mathematica\nRange[101, 110]\n```',
 '```mathematica\nTable[111 + i, {i, 0, 9}]\n```',
 '```mathematica\nRange[121, 130]\n```',
 '```mathematica\nRange[131, 140]\n```',
 '```mathematica\nRange[141, 150]\n```',
 '```mathematica\nRange[151, 160]\n```',
 '```mathematica\nRange[161, 170]\n```',
 '```mathematica\nRange[171, 180]\n```',
 '```mathematica\nRange[181, 190]\n```',
 '```mathematica\nRange[191, 200]\n```',
 '```mathematica\nRange[2, 20, 2]\n```',
 '```mathematica\nRange[3, 30, 3]\n```',
 '```mathematica\nTable[4*i, {i, 1, 10}]\n```',
 '```mathematica\nRange[5, 50, 5]\n```',
 '```mathematica\nTable[6*n, {n, 1, 10}]\n```',
 '```mathematica\nTable[7*n, {n, 1, 10}]\n```',
 '```mathematica\nTable[8*i, {i, 1, 10}]\n```',
 '```mathematica\nTable[9*i, {i, 1, 10}]\n```',
 '```mathematica\nRange[10, 100, 10]\n```',
 '```mathematica\nRange[1, 19, 2]\n```',
 '```mathematica\nRange[2, 20, 2]\n```',
 '```mathematica\nRange[11, 20]\n```',
 '```mathematica\nRange[21, 30]\n```',
 '```mathematica\nRange[31, 40]\n```',
 '```mathematica\nRange[41, 50]\n```',
 '```mathematica\nRange[51, 60]\n```',
 '```mathematica\nRange[61, 70]\n```',
 '```mathematica\nRange[71, 80]\n```',
 '```mathematica\nRange[81, 90]\n```',
 '```mathematica\nRange[91, 100]\n```',
 '```mathematica\nRange[101, 110]\n```',
 '```mathematica\nRange[111, 120]\n```',
 '```mathematica\nRange[121, 130]\n```',
 '```mathematica\nRange[131, 140]\n```',
 '```mathematica\nRange[141, 150]\n```',
 '```mathematica\nRange[151, 160]\n```',
 '```mathematica\nRange[161, 170]\n```',
 '```mathematica\nRange[171, 180]\n```',
 '```mathematica\nRange[181, 190]\n```',
 '```mathematica\nRange[191, 200]\n```',
 '```mathematica\nPrime[Range[10]]\n```',
 '```mathematica\nFibonacci[Range[10]]\n```',
 '```mathematica\nTable[2^n, {n, 0, 9}]\n```',
 '```mathematica\n3^Range[0, 9]\n```',
 '```mathematica\nTable[n^2, {n, 1, 10}]\n```',
 '```mathematica\nTable[n^3, {n, 1, 10}]\n```',
 '```mathematica\nTable[n!, {n, 1, 10}]\n```',
 '```mathematica\nTable[n*(n + 1)/2, {n, 1, 10}]\n```',
 '```mathematica\na[1] = 2; a[2] = 1; a[n_] := a[n] = a[n-1] + a[n-2]\nTable[a[n], {n, 10}]\n```',
 '```mathematica\nTable[Fibonacci[2 n + 1] - 1, {n, 0, 9}]\n```',
 '```mathematica\nTable[n^n, {n, 1, 10}]\n```',
 '```mathematica\nTable[n!*Binomial[2*n, n]/(n + 1), {n, 0, 9}]\n```',
 '```mathematica\nSelect[Range[30], PrimeQ]\n```',
 '```mathematica\nSelect[Range[30], PrimeQ[# + 1] &]\n```',
 '```mathematica\nTable[BaseForm[n, 2], {n, 1, 10}]\n```',
 '```mathematica\nTable[n^Round[n^(1/3)], {n, 0, 9}]\n```',
 '```mathematica\nSelect[Range[1, 100000], Total[Factorial /@ IntegerDigits[#]] == # &]\n```',
 '```mathematica\nTable[n^2 + 1, {n, 1, 10}]\n```',
 '```mathematica\nSelect[Range[1, 1000], ContainsOnly[IntegerDigits[#], {0, 1, 8}] &]\n```',
 '```mathematica\nTable[2^prime - 1, {prime, Prime[Range[10]]}]\n```',
 '```mathematica\na[1] = 1; a[2] = 2;\na[n_] := a[n] = a[n - 1] + n + Floor[Sqrt[n]]\nTable[a[n], {n, 1, 10}]\n```',
 '```mathematica\na[1] = 1; a[2] = 2; a[n_] := a[n] = a[n - 1] + a[n - 2] + n - 1;\nTable[a[n], {n, 1, 10}]\n```',
 '```mathematica\nTable[n^2 + n + 1, {n, 0, 9}]\n```',
 '```mathematica\nTable[IntegerExponent[n, 2], {n, 0, 9}]\n```',
 '```mathematica\na[0] = 1;\na[n_] := a[n] = n*a[n - 1] + 1;\nTable[a[n], {n, 0, 9}]\n```',
 '```mathematica\nPrime[Range[10]]\n```',
 '```mathematica\nNestList[StringReplace[#, x : Repeated[_, {2, Infinity}] :> ToString[StringLength[x]] <> StringTake[x, 1]] &, "1", 4]\n```',
 '```mathematica\nPrime[Range[10]]\n```',
 '```mathematica\n2^(Range[10] - 1)\n```',
 '```mathematica\nTable[2^n - 1, {n, 0, 9}]\n```',
 '```mathematica\nPrime[Range[10]]\n```',
 '```mathematica\nFibonacci[Range[10]]\n```',
 '```mathematica\nTable[2^n, {n, 0, 9}]\n```',
 '```mathematica\nTable[3^n, {n, 0, 9}]\n```',
 '```mathematica\nTable[i^2, {i, 1, 10}]\n```',
 '```mathematica\nTable[n^3, {n, 1, 10}]\n```',
 '```mathematica\nTable[Factorial[n], {n, 0, 9}]\n```',
 '```mathematica\nTable[n(n + 1)/2, {n, 1, 10}]\n```',
 '```mathematica\nNestList[Total@Take[#, -2] &, {2, 1}, 8]\n```',
 '```mathematica\nTable[Floor[n*(n + 1)*(2*n + 1)/6], {n, 0, 9}]\n```',
 '```mathematica\nTable[n^n, {n, 1, 10}]\n```',
 '```mathematica\nTable[Binomial[2*n, n]/(n + 1), {n, 0, 9}]\n```',
 '```mathematica\nPrime[Range[10]]\n```',
 '```mathematica\nSelect[Range[50], ! PrimeQ[#] && ! PrimeQ[# + 2] &][[1 ;; 10]]\n```',
 '```mathematica\nTable[IntegerString[i, 2], {i, 1, 10}]\n```',
 '```mathematica\nTable[n^Round[n^(1/3)], {n, 0, 9}]\n```',
 '```mathematica\nSelect[Range[1, 100000], # == Total[Factorial /@ IntegerDigits[#]] &]\n```',
 '```mathematica\nTable[n^2 + 1, {n, 1, 10}]\n```',
 '```mathematica\nSelect[Range[1, 110], MemberQ[{1, 8, 0}, Mod[#, 10]] &]\n```',
 '```mathematica\nTable[2^Prime[n] - 1, {n, 1, 10}]\n```',
 '```mathematica\na[1] = 1; a[2] = 2; a[n_] := a[n] = a[n - 1] + a[n - 2] /; n > 5 && EvenQ[n];\na[n_] := a[n] = 2 a[n - 1] /; n > 2 && OddQ[n];\na[n_] := a[n] = a[n - 1] + n /; n > 2 && EvenQ[n] && n <= 5;\nTable[a[n], {n, 1, 10}]\n```',
 '```mathematica\na[1] = 1; a[2] = 2; a[n_] := a[n] = a[n - 1] + a[n - 2] + Floor[n/3];\nTable[a[n], {n, 1, 10}]\n```',
 '```mathematica\nTable[n^3/6 + n^2/2 + n/3, {n, 1, 10}]\n```',
 '```mathematica\nTable[IntegerExponent[n, 2], {n, 0, 9}]\n```',
 '```mathematica\na[n_] := a[n] = a[n - 1] + Sum[Binomial[n - 1, k] a[k] a[n - 1 - k], {k, 0, n - 1}];\na[0] = 1;\nTable[a[n], {n, 0, 9}]\n```',
 '```mathematica\nPrime[Range[10]]\n```',
 '```mathematica\nNestList[StringJoin[Riffle[ToString /@ Tally[Characters[ToString[#]]][[All, 2]], Tally[Characters[ToString[#]]][[All, 1]]]] &, 1, 4]\n```',
 '```mathematica\nPrime[Range[10]]\n```',
 '```mathematica\nTable[2^n, {n, 0, 9}]\n```',
 '```mathematica\nTable[2^n - 1, {n, 0, 9}]\n```',
 '```mathematica\nPrime[Range[10]]\n```',
 '```mathematica\nFibonacci /@ Range[10]\n```',
 '```mathematica\nTable[2^n, {n, 0, 9}]\n```',
 '```mathematica\nTable[3^n, {n, 0, 9}]\n```',
 '```mathematica\nTable[i^2, {i, 1, 10}]\n```',
 '```mathematica\nTable[n^3, {n, 1, 10}]\n```',
 '```mathematica\nTable[Factorial[n], {n, 0, 9}]\n```',
 '```mathematica\nTable[n(n + 1)/2, {n, 1, 10}]\n```',
 '```mathematica\nNestList[#[[2]] + #[[3]] &, {2, 1, 3}, 9][[All, 1]]\n```',
 '```mathematica\nTable[Floor[(GoldenRatio^n - (-GoldenRatio)^(-n))/Sqrt[5]], {n, 0, 9}]\n```',
 '```mathematica\nTable[n^n, {n, 1, 10}]\n```',
 '```mathematica\nTable[n!*Binomial[2*n, n]/(n + 1), {n, 0, 9}]\n```',
 '```mathematica\nPrime[Range[10]]\n```',
 '```mathematica\nSelect[Range[30], ! PrimeQ[#] && ! PrimeQ[# + 2] &]\n```',
 '```mathematica\nTable[IntegerString[i, 2], {i, 1, 10}]\n```',
 '```mathematica\nTable[If[Mod[n, 2] == 0, n^9, n^3], {n, 0, 9}]\n```',
 '```mathematica\nSelect[Range[1, 50000], # == Total[Factorial /@ IntegerDigits[#]] &]\n```',
 '```mathematica\nTable[n^2 + 1, {n, 1, 10}]\n```',
 '```mathematica\nSelect[Range[1, 200], MemberQ[IntegerDigits[#], 1 | 8 | 0] &]\n```',
 '```mathematica\nTable[2^Prime[n] - 1, {n, 1, 10}]\n```',
 '```mathematica\na[n_] := a[n] = a[n - 1] + a[n - 2] - a[n - 3] + n; a[1] = 1; a[2] = 2; a[3] = 4; Table[a[i], {i, 1, 10}]\n```',
 '```mathematica\na[1] = 1; a[2] = 2; a[n_] := a[n] = a[n - 1] + a[n - 2] + Floor[n/3];\nTable[a[n], {n, 1, 10}]\n```',
 '```mathematica\nTable[n^2 + n + 1, {n, 0, 9}]\n```',
 '```mathematica\nTable[IntegerExponent[n, 2], {n, 0, 9}]\n```',
 '```mathematica\na[n_] := a[n] = a[n - 1] + n*a[n - 2];\na[0] = 1; a[1] = 1;\nTable[a[n], {n, 0, 9}]\n```',
 '```mathematica\nPrime[Range[10]]\n```',
 '```mathematica\nNestList[StringJoin @@ Riffle[ToString /@ Length /@ Split[#], Characters[#][[;; ;; Length /@ Split[#]]]] &, "1", 4]\n```',
 '```mathematica\nPrime[Range[10]]\n```',
 '```mathematica\n2^Range[0, 9]\n```',
 '```mathematica\nTable[2^n - 1, {n, 0, 9}]\n```',
 '```mathematica\nPrime[Range[10]]\n```',
 '```mathematica\nFibonacci /@ Range[10]\n```',
 '```mathematica\nTable[2^n, {n, 0, 9}]\n```',
 '```mathematica\nTable[3^n, {n, 0, 9}]\n```',
 '```mathematica\nTable[n^2, {n, 1, 10}]\n```',
 '```mathematica\nTable[n^3, {n, 1, 10}]\n```',
 '```mathematica\nTable[n!, {n, 1, 10}]\n```',
 '```mathematica\nTable[n(n + 1)/2, {n, 1, 10}]\n```',
 '```mathematica\nNestList[#1 + #2 & @@ Reverse@Most@# &, {2, 1}, 9]\n```',
 '```mathematica\nTable[Floor[(GoldenRatio^n - (-GoldenRatio)^(-n))/Sqrt[5]], {n, 0, 9}]\n```',
 '```mathematica\nTable[n^n, {n, 1, 10}]\n```',
 '```mathematica\nTable[Binomial[2*n, n]/(n + 1), {n, 0, 9}]\n```',
 '```mathematica\nPrime[Range[10]]\n```',
 '```mathematica\nSelect[Range[50], PrimeQ[# + 1] || PrimeQ[# - 1] &]\n```',
 '```mathematica\nTable[BaseForm[i, 2], {i, 1, 10}]\n```',
 '```mathematica\nTable[If[Mod[n, 2] == 0, n^9, n^3], {n, 0, 9}]\n```',
 '```mathematica\nSelect[Range[1, 50000], Total[Factorial /@ IntegerDigits[#]] == # &]\n```',
 '```mathematica\nTable[n^2 + 1, {n, 1, 10}]\n```',
 '```mathematica\nSelect[Range[1, 200], MemberQ[IntegerDigits[#], 1] &]\n```',
 '```mathematica\nTable[2^Prime[n] - 1, {n, 1, 10}]\n```',
 '```mathematica\na[1] = 1; a[2] = 2; a[n_] := a[n] = a[n - 1] + a[Floor[n/2]]; Table[a[n], {n, 1, 10}]\n```',
 '```mathematica\na[1] = 1; a[2] = 2; a[n_] := a[n] = a[n - 1] + a[n - 2] + n - 1\nTable[a[n], {n, 1, 10}]\n```',
 '```mathematica\nTable[n^3/6 + n^2/2 + n/3, {n, 1, 10}]\n```',
 '```mathematica\nTable[HammingWeight[n], {n, 0, 9}]\n```',
 '```mathematica\na[n_] := a[n] = a[n - 1] + n*a[n - 2];\na[0] = 1; a[1] = 1;\nTable[a[n], {n, 0, 9}]\n```',
 '```mathematica\nPrime[Range[10]]\n```',
 '```mathematica\nNestList[StringJoin[Riffle[ToString /@ Length /@ Split[Characters[#]], Characters[#][[Flatten[Position[Split[Characters[#]], _]]]]]] &, "1", 4]\n```',
 '```mathematica\nPrime[Range[10]]\n```',
 '```mathematica\nTable[2^n, {n, 0, 9}]\n```',
 '```mathematica\nTable[2^n - 1, {n, 0, 9}]\n```',
 '```mathematica\nPrime[Range[10]]\n```',
 '```mathematica\nFibonacci /@ Range[10]\n```',
 '```mathematica\nTable[2^n, {n, 0, 9}]\n```',
 '```mathematica\nTable[3^n, {n, 0, 9}]\n```',
 '```mathematica\nTable[n^2, {n, 1, 10}]\n```',
 '```mathematica\nTable[n^3, {n, 1, 10}]\n```',
 '```mathematica\nTable[n!, {n, 0, 9}]\n```',
 '```mathematica\nTable[n*(n + 1)/2, {n, 1, 10}]\n```',
 '```mathematica\nNestList[#1 + #2 & @@ Reverse@Most@# &, {2, 1}, 9]\n```',
 '```mathematica\nTable[Floor[(GoldenRatio^n - (-GoldenRatio)^(-n))/Sqrt[5]], {n, 0, 9}]\n```',
 '```mathematica\nTable[n^n, {n, 1, 10}]\n```',
 '```mathematica\nTable[Binomial[2*n, n]/(n + 1), {n, 0, 9}]\n```',
 '```mathematica\nPrime[Range[10]]\n```',
 '```mathematica\nSelect[Range[50], PrimeQ[# + 1] || PrimeQ[# - 1] &]\n```',
 '```mathematica\nTable[BaseForm[n, 2], {n, 1, 10}]\n```',
 '```mathematica\nTable[If[Mod[n, 2] == 0, n^9, n^3], {n, 0, 9}]\n```',
 '```mathematica\nSelect[Range[1, 100000], Total[Factorial /@ IntegerDigits[#]] == # &]\n```',
 '```mathematica\nTable[n^2 + 1, {n, 1, 10}]\n```',
 '```mathematica\nSelect[Range[1, 200], MemberQ[IntegerDigits[#], 1 | 8 | 0] &]\n```',
 '```mathematica\nTable[2^Prime[n] - 1, {n, 1, 10}]\n```',
 '```mathematica\na[1] = 1; a[2] = 2; a[n_] := a[n] = a[n - 1] + a[Floor[n/2]]; Table[a[n], {n, 1, 10}]\n```',
 '```mathematica\na[1] = 1; a[2] = 2; a[n_] := a[n] = a[n - 1] + a[n - 2] + n - 1;\nTable[a[n], {n, 1, 10}]\n```',
 '```mathematica\nTable[n^2 + n + 1, {n, 0, 9}]\n```',
 '```mathematica\nTable[IntegerExponent[n, 2], {n, 0, 9}]\n```',
 '```mathematica\na[0] = 1;\na[n_] := a[n] = n*a[n - 1] + 1\nTable[a[n], {n, 0, 9}]\n```',
 '```mathematica\nPrime[Range[10]]\n```',
 '```mathematica\nNestList[StringJoin[Riffle[ToString /@ Length /@ Split[Characters[#]], Characters[#][[Flatten[Position[Split[Characters[#]], _]]]]]] &, "1", 4]\n```',
 '```mathematica\nPrime[Range[10]]\n```',
 '```mathematica\nTable[2^n, {n, 0, 9}]\n```',
 '```mathematica\nTable[2^n - 1, {n, 0, 9}]\n```',
 '```mathematica\nTable[n^2, {n, 1, 10}]\n```',
 '```mathematica\nTable[n^3, {n, 1, 10}]\n```',
 '```mathematica\nNestList[Mod[# + 1, 3] &, 2, 9]\n```',
 '```mathematica\nFlatten[Table[ConstantArray[i, i - 1], {i, 1, 5}]]\n```',
 '```mathematica\nTable[2^x, {x, 1, 10}]\n```',
 '```mathematica\nTable[n^2 + 1, {n, 1, 10}]\n```',
 '```mathematica\nSelect[Range[7, 41], PrimeQ]\n```',
 '```mathematica\nTable[FromDigits[ConstantArray[1, n]], {n, 1, 10}]\n```',
 '```mathematica\nTable[FromDigits[Append[ConstantArray[3, n], 1]], {n, 1, 8}]\n```',
 '```wolfram\nTable[n^2 + n - 1, {n, 1, 10}]\n```',
 '```mathematica\nTable[2^(n - 1)*(2^n - 1), {n, Prime[Range[6]]}]\n```',
 '```mathematica\nRecurrenceTable[{a[n] == a[n - 1] + a[n - 2] + Fibonacci[n - 2], a[1] == 0, a[2] == 0}, a, {n, 10}]\n```',
 '```mathematica\nSelect[Prime[Range[2, 50]], PrimeQ[# + 2] &][[All, 1]] + 2\n```',
 '```mathematica\nSelect[Range[1, 50000], # == Total[Factorial /@ IntegerDigits[#]] &]\n```',
 '```mathematica\nSelect[Range[2, 2500], PrimeQ[2^# - 1] &][[1 ;; 10]]\n```',
 '```mathematica\nFoldList[#1*#2 + 1 &, 2, {1, 2, 3, 4, 5}]\n```',
 '```mathematica\nPrime[Range[10]]\n```',
 '```mathematica\nSelect[Range[1, 200], ContainsOnly[IntegerDigits[#], {0, 1, 8}] &]\n```',
 '```mathematica\nTable[IntegerExponent[n, 2], {n, 0, 9}]\n```',
 '```mathematica\nFlatten[Table[n - PrimePi[n], {n, 0, 9}]]\n```',
 '```mathematica\nPrime[Range[10]]\n```',
 '```mathematica\nSequence[1, 4, 2, 1, 3, 5, 9, 2, 6, 5]\n```',
 '```mathematica\nsequence = IntegerDigits[1732050798]\n```',
 '```mathematica\nNestList[Mod[# + Fibonacci[Length[NestWhileList[Mod[# + Fibonacci[Length[#]] &, {1}, # != 11 &]]]], 12] &, 1, 7]\n```',
 '```mathematica\nTable[2^n - 1, {n, 0, 7}]\n```',
 '```mathematica\nSelect[Range[3, 100], PrimeQ[#] && PrimeQ[2*# + 1] &]\n```',
 '```mathematica\na[n_] := a[n] = a[n - a[n - 1]] + a[n - a[n - 2]]; a[1] = a[2] = 1;\nTable[a[i], {i, 1, 8}]\n```',
 '```mathematica\na[0] = 1; a[1] = 0; a[2] = 1;\na[n_] := a[n] = a[n - 1] + a[n - 3];\nTable[a[n], {n, 0, 7}]\n```',
 '```mathematica\nTable[i^2, {i, 1, 10}]\n```',
 '```mathematica\nTable[n^3, {n, 1, 10}]\n```',
 '```mathematica\nFlatten@Table[{2, Table[1, {j}]}, {j, 1, 3}]\n```',
 '```mathematica\nFlatten[Table[ConstantArray[n, n - 1], {n, 1, 5}]]\n```',
 '```mathematica\nTable[2^n, {n, 1, 10}]\n```',
 '```mathematica\nTable[n^2 + 1, {n, 1, 10}]\n```',
 '```mathematica\nSelect[Range[7, 41], PrimeQ]\n```',
 '```mathematica\nTable[FromDigits@ConstantArray[1, i], {i, 1, 10}]\n```',
 '```mathematica\nTable[FromDigits[Append[ConstantArray[3, n], 1]], {n, 1, 8}]\n```',
 '```mathematica\nTable[n^2 + n - 1, {n, 1, 10}]\n```',
 '```mathematica\nSelect[Range[2, 2500000], PrimeOmega[#] == 2 && PrimeNu[#] == 1 &] // Map[2^(# - 1) (2^# - 1) &]\n```',
 '```mathematica\na[1] = 0; a[2] = 0; a[n_] := a[n] = a[n - 1] + PrimePi[n - 1];\nTable[a[n], {n, 1, 10}]\n```',
 '```mathematica\nSelect[Range[3, 400], PrimeQ[# + 2] &]\n```',
 '```mathematica\nSelect[Range[1, 50000], Total[Factorial[IntegerDigits[#]]] == # &]\n```',
 '```mathematica\nSelect[Range[2, 2300], PrimeQ[2^# - 1] &]\n```',
 '```mathematica\nNestList[# (#+1) &, 2, 5]\n```',
 '```mathematica\nPrime[Range[10]]\n```',
 '```mathematica\nSelect[Range[1, 200], MemberQ[IntegerDigits[#], 1 | 8 | 0] &]\n```',
 '```mathematica\nNestList[Mod[# + 1, 4] &, 0, 9]\n```',
 '```mathematica\nNestList[If[EvenQ[#], #/2, 3 # + 1] &, 0, 9]\n```',
 '```mathematica\nPrime[Range[10]]\n```',
 '```mathematica\nNestList[Mod[3 # + 1, 10] &, 1, 9]\n```',

In [100]:
test_answers = [
    '```mathematica\nFindSequenceFunction[{62, 98, 130, 154, 290, 315, 324, 385, 408, 447}, n]\n```', # no
    '```mathematica\nFindSequenceFunction[{2, 42, 66, 102, 153, 195, 201, 252, 306, 396}, n]\n```', # no
    '```mathematica\nSequence[187, 218, 260, 295, 301, 314, 379, 410, 452, 469]\n```', # yes
    '```mathematica\nSelect[Range[1000], PrimeQ[# + 1] && PrimeQ[# + 3] &]\n```', # no
    '```mathematica\na[n_] := If[n == 1, 4, If[EvenQ[n], a[n - 1] + 7*n, a[n - 1] + 18*(n - 1)]];\nTable[a[n], {n, 1, 10}]\n```', # no
    '```mathematica\nSelect[Range[100, 1000], Max[IntegerDigits[#]] == 5 &]\n```', # no
    '```mathematica\nSequence[29, 63, 95, 140, 150, 190, 221, 437, 482, 491]\n```', # yes
    '```mathematica\nSequence[72, 106, 139, 165, 171, 192, 199, 429, 453, 477]\n```', # yes
    '```mathematica\nTable[n + Sum[If[Mod[n, i] == 0, i, 0], {i, 1, n - 1}], {n, 15, 450}]\n```', #no 
]

In [101]:
import re

def preprocess_code_mathematica(code):
    # Remove leading and trailing substrings
    code = re.sub(r'^```(?:Mathematica|mathematica)?\n|\n```$', '', code)
    return code

def find_matched_programs_mathematica(mathematica_programs):
    # Regular expression patterns to match different cases
    patterns = [
        r'^\s*Print\s*\[\s*(?:\{\s*\d+(?:,\s*\d+)*\s*\}|\d+(?:,\s*\d+)*)\s*\]\s*;',
        r'^\s*Sequence\s*\[\s*\d+(?:,\s*\d+)*\s*\]\s*;?$',
        r'^\s*(?:\w+\s*=\s*)?IntegerDigits\s*\[\s*\d+\s*\]\s*;?$',
    ]
    
    # List to store matched programs and their indices
    matched_programs = []
    indexes = []

    # Iterate over each Mathematica code string
    for i, program in enumerate(mathematica_programs):
        # Preprocess the code string
        program = preprocess_code_mathematica(program)
        
        # Check if the program matches any of the patterns
        for pattern in patterns:
            if re.match(pattern, program, re.MULTILINE):
                matched_programs.append(program)
                indexes.append(i)
                break  # Move to the next program if a match is found
    
    return matched_programs, indexes

In [102]:
# Find matched programs
matches, indexes = find_matched_programs_mathematica(test_answers)

# Print the matches and their indexes
for match, index in zip(matches, indexes):
    print(f"Matched program at index {index}:")
    print(match)
    print()  # Add an empty line for clarity

Matched program at index 2:
Sequence[187, 218, 260, 295, 301, 314, 379, 410, 452, 469]

Matched program at index 6:
Sequence[29, 63, 95, 140, 150, 190, 221, 437, 482, 491]

Matched program at index 7:
Sequence[72, 106, 139, 165, 171, 192, 199, 429, 453, 477]

In [74]:
indexes

[321,
 322,
 406,
 434,
 440,
 441,
 443,
 446,
 453,
 454,
 456,
 457,
 459,
 466,
 467,
 468,
 471,
 472,
 473,
 478,
 480,
 481,
 483,
 488,
 490,
 491,
 496,
 499,
 502,
 503,
 504,
 508,
 509,
 510,
 511,
 513,
 516,
 520,
 521,
 524,
 525,
 526,
 527,
 528,
 533,
 538,
 541,
 542,
 543,
 544,
 546,
 548,
 550,
 551,
 553,
 554,
 555,
 557,
 558,
 561,
 563,
 565,
 571,
 572,
 573,
 576,
 580,
 583,
 584,
 585,
 586,
 587,
 588]

In [75]:
mathe_df.loc[indexes, 'print_code'] = 1
mathe_df

,Unnamed: 0,sequence,complexity,length_type,language,q_length,GPT4_answer,a_length,temperature,real_code,print_code,no_code,explanation,no_sense,exe_out,correct_execution,Levenshtein
0,7080,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",1.0,0.0,Mathematica,173.0,"```mathematica\nTable[2 i, {i, 1, 10}]\n```",41.0,1.000,0.0,0,0.0,0.0,0,"2, 4, 6, 8, 10, 12, 14, 16, 18, 20",True,0
1,7081,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",1.0,0.0,Mathematica,174.0,"```mathematica\nTable[3*n, {n, 1, 10}]\n```",41.0,1.000,0.0,0,0.0,0.0,0,"3, 6, 9, 12, 15, 18, 21, 24, 27, 30",True,0
2,7082,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",1.0,0.0,Mathematica,175.0,"```mathematica\nRange[4, 40, 4]\n```",34.0,1.000,0.0,0,0.0,0.0,0,"4, 8, 12, 16, 20, 24, 28, 32, 36, 40",True,0
3,7083,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",1.0,0.0,Mathematica,176.0,"```mathematica\nTable[5*i, {i, 1, 10}]\n```",41.0,1.000,0.0,0,0.0,0.0,0,"5, 10, 15, 20, 25, 30, 35, 40, 45, 50",True,0
4,7084,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",1.0,0.0,Mathematica,176.0,"```mathematica\nTable[6*i, {i, 1, 10}]\n```",41.0,1.000,0.0,0,0.0,0.0,0,"6, 12, 18, 24, 30, 36, 42, 48, 54, 60",True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
585,7665,"187, 218, 260, 295, 301, 314, 379, 410, 452, 469",4.0,0.0,Mathematica,186.0,"```mathematica\nSequence[187, 218, 260, 295, 3...",77.0,0.001,0.0,1,0.0,0.0,0,Execution error,False,50000
586,7666,"29, 63, 95, 140, 150, 190, 221, 437, 482, 491",4.0,0.0,Mathematica,183.0,"```mathematica\nSequence[29, 63, 95, 140, 150,...",74.0,0.001,0.0,1,0.0,0.0,0,Execution error,False,50000
587,7667,"3, 11, 84, 144, 156, 177, 188, 199, 229, 284",4.0,0.0,Mathematica,182.0,"```mathematica\nSequence[3, 11, 84, 144, 156, ...",73.0,0.001,0.0,1,0.0,0.0,0,Execution error,False,50000
588,7668,"26, 94, 98, 137, 176, 301, 323, 330, 372, 444",4.0,0.0,Mathematica,183.0,"```mathematica\nSequence[26, 94, 98, 137, 176,...",74.0,0.001,0.0,1,0.0,0.0,0,Execution error,False,50000
589,7669,"39, 81, 88, 210, 215, 378, 416, 430, 439, 490",4.0,0.0,Mathematica,183.0,"```mathematica\nTable[n^3 - n, {n, 4, 13}]\n```",45.0,0.001,0.0,0,0.0,0.0,0,"60, 120, 210, 336, 504, 720, 990, 1320, 1716, ...",False,30

In [76]:
mathe_df.to_csv("automatic_mathematica.csv", index=False)

# Arnold C

In [2]:
import pandas as pd

In [4]:
arnoldC_df = pd.read_csv("arnoldC_evaluation.csv")
answers = list(arnoldC_df["GPT4_answer"].values)
answers

["```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION @I LIED\nGET UP 20\nENOUGH TALK\n\nSTICK AROUND limit\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 2\nENOUGH TALK\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 0\nHEY CHRISTMAS TREE limit\nYOU SET US UP 30\nSTICK AROUND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 3\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nPLUS 3\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE number\nI LIED limit\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 4\nHEY CHRISTMAS TREE limit\nYOU SET US UP 40\nSTICK AROUND number\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 4\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE number\nI LIED limit\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```ArnoldC\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE step\nYOU SET US UP 5\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP step\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION number\nLET OFF SOME STEAM BENNET 50\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE result\nYOU SET US UP @NO PROBLEMO\nSTICK AROUND number\nTALK TO THE HAND result\nGET UP result\nYOU'RE FIRED 6\nENOUGH TALK\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nYOU'RE FIRED 1\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE number\nI LET HIM GO 10\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
 "```ArnoldC\nIT'S SHOWTIME\nHEY CHRISTMAS TREE sequence\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE num\nYOU SET US UP 0\nHEY CHRISTMAS TREE limit\nYOU SET US UP 70\nSTICK AROUND sequence\nGET TO THE CHOPPER num\nHERE IS MY INVITATION num\nGET UP 7\nENOUGH TALK\nTALK TO THE HAND num\nGET TO THE CHOPPER sequence\nHERE IS MY INVITATION sequence\nHE HAD TO SPLIT 7\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE num\nI LET HIM GO limit\nYOU HAVE NO RESPECT FOR LOGIC\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 0\nHEY CHRISTMAS TREE limit\nYOU SET US UP 10\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 8\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 0\nHEY CHRISTMAS TREE i\nYOU SET US UP 1\nSTICK AROUND i\nTALK TO THE HAND i\nGET TO THE CHOPPER number\nHERE IS MY INVITATION i\nGET UP 9\nENOUGH TALK\nGET TO THE CHOPPER i\nHERE IS MY INVITATION i\nGET UP 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 0\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 10\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE number\nLESS THAN 100\nBULLSHIT\nCHILL\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE increment\nYOU SET US UP 2\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION 20\nENOUGH TALK\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP increment\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE step\nYOU SET US UP @I LIED\nSTICK AROUND limit\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP step\nENOUGH TALK\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET UP step\nENOUGH TALK\nCHILL\nYOU HAVE NO RESPECT FOR LOGIC\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nSTICK AROUND limit\nTALK TO THE HAND number\nGET TO THE CHOPPA number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nGET TO THE CHOPPA limit\nHERE IS MY INVITATION 20\nLET OFF SOME STEAM BENNET number\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 20\nSTICK AROUND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE number\nLESS THAN 31\nBULLSHIT\nCHILL\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 31\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nENOUGH TALK\nYOU HAVE NO RESPECT FOR LOGIC\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 41\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nYOU'RE FIRED 1\nBECAUSE I'M GOING TO SAY PLEASE number\nI LIED 50\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nGET TO THE CHOPPER number\nHERE IS MY INVITATION 51\nENOUGH TALK\nSTICK AROUND number\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION @I LIED\nYOU'RE FIRED @NO PROBLEMO\nENOUGH TALK\n\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP @I LIED\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN @ONE\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```ArnoldC\nIT'S SHOWTIME\nHEY CHRISTMAS TREE sequence\nYOU SET US UP 71\nSTICK AROUND sequence\nTALK TO THE HAND sequence\nGET UP sequence\nYOU HAVE NO RESPECT FOR LOGIC\nBECAUSE I'M GOING TO SAY PLEASE sequence < 81\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 81\nSTICK AROUND number\n    TALK TO THE HAND number\n    GET UP number\n    BECAUSE I'M GOING TO SAY PLEASE number < 91\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nSTICK AROUND limit\nTALK TO THE HAND number\nGET UP number\nYOU'RE FIRED 1\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION number\nYOU'RE FIRED 10\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 101\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nYOU'RE FIRED 1\nBECAUSE I'M GOING TO SAY PLEASE number\nI LET HIM GO 110\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 111\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nYOU'RE FIRED 1\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE number\nI LET HIM GO 120\nBULLSHIT\nCHILL\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP 130\nSTICK AROUND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nTALK TO THE HAND number\nBECAUSE I'M GOING TO SAY PLEASE limit\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nYOU'RE FIRED 1\nENOUGH TALK\nCHILL limit\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 130\nSTICK AROUND number\nI LET HIM GO 140\nGET UP number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nTALK TO THE HAND number\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP 150\nSTICK AROUND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE number\nI LIED limit\nYOU HAVE NO RESPECT FOR LOGIC\nBULLSHIT\nYOU HAVE BEEN TERMINATED\nCHILL\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 151\nSTICK AROUND number\nI WANT TO ASK YOU A BUNCH OF THINGS AND I WANT TO HAVE THEM ANSWERED IMMEDIATELY\nTALK TO THE HAND number\nGET UP number\nYOU'RE FIRED 1\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE number\nLESS THAN 161\nBULLSHIT\nCHILL\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
 "```ArnoldC\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 161\n\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\n\nBECAUSE I'M GOING TO SAY PLEASE number\nLESS THAN 171\nYOU HAVE NO RESPECT FOR LOGIC\n\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```ArnoldC\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 171\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nBECAUSE I'M GOING TO SAY PLEASE number\nLESS THAN 181\nYOU HAVE NO RESPECT FOR LOGIC\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE condition\nYOU SET US UP 0\nGET TO THE CHOPPER number\nHERE IS MY INVITATION 181\nENOUGH TALK\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION 190\nENOUGH TALK\nSTICK AROUND condition\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nGET TO THE CHOPPER condition\nHERE IS MY INVITATION number\nLET OFF SOME STEAM BENNET limit\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 191\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE number I LIED 200\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 0\nHEY CHRISTMAS TREE limit\nYOU SET US UP 10\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 2\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE step\nYOU SET US UP 3\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP step\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET UP step\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE limit\nI'LL BE BACK 30\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE increment\nYOU SET US UP 4\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP increment\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET UP increment\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE limit\nI LIED 40\nYOU HAVE NO RESPECT FOR LOGIC\nCHILL\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 0\nHEY CHRISTMAS TREE limit\nYOU SET US UP 10\nSTICK AROUND limit\nGET UP number\nYOU'RE FIRED 5\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE step\nYOU SET US UP 6\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP step\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET UP 6\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE counter\nYOU SET US UP 0\nSTICK AROUND counter\nTALK TO THE HAND number\nGET UP number\nYOU'RE FIRED 7\nGET DOWN counter\nYOU'RE FIRED 1\nCHILL counter LESS THAN 10\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 8\nHEY CHRISTMAS TREE limit\nYOU SET US UP 80\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nYOU'RE FIRED 8\nCHILL number\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE multiplier\nYOU SET US UP 1\nSTICK AROUND multiplier\nTALK TO THE HAND number\nGET UP number\nYOU'RE FIRED 9\nGET TO THE CHOPPER multiplier\nHERE IS MY INVITATION multiplier\nGET UP 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE step\nYOU SET US UP 10\nSTICK AROUND limit\nTALK TO THE HAND number\nGET UP number\nYOU'RE FIRED step\nBECAUSE I'M GOING TO SAY PLEASE number\nI LET HIM GO 100\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE step\nYOU SET US UP 2\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION 20\nENOUGH TALK\nSTICK AROUND number\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP step\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE step\nYOU SET US UP 2\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION 20\nENOUGH TALK\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP step\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 2\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 11\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nYOU'RE FIRED 1\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE number\nLESS THAN 21\nBULLSHIT\nCHILL\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nSTICK AROUND limit\nTALK TO THE HAND number\nGET UP number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION 30\nYOU'RE FIRED number\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```ArnoldC\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION @I LIED\nGET UP 40\nENOUGH TALK\n\nSTICK AROUND limit\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 41\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nYOU'RE FIRED 1\nHE HAD TO SPLIT 50\nYOU HAVE NO RESPECT FOR LOGIC\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP 60\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nYOU'RE FIRED 1\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE number\nLESS THAN limit\nKNOCK KNOCK\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 61\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE number\nLESS THAN 71\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 71\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nYOU'RE FIRED 1\nHE HAD TO SPLIT 80\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 81\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nYOU'RE FIRED 1\nBECAUSE I'M GOING TO SAY PLEASE number\nLESS THAN 91\nENOUGH TALK\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 91\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nENOUGH TALK\nYOU HAVE NO RESPECT FOR LOGIC\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 100\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nBECAUSE I'M GOING TO SAY PLEASE number\nLESS THAN 111\nYOU HAVE NO RESPECT FOR LOGIC\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION @I LIED\nGET UP 120\nENOUGH TALK\n\nSTICK AROUND limit\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\n\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 121\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nYOU'RE FIRED 1\nBECAUSE I'M GOING TO SAY PLEASE number\nLESS THAN 131\nBULLSHIT\nCHILL\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 130\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nENOUGH TALK\nYOU HAVE NO RESPECT FOR LOGIC\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE sequence\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP 10\nHEY CHRISTMAS TREE i\nYOU SET US UP 0\nSTICK AROUND i\nTALK TO THE HAND sequence\nGET UP sequence\nGET TO THE CHOPPER sequence\nHERE IS MY INVITATION sequence\nYOU'RE FIRED 1\nENOUGH TALK\nGET TO THE CHOPPER i\nHERE IS MY INVITATION i\nYOU'RE FIRED 1\nENOUGH TALK\nCHILL i\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE step\nYOU SET US UP 1\n\nSTICK AROUND limit\nTALK TO THE HAND number\nGET UP number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP step\nENOUGH TALK\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION 160\nLET OFF SOME STEAM BENNET number\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",

In [6]:
original_seq = arnoldC_df["sequence"].values
original_seq

array(['2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
       '3, 6, 9, 12, 15, 18, 21, 24, 27, 30',
       '4, 8, 12, 16, 20, 24, 28, 32, 36, 40',
       '5, 10, 15, 20, 25, 30, 35, 40, 45, 50',
       '6, 12, 18, 24, 30, 36, 42, 48, 54, 60',
       '7, 14, 21, 28, 35, 42, 49, 56, 63, 70',
       '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
       '9, 18, 27, 36, 45, 54, 63, 72, 81, 90',
       '10, 20, 30, 40, 50, 60, 70, 80, 90, 100',
       '1, 3, 5, 7, 9, 11, 13, 15, 17, 19',
       '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
       '11, 12, 13, 14, 15, 16, 17, 18, 19, 20',
       '21, 22, 23, 24, 25, 26, 27, 28, 29, 30',
       '31, 32, 33, 34, 35, 36, 37, 38, 39, 40',
       '41, 42, 43, 44, 45, 46, 47, 48, 49, 50',
       '51, 52, 53, 54, 55, 56, 57, 58, 59, 60',
       '61, 62, 63, 64, 65, 66, 67, 68, 69, 70',
       '71, 72, 73, 74, 75, 76, 77, 78, 79, 80',
       '81, 82, 83, 84, 85, 86, 87, 88, 89, 90',
       '91, 92, 93, 94, 95, 96, 97, 98, 99, 100',
       '101, 102, 103, 104, 105, 106, 107, 108, 109, 110',
       '111, 112, 113, 114, 115, 116, 117, 118, 119, 120',
       '121, 122, 123, 124, 125, 126, 127, 128, 129, 130',
       '131, 132, 133, 134, 135, 136, 137, 138, 139, 140',
       '141, 142, 143, 144, 145, 146, 147, 148, 149, 150',
       '151, 152, 153, 154, 155, 156, 157, 158, 159, 160',
       '161, 162, 163, 164, 165, 166, 167, 168, 169, 170',
       '171, 172, 173, 174, 175, 176, 177, 178, 179, 180',
       '181, 182, 183, 184, 185, 186, 187, 188, 189, 190',
       '191, 192, 193, 194, 195, 196, 197, 198, 199, 200',
       '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
       '3, 6, 9, 12, 15, 18, 21, 24, 27, 30',
       '4, 8, 12, 16, 20, 24, 28, 32, 36, 40',
       '5, 10, 15, 20, 25, 30, 35, 40, 45, 50',
       '6, 12, 18, 24, 30, 36, 42, 48, 54, 60',
       '7, 14, 21, 28, 35, 42, 49, 56, 63, 70',
       '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
       '9, 18, 27, 36, 45, 54, 63, 72, 81, 90',
       '10, 20, 30, 40, 50, 60, 70, 80, 90, 100',
       '1, 3, 5, 7, 9, 11, 13, 15, 17, 19',
       '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
       '11, 12, 13, 14, 15, 16, 17, 18, 19, 20',
       '21, 22, 23, 24, 25, 26, 27, 28, 29, 30',
       '31, 32, 33, 34, 35, 36, 37, 38, 39, 40',
       '41, 42, 43, 44, 45, 46, 47, 48, 49, 50',
       '51, 52, 53, 54, 55, 56, 57, 58, 59, 60',
       '61, 62, 63, 64, 65, 66, 67, 68, 69, 70',
       '71, 72, 73, 74, 75, 76, 77, 78, 79, 80',
       '81, 82, 83, 84, 85, 86, 87, 88, 89, 90',
       '91, 92, 93, 94, 95, 96, 97, 98, 99, 100',
       '101, 102, 103, 104, 105, 106, 107, 108, 109, 110',
       '111, 112, 113, 114, 115, 116, 117, 118, 119, 120',
       '121, 122, 123, 124, 125, 126, 127, 128, 129, 130',
       '131, 132, 133, 134, 135, 136, 137, 138, 139, 140',
       '141, 142, 143, 144, 145, 146, 147, 148, 149, 150',
       '151, 152, 153, 154, 155, 156, 157, 158, 159, 160',
       '161, 162, 163, 164, 165, 166, 167, 168, 169, 170',
       '171, 172, 173, 174, 175, 176, 177, 178, 179, 180',
       '181, 182, 183, 184, 185, 186, 187, 188, 189, 190',
       '191, 192, 193, 194, 195, 196, 197, 198, 199, 200',
       '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
       '3, 6, 9, 12, 15, 18, 21, 24, 27, 30',
       '4, 8, 12, 16, 20, 24, 28, 32, 36, 40',
       '5, 10, 15, 20, 25, 30, 35, 40, 45, 50',
       '6, 12, 18, 24, 30, 36, 42, 48, 54, 60',
       '7, 14, 21, 28, 35, 42, 49, 56, 63, 70',
       '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
       '9, 18, 27, 36, 45, 54, 63, 72, 81, 90',
       '10, 20, 30, 40, 50, 60, 70, 80, 90, 100',
       '1, 3, 5, 7, 9, 11, 13, 15, 17, 19',
       '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
       '11, 12, 13, 14, 15, 16, 17, 18, 19, 20',
       '21, 22, 23, 24, 25, 26, 27, 28, 29, 30',
       '31, 32, 33, 34, 35, 36, 37, 38, 39, 40',
       '41, 42, 43, 44, 45, 46, 47, 48, 49, 50',
       '51, 52, 53, 54, 55, 56, 57, 58, 59, 60',
       '61, 62, 63, 64, 65, 66, 67, 68, 69, 70',
       '71, 72, 73, 74, 75, 76, 77, 78, 79, 80',
       '81, 82, 83, 84, 85, 86, 87, 88, 89, 90',
       '91, 92, 93, 94, 95, 96, 97, 98, 99, 100',
       '101, 102, 103, 104, 105, 106, 107, 108, 109, 110',
       '111, 112, 113, 114, 115, 116, 117, 118, 119, 120',
       '121, 122, 123, 124, 125, 126, 127, 128, 129, 130',
       '131, 132, 133, 134, 135, 136, 137, 138, 139, 140',
       '141, 142, 143, 144, 145, 146, 147, 148, 149, 150',
       '151, 152, 153, 154, 155, 156, 157, 158, 159, 160',
       '161, 162, 163, 164, 165, 166, 167, 168, 169, 170',
       '171, 172, 173, 174, 175, 176, 177, 178, 179, 180',
       '181, 182, 183, 184, 185, 186, 187, 188, 189, 190',
       '191, 192, 193, 194, 195, 196, 197, 198, 199, 200',
       '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
       '3, 6, 9, 12, 15, 18, 21, 24, 27, 30',
       '4, 8, 12, 16, 20, 24, 28, 32, 36, 40',
       '5, 10, 15, 20, 25, 30, 35, 40, 45, 50',
       '6, 12, 18, 24, 30, 36, 42, 48, 54, 60',
       '7, 14, 21, 28, 35, 42, 49, 56, 63, 70',
       '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
       '9, 18, 27, 36, 45, 54, 63, 72, 81, 90',
       '10, 20, 30, 40, 50, 60, 70, 80, 90, 100',
       '1, 3, 5, 7, 9, 11, 13, 15, 17, 19',
       '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
       '11, 12, 13, 14, 15, 16, 17, 18, 19, 20',
       '21, 22, 23, 24, 25, 26, 27, 28, 29, 30',
       '31, 32, 33, 34, 35, 36, 37, 38, 39, 40',
       '41, 42, 43, 44, 45, 46, 47, 48, 49, 50',
       '51, 52, 53, 54, 55, 56, 57, 58, 59, 60',
       '61, 62, 63, 64, 65, 66, 67, 68, 69, 70',
       '71, 72, 73, 74, 75, 76, 77, 78, 79, 80',
       '81, 82, 83, 84, 85, 86, 87, 88, 89, 90',
       '91, 92, 93, 94, 95, 96, 97, 98, 99, 100',
       '101, 102, 103, 104, 105, 106, 107, 108, 109, 110',
       '111, 112, 113, 114, 115, 116, 117, 118, 119, 120',
       '121, 122, 123, 124, 125, 126, 127, 128, 129, 130',
       '131, 132, 133, 134, 135, 136, 137, 138, 139, 140',
       '141, 142, 143, 144, 145, 146, 147, 148, 149, 150',
       '151, 152, 153, 154, 155, 156, 157, 158, 159, 160',
       '161, 162, 163, 164, 165, 166, 167, 168, 169, 170',
       '171, 172, 173, 174, 175, 176, 177, 178, 179, 180',
       '181, 182, 183, 184, 185, 186, 187, 188, 189, 190',
       '191, 192, 193, 194, 195, 196, 197, 198, 199, 200',
       '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
       '3, 6, 9, 12, 15, 18, 21, 24, 27, 30',
       '4, 8, 12, 16, 20, 24, 28, 32, 36, 40',
       '5, 10, 15, 20, 25, 30, 35, 40, 45, 50',
       '6, 12, 18, 24, 30, 36, 42, 48, 54, 60',
       '7, 14, 21, 28, 35, 42, 49, 56, 63, 70',
       '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
       '9, 18, 27, 36, 45, 54, 63, 72, 81, 90',
       '10, 20, 30, 40, 50, 60, 70, 80, 90, 100',
       '1, 3, 5, 7, 9, 11, 13, 15, 17, 19',
       '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
       '11, 12, 13, 14, 15, 16, 17, 18, 19, 20',
       '21, 22, 23, 24, 25, 26, 27, 28, 29, 30',
       '31, 32, 33, 34, 35, 36, 37, 38, 39, 40',
       '41, 42, 43, 44, 45, 46, 47, 48, 49, 50',
       '51, 52, 53, 54, 55, 56, 57, 58, 59, 60',
       '61, 62, 63, 64, 65, 66, 67, 68, 69, 70',
       '71, 72, 73, 74, 75, 76, 77, 78, 79, 80',
       '81, 82, 83, 84, 85, 86, 87, 88, 89, 90',
       '91, 92, 93, 94, 95, 96, 97, 98, 99, 100',
       '101, 102, 103, 104, 105, 106, 107, 108, 109, 110',
       '111, 112, 113, 114, 115, 116, 117, 118, 119, 120',
       '121, 122, 123, 124, 125, 126, 127, 128, 129, 130',
       '131, 132, 133, 134, 135, 136, 137, 138, 139, 140',
       '141, 142, 143, 144, 145, 146, 147, 148, 149, 150',
       '151, 152, 153, 154, 155, 156, 157, 158, 159, 160',
       '161, 162, 163, 164, 165, 166, 167, 168, 169, 170',
       '171, 172, 173, 174, 175, 176, 177, 178, 179, 180',
       '181, 182, 183, 184, 185, 186, 187, 188, 189, 190',
       '191, 192, 193, 194, 195, 196, 197, 198, 199, 200',
       '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
       '1, 1, 2, 3, 5, 8, 13, 21, 34, 55',
       '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
       '1, 3, 9, 27, 81, 243, 729, 2187, 6561, 19683',
       '1, 4, 9, 16, 25, 36, 49, 64, 81, 100',
       '1, 8, 27, 64, 125, 216, 343, 512, 729, 1000',
       '1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880',
       '1, 3, 6, 10, 15, 21, 28, 36, 45, 55',
       '2, 1, 3, 4, 7, 11, 18, 29, 47, 76',
       '0, 1, 2, 5, 12, 29, 70, 169, 408, 985',
       '1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000',
       '1, 2, 6, 20, 70, 252, 924, 3432, 12870, 48620',
       '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
       '4, 6, 9, 10, 14, 15, 21, 22, 25, 26',
       '1, 10, 11, 100, 101, 110, 111, 1000, 1001, 1010',
       '0, 1, 81, 512, 2401, 4913, 5832, 17576, 19683, 234256',
       '1, 2, 145, 40585', '2, 5, 12, 20, 29, 39, 50, 62, 75, 89',
       '1, 8, 10, 18, 19, 100, 101, 108, 109, 110',
       '3, 7, 31, 127, 2047, 8191, 131071, 524287, 8388607, 536870911',
       '1, 2, 4, 8, 16, 23, 28, 38, 58, 89',
       '1, 2, 4, 8, 15, 26, 42, 64, 93, 129',
       '1, 5, 12, 22, 35, 51, 70, 92, 117, 145',
       '0, 1, 1, 2, 1, 2, 2, 3, 1, 3',
       '1, 2, 5, 15, 52, 203, 877, 4140, 21147, 115975',
       '2, 3, 5, 7, 11, 13, 17, 19, 23, 29', '1, 11, 21, 1211, 111221',
       '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
       '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
       '1, 3, 7, 15, 31, 63, 127, 255, 511, 1023',
       '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
       '1, 1, 2, 3, 5, 8, 13, 21, 34, 55',
       '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
       '1, 3, 9, 27, 81, 243, 729, 2187, 6561, 19683',
       '1, 4, 9, 16, 25, 36, 49, 64, 81, 100',
       '1, 8, 27, 64, 125, 216, 343, 512, 729, 1000',
       '1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880',
       '1, 3, 6, 10, 15, 21, 28, 36, 45, 55',
       '2, 1, 3, 4, 7, 11, 18, 29, 47, 76',
       '0, 1, 2, 5, 12, 29, 70, 169, 408, 985',
       '1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000',
       '1, 2, 6, 20, 70, 252, 924, 3432, 12870, 48620',
       '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
       '4, 6, 9, 10, 14, 15, 21, 22, 25, 26',
       '1, 10, 11, 100, 101, 110, 111, 1000, 1001, 1010',
       '0, 1, 81, 512, 2401, 4913, 5832, 17576, 19683, 234256',
       '1, 2, 145, 40585', '2, 5, 12, 20, 29, 39, 50, 62, 75, 89',
       '1, 8, 10, 18, 19, 100, 101, 108, 109, 110',
       '3, 7, 31, 127, 2047, 8191, 131071, 524287, 8388607, 536870911',
       '1, 2, 4, 8, 16, 23, 28, 38, 58, 89',
       '1, 2, 4, 8, 15, 26, 42, 64, 93, 129',
       '1, 5, 12, 22, 35, 51, 70, 92, 117, 145',
       '0, 1, 1, 2, 1, 2, 2, 3, 1, 3',
       '1, 2, 5, 15, 52, 203, 877, 4140, 21147, 115975',
       '2, 3, 5, 7, 11, 13, 17, 19, 23, 29', '1, 11, 21, 1211, 111221',
       '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
       '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
       '1, 3, 7, 15, 31, 63, 127, 255, 511, 1023',
       '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
       '1, 1, 2, 3, 5, 8, 13, 21, 34, 55',
       '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
       '1, 3, 9, 27, 81, 243, 729, 2187, 6561, 19683',
       '1, 4, 9, 16, 25, 36, 49, 64, 81, 100',
       '1, 8, 27, 64, 125, 216, 343, 512, 729, 1000',
       '1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880',
       '1, 3, 6, 10, 15, 21, 28, 36, 45, 55',
       '2, 1, 3, 4, 7, 11, 18, 29, 47, 76',
       '0, 1, 2, 5, 12, 29, 70, 169, 408, 985',
       '1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000',
       '1, 2, 6, 20, 70, 252, 924, 3432, 12870, 48620',
       '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
       '4, 6, 9, 10, 14, 15, 21, 22, 25, 26',
       '1, 10, 11, 100, 101, 110, 111, 1000, 1001, 1010',
       '0, 1, 81, 512, 2401, 4913, 5832, 17576, 19683, 234256',
       '1, 2, 145, 40585', '2, 5, 12, 20, 29, 39, 50, 62, 75, 89',
       '1, 8, 10, 18, 19, 100, 101, 108, 109, 110',
       '3, 7, 31, 127, 2047, 8191, 131071, 524287, 8388607, 536870911',
       '1, 2, 4, 8, 16, 23, 28, 38, 58, 89',
       '1, 2, 4, 8, 15, 26, 42, 64, 93, 129',
       '1, 5, 12, 22, 35, 51, 70, 92, 117, 145',
       '0, 1, 1, 2, 1, 2, 2, 3, 1, 3',
       '1, 2, 5, 15, 52, 203, 877, 4140, 21147, 115975',
       '2, 3, 5, 7, 11, 13, 17, 19, 23, 29', '1, 11, 21, 1211, 111221',
       '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
       '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
       '1, 3, 7, 15, 31, 63, 127, 255, 511, 1023',
       '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
       '1, 1, 2, 3, 5, 8, 13, 21, 34, 55',
       '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
       '1, 3, 9, 27, 81, 243, 729, 2187, 6561, 19683',
       '1, 4, 9, 16, 25, 36, 49, 64, 81, 100',
       '1, 8, 27, 64, 125, 216, 343, 512, 729, 1000',
       '1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880',
       '1, 3, 6, 10, 15, 21, 28, 36, 45, 55',
       '2, 1, 3, 4, 7, 11, 18, 29, 47, 76',
       '0, 1, 2, 5, 12, 29, 70, 169, 408, 985',
       '1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000',
       '1, 2, 6, 20, 70, 252, 924, 3432, 12870, 48620',
       '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
       '4, 6, 9, 10, 14, 15, 21, 22, 25, 26',
       '1, 10, 11, 100, 101, 110, 111, 1000, 1001, 1010',
       '0, 1, 81, 512, 2401, 4913, 5832, 17576, 19683, 234256',
       '1, 2, 145, 40585', '2, 5, 12, 20, 29, 39, 50, 62, 75, 89',
       '1, 8, 10, 18, 19, 100, 101, 108, 109, 110',
       '3, 7, 31, 127, 2047, 8191, 131071, 524287, 8388607, 536870911',
       '1, 2, 4, 8, 16, 23, 28, 38, 58, 89',
       '1, 2, 4, 8, 15, 26, 42, 64, 93, 129',
       '1, 5, 12, 22, 35, 51, 70, 92, 117, 145',
       '0, 1, 1, 2, 1, 2, 2, 3, 1, 3',
       '1, 2, 5, 15, 52, 203, 877, 4140, 21147, 115975',
       '2, 3, 5, 7, 11, 13, 17, 19, 23, 29', '1, 11, 21, 1211, 111221',
       '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
       '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
       '1, 3, 7, 15, 31, 63, 127, 255, 511, 1023',
       '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
       '1, 1, 2, 3, 5, 8, 13, 21, 34, 55',
       '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
       '1, 3, 9, 27, 81, 243, 729, 2187, 6561, 19683',
       '1, 4, 9, 16, 25, 36, 49, 64, 81, 100',
       '1, 8, 27, 64, 125, 216, 343, 512, 729, 1000',
       '1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880',
       '1, 3, 6, 10, 15, 21, 28, 36, 45, 55',
       '2, 1, 3, 4, 7, 11, 18, 29, 47, 76',
       '0, 1, 2, 5, 12, 29, 70, 169, 408, 985',
       '1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489, 10000000000',
       '1, 2, 6, 20, 70, 252, 924, 3432, 12870, 48620',
       '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
       '4, 6, 9, 10, 14, 15, 21, 22, 25, 26',
       '1, 10, 11, 100, 101, 110, 111, 1000, 1001, 1010',
       '0, 1, 81, 512, 2401, 4913, 5832, 17576, 19683, 234256',
       '1, 2, 145, 40585', '2, 5, 12, 20, 29, 39, 50, 62, 75, 89',
       '1, 8, 10, 18, 19, 100, 101, 108, 109, 110',
       '3, 7, 31, 127, 2047, 8191, 131071, 524287, 8388607, 536870911',
       '1, 2, 4, 8, 16, 23, 28, 38, 58, 89',
       '1, 2, 4, 8, 15, 26, 42, 64, 93, 129',
       '1, 5, 12, 22, 35, 51, 70, 92, 117, 145',
       '0, 1, 1, 2, 1, 2, 2, 3, 1, 3',
       '1, 2, 5, 15, 52, 203, 877, 4140, 21147, 115975',
       '2, 3, 5, 7, 11, 13, 17, 19, 23, 29', '1, 11, 21, 1211, 111221',
       '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
       '1, 2, 4, 8, 16, 32, 64, 128, 256, 512',
       '1, 3, 7, 15, 31, 63, 127, 255, 511, 1023',
       '1, 4, 9, 16, 25, 36, 49, 64, 81, 100',
       '1, 8, 27, 64, 125, 216, 343, 512, 729, 1000',
       '2, 1, 2, 1, 2, 2, 1, 2, 2, 2', '1, 2, 2, 3, 3, 4, 4, 4, 5, 5',
       '2, 4, 8, 16, 32, 64, 128, 256, 512, 1024',
       '2, 5, 12, 20, 29, 39, 50, 62, 75, 89',
       '7, 11, 13, 17, 19, 23, 29, 31, 37, 41',
       '1, 11, 111, 1111, 11111, 111111, 1111111, 11111111, 111111111, 1111111111',
       '31, 331, 3331, 33331, 333331, 3333331, 33333331, 333333331',
       '1, 3, 7, 13, 21, 31, 43, 57, 73, 91',
       '6, 28, 496, 8128, 130816, 2096128',
       '0, 0, 2, 3, 5, 7, 11, 15, 22, 30',
       '3, 37, 67, 101, 137, 199, 269, 307, 353, 389', '1, 2, 145, 40585',
       '19, 31, 61, 89, 107, 127, 521, 607, 1279, 2203',
       '2, 3, 7, 42, 1806, 3263442', '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
       '1, 8, 10, 18, 19, 100, 101, 108, 109, 110',
       '0, 1, 1, 2, 1, 2, 2, 3, 1, 3', '0, 1, 1, 2, 2, 4, 2, 6, 4, 6',
       '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
       '1, 4, 2, 1, 3, 5, 9, 2, 6, 5', '1, 7, 3, 2, 0, 5, 0, 7, 9, 8',
       '1, 0, 1, 2, 3, 1, 6, 11', '1, 1, 1, 3, 7, 15, 31, 63',
       '3, 5, 11, 17, 31, 41, 59, 67', '1, 2, 3, 4, 6, 8, 11, 13',
       '1, 0, 1, 1, 2, 3, 6, 11', '1, 4, 9, 16, 25, 36, 49, 64, 81, 100',
       '1, 8, 27, 64, 125, 216, 343, 512, 729, 1000',
       '2, 1, 2, 1, 2, 2, 1, 2, 2, 2', '1, 2, 2, 3, 3, 4, 4, 4, 5, 5',
       '2, 4, 8, 16, 32, 64, 128, 256, 512, 1024',
       '2, 5, 12, 20, 29, 39, 50, 62, 75, 89',
       '7, 11, 13, 17, 19, 23, 29, 31, 37, 41',
       '1, 11, 111, 1111, 11111, 111111, 1111111, 11111111, 111111111, 1111111111',
       '31, 331, 3331, 33331, 333331, 3333331, 33333331, 333333331',
       '1, 3, 7, 13, 21, 31, 43, 57, 73, 91',
       '6, 28, 496, 8128, 130816, 2096128',
       '0, 0, 2, 3, 5, 7, 11, 15, 22, 30',
       '3, 37, 67, 101, 137, 199, 269, 307, 353, 389', '1, 2, 145, 40585',
       '19, 31, 61, 89, 107, 127, 521, 607, 1279, 2203',
       '2, 3, 7, 42, 1806, 3263442', '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
       '1, 8, 10, 18, 19, 100, 101, 108, 109, 110',
       '0, 1, 1, 2, 1, 2, 2, 3, 1, 3', '0, 1, 1, 2, 2, 4, 2, 6, 4, 6',
       '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
       '1, 4, 2, 1, 3, 5, 9, 2, 6, 5', '1, 7, 3, 2, 0, 5, 0, 7, 9, 8',
       '1, 0, 1, 2, 3, 1, 6, 11', '1, 1, 1, 3, 7, 15, 31, 63',
       '3, 5, 11, 17, 31, 41, 59, 67', '1, 2, 3, 4, 6, 8, 11, 13',
       '1, 0, 1, 1, 2, 3, 6, 11', '1, 4, 9, 16, 25, 36, 49, 64, 81, 100',
       '1, 8, 27, 64, 125, 216, 343, 512, 729, 1000',
       '2, 1, 2, 1, 2, 2, 1, 2, 2, 2', '1, 2, 2, 3, 3, 4, 4, 4, 5, 5',
       '2, 4, 8, 16, 32, 64, 128, 256, 512, 1024',
       '2, 5, 12, 20, 29, 39, 50, 62, 75, 89',
       '7, 11, 13, 17, 19, 23, 29, 31, 37, 41',
       '1, 11, 111, 1111, 11111, 111111, 1111111, 11111111, 111111111, 1111111111',
       '31, 331, 3331, 33331, 333331, 3333331, 33333331, 333333331',
       '1, 3, 7, 13, 21, 31, 43, 57, 73, 91',
       '6, 28, 496, 8128, 130816, 2096128',
       '0, 0, 2, 3, 5, 7, 11, 15, 22, 30',
       '3, 37, 67, 101, 137, 199, 269, 307, 353, 389', '1, 2, 145, 40585',
       '19, 31, 61, 89, 107, 127, 521, 607, 1279, 2203',
       '2, 3, 7, 42, 1806, 3263442', '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
       '1, 8, 10, 18, 19, 100, 101, 108, 109, 110',
       '0, 1, 1, 2, 1, 2, 2, 3, 1, 3', '0, 1, 1, 2, 2, 4, 2, 6, 4, 6',
       '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
       '1, 4, 2, 1, 3, 5, 9, 2, 6, 5', '1, 7, 3, 2, 0, 5, 0, 7, 9, 8',
       '1, 0, 1, 2, 3, 1, 6, 11', '1, 1, 1, 3, 7, 15, 31, 63',
       '3, 5, 11, 17, 31, 41, 59, 67', '1, 2, 3, 4, 6, 8, 11, 13',
       '1, 0, 1, 1, 2, 3, 6, 11', '1, 4, 9, 16, 25, 36, 49, 64, 81, 100',
       '1, 8, 27, 64, 125, 216, 343, 512, 729, 1000',
       '2, 1, 2, 1, 2, 2, 1, 2, 2, 2', '1, 2, 2, 3, 3, 4, 4, 4, 5, 5',
       '2, 4, 8, 16, 32, 64, 128, 256, 512, 1024',
       '2, 5, 12, 20, 29, 39, 50, 62, 75, 89',
       '7, 11, 13, 17, 19, 23, 29, 31, 37, 41',
       '1, 11, 111, 1111, 11111, 111111, 1111111, 11111111, 111111111, 1111111111',
       '31, 331, 3331, 33331, 333331, 3333331, 33333331, 333333331',
       '1, 3, 7, 13, 21, 31, 43, 57, 73, 91',
       '6, 28, 496, 8128, 130816, 2096128',
       '0, 0, 2, 3, 5, 7, 11, 15, 22, 30',
       '3, 37, 67, 101, 137, 199, 269, 307, 353, 389', '1, 2, 145, 40585',
       '19, 31, 61, 89, 107, 127, 521, 607, 1279, 2203',
       '2, 3, 7, 42, 1806, 3263442', '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
       '1, 8, 10, 18, 19, 100, 101, 108, 109, 110',
       '0, 1, 1, 2, 1, 2, 2, 3, 1, 3', '0, 1, 1, 2, 2, 4, 2, 6, 4, 6',
       '2, 3, 5, 7, 11, 13, 17, 19, 23, 29',
       '1, 4, 2, 1, 3, 5, 9, 2, 6, 5', '1, 7, 3, 2, 0, 5, 0, 7, 9, 8',
       '1, 0, 1, 2, 3, 1, 6, 11', '1, 1, 1, 3, 7, 15, 31, 63',
       '3, 5, 11, 17, 31, 41, 59, 67', '1, 2, 3, 4, 6, 8, 11, 13',

In [27]:
print(len(original_seq))
print(len(answers))

filtered_df = arnoldC_df[arnoldC_df["correctness"] == True]

seq_test = list(filtered_df["sequence"].values)
answers_test = list(filtered_df["GPT4_answer"].values)

590
590

In [74]:
answers_test

["```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 0\nHEY CHRISTMAS TREE limit\nYOU SET US UP 10\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 8\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 0\nHEY CHRISTMAS TREE limit\nYOU SET US UP 10\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 2\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE step\nYOU SET US UP 2\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION 20\nENOUGH TALK\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP step\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 2\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 0\nHEY CHRISTMAS TREE limit\nYOU SET US UP 10\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 8\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 0\nHEY CHRISTMAS TREE limit\nYOU SET US UP 10\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 2\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 0\nHEY CHRISTMAS TREE limit\nYOU SET US UP 10\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 4\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 0\nHEY CHRISTMAS TREE limit\nYOU SET US UP 10\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 2\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 0\nHEY CHRISTMAS TREE limit\nYOU SET US UP 10\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 8\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 1\nHEY CHRISTMAS TREE result\nYOU SET US UP 1\nHEY CHRISTMAS TREE limit\nYOU SET US UP 10\nSTICK AROUND limit\nTALK TO THE HAND result\nGET TO THE CHOPPER result\nHERE IS MY INVITATION result\nYOU'RE FIRED number\nENOUGH TALK\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 1\nHEY CHRISTMAS TREE limit\nYOU SET US UP 10\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nYOU'RE FIRED 2\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number1\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE number2\nYOU SET US UP 0\nHEY CHRISTMAS TREE number3\nYOU SET US UP 0\nHEY CHRISTMAS TREE number4\nYOU SET US UP 0\nHEY CHRISTMAS TREE number5\nYOU SET US UP 0\nHEY CHRISTMAS TREE number6\nYOU SET US UP 0\nHEY CHRISTMAS TREE number7\nYOU SET US UP 0\nHEY CHRISTMAS TREE number8\nYOU SET US UP 0\nHEY CHRISTMAS TREE number9\nYOU SET US UP 0\nHEY CHRISTMAS TREE number10\nYOU SET US UP 0\n\nGET TO THE CHOPPER number1\nHERE IS MY INVITATION 1\nENOUGH TALK\n\nGET TO THE CHOPPER number2\nHERE IS MY INVITATION 4\nENOUGH TALK\n\nGET TO THE CHOPPER number3\nHERE IS MY INVITATION 2\nENOUGH TALK\n\nGET TO THE CHOPPER number4\nHERE IS MY INVITATION 1\nENOUGH TALK\n\nGET TO THE CHOPPER number5\nHERE IS MY INVITATION 3\nENOUGH TALK\n\nGET TO THE CHOPPER number6\nHERE IS MY INVITATION 5\nENOUGH TALK\n\nGET TO THE CHOPPER number7\nHERE IS MY INVITATION 9\nENOUGH TALK\n\nGET TO THE CHOPPER number8\nHERE IS MY INVITATION 2\nENOUGH TALK\n\nGET TO THE CHOPPER number9\nHERE IS MY INVITATION 6\nENOUGH TALK\n\nGET TO THE CHOPPER number10\nHERE IS MY INVITATION 5\nENOUGH TALK\n\nTALK TO THE HAND number1\nTALK TO THE HAND number2\nTALK TO THE HAND number3\nTALK TO THE HAND number4\nTALK TO THE HAND number5\nTALK TO THE HAND number6\nTALK TO THE HAND number7\nTALK TO THE HAND number8\nTALK TO THE HAND number9\nTALK TO THE HAND number10\n\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\n    HEY CHRISTMAS TREE num0\n    YOU SET US UP @I LIED\n    HEY CHRISTMAS TREE num1\n    YOU SET US UP @NO PROBLEMO\n    HEY CHRISTMAS TREE num2\n    YOU SET US UP 18\n    HEY CHRISTMAS TREE num3\n    YOU SET US UP 39\n    HEY CHRISTMAS TREE num4\n    YOU SET US UP 71\n    HEY CHRISTMAS TREE num5\n    YOU SET US UP 194\n    HEY CHRISTMAS TREE num6\n    YOU SET US UP 197\n    HEY CHRISTMAS TREE num7\n    YOU SET US UP 219\n    HEY CHRISTMAS TREE num8\n    YOU SET US UP 263\n    HEY CHRISTMAS TREE num9\n    YOU SET US UP 270\n    HEY CHRISTMAS TREE num10\n    YOU SET US UP 416\n    HEY CHRISTMAS TREE num11\n    YOU SET US UP 473\n    \n    TALK TO THE HAND num2\n    TALK TO THE HAND num3\n    TALK TO THE HAND num4\n    TALK TO THE HAND num5\n    TALK TO THE HAND num6\n    TALK TO THE HAND num7\n    TALK TO THE HAND num8\n    TALK TO THE HAND num9\n    TALK TO THE HAND num10\n    TALK TO THE HAND num11\nYOU HAVE BEEN TERMINATED\n```",
 "```ArnoldC\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number1\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE number2\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE number3\nYOU SET US UP 72\nHEY CHRISTMAS TREE number4\nYOU SET US UP 106\nHEY CHRISTMAS TREE number5\nYOU SET US UP 139\nHEY CHRISTMAS TREE number6\nYOU SET US UP 165\nHEY CHRISTMAS TREE number7\nYOU SET US UP 171\nHEY CHRISTMAS TREE number8\nYOU SET US UP 192\nHEY CHRISTMAS TREE number9\nYOU SET US UP 199\nHEY CHRISTMAS TREE number10\nYOU SET US UP 429\nHEY CHRISTMAS TREE number11\nYOU SET US UP 453\nHEY CHRISTMAS TREE number12\nYOU SET US UP 477\n\nTALK TO THE HAND number3\nTALK TO THE HAND number4\nTALK TO THE HAND number5\nTALK TO THE HAND number6\nTALK TO THE HAND number7\nTALK TO THE HAND number8\nTALK TO THE HAND number9\nTALK TO THE HAND number10\nTALK TO THE HAND number11\nTALK TO THE HAND number12\n\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number1\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE number2\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE number3\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE number4\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE number5\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE number6\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE number7\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE number8\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE number9\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE number10\nYOU SET US UP @I LIED\n\nGET TO THE CHOPPER number1\nHERE IS MY INVITATION 187\nENOUGH TALK\n\nGET TO THE CHOPPER number2\nHERE IS MY INVITATION 218\nENOUGH TALK\n\nGET TO THE CHOPPER number3\nHERE IS MY INVITATION 260\nENOUGH TALK\n\nGET TO THE CHOPPER number4\nHERE IS MY INVITATION 295\nENOUGH TALK\n\nGET TO THE CHOPPER number5\nHERE IS MY INVITATION 301\nENOUGH TALK\n\nGET TO THE CHOPPER number6\nHERE IS MY INVITATION 314\nENOUGH TALK\n\nGET TO THE CHOPPER number7\nHERE IS MY INVITATION 379\nENOUGH TALK\n\nGET TO THE CHOPPER number8\nHERE IS MY INVITATION 410\nENOUGH TALK\n\nGET TO THE CHOPPER number9\nHERE IS MY INVITATION 452\nENOUGH TALK\n\nGET TO THE CHOPPER number10\nHERE IS MY INVITATION 469\nENOUGH TALK\n\nTALK TO THE HAND number1\nTALK TO THE HAND number2\nTALK TO THE HAND number3\nTALK TO THE HAND number4\nTALK TO THE HAND number5\nTALK TO THE HAND number6\nTALK TO THE HAND number7\nTALK TO THE HAND number8\nTALK TO THE HAND number9\nTALK TO THE HAND number10\n\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE sequenceStart\nYOU SET US UP 29\nHEY CHRISTMAS TREE sequenceTwo\nYOU SET US UP 63\nHEY CHRISTMAS TREE sequenceThree\nYOU SET US UP 95\nHEY CHRISTMAS TREE sequenceFour\nYOU SET US UP 140\nHEY CHRISTMAS TREE sequenceFive\nYOU SET US UP 150\nHEY CHRISTMAS TREE sequenceSix\nYOU SET US UP 190\nHEY CHRISTMAS TREE sequenceSeven\nYOU SET US UP 221\nHEY CHRISTMAS TREE sequenceEight\nYOU SET US UP 437\nHEY CHRISTMAS TREE sequenceNine\nYOU SET US UP 482\nHEY CHRISTMAS TREE sequenceTen\nYOU SET US UP 491\n\nTALK TO THE HAND sequenceStart\nTALK TO THE HAND sequenceTwo\nTALK TO THE HAND sequenceThree\nTALK TO THE HAND sequenceFour\nTALK TO THE HAND sequenceFive\nTALK TO THE HAND sequenceSix\nTALK TO THE HAND sequenceSeven\nTALK TO THE HAND sequenceEight\nTALK TO THE HAND sequenceNine\nTALK TO THE HAND sequenceTen\n\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE variable1\nYOU SET US UP 3\nHEY CHRISTMAS TREE variable2\nYOU SET US UP 11\nHEY CHRISTMAS TREE variable3\nYOU SET US UP 84\nHEY CHRISTMAS TREE variable4\nYOU SET US UP 144\nHEY CHRISTMAS TREE variable5\nYOU SET US UP 156\nHEY CHRISTMAS TREE variable6\nYOU SET US UP 177\nHEY CHRISTMAS TREE variable7\nYOU SET US UP 188\nHEY CHRISTMAS TREE variable8\nYOU SET US UP 199\nHEY CHRISTMAS TREE variable9\nYOU SET US UP 229\nHEY CHRISTMAS TREE variable10\nYOU SET US UP 284\nTALK TO THE HAND variable1\nTALK TO THE HAND variable2\nTALK TO THE HAND variable3\nTALK TO THE HAND variable4\nTALK TO THE HAND variable5\nTALK TO THE HAND variable6\nTALK TO THE HAND variable7\nTALK TO THE HAND variable8\nTALK TO THE HAND variable9\nTALK TO THE HAND variable10\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number1\nYOU SET US UP 134\nHEY CHRISTMAS TREE number2\nYOU SET US UP 224\nHEY CHRISTMAS TREE number3\nYOU SET US UP 293\nHEY CHRISTMAS TREE number4\nYOU SET US UP 378\nHEY CHRISTMAS TREE number5\nYOU SET US UP 379\nHEY CHRISTMAS TREE number6\nYOU SET US UP 395\nHEY CHRISTMAS TREE number7\nYOU SET US UP 434\nHEY CHRISTMAS TREE number8\nYOU SET US UP 451\nHEY CHRISTMAS TREE number9\nYOU SET US UP 482\nHEY CHRISTMAS TREE number10\nYOU SET US UP 496\n\nTALK TO THE HAND number1\nTALK TO THE HAND number2\nTALK TO THE HAND number3\nTALK TO THE HAND number4\nTALK TO THE HAND number5\nTALK TO THE HAND number6\nTALK TO THE HAND number7\nTALK TO THE HAND number8\nTALK TO THE HAND number9\nTALK TO THE HAND number10\n\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number0\nYOU SET US UP 39\nHEY CHRISTMAS TREE number1\nYOU SET US UP 81\nHEY CHRISTMAS TREE number2\nYOU SET US UP 88\nHEY CHRISTMAS TREE number3\nYOU SET US UP 210\nHEY CHRISTMAS TREE number4\nYOU SET US UP 215\nHEY CHRISTMAS TREE number5\nYOU SET US UP 378\nHEY CHRISTMAS TREE number6\nYOU SET US UP 416\nHEY CHRISTMAS TREE number7\nYOU SET US UP 430\nHEY CHRISTMAS TREE number8\nYOU SET US UP 439\nHEY CHRISTMAS TREE number9\nYOU SET US UP 490\n\nTALK TO THE HAND number0\nTALK TO THE HAND number1\nTALK TO THE HAND number2\nTALK TO THE HAND number3\nTALK TO THE HAND number4\nTALK TO THE HAND number5\nTALK TO THE HAND number6\nTALK TO THE HAND number7\nTALK TO THE HAND number8\nTALK TO THE HAND number9\n\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number1\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE number2\nYOU SET US UP 26\nHEY CHRISTMAS TREE number3\nYOU SET US UP 40\nHEY CHRISTMAS TREE number4\nYOU SET US UP 202\nHEY CHRISTMAS TREE number5\nYOU SET US UP 267\nHEY CHRISTMAS TREE number6\nYOU SET US UP 282\nHEY CHRISTMAS TREE number7\nYOU SET US UP 340\nHEY CHRISTMAS TREE number8\nYOU SET US UP 359\nHEY CHRISTMAS TREE number9\nYOU SET US UP 408\nHEY CHRISTMAS TREE number10\nYOU SET US UP 410\nHEY CHRISTMAS TREE number11\nYOU SET US UP 495\nTALK TO THE HAND number2\nTALK TO THE HAND number3\nTALK TO THE HAND number4\nTALK TO THE HAND number5\nTALK TO THE HAND number6\nTALK TO THE HAND number7\nTALK TO THE HAND number8\nTALK TO THE HAND number9\nTALK TO THE HAND number10\nTALK TO THE HAND number11\nYOU HAVE BEEN TERMINATED\n```"]

In [28]:
seq_test

['8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '4, 8, 12, 16, 20, 24, 28, 32, 36, 40',
 '2, 4, 6, 8, 10, 12, 14, 16, 18, 20',
 '8, 16, 24, 32, 40, 48, 56, 64, 72, 80',
 '1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880',
 '2, 4, 8, 16, 32, 64, 128, 256, 512, 1024',
 '1, 4, 2, 1, 3, 5, 9, 2, 6, 5',
 '18, 39, 71, 194, 197, 219, 263, 270, 416, 473',
 '72, 106, 139, 165, 171, 192, 199, 429, 453, 477',
 '187, 218, 260, 295, 301, 314, 379, 410, 452, 469',
 '29, 63, 95, 140, 150, 190, 221, 437, 482, 491',
 '3, 11, 84, 144, 156, 177, 188, 199, 229, 284',
 '134, 224, 293, 378, 379, 395, 434, 451, 482, 496',
 '39, 81, 88, 210, 215, 378, 416, 430, 439, 490',
 '26, 40, 202, 267, 282, 340, 359, 408, 410, 495']

In [86]:
one_seq = '26, 40, 202, 267, 282, 340, 359, 408, 410, 495'
one_seq = one_seq.replace(" ", "")
print(one_seq)
all_numbers = one_seq.split(",")
print(all_numbers)

26,40,202,267,282,340,359,408,410,495
['26', '40', '202', '267', '282', '340', '359', '408', '410', '495']

In [87]:
one_prog_str = answers_test[18]
one_prog_str

"```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number1\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE number2\nYOU SET US UP 26\nHEY CHRISTMAS TREE number3\nYOU SET US UP 40\nHEY CHRISTMAS TREE number4\nYOU SET US UP 202\nHEY CHRISTMAS TREE number5\nYOU SET US UP 267\nHEY CHRISTMAS TREE number6\nYOU SET US UP 282\nHEY CHRISTMAS TREE number7\nYOU SET US UP 340\nHEY CHRISTMAS TREE number8\nYOU SET US UP 359\nHEY CHRISTMAS TREE number9\nYOU SET US UP 408\nHEY CHRISTMAS TREE number10\nYOU SET US UP 410\nHEY CHRISTMAS TREE number11\nYOU SET US UP 495\nTALK TO THE HAND number2\nTALK TO THE HAND number3\nTALK TO THE HAND number4\nTALK TO THE HAND number5\nTALK TO THE HAND number6\nTALK TO THE HAND number7\nTALK TO THE HAND number8\nTALK TO THE HAND number9\nTALK TO THE HAND number10\nTALK TO THE HAND number11\nYOU HAVE BEEN TERMINATED\n```"

In [104]:
print("source: ")
print(one_prog_str)
print("\n")

indexes = [-1] * len(all_numbers)
for i in range(len(all_numbers)):
    if all_numbers[i] in one_prog_str:
        ind = one_prog_str.index(all_numbers[i])
        indexes[i]=ind
        print("{} found at {}".format(all_numbers[i], ind) )

print("indexes: ", str(indexes))
print("\n")

print("printing places by index")
print("----------------------------")

for i in range(len(indexes)):
    if indexes[i] > -1:
        print("original: {}, found: {}".format(all_numbers[i], one_prog_str[indexes[i]: indexes[i]+3]))
    else:
        print("invelid index: {}".format(indexes[i]))

source:
```arnoldc
IT'S SHOWTIME
HEY CHRISTMAS TREE number1
YOU SET US UP @I LIED
HEY CHRISTMAS TREE number2
YOU SET US UP 26
HEY CHRISTMAS TREE number3
YOU SET US UP 40
HEY CHRISTMAS TREE number4
YOU SET US UP 202
HEY CHRISTMAS TREE number5
YOU SET US UP 267
HEY CHRISTMAS TREE number6
YOU SET US UP 282
HEY CHRISTMAS TREE number7
YOU SET US UP 340
HEY CHRISTMAS TREE number8
YOU SET US UP 359
HEY CHRISTMAS TREE number9
YOU SET US UP 408
HEY CHRISTMAS TREE number10
YOU SET US UP 410
HEY CHRISTMAS TREE number11
YOU SET US UP 495
TALK TO THE HAND number2
TALK TO THE HAND number3
TALK TO THE HAND number4
TALK TO THE HAND number5
TALK TO THE HAND number6
TALK TO THE HAND number7
TALK TO THE HAND number8
TALK TO THE HAND number9
TALK TO THE HAND number10
TALK TO THE HAND number11
YOU HAVE BEEN TERMINATED
```


26 found at 115
40 found at 159
202 found at 203
267 found at 248
282 found at 293
340 found at 338
359 found at 383
408 found at 428
410 found at 474
495 found at 520
indexes:  [115, 159, 203, 248, 293, 338, 383, 428, 474, 520]


printing places by index
----------------------------
original: 26, found: 26

original: 40, found: 40

original: 202, found: 202
original: 267, found: 267
original: 282, found: 282
original: 340, found: 340
original: 359, found: 359
original: 408, found: 408
original: 410, found: 410
original: 495, found: 495

In [134]:
def test_all_content(orig_seq_str, answer_code_str):
    clean_seq = orig_seq_str.replace(" ", "")
    separated_numbers = clean_seq.split(',')

    indexes = [-1] * len(separated_numbers)
    contained = [False] * len(separated_numbers)
    for i in range(len(separated_numbers)):
        # print(" is there ", "[", separated_numbers[i], "]")
        wanted = " " + str(separated_numbers[i])
        if wanted in answer_code_str:
            indexes[i] = answer_code_str.index(separated_numbers[i])
            contained[i] = True
    # if all(contained):
    #     print("========================================== success!!!!")
    #     print("separated_numbers", separated_numbers)
    #     print("indexes: ", indexes)
    #     print("\n")
    #     print(answer_code_str)
    return all(contained)

def test_declaration_seq(original_seq, answer_code_str):
    return original_seq in answer_code_str

In [128]:
# for h in range(len(answers_test)):
#     for i  in range(len(seq_test)):
#         is_there, indexes = test_all_content(seq_test[i], answers_test[h])
#         if is_there:
#             print("========================================== success [end]!!!!")

In [129]:
# for h in range(len(answers_test)):
#     for i  in range(len(seq_test)):
#         is_there = test_declaration_seq(seq_test[i], answers_test[h])
#         if is_there:
#             print("========================================== success [end]!!!!")

In [132]:
original_seq
answers

["```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION @I LIED\nGET UP 20\nENOUGH TALK\n\nSTICK AROUND limit\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 2\nENOUGH TALK\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 0\nHEY CHRISTMAS TREE limit\nYOU SET US UP 30\nSTICK AROUND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 3\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nPLUS 3\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE number\nI LIED limit\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 4\nHEY CHRISTMAS TREE limit\nYOU SET US UP 40\nSTICK AROUND number\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 4\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE number\nI LIED limit\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```ArnoldC\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE step\nYOU SET US UP 5\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP step\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION number\nLET OFF SOME STEAM BENNET 50\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE result\nYOU SET US UP @NO PROBLEMO\nSTICK AROUND number\nTALK TO THE HAND result\nGET UP result\nYOU'RE FIRED 6\nENOUGH TALK\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nYOU'RE FIRED 1\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE number\nI LET HIM GO 10\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
 "```ArnoldC\nIT'S SHOWTIME\nHEY CHRISTMAS TREE sequence\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE num\nYOU SET US UP 0\nHEY CHRISTMAS TREE limit\nYOU SET US UP 70\nSTICK AROUND sequence\nGET TO THE CHOPPER num\nHERE IS MY INVITATION num\nGET UP 7\nENOUGH TALK\nTALK TO THE HAND num\nGET TO THE CHOPPER sequence\nHERE IS MY INVITATION sequence\nHE HAD TO SPLIT 7\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE num\nI LET HIM GO limit\nYOU HAVE NO RESPECT FOR LOGIC\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 0\nHEY CHRISTMAS TREE limit\nYOU SET US UP 10\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 8\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 0\nHEY CHRISTMAS TREE i\nYOU SET US UP 1\nSTICK AROUND i\nTALK TO THE HAND i\nGET TO THE CHOPPER number\nHERE IS MY INVITATION i\nGET UP 9\nENOUGH TALK\nGET TO THE CHOPPER i\nHERE IS MY INVITATION i\nGET UP 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 0\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 10\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE number\nLESS THAN 100\nBULLSHIT\nCHILL\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE increment\nYOU SET US UP 2\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION 20\nENOUGH TALK\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP increment\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE step\nYOU SET US UP @I LIED\nSTICK AROUND limit\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP step\nENOUGH TALK\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET UP step\nENOUGH TALK\nCHILL\nYOU HAVE NO RESPECT FOR LOGIC\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nSTICK AROUND limit\nTALK TO THE HAND number\nGET TO THE CHOPPA number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nGET TO THE CHOPPA limit\nHERE IS MY INVITATION 20\nLET OFF SOME STEAM BENNET number\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 20\nSTICK AROUND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE number\nLESS THAN 31\nBULLSHIT\nCHILL\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 31\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nENOUGH TALK\nYOU HAVE NO RESPECT FOR LOGIC\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 41\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nYOU'RE FIRED 1\nBECAUSE I'M GOING TO SAY PLEASE number\nI LIED 50\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nGET TO THE CHOPPER number\nHERE IS MY INVITATION 51\nENOUGH TALK\nSTICK AROUND number\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION @I LIED\nYOU'RE FIRED @NO PROBLEMO\nENOUGH TALK\n\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP @I LIED\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN @ONE\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```ArnoldC\nIT'S SHOWTIME\nHEY CHRISTMAS TREE sequence\nYOU SET US UP 71\nSTICK AROUND sequence\nTALK TO THE HAND sequence\nGET UP sequence\nYOU HAVE NO RESPECT FOR LOGIC\nBECAUSE I'M GOING TO SAY PLEASE sequence < 81\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 81\nSTICK AROUND number\n    TALK TO THE HAND number\n    GET UP number\n    BECAUSE I'M GOING TO SAY PLEASE number < 91\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nSTICK AROUND limit\nTALK TO THE HAND number\nGET UP number\nYOU'RE FIRED 1\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION number\nYOU'RE FIRED 10\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 101\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nYOU'RE FIRED 1\nBECAUSE I'M GOING TO SAY PLEASE number\nI LET HIM GO 110\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 111\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nYOU'RE FIRED 1\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE number\nI LET HIM GO 120\nBULLSHIT\nCHILL\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP 130\nSTICK AROUND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nTALK TO THE HAND number\nBECAUSE I'M GOING TO SAY PLEASE limit\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nYOU'RE FIRED 1\nENOUGH TALK\nCHILL limit\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 130\nSTICK AROUND number\nI LET HIM GO 140\nGET UP number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nTALK TO THE HAND number\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP 150\nSTICK AROUND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE number\nI LIED limit\nYOU HAVE NO RESPECT FOR LOGIC\nBULLSHIT\nYOU HAVE BEEN TERMINATED\nCHILL\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 151\nSTICK AROUND number\nI WANT TO ASK YOU A BUNCH OF THINGS AND I WANT TO HAVE THEM ANSWERED IMMEDIATELY\nTALK TO THE HAND number\nGET UP number\nYOU'RE FIRED 1\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE number\nLESS THAN 161\nBULLSHIT\nCHILL\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
 "```ArnoldC\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 161\n\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\n\nBECAUSE I'M GOING TO SAY PLEASE number\nLESS THAN 171\nYOU HAVE NO RESPECT FOR LOGIC\n\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```ArnoldC\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 171\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nBECAUSE I'M GOING TO SAY PLEASE number\nLESS THAN 181\nYOU HAVE NO RESPECT FOR LOGIC\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE condition\nYOU SET US UP 0\nGET TO THE CHOPPER number\nHERE IS MY INVITATION 181\nENOUGH TALK\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION 190\nENOUGH TALK\nSTICK AROUND condition\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nGET TO THE CHOPPER condition\nHERE IS MY INVITATION number\nLET OFF SOME STEAM BENNET limit\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 191\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE number I LIED 200\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 0\nHEY CHRISTMAS TREE limit\nYOU SET US UP 10\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 2\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE step\nYOU SET US UP 3\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP step\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET UP step\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE limit\nI'LL BE BACK 30\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE increment\nYOU SET US UP 4\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP increment\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET UP increment\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE limit\nI LIED 40\nYOU HAVE NO RESPECT FOR LOGIC\nCHILL\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 0\nHEY CHRISTMAS TREE limit\nYOU SET US UP 10\nSTICK AROUND limit\nGET UP number\nYOU'RE FIRED 5\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE step\nYOU SET US UP 6\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP step\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET UP 6\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE counter\nYOU SET US UP 0\nSTICK AROUND counter\nTALK TO THE HAND number\nGET UP number\nYOU'RE FIRED 7\nGET DOWN counter\nYOU'RE FIRED 1\nCHILL counter LESS THAN 10\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 8\nHEY CHRISTMAS TREE limit\nYOU SET US UP 80\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nYOU'RE FIRED 8\nCHILL number\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE multiplier\nYOU SET US UP 1\nSTICK AROUND multiplier\nTALK TO THE HAND number\nGET UP number\nYOU'RE FIRED 9\nGET TO THE CHOPPER multiplier\nHERE IS MY INVITATION multiplier\nGET UP 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE step\nYOU SET US UP 10\nSTICK AROUND limit\nTALK TO THE HAND number\nGET UP number\nYOU'RE FIRED step\nBECAUSE I'M GOING TO SAY PLEASE number\nI LET HIM GO 100\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE step\nYOU SET US UP 2\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION 20\nENOUGH TALK\nSTICK AROUND number\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP step\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE step\nYOU SET US UP 2\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION 20\nENOUGH TALK\nSTICK AROUND limit\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP step\nENOUGH TALK\nTALK TO THE HAND number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 2\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 11\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nYOU'RE FIRED 1\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE number\nLESS THAN 21\nBULLSHIT\nCHILL\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nSTICK AROUND limit\nTALK TO THE HAND number\nGET UP number\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION 30\nYOU'RE FIRED number\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```ArnoldC\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION @I LIED\nGET UP 40\nENOUGH TALK\n\nSTICK AROUND limit\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 41\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nYOU'RE FIRED 1\nHE HAD TO SPLIT 50\nYOU HAVE NO RESPECT FOR LOGIC\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP 60\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nYOU'RE FIRED 1\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE number\nLESS THAN limit\nKNOCK KNOCK\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 61\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nENOUGH TALK\nBECAUSE I'M GOING TO SAY PLEASE number\nLESS THAN 71\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 71\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nYOU'RE FIRED 1\nHE HAD TO SPLIT 80\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 81\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nYOU'RE FIRED 1\nBECAUSE I'M GOING TO SAY PLEASE number\nLESS THAN 91\nENOUGH TALK\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 91\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nENOUGH TALK\nYOU HAVE NO RESPECT FOR LOGIC\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 100\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nBECAUSE I'M GOING TO SAY PLEASE number\nLESS THAN 111\nYOU HAVE NO RESPECT FOR LOGIC\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION @I LIED\nGET UP 120\nENOUGH TALK\n\nSTICK AROUND limit\nTALK TO THE HAND number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP 1\nENOUGH TALK\n\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION limit\nGET DOWN 1\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 121\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nYOU'RE FIRED 1\nBECAUSE I'M GOING TO SAY PLEASE number\nLESS THAN 131\nBULLSHIT\nCHILL\nYOU HAVE NO RESPECT FOR LOGIC\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP 130\nSTICK AROUND number\nTALK TO THE HAND number\nGET UP number\nENOUGH TALK\nYOU HAVE NO RESPECT FOR LOGIC\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE sequence\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP 10\nHEY CHRISTMAS TREE i\nYOU SET US UP 0\nSTICK AROUND i\nTALK TO THE HAND sequence\nGET UP sequence\nGET TO THE CHOPPER sequence\nHERE IS MY INVITATION sequence\nYOU'RE FIRED 1\nENOUGH TALK\nGET TO THE CHOPPER i\nHERE IS MY INVITATION i\nYOU'RE FIRED 1\nENOUGH TALK\nCHILL i\nYOU HAVE BEEN TERMINATED\n```",
 "```arnoldc\nIT'S SHOWTIME\nHEY CHRISTMAS TREE number\nYOU SET US UP @I LIED\nHEY CHRISTMAS TREE limit\nYOU SET US UP @NO PROBLEMO\nHEY CHRISTMAS TREE step\nYOU SET US UP 1\n\nSTICK AROUND limit\nTALK TO THE HAND number\nGET UP number\nGET TO THE CHOPPER number\nHERE IS MY INVITATION number\nGET UP step\nENOUGH TALK\nGET TO THE CHOPPER limit\nHERE IS MY INVITATION 160\nLET OFF SOME STEAM BENNET number\nENOUGH TALK\nCHILL\nYOU HAVE BEEN TERMINATED\n```",

In [137]:
print_cases = [0] * len(answers)

for s in range(len(original_seq)):
    for a in range(len(answers)):
        is_print_case = test_all_content(original_seq[s], answers[a])
        if is_print_case:
            print_cases[a] = 1
            print("================================ SUCCESS!!!")
            print("Sequence: ", original_seq[s])
            print("\n")
            print(answers[a])
            break
        else:
            is_print_case = test_declaration_seq(original_seq[s], answers[a])
            if is_print_case:
                print_cases[a] = 1
                break

================================ SUCCESS!!!
Sequence:  0, 1, 81, 512, 2401, 4913, 5832, 17576, 19683, 234256


```arnoldc
IT'S SHOWTIME
HEY CHRISTMAS TREE sequence
YOU SET US UP 10
HEY CHRISTMAS TREE index
YOU SET US UP @I LIED
HEY CHRISTMAS TREE result
YOU SET US UP @I LIED
STICK AROUND index
GET TO THE CHOPPER result
HERE IS MY INVITATION 0
ENOUGH TALK
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 1
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 81
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 512
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 2401
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 4913
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 5832
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 17576
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 19683
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 234256
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
TALK TO THE HAND result
GET UP index
GET TO THE CHOPPER index
HERE IS MY INVITATION index
GET DOWN 1
ENOUGH TALK
CHILL
YOU HAVE BEEN TERMINATED
```
================================ SUCCESS!!!
Sequence:  1, 8, 10, 18, 19, 100, 101, 108, 109, 110


```arnoldc
IT'S SHOWTIME
HEY CHRISTMAS TREE sequence
YOU SET US UP @I LIED
HEY CHRISTMAS TREE index
YOU SET US UP 0
HEY CHRISTMAS TREE limit
YOU SET US UP 10
STICK AROUND index
TALK TO THE HAND index
GET TO THE CHOPPER index
HERE IS MY INVITATION index
GET UP 1
ENOUGH TALK
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 1
YOU'RE FIRED 8
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 10
YOU'RE FIRED 8
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 18
YOU'RE FIRED 1
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 19
YOU'RE FIRED 81
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 100
YOU'RE FIRED 1
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 101
YOU'RE FIRED 7
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 108
YOU'RE FIRED 1
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 109
YOU'RE FIRED 1
ENOUGH TALK
BULLSHIT
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 110
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
TALK TO THE HAND sequence
CHILL
YOU HAVE BEEN TERMINATED
```
================================ SUCCESS!!!
Sequence:  1, 2, 4, 8, 16, 23, 28, 38, 58, 89


```arnoldc
IT'S SHOWTIME
HEY CHRISTMAS TREE sequence
YOU SET US UP @NO PROBLEMO
HEY CHRISTMAS TREE limit
YOU SET US UP 10
HEY CHRISTMAS TREE next
YOU SET US UP 0
HEY CHRISTMAS TREE i
YOU SET US UP 1
STICK AROUND i
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 1
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 2
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 4
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 8
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 16
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 23
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 28
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 38
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 58
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 89
  TALK TO THE HAND next
  GET UP i
CHILL
YOU HAVE BEEN TERMINATED
```
================================ SUCCESS!!!
Sequence:  0, 1, 1, 2, 1, 2, 2, 3, 1, 3


```ArnoldC
IT'S SHOWTIME
HEY CHRISTMAS TREE number
YOU SET US UP @I LIED
HEY CHRISTMAS TREE limit
YOU SET US UP @NO PROBLEMO
HEY CHRISTMAS TREE isPrime
YOU SET US UP 0
GET TO THE CHOPPER limit
HERE IS MY INVITATION 30
ENOUGH TALK
STICK AROUND limit
HEY CHRISTMAS TREE divisor
YOU SET US UP 0
GET TO THE CHOPPER number
HERE IS MY INVITATION number
GET UP 1
ENOUGH TALK
GET TO THE CHOPPER isPrime
HERE IS MY INVITATION @NO PROBLEMO
ENOUGH TALK
GET TO THE CHOPPER divisor
HERE IS MY INVITATION 2
ENOUGH TALK
STICK AROUND number
GET TO THE CHOPPER isPrime
HERE IS MY INVITATION isPrime
KNOCK KNOCK number
DIVIDE AND CONQUER divisor
YOU'RE FIRED isPrime
ENOUGH TALK
GET TO THE CHOPPER divisor
HERE IS MY INVITATION divisor
GET UP 1
ENOUGH TALK
CHILL
BECAUSE I'M GOING TO SAY PLEASE isPrime
TALK TO THE HAND number
BULLSHIT
YOU HAVE NO RESPECT FOR LOGIC
YOU HAVE BEEN TERMINATED
```
================================ SUCCESS!!!
Sequence:  0, 1, 81, 512, 2401, 4913, 5832, 17576, 19683, 234256


```arnoldc
IT'S SHOWTIME
HEY CHRISTMAS TREE sequence
YOU SET US UP 10
HEY CHRISTMAS TREE index
YOU SET US UP @I LIED
HEY CHRISTMAS TREE result
YOU SET US UP @I LIED
STICK AROUND index
GET TO THE CHOPPER result
HERE IS MY INVITATION 0
ENOUGH TALK
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 1
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 81
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 512
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 2401
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 4913
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 5832
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 17576
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 19683
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 234256
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
TALK TO THE HAND result
GET UP index
GET TO THE CHOPPER index
HERE IS MY INVITATION index
GET DOWN 1
ENOUGH TALK
CHILL
YOU HAVE BEEN TERMINATED
```
================================ SUCCESS!!!
Sequence:  1, 8, 10, 18, 19, 100, 101, 108, 109, 110


```arnoldc
IT'S SHOWTIME
HEY CHRISTMAS TREE sequence
YOU SET US UP @I LIED
HEY CHRISTMAS TREE index
YOU SET US UP 0
HEY CHRISTMAS TREE limit
YOU SET US UP 10
STICK AROUND index
TALK TO THE HAND index
GET TO THE CHOPPER index
HERE IS MY INVITATION index
GET UP 1
ENOUGH TALK
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 1
YOU'RE FIRED 8
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 10
YOU'RE FIRED 8
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 18
YOU'RE FIRED 1
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 19
YOU'RE FIRED 81
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 100
YOU'RE FIRED 1
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 101
YOU'RE FIRED 7
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 108
YOU'RE FIRED 1
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 109
YOU'RE FIRED 1
ENOUGH TALK
BULLSHIT
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 110
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
TALK TO THE HAND sequence
CHILL
YOU HAVE BEEN TERMINATED
```
================================ SUCCESS!!!
Sequence:  1, 2, 4, 8, 16, 23, 28, 38, 58, 89


```arnoldc
IT'S SHOWTIME
HEY CHRISTMAS TREE sequence
YOU SET US UP @NO PROBLEMO
HEY CHRISTMAS TREE limit
YOU SET US UP 10
HEY CHRISTMAS TREE next
YOU SET US UP 0
HEY CHRISTMAS TREE i
YOU SET US UP 1
STICK AROUND i
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 1
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 2
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 4
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 8
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 16
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 23
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 28
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 38
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 58
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 89
  TALK TO THE HAND next
  GET UP i
CHILL
YOU HAVE BEEN TERMINATED
```
================================ SUCCESS!!!
Sequence:  0, 1, 1, 2, 1, 2, 2, 3, 1, 3


```ArnoldC
IT'S SHOWTIME
HEY CHRISTMAS TREE number
YOU SET US UP @I LIED
HEY CHRISTMAS TREE limit
YOU SET US UP @NO PROBLEMO
HEY CHRISTMAS TREE isPrime
YOU SET US UP 0
GET TO THE CHOPPER limit
HERE IS MY INVITATION 30
ENOUGH TALK
STICK AROUND limit
HEY CHRISTMAS TREE divisor
YOU SET US UP 0
GET TO THE CHOPPER number
HERE IS MY INVITATION number
GET UP 1
ENOUGH TALK
GET TO THE CHOPPER isPrime
HERE IS MY INVITATION @NO PROBLEMO
ENOUGH TALK
GET TO THE CHOPPER divisor
HERE IS MY INVITATION 2
ENOUGH TALK
STICK AROUND number
GET TO THE CHOPPER isPrime
HERE IS MY INVITATION isPrime
KNOCK KNOCK number
DIVIDE AND CONQUER divisor
YOU'RE FIRED isPrime
ENOUGH TALK
GET TO THE CHOPPER divisor
HERE IS MY INVITATION divisor
GET UP 1
ENOUGH TALK
CHILL
BECAUSE I'M GOING TO SAY PLEASE isPrime
TALK TO THE HAND number
BULLSHIT
YOU HAVE NO RESPECT FOR LOGIC
YOU HAVE BEEN TERMINATED
```
================================ SUCCESS!!!
Sequence:  0, 1, 81, 512, 2401, 4913, 5832, 17576, 19683, 234256


```arnoldc
IT'S SHOWTIME
HEY CHRISTMAS TREE sequence
YOU SET US UP 10
HEY CHRISTMAS TREE index
YOU SET US UP @I LIED
HEY CHRISTMAS TREE result
YOU SET US UP @I LIED
STICK AROUND index
GET TO THE CHOPPER result
HERE IS MY INVITATION 0
ENOUGH TALK
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 1
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 81
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 512
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 2401
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 4913
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 5832
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 17576
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 19683
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 234256
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
TALK TO THE HAND result
GET UP index
GET TO THE CHOPPER index
HERE IS MY INVITATION index
GET DOWN 1
ENOUGH TALK
CHILL
YOU HAVE BEEN TERMINATED
```
================================ SUCCESS!!!
Sequence:  1, 8, 10, 18, 19, 100, 101, 108, 109, 110


```arnoldc
IT'S SHOWTIME
HEY CHRISTMAS TREE sequence
YOU SET US UP @I LIED
HEY CHRISTMAS TREE index
YOU SET US UP 0
HEY CHRISTMAS TREE limit
YOU SET US UP 10
STICK AROUND index
TALK TO THE HAND index
GET TO THE CHOPPER index
HERE IS MY INVITATION index
GET UP 1
ENOUGH TALK
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 1
YOU'RE FIRED 8
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 10
YOU'RE FIRED 8
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 18
YOU'RE FIRED 1
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 19
YOU'RE FIRED 81
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 100
YOU'RE FIRED 1
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 101
YOU'RE FIRED 7
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 108
YOU'RE FIRED 1
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 109
YOU'RE FIRED 1
ENOUGH TALK
BULLSHIT
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 110
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
TALK TO THE HAND sequence
CHILL
YOU HAVE BEEN TERMINATED
```
================================ SUCCESS!!!
Sequence:  1, 2, 4, 8, 16, 23, 28, 38, 58, 89


```arnoldc
IT'S SHOWTIME
HEY CHRISTMAS TREE sequence
YOU SET US UP @NO PROBLEMO
HEY CHRISTMAS TREE limit
YOU SET US UP 10
HEY CHRISTMAS TREE next
YOU SET US UP 0
HEY CHRISTMAS TREE i
YOU SET US UP 1
STICK AROUND i
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 1
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 2
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 4
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 8
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 16
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 23
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 28
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 38
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 58
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 89
  TALK TO THE HAND next
  GET UP i
CHILL
YOU HAVE BEEN TERMINATED
```
================================ SUCCESS!!!
Sequence:  0, 1, 1, 2, 1, 2, 2, 3, 1, 3


```ArnoldC
IT'S SHOWTIME
HEY CHRISTMAS TREE number
YOU SET US UP @I LIED
HEY CHRISTMAS TREE limit
YOU SET US UP @NO PROBLEMO
HEY CHRISTMAS TREE isPrime
YOU SET US UP 0
GET TO THE CHOPPER limit
HERE IS MY INVITATION 30
ENOUGH TALK
STICK AROUND limit
HEY CHRISTMAS TREE divisor
YOU SET US UP 0
GET TO THE CHOPPER number
HERE IS MY INVITATION number
GET UP 1
ENOUGH TALK
GET TO THE CHOPPER isPrime
HERE IS MY INVITATION @NO PROBLEMO
ENOUGH TALK
GET TO THE CHOPPER divisor
HERE IS MY INVITATION 2
ENOUGH TALK
STICK AROUND number
GET TO THE CHOPPER isPrime
HERE IS MY INVITATION isPrime
KNOCK KNOCK number
DIVIDE AND CONQUER divisor
YOU'RE FIRED isPrime
ENOUGH TALK
GET TO THE CHOPPER divisor
HERE IS MY INVITATION divisor
GET UP 1
ENOUGH TALK
CHILL
BECAUSE I'M GOING TO SAY PLEASE isPrime
TALK TO THE HAND number
BULLSHIT
YOU HAVE NO RESPECT FOR LOGIC
YOU HAVE BEEN TERMINATED
```
================================ SUCCESS!!!
Sequence:  0, 1, 81, 512, 2401, 4913, 5832, 17576, 19683, 234256


```arnoldc
IT'S SHOWTIME
HEY CHRISTMAS TREE sequence
YOU SET US UP 10
HEY CHRISTMAS TREE index
YOU SET US UP @I LIED
HEY CHRISTMAS TREE result
YOU SET US UP @I LIED
STICK AROUND index
GET TO THE CHOPPER result
HERE IS MY INVITATION 0
ENOUGH TALK
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 1
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 81
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 512
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 2401
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 4913
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 5832
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 17576
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 19683
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
BECAUSE I'M GOING TO SAY PLEASE index
GET TO THE CHOPPER result
HERE IS MY INVITATION 234256
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
TALK TO THE HAND result
GET UP index
GET TO THE CHOPPER index
HERE IS MY INVITATION index
GET DOWN 1
ENOUGH TALK
CHILL
YOU HAVE BEEN TERMINATED
```
================================ SUCCESS!!!
Sequence:  1, 8, 10, 18, 19, 100, 101, 108, 109, 110


```arnoldc
IT'S SHOWTIME
HEY CHRISTMAS TREE sequence
YOU SET US UP @I LIED
HEY CHRISTMAS TREE index
YOU SET US UP 0
HEY CHRISTMAS TREE limit
YOU SET US UP 10
STICK AROUND index
TALK TO THE HAND index
GET TO THE CHOPPER index
HERE IS MY INVITATION index
GET UP 1
ENOUGH TALK
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 1
YOU'RE FIRED 8
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 10
YOU'RE FIRED 8
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 18
YOU'RE FIRED 1
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 19
YOU'RE FIRED 81
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 100
YOU'RE FIRED 1
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 101
YOU'RE FIRED 7
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 108
YOU'RE FIRED 1
ENOUGH TALK
BULLSHIT
BECAUSE I'M GOING TO SAY PLEASE index
I LIED
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 109
YOU'RE FIRED 1
ENOUGH TALK
BULLSHIT
GET TO THE CHOPPER sequence
HERE IS MY INVITATION 110
ENOUGH TALK
YOU HAVE NO RESPECT FOR LOGIC
TALK TO THE HAND sequence
CHILL
YOU HAVE BEEN TERMINATED
```
================================ SUCCESS!!!
Sequence:  1, 2, 4, 8, 16, 23, 28, 38, 58, 89


```arnoldc
IT'S SHOWTIME
HEY CHRISTMAS TREE sequence
YOU SET US UP @NO PROBLEMO
HEY CHRISTMAS TREE limit
YOU SET US UP 10
HEY CHRISTMAS TREE next
YOU SET US UP 0
HEY CHRISTMAS TREE i
YOU SET US UP 1
STICK AROUND i
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 1
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 2
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 4
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 8
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 16
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 23
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 28
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 38
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 58
  BECAUSE I'M GOING TO SAY PLEASE i
  I LET HIM GO 89
  TALK TO THE HAND next
  GET UP i
CHILL
YOU HAVE BEEN TERMINATED
```
================================ SUCCESS!!!
Sequence:  0, 1, 1, 2, 1, 2, 2, 3, 1, 3


```ArnoldC
IT'S SHOWTIME
HEY CHRISTMAS TREE number
YOU SET US UP @I LIED
HEY CHRISTMAS TREE limit
YOU SET US UP @NO PROBLEMO
HEY CHRISTMAS TREE isPrime
YOU SET US UP 0
GET TO THE CHOPPER limit
HERE IS MY INVITATION 30
ENOUGH TALK

In [138]:
print_cases

[1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [139]:
arnoldC_df["print_code"] = print_cases

In [140]:
arnoldC_df.to_csv("automatic_arnoldC.csv", index=False)