In [3]:
import pandas as pd

In [4]:
formulas_ds = pd.read_csv('new-multi-formulae.csv')
formulas_ds

,grok_4.1,gpt-5.2,claude-4.5,gemini-3-pro,mistral-large-3
0,"[""a(n) = 2*n for n=1..10""]","[""a_n = 2 n"",""a_n = n + n""]","[""a(n) = 2n"", ""a(n) = 2(n+1)"", ""a(n) = 2n for ...","[""2n""]","[""a_n = 2n, n ∈ [1,10]""]"
1,"[""a(n) = 3*n for n=1..10""]","[""a_n = 3 n""]","[""a(n) = 3n"", ""a(n) = 3(n+1)"", ""a(n) = 3n for ...","[""3n""]","[""a_n = 3n, n ∈ [1,10]""]"
2,"[""a(n) = 4*n for n=1..10""]","[""a_n = 4 n""]","[""a(n) = 4n"", ""a(n) = 4(n+1)"", ""a(n) = 4n for ...","[""4n""]","[""a_n = 4n, n ∈ [1,10]""]"
3,"[""a(n) = 5*n for n=1..10""]","[""a_n = 5 n""]","[""a(n) = 5n"", ""a(n) = 5(n+1)"", ""a(n) = 5n for ...","[""5n""]","[""a_n = 5n, n ∈ [1,10]""]"
4,"[""a(n) = 6*n for n=1..10""]","[""a_n = 6 n""]","[""a(n) = 6n"", ""a(n) = 6(n+1)"", ""a(n) = 6n for ...","[""6n""]","[""a_n = 6n, n ∈ [1,10]""]"
...,...,...,...,...,...
85,"[""*not found*""]","[""*not found""]",*not found,*not found,"[""*not found""]"
86,"[""*not found*""]","[""*not found""]",*not found,*not found,"[""*not found""]"
87,"[""*not found*""]","[""*not found""]",*not found,*not found,"[""*not found""]"
88,"[""*not found*""]","[""*not found""]",*not found,*not found,"[""*not found""]"
89,"[""*not found*""]","[""*not found""]",*not found,*not found,"[""*not found""]"

In [6]:
model_names = [col for col in formulas_ds.columns if col not in {'sequence', 'Complexity'}]
model_names

['grok_4.1', 'gpt-5.2', 'claude-4.5', 'gemini-3-pro', 'mistral-large-3']

In [7]:
import ast
import json

def separate_formulas(df, model_column):
    # Find the maximum number of formulas in the column
    max_formulas = 0
    
    for index, row in df.iterrows():
        try:
            sample = row[model_column]
            print('processing: ', sample)
            sample_list = json.loads(sample.replace("'", '"'))
            # Only count non "*not found" entries for max_formulas
            valid_formulas = [f for f in sample_list if f != "*not found"]
            max_formulas = max(max_formulas, len(valid_formulas))
        except Exception as e:
            print(f"Error processing row {sample}, {index}: {e}")
    
    # Create new columns based on max_formulas
    for i in range(max_formulas):
        column_name = f"{model_column}_{i+1}"
        df[column_name] = '*not found'
    
    # Populate the new columns with formulas
    for index, row in df.iterrows():
        try:
            sample = row[model_column]
            sample_list = json.loads(sample.replace("'", '"'))
            
            # Filter out "*not found" entries
            valid_formulas = [f for f in sample_list if f != "*not found"]
            
            # Assign each valid formula to its corresponding column
            for i, formula in enumerate(valid_formulas):
                column_name = f"{model_column}_{i+1}"
                df.at[index, column_name] = formula
        except Exception as e:
            print(f"Error processing row {index}: {e}")
    
    return df

# Usage example: apply to all model names
for model in model_names:
    formulas_ds = separate_formulas(formulas_ds, model)
formulas_ds.tail()

processing:  ["a(n) = 2*n for n=1..10"]
processing:  ["a(n) = 3*n for n=1..10"]
processing:  ["a(n) = 4*n for n=1..10"]
processing:  ["a(n) = 5*n for n=1..10"]
processing:  ["a(n) = 6*n for n=1..10"]
processing:  ["a(n) = 7*n for n=1..10"]
processing:  ["a(n) = 8*n for n=1..10"]
processing:  ["a(n) = 9*n for n=1..10"]
processing:  ["a(n) = 10*n for n=1..10"]
processing:  ["a(n) = 2*n - 1 for odd numbers"]
processing:  ["a(n) = 2*n for even numbers"]
processing:  ["a(n) = n + 10 for n=1..10"]
processing:  ["a(n) = n + 20 for n=1..10"]
processing:  ["a(n) = n + 30 for n=1..10"]
processing:  ["a(n) = n + 40 for n=1..10"]
processing:  ["a(n) = n + 50 for n=1..10"]
processing:  ["a(n) = n + 60 for n=1..10"]
processing:  ["a(n) = n + 70 for n=1..10"]
processing:  ["a(n) = n + 80 for n=1..10"]
processing:  ["a(n) = n + 90 for n=1..10"]
processing:  ["a(n) = n + 100 for n=1..10"]
processing:  ["a(n) = n + 110 for n=1..10"]
processing:  ["a(n) = n + 120 for n=1..10"]
processing:  ["a(n) = n + 130 for n=1..10"]
processing:  ["a(n) = n + 140 for n=1..10"]
processing:  ["a(n) = n + 150 for n=1..10"]
processing:  ["a(n) = n + 160 for n=1..10"]
processing:  ["a(n) = n + 170 for n=1..10"]
processing:  ["a(n) = n + 180 for n=1..10"]
processing:  ["a(n) = n + 190 for n=1..10"]
processing:  ["primes"]
processing:  ["Fibonacci numbers F(n) for n=3..12"]
processing:  ["a(n) = 2^n for n=0..9"]
processing:  ["a(n) = 3^n for n=0..9"]
processing:  ["a(n) = n^2 for n=1..10"]
processing:  ["a(n) = n^3 for n=1..10"]
processing:  ["a(n) = n! for n=0..9"]
processing:  ["triangular numbers T(n) = n(n+1)/2 for n=1..10"]
processing:  ["Lucas numbers L(n) for n=2..11"]
processing:  ["Pell numbers P(n) for n=0..9"]
processing:  ["a(n) = n^n for n=1..10"]
processing:  ["central binomial coefficients C(2n,n) for n=1..10"]
processing:  ["primes"]
processing:  ["*not found*"]
processing:  ["numbers containing digits 1 and 0 only, in base 10, read as base 10"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["a(n) = n(n+1) for n=2..10"]
processing:  ["numbers containing digits 1 and 0 only, in base 10"]
processing:  ["Mersenne primes 2^p - 1"]
processing:  ["Fibonacci-Lucas mixed, or powers of 2 with adjustment"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["Bell numbers B(n) for n=0..9"]
processing:  ["primes"]
processing:  ["look-and-say sequence"]
processing:  ["primes"]
processing:  ["a(n) = 2^n for n=0..9"]
processing:  ["a(n) = 2^n - 1 for n=1..10"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["*not found*"]
processing:  ["a_n = 2 n","a_n = n + n"]
processing:  ["a_n = 3 n"]
processing:  ["a_n = 4 n"]
processing:  ["a_n = 5 n"]
processing:  ["a_n = 6 n"]
processing:  ["a_n = 7 n"]
processing:  ["a_n = 8 n"]
processing:  ["a_n = 9 n"]
processing:  ["a_n = 10 n"]
processing:  ["a_n = 2 n - 1"]
processing:  ["a_n = 2 n"]
processing:  ["a_n = n + 10"]
processing:  ["a_n = n + 20"]
processing:  ["a_n = n + 30"]
processing:  ["a_n = n + 40"]
processing:  ["a_n = n + 50"]
processing:  ["a_n = n + 60"]
processing:  ["a_n = n + 70"]
processing:  ["a_n = n + 80"]
processing:  ["a_n = n + 90"]
processing:  ["a_n = n + 100"]
processing:  ["a_n = n + 110"]
processing:  ["a_n = n + 120"]
processing:  ["a_n = n + 130"]
processing:  ["a_n = n + 140"]
processing:  ["a_n = n + 150"]
processing:  ["a_n = n + 160"]
processing:  ["a_n = n + 170"]
processing:  ["a_n = n + 180"]
processing:  ["a_n = n + 190"]
processing:  ["a_n = p_n (nth prime)"]
processing:  ["a_n = F_n"]
processing:  ["a_n = 2^{n-1}"]
processing:  ["a_n = 3^{n-1}"]
processing:  ["a_n = n^2"]
processing:  ["a_n = n^3"]
processing:  ["a_n = n!"]
processing:  ["a_n = n(n+1)/2"]
processing:  ["a_n = a_{n-1}+a_{n-2}, a_1=2,a_2=1"]
processing:  ["a_n = 2 a_{n-1}+a_{n-2}, a_1=0,a_2=1"]
processing:  ["a_n = n^n"]
processing:  ["a_n = binom(2n,n)"]
processing:  ["a_n = p_n (nth prime)"]
processing:  ["a_n = floor((n+1)(n+2)/4)"]
processing:  ["a_n = interpretation of n in base 2 written in base 10"]
processing:  ["*not found"]
processing:  ["a_n in {1,2,145,40585} (factorions)"]
processing:  ["*not found"]
processing:  ["a_n = numbers composed of digits {0,1,8,9}"]
processing:  ["a_n = 2^{n+1}-1"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["a_n = number of 1s in binary expansion of n"]
processing:  ["*not found"]
processing:  ["a_n = p_n (nth prime)"]
processing:  ["a_n = look-and-say sequence"]
processing:  ["a_n = p_n (nth prime)"]
processing:  ["a_n = 2^{n-1}"]
processing:  ["a_n = 2^n - 1"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["*not found"]
processing:  ["a(n) = 2n", "a(n) = 2(n+1)", "a(n) = 2n for n=1..10"]
processing:  ["a(n) = 3n", "a(n) = 3(n+1)", "a(n) = 3n for n=1..10"]
processing:  ["a(n) = 4n", "a(n) = 4(n+1)", "a(n) = 4n for n=1..10"]
processing:  ["a(n) = 5n", "a(n) = 5(n+1)", "a(n) = 5n for n=1..10"]
processing:  ["a(n) = 6n", "a(n) = 6(n+1)", "a(n) = 6n for n=1..10"]
processing:  ["a(n) = 7n", "a(n) = 7(n+1)", "a(n) = 7n for n=1..10"]
processing:  ["a(n) = 8n", "a(n) = 8(n+1)", "a(n) = 8n for n=1..10"]
processing:  ["a(n) = 9n", "a(n) = 9(n+1)", "a(n) = 9n for n=1..10"]
processing:  ["a(n) = 10n", "a(n) = 10(n+1)", "a(n) = 10n for n=1..10"]
processing:  ["a(n) = 2n - 1", "a(n) = 2n + 1 for n=0..9", "a(n) = 2(n-1) + 1"]
processing:  ["a(n) = 2n", "a(n) = 2(n+1)", "a(n) = 2n for n=1..10"]
processing:  ["a(n) = n + 10", "a(n) = 10 + n for n=1..10"]
processing:  ["a(n) = n + 20", "a(n) = 20 + n for n=1..10"]
processing:  ["a(n) = n + 30", "a(n) = 30 + n for n=1..10"]
processing:  ["a(n) = n + 40", "a(n) = 40 + n for n=1..10"]
processing:  ["a(n) = n + 50", "a(n) = 50 + n for n=1..10"]
processing:  ["a(n) = n + 60", "a(n) = 60 + n for n=1..10"]
processing:  ["a(n) = n + 70", "a(n) = 70 + n for n=1..10"]
processing:  ["a(n) = n + 80", "a(n) = 80 + n for n=1..10"]
processing:  ["a(n) = n + 90", "a(n) = 90 + n for n=1..10"]
processing:  ["a(n) = n + 100", "a(n) = 100 + n for n=1..10"]
processing:  ["a(n) = n + 110", "a(n) = 110 + n for n=1..10"]
processing:  ["a(n) = n + 120", "a(n) = 120 + n for n=1..10"]
processing:  ["a(n) = n + 130", "a(n) = 130 + n for n=1..10"]
processing:  ["a(n) = n + 140", "a(n) = 140 + n for n=1..10"]
processing:  ["a(n) = n + 150", "a(n) = 150 + n for n=1..10"]
processing:  ["a(n) = n + 160", "a(n) = 160 + n for n=1..10"]
processing:  ["a(n) = n + 170", "a(n) = 170 + n for n=1..10"]
processing:  ["a(n) = n + 180", "a(n) = 180 + n for n=1..10"]
processing:  ["a(n) = n + 190", "a(n) = 190 + n for n=1..10"]
processing:  ["a(n) = nth prime number", "a(n) = p_n where p_n is the nth prime"]
processing:  ["a(n) = F(n) where F(n) = F(n-1) + F(n-2), F(0)=1, F(1)=1", "a(n) = Fibonacci(n)"]
processing:  ["a(n) = 2^(n-1)", "a(n) = 2^n for n=0..9"]
processing:  ["a(n) = 3^(n-1)", "a(n) = 3^n for n=0..9"]
processing:  ["a(n) = n^2", "a(n) = n*n for n=1..10"]
processing:  ["a(n) = n^3", "a(n) = n*n*n for n=1..10"]
processing:  ["a(n) = n!", "a(n) = factorial(n) for n=1..10"]
processing:  ["a(n) = n(n+1)/2", "a(n) = T(n) triangular numbers"]
processing:  ["a(n) = a(n-1) + a(n-2) with a(0)=2, a(1)=1", "a(n) = Lucas-like sequence"]
processing:  ["a(n) = Motzkin numbers", "a(n) = M(n)"]
processing:  ["a(n) = n^n", "a(n) = n to the power n"]
processing:  ["a(n) = C(2n,n)", "a(n) = central binomial coefficient", "a(n) = (2n)!/(n!*n!)"]
processing:  ["a(n) = nth prime number", "a(n) = p_n"]
processing:  ["a(n) = composite numbers", "a(n) = semiprimes and composites"]
processing:  *not found
Error processing row *not found, 44: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 45: Expecting value: line 1 column 1 (char 0)
processing:  ["a(n) = factorions", "a(n) = sum of factorials of digits equals n"]
processing:  *not found
Error processing row *not found, 47: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 48: Expecting value: line 1 column 1 (char 0)
processing:  ["a(n) = 2^(2^n + n) - 1", "a(n) = Mersenne-related sequence"]
processing:  *not found
Error processing row *not found, 50: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 51: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 52: Expecting value: line 1 column 1 (char 0)
processing:  ["a(n) = popcount(n) mod 2", "a(n) = parity of binary weight"]
processing:  ["a(n) = Catalan numbers", "a(n) = C(2n,n)/(n+1)"]
processing:  ["a(n) = nth prime", "a(n) = prime(n)"]
processing:  ["a(n) = look-and-say sequence", "a(n) = Conway sequence"]
processing:  ["a(n) = nth prime", "a(n) = prime(n)"]
processing:  ["a(n) = 2^(n-1)", "a(n) = powers of 2"]
processing:  ["a(n) = 2^n - 1", "a(n) = Mersenne numbers"]
processing:  *not found
Error processing row *not found, 60: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 61: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 62: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 63: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 64: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 65: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 66: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 67: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 68: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 69: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 70: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 71: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 72: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 73: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 74: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 75: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 76: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 77: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 78: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 79: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 80: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 81: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 82: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 83: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 84: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 85: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 86: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 87: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 88: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 89: Expecting value: line 1 column 1 (char 0)
Error processing row 44: Expecting value: line 1 column 1 (char 0)
Error processing row 45: Expecting value: line 1 column 1 (char 0)
Error processing row 47: Expecting value: line 1 column 1 (char 0)
Error processing row 48: Expecting value: line 1 column 1 (char 0)
Error processing row 50: Expecting value: line 1 column 1 (char 0)
Error processing row 51: Expecting value: line 1 column 1 (char 0)
Error processing row 52: Expecting value: line 1 column 1 (char 0)
Error processing row 60: Expecting value: line 1 column 1 (char 0)
Error processing row 61: Expecting value: line 1 column 1 (char 0)
Error processing row 62: Expecting value: line 1 column 1 (char 0)
Error processing row 63: Expecting value: line 1 column 1 (char 0)
Error processing row 64: Expecting value: line 1 column 1 (char 0)
Error processing row 65: Expecting value: line 1 column 1 (char 0)
Error processing row 66: Expecting value: line 1 column 1 (char 0)
Error processing row 67: Expecting value: line 1 column 1 (char 0)
Error processing row 68: Expecting value: line 1 column 1 (char 0)
Error processing row 69: Expecting value: line 1 column 1 (char 0)
Error processing row 70: Expecting value: line 1 column 1 (char 0)
Error processing row 71: Expecting value: line 1 column 1 (char 0)
Error processing row 72: Expecting value: line 1 column 1 (char 0)
Error processing row 73: Expecting value: line 1 column 1 (char 0)
Error processing row 74: Expecting value: line 1 column 1 (char 0)
Error processing row 75: Expecting value: line 1 column 1 (char 0)
Error processing row 76: Expecting value: line 1 column 1 (char 0)
Error processing row 77: Expecting value: line 1 column 1 (char 0)
Error processing row 78: Expecting value: line 1 column 1 (char 0)
Error processing row 79: Expecting value: line 1 column 1 (char 0)
Error processing row 80: Expecting value: line 1 column 1 (char 0)
Error processing row 81: Expecting value: line 1 column 1 (char 0)
Error processing row 82: Expecting value: line 1 column 1 (char 0)
Error processing row 83: Expecting value: line 1 column 1 (char 0)
Error processing row 84: Expecting value: line 1 column 1 (char 0)
Error processing row 85: Expecting value: line 1 column 1 (char 0)
Error processing row 86: Expecting value: line 1 column 1 (char 0)
Error processing row 87: Expecting value: line 1 column 1 (char 0)
Error processing row 88: Expecting value: line 1 column 1 (char 0)
Error processing row 89: Expecting value: line 1 column 1 (char 0)
processing:  ["2n"]
processing:  ["3n"]
processing:  ["4n"]
processing:  ["5n"]
processing:  ["6n"]
processing:  ["7n"]
processing:  ["8n"]
processing:  ["9n"]
processing:  ["10n"]
processing:  ["2n - 1"]
processing:  ["2n"]
processing:  ["n + 10"]
processing:  ["n + 20"]
processing:  ["n + 30"]
processing:  ["n + 40"]
processing:  ["n + 50"]
processing:  ["n + 60"]
processing:  ["n + 70"]
processing:  ["n + 80"]
processing:  ["n + 90"]
processing:  ["n + 100"]
processing:  ["n + 110"]
processing:  ["n + 120"]
processing:  ["n + 130"]
processing:  ["n + 140"]
processing:  ["n + 150"]
processing:  ["n + 160"]
processing:  ["n + 170"]
processing:  ["n + 180"]
processing:  ["n + 190"]
processing:  ["prime(n)"]
processing:  ["Fibonacci(n)"]
processing:  ["2^(n-1)"]
processing:  ["3^(n-1)"]
processing:  ["n^2"]
processing:  ["n^3"]
processing:  ["(n-1)!"]
processing:  ["n(n+1)/2"]
processing:  ["Lucas(n)"]
processing:  ["Pell(n)"]
processing:  ["n^n"]
processing:  ["binomial(2(n-1), n-1)"]
processing:  ["prime(n)"]
processing:  ["Composite(n)"]
processing:  ["int(bin(n))"]
processing:  ["n = sum(digit^k)"]
processing:  ["Factorions: n = sum(digit!)"]
processing:  *not found
Error processing row *not found, 47: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 48: Expecting value: line 1 column 1 (char 0)
processing:  ["Mersenne Primes: 2^p - 1"]
processing:  *not found
Error processing row *not found, 50: Expecting value: line 1 column 1 (char 0)
processing:  ["Cake Numbers: (n^3 + 5n + 6)/6"]
processing:  ["Pentagonal Numbers: n(3n-1)/2"]
processing:  ["HammingWeight(n-1)"]
processing:  ["Bell(n)"]
processing:  ["prime(n)"]
processing:  ["Look-and-Say Sequence"]
processing:  ["prime(n)"]
processing:  ["2^(n-1)"]
processing:  ["2^n - 1"]
processing:  *not found
Error processing row *not found, 60: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 61: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 62: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 63: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 64: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 65: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 66: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 67: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 68: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 69: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 70: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 71: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 72: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 73: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 74: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 75: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 76: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 77: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 78: Expecting value: line 1 column 1 (char 0)
processing:  *not found
Error processing row *not found, 79: Expecting value: line 1 column 1 (char 0)
processing:  *not found

,grok_4.1,gpt-5.2,claude-4.5,gemini-3-pro,mistral-large-3,grok_4.1_1,gpt-5.2_1,gpt-5.2_2,claude-4.5_1,claude-4.5_2,claude-4.5_3,gemini-3-pro_1,mistral-large-3_1
85,"[""*not found*""]","[""*not found""]",*not found,*not found,"[""*not found""]",*not found*,*not found,*not found,*not found,*not found,*not found,*not found,*not found
86,"[""*not found*""]","[""*not found""]",*not found,*not found,"[""*not found""]",*not found*,*not found,*not found,*not found,*not found,*not found,*not found,*not found
87,"[""*not found*""]","[""*not found""]",*not found,*not found,"[""*not found""]",*not found*,*not found,*not found,*not found,*not found,*not found,*not found,*not found
88,"[""*not found*""]","[""*not found""]",*not found,*not found,"[""*not found""]",*not found*,*not found,*not found,*not found,*not found,*not found,*not found,*not found
89,"[""*not found*""]","[""*not found""]",*not found,*not found,"[""*not found""]",*not found*,*not found,*not found,*not found,*not found,*not found,*not found,*not found

In [8]:
print(list(formulas_ds.columns))
print(len(formulas_ds.columns))

['grok_4.1', 'gpt-5.2', 'claude-4.5', 'gemini-3-pro', 'mistral-large-3', 'grok_4.1_1', 'gpt-5.2_1', 'gpt-5.2_2', 'claude-4.5_1', 'claude-4.5_2', 'claude-4.5_3', 'gemini-3-pro_1', 'mistral-large-3_1']
13

In [9]:
formulas_ds.to_csv('new-multi-formulae-separated.csv', index=False)